%% P4_Exp07_LFP_SOHTestingCostSensitivity.m
% Purpose:
% This script generates Extended Data Fig. 6 for the fixed-scale LFP
% recertification model by evaluating the sensitivity of the optimized
% health-information investment to the unit SOH testing cost.
%
% The script reads the decision-loss curves saved from Part4/Main01 and
% recalculates the optimal labelled-pack number k* under different
% pack-level SOH testing costs. It does not rerun Monte Carlo simulation or
% threshold-grid search.

clear; clc; close all;

set(groot, 'DefaultFigureVisible', 'on');

%% 1) Configuration and path setup
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

cfg.part4_dir = script_dir;
cfg.output_dir = fullfile(cfg.part4_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.input_mat = fullfile(cfg.results_dir, 'P4_Exp01_FixedScale_LFP_Workspace.mat');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.extended_fig_dir = fullfile(cfg.figure_root, 'Extended');

cfg.summary_csv = fullfile(cfg.results_dir, 'P4_Exp07_LFP_SOHTestingCostSensitivity_Summary.csv');
cfg.allK_csv = fullfile(cfg.results_dir, 'P4_Exp07_LFP_SOHTestingCostSensitivity_AllK.csv');
cfg.result_mat = fullfile(cfg.results_dir, 'P4_Exp07_LFP_SOHTestingCostSensitivity_Results.mat');

cfg.fig_dual = fullfile(cfg.extended_fig_dir, 'ExD06a_LFP_SOH_testing_cost_sensitivity.fig');
cfg.png_dual = fullfile(cfg.extended_fig_dir, 'ExD06a_LFP_SOH_testing_cost_sensitivity.png');
cfg.fig_cost_decomp = fullfile(cfg.extended_fig_dir, 'ExD06b_LFP_SOH_testing_cost_cost_decomposition.fig');
cfg.png_cost_decomp = fullfile(cfg.extended_fig_dir, 'ExD06b_LFP_SOH_testing_cost_cost_decomposition.png');

cfg.png_resolution = 600;

folder_list = {cfg.output_dir, cfg.results_dir, cfg.figure_root, cfg.extended_fig_dir};

for ii = 1:numel(folder_list)
    if ~exist(folder_list{ii}, 'dir')
        mkdir(folder_list{ii});
    end
end

fprintf('================ Extended Data Fig. 6 LFP label-cost sensitivity ================\n');
fprintf('Input workspace file: %s\n', cfg.input_mat);
fprintf('Output folder:        %s\n', cfg.output_dir);
fprintf('Figure folder: %s\n', cfg.extended_fig_dir);

%% 2) Load saved fixed-scale LFP workspace
if ~isfile(cfg.input_mat)
    error(['Input file not found: %s\n' ...
        'Please run P4_Exp01_FixedScale_LFP_Optimization.m first to generate the fixed-scale LFP workspace.'], ...
        cfg.input_mat);
end

S = load(cfg.input_mat);

required_vars = { ...
    'k_vals', ...
    'O_base', ...
    'A_base', ...
    'R_base', ...
    'T1_base', ...
    'T2_base', ...
    'Fixed_Scale_N', ...
    'c_train'};

for ii = 1:numel(required_vars)
    if ~isfield(S, required_vars{ii})
        error('Required variable is missing from %s: %s', ...
            cfg.input_mat, required_vars{ii});
    end
end

k_vals = S.k_vals(:);
O_base = S.O_base(:);
A_base = S.A_base(:);
R_base = S.R_base(:);
T1_base = S.T1_base(:);
T2_base = S.T2_base(:);

Fixed_Scale_N = S.Fixed_Scale_N;
c_train = S.c_train;

n_k = numel(k_vals);

if any([numel(O_base), numel(A_base), numel(R_base), ...
        numel(T1_base), numel(T2_base)] ~= n_k)
    error('k_vals, O_base, A_base, R_base, T1_base, and T2_base have inconsistent lengths.');
end

if isfield(S, 'c_pack')
    c_pack_baseline = S.c_pack;
else
    c_pack_baseline = 300;
end

fprintf('Fixed-scale LFP workspace loaded successfully.\n');
fprintf('k range: %d to %d, with %d k values in total.\n', ...
    min(k_vals), max(k_vals), n_k);
fprintf('Fixed deployment scale: %d packs.\n', Fixed_Scale_N);
fprintf('Baseline SOH testing cost: %.2f USD per pack.\n', c_pack_baseline);

%% 3) Define SOH testing-cost scenarios
c_pack_list = [50; 100; 150; 200; 250; 300; 350; 400; ...
               450; 500; 550; 600; 650; 700; 750; 800];

n_scenario = numel(c_pack_list);

%% 4) Recalculate the optimal k* under different SOH testing costs
Decision_Loss_per_pack = O_base + A_base + R_base;

k_star = zeros(n_scenario, 1);
T1_star = zeros(n_scenario, 1);
T2_star = zeros(n_scenario, 1);

Opportunity_loss_USD = zeros(n_scenario, 1);
Verification_cost_USD = zeros(n_scenario, 1);
Risk_penalty_USD = zeros(n_scenario, 1);

SOH_testing_cost_USD = zeros(n_scenario, 1);
Training_cost_USD = zeros(n_scenario, 1);
Information_cost_USD = zeros(n_scenario, 1);

Total_cost_USD = zeros(n_scenario, 1);
Cost_per_pack_USD = zeros(n_scenario, 1);

opt_idx = zeros(n_scenario, 1);

TotalCost_byScenario_K = zeros(n_scenario, n_k);
InfoCost_byScenario_K = zeros(n_scenario, n_k);
DecisionLoss_byScenario_K = zeros(n_scenario, n_k);

for ii = 1:n_scenario

    c_pack_now = c_pack_list(ii);

    SOH_testing_cost_byK = k_vals .* c_pack_now;
    Training_cost_byK = c_train .* ones(n_k, 1);
    Info_cost_byK = SOH_testing_cost_byK + Training_cost_byK;

    Decision_loss_total_byK = Fixed_Scale_N .* Decision_Loss_per_pack;
    Total_cost_byK = Decision_loss_total_byK + Info_cost_byK;

    TotalCost_byScenario_K(ii, :) = Total_cost_byK(:)';
    InfoCost_byScenario_K(ii, :) = Info_cost_byK(:)';
    DecisionLoss_byScenario_K(ii, :) = Decision_loss_total_byK(:)';

    [Total_cost_min, idx_now] = min(Total_cost_byK);

    opt_idx(ii) = idx_now;
    k_star(ii) = k_vals(idx_now);
    T1_star(ii) = T1_base(idx_now);
    T2_star(ii) = T2_base(idx_now);

    Opportunity_loss_USD(ii) = Fixed_Scale_N .* O_base(idx_now);
    Verification_cost_USD(ii) = Fixed_Scale_N .* A_base(idx_now);
    Risk_penalty_USD(ii) = Fixed_Scale_N .* R_base(idx_now);

    SOH_testing_cost_USD(ii) = k_vals(idx_now) .* c_pack_now;
    Training_cost_USD(ii) = c_train;
    Information_cost_USD(ii) = SOH_testing_cost_USD(ii) + Training_cost_USD(ii);

    Total_cost_USD(ii) = Total_cost_min;
    Cost_per_pack_USD(ii) = Total_cost_min ./ Fixed_Scale_N;
end

%% 5) Save summary tables
Summary_Table = table( ...
    c_pack_list, ...
    k_star, ...
    T1_star, ...
    T2_star, ...
    Opportunity_loss_USD, ...
    Verification_cost_USD, ...
    Risk_penalty_USD, ...
    SOH_testing_cost_USD, ...
    Training_cost_USD, ...
    Information_cost_USD, ...
    Total_cost_USD, ...
    Cost_per_pack_USD, ...
    'VariableNames', { ...
    'SOH_testing_cost_USD_per_pack', ...
    'k_star', ...
    'T1_star', ...
    'T2_star', ...
    'Opportunity_loss_USD', ...
    'Verification_cost_USD', ...
    'Risk_penalty_USD', ...
    'SOH_testing_cost_USD', ...
    'Training_cost_USD', ...
    'Information_cost_USD', ...
    'Total_cost_USD', ...
    'Total_cost_per_pack_USD'});

disp(' ');
disp('========== Extended Data Fig. 6: LFP SOH testing-cost sensitivity ==========');
disp(Summary_Table);

writetable(Summary_Table, cfg.summary_csv);

AllK_Table = table( ...
    k_vals, ...
    O_base, ...
    A_base, ...
    R_base, ...
    Decision_Loss_per_pack, ...
    T1_base, ...
    T2_base, ...
    'VariableNames', { ...
    'k', ...
    'Opportunity_loss_per_pack_USD', ...
    'Verification_cost_per_pack_USD', ...
    'Risk_penalty_per_pack_USD', ...
    'Decision_loss_per_pack_USD', ...
    'T1_opt_at_k', ...
    'T2_opt_at_k'});

for ii = 1:n_scenario

    c_pack_now = c_pack_list(ii);

    var_total = sprintf('Total_cost_cpack_%d_USD', c_pack_now);
    var_info  = sprintf('Info_cost_cpack_%d_USD', c_pack_now);
    var_dec   = sprintf('Decision_loss_total_cpack_%d_USD', c_pack_now);

    AllK_Table.(var_total) = TotalCost_byScenario_K(ii, :)';
    AllK_Table.(var_info)  = InfoCost_byScenario_K(ii, :)';
    AllK_Table.(var_dec)   = DecisionLoss_byScenario_K(ii, :)';
end

writetable(AllK_Table, cfg.allK_csv);

save(cfg.result_mat, ...
    'cfg', ...
    'Summary_Table', ...
    'AllK_Table', ...
    'c_pack_list', ...
    'c_pack_baseline', ...
    'k_vals', ...
    'k_star', ...
    'T1_star', ...
    'T2_star', ...
    'Opportunity_loss_USD', ...
    'Verification_cost_USD', ...
    'Risk_penalty_USD', ...
    'SOH_testing_cost_USD', ...
    'Training_cost_USD', ...
    'Information_cost_USD', ...
    'Total_cost_USD', ...
    'Cost_per_pack_USD', ...
    'TotalCost_byScenario_K', ...
    'InfoCost_byScenario_K', ...
    'DecisionLoss_byScenario_K', ...
    '-v7.3');

fprintf('Summary table saved: %s\n', cfg.summary_csv);
fprintf('All-k cost table saved: %s\n', cfg.allK_csv);
fprintf('MAT result saved: %s\n', cfg.result_mat);

%% 6) Extended Fig. 6a: dual-axis plot of k* and total cost per pack
fig_a = figure( ...
    'Name', 'Extended_Fig6a_label_cost_dual_axis', ...
    'Color', 'w', ...
    'Position', [100, 80, 820, 580]);

yyaxis left
h1 = plot(c_pack_list, k_star, '-o', ...
    'LineWidth', 2.0, ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', 'w');
ylabel('Optimal labelled packs, k^*', ...
    'FontName', 'Arial', ...
    'FontSize', 11);
ylim([0, max(k_star) + 2]);

yyaxis right
h2 = plot(c_pack_list, Cost_per_pack_USD, '-s', ...
    'LineWidth', 2.0, ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', 'w');
ylabel('Total cost (USD per pack)', ...
    'FontName', 'Arial', ...
    'FontSize', 11);

hold on;

xline(c_pack_baseline, '--', ...
    'Baseline', ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'LineWidth', 1.2, ...
    'Color', [0.35, 0.35, 0.35], ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('SOH testing cost (USD per pack)', ...
    'FontName', 'Arial', ...
    'FontSize', 11);

title('Optimal health-information investment and per-pack recertification cost', ...
    'FontName', 'Arial', ...
    'FontSize', 11.5, ...
    'FontWeight', 'normal');

xlim([40, 820]);
xticks(100:100:800);

legend([h1, h2], ...
    {'Optimal labelled packs, k^*', 'Total cost per pack'}, ...
    'Location', 'best', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'LineWidth', 1.0, ...
    'TickDir', 'out');

local_save_figure(fig_a, cfg.fig_dual, cfg.png_dual, cfg.png_resolution);

%% 7) Extended Fig. 6b: Cost decomposition at optimal k*
fig_b = figure( ...
    'Name', 'Extended_Fig6b_cost_decomposition', ...
    'Color', 'w', ...
    'Position', [140, 100, 860, 580]);

Opp_1e4   = Opportunity_loss_USD  ./ 1e4;
Ver_1e4   = Verification_cost_USD ./ 1e4;
Risk_1e4  = Risk_penalty_USD      ./ 1e4;
Test_1e4  = SOH_testing_cost_USD  ./ 1e4;
Train_1e4 = Training_cost_USD     ./ 1e4;

Cost_Stack_1e4USD = [ ...
    Opp_1e4, ...
    Ver_1e4, ...
    Risk_1e4, ...
    Test_1e4, ...
    Train_1e4];

color_opp   = [0.07, 0.39, 0.74];
color_ver   = [0.36, 0.66, 0.93];
color_risk  = [0.75, 0.85, 0.96];
color_test  = [0.48, 0.29, 0.78];
color_train = [0.82, 0.72, 0.95];

hb = bar(c_pack_list, Cost_Stack_1e4USD, 'stacked', ...
    'BarWidth', 0.78, ...
    'EdgeColor', 'none');

hold on;

set(hb(1), 'FaceColor', color_opp);
set(hb(2), 'FaceColor', color_ver);
set(hb(3), 'FaceColor', color_risk);
set(hb(4), 'FaceColor', color_test);
set(hb(5), 'FaceColor', color_train);

DecisionBlock_1e4 = Opp_1e4 + Ver_1e4 + Risk_1e4;

plot(c_pack_list, DecisionBlock_1e4, '--', ...
    'Color', [0.25, 0.25, 0.25], ...
    'LineWidth', 1.2);

xline(c_pack_baseline, '--', ...
    'Baseline', ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'LineWidth', 1.1, ...
    'Color', [0.35, 0.35, 0.35]);

grid on;
box on;

xlabel('SOH testing cost (USD per pack)', ...
    'FontName', 'Arial', ...
    'FontSize', 11);

ylabel('Cost component (10^4 USD)', ...
    'FontName', 'Arial', ...
    'FontSize', 11);

title('Cost decomposition at k^*', ...
    'FontName', 'Arial', ...
    'FontSize', 11.5, ...
    'FontWeight', 'normal');

xlim([20, 840]);
ylim([0, max(sum(Cost_Stack_1e4USD, 2)) * 1.08]);
xticks(100:100:800);

legend(hb, ...
    {'Opportunity loss', ...
     'Verification cost', ...
     'Risk penalty', ...
     'SOH testing cost', ...
     'Training cost'}, ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 8.2);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 10, ...
    'LineWidth', 1.0, ...
    'TickDir', 'out');

local_save_figure(fig_b, cfg.fig_cost_decomp, cfg.png_cost_decomp, cfg.png_resolution);

fprintf('\n>>> Extended Data Fig. 6 LFP label-cost sensitivity completed.\n');
fprintf('>>> Output tables saved in: %s\n', cfg.results_dir);
fprintf('>>> Figures saved in: %s\n', cfg.extended_fig_dir);
fprintf('===============================================================================\n');

%% Local helper function
function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end