%% P4_Exp10_LFP_GrayZoneToleranceMechanism.m
% Purpose:
% This script analyzes the gray-zone tolerance mechanism under the fixed-scale LFP
% baseline policy and generates Supplementary Fig. 19.
%
% The baseline policy, including k*, T1*, and T2*, is first fixed to analyze severe-trigger
% rates and penalty-related costs under eta_1 and eta_2 sensitivity. The script then
% re-optimizes k, T1, and T2 under each eta setting to compare fixed-policy and re-optimized-policy costs.
% The re-optimization uses the shared Part4 residual generator.


clear; clc; close all;

set(groot, 'DefaultFigureVisible', 'on');

%% 1) Configuration and path setup
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
 script_dir = pwd;
end

cfg.part4_dir = script_dir;

cfg.output_dir = fullfile(cfg.part4_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(cfg.part4_dir, 'Figures');
cfg.supp_fig_dir = fullfile(cfg.figure_root, 'Supplementary');

cfg.input_mat = fullfile(cfg.results_dir, 'P4_Exp01_FixedScale_LFP_Workspace.mat');

cfg.function_dir = fullfile(cfg.part4_dir, 'Function');

% Output tables.
cfg.eta1_fixed_csv = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_FixedPolicy_Eta1.csv');
cfg.eta2_fixed_csv = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_FixedPolicy_Eta2.csv');

cfg.eta1_reopt_csv = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_Reoptimized_Eta1.csv');
cfg.eta2_reopt_csv = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_Reoptimized_Eta2.csv');

cfg.eta1_compare_csv = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_FixedVsReoptimized_Eta1.csv');
cfg.eta2_compare_csv = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_FixedVsReoptimized_Eta2.csv');

cfg.result_mat = fullfile(cfg.results_dir, 'P4_Exp10_LFP_GrayZoneToleranceMechanism_Results.mat');

% Output figures.
cfg.fig_eta1_trigger = fullfile(cfg.supp_fig_dir, 'SupFig19a_LFP_gray_zone_Eta1_trigger_rate_composition.fig');
cfg.png_eta1_trigger = fullfile(cfg.supp_fig_dir, 'SupFig19a_LFP_gray_zone_Eta1_trigger_rate_composition.png');

cfg.fig_eta1_cost = fullfile(cfg.supp_fig_dir, 'SupFig19b_LFP_gray_zone_Eta1_penalty_cost_composition.fig');
cfg.png_eta1_cost = fullfile(cfg.supp_fig_dir, 'SupFig19b_LFP_gray_zone_Eta1_penalty_cost_composition.png');

cfg.fig_eta2_trigger = fullfile(cfg.supp_fig_dir, 'SupFig19c_LFP_gray_zone_Eta2_trigger_rate_composition.fig');
cfg.png_eta2_trigger = fullfile(cfg.supp_fig_dir, 'SupFig19c_LFP_gray_zone_Eta2_trigger_rate_composition.png');

cfg.fig_eta2_cost = fullfile(cfg.supp_fig_dir, 'SupFig19d_LFP_gray_zone_Eta2_penalty_cost_composition.fig');
cfg.png_eta2_cost = fullfile(cfg.supp_fig_dir, 'SupFig19d_LFP_gray_zone_Eta2_penalty_cost_composition.png');

cfg.fig_eta1_compare = fullfile(cfg.supp_fig_dir, 'SupFig19e_LFP_gray_zone_fixed_vs_reoptimized_Eta1.fig');
cfg.png_eta1_compare = fullfile(cfg.supp_fig_dir, 'SupFig19e_LFP_gray_zone_fixed_vs_reoptimized_Eta1.png');

cfg.fig_eta2_compare = fullfile(cfg.supp_fig_dir, 'SupFig19f_LFP_gray_zone_fixed_vs_reoptimized_Eta2.fig');
cfg.png_eta2_compare = fullfile(cfg.supp_fig_dir, 'SupFig19f_LFP_gray_zone_fixed_vs_reoptimized_Eta2.png');

cfg.png_resolution = 600;

% Re-optimization control.
cfg.do_reoptimize = true;

folder_list = { ...
 cfg.output_dir, ...
 cfg.results_dir, ...
 cfg.figure_root, ...
 cfg.supp_fig_dir};

for ii = 1:numel(folder_list)
 if ~exist(folder_list{ii}, 'dir')
 mkdir(folder_list{ii});
 end
end

addpath(cfg.function_dir);

if exist('local_build_noise_by_k', 'file') ~= 2
 error('Function local_build_noise_by_k.m was not found in: %s', cfg.function_dir);
end

fprintf('================ P4 Exp10: LFP gray-zone tolerance mechanism ================\n');
fprintf('Input workspace file: %s\n', cfg.input_mat);
fprintf('Function folder: %s\n', cfg.function_dir);
fprintf('Output folder: %s\n', cfg.results_dir);
fprintf('Figure folder: %s\n', cfg.supp_fig_dir);

%% 2) Load the updated fixed-scale LFP workspace
if ~isfile(cfg.input_mat)
 error(['Input file not found: %s\n' ...
 'Please run P4_Exp01_FixedScale_LFP_Optimization.m first to generate the fixed-scale LFP workspace.'], ...
 cfg.input_mat);
end

S = load(cfg.input_mat);

required_vars = { ...
 's_true', ...
 'Pi_True', ...
 'Pi_True_Max', ...
 'True_Action_i', ...
 'Eta_1', ...
 'Eta_2', ...
 'Lambda_A', ...
 'Lambda_R', ...
 'Fixed_Scale_N', ...
 'c_pack', ...
 'c_train', ...
 'k_vals', ...
 'k_emp', ...
 'k_anchor', ...
 'k_bridge_end', ...
 'err_cell', ...
 'w_curve', ...
 'muM_curve', ...
 'sigM_curve', ...
 'muR_curve', ...
 'sigR_curve', ...
 'rmse_target', ...
 'base_u', ...
 'base_z', ...
 'base_pick', ...
 'base_bridge'};

for ii = 1:numel(required_vars)
 if ~isfield(S, required_vars{ii})
 error('Required variable is missing from %s: %s', ...
 cfg.input_mat, required_vars{ii});
 end
end

% Basic sample-level variables.
s_true = S.s_true(:);
Pi_True = S.Pi_True;
Pi_True_Max = S.Pi_True_Max(:);
True_Action_i = S.True_Action_i(:);

N_sim = numel(s_true);

if size(Pi_True, 1) ~= N_sim || size(Pi_True, 2) ~= 3
 error('Pi_True must have size [N_sim, 3].');
end

if numel(Pi_True_Max) ~= N_sim || numel(True_Action_i) ~= N_sim
 error('Pi_True_Max and True_Action_i must have length N_sim.');
end

% Baseline gray-zone and penalty parameters.
Eta_1_base = S.Eta_1;
Eta_2_base = S.Eta_2;

Lambda_A = S.Lambda_A;
Lambda_R = S.Lambda_R;

Fixed_Scale_N = S.Fixed_Scale_N;
c_pack = S.c_pack;
c_train = S.c_train;

% Residual model and common random-number variables.
k_vals = S.k_vals(:);
k_emp = S.k_emp(:);
k_anchor = S.k_anchor;
k_bridge_end = S.k_bridge_end;
err_cell = S.err_cell;

w_curve = S.w_curve(:);
muM_curve = S.muM_curve(:);
sigM_curve = S.sigM_curve(:);
muR_curve = S.muR_curve(:);
sigR_curve = S.sigR_curve(:);
rmse_target = S.rmse_target(:);

base_u = S.base_u(:);
base_z = S.base_z(:);
base_pick = S.base_pick(:);
base_bridge = S.base_bridge(:);

if numel(base_u) ~= N_sim || numel(base_z) ~= N_sim || ...
 numel(base_pick) ~= N_sim || numel(base_bridge) ~= N_sim
 error('base_u, base_z, base_pick, and base_bridge must have length N_sim.');
end

% Threshold grids.
if isfield(S, 'T1_grid')
 T1_grid = S.T1_grid;
else
 T1_grid = 0.400:0.005:0.500;
 warning('T1_grid was not found. Default LFP T1_grid = 0.400:0.005:0.500 was used.');
end

if isfield(S, 'T2_grid')
 T2_grid = S.T2_grid;
else
 T2_grid = 0.850:0.005:1.000;
 warning('T2_grid was not found. Default LFP T2_grid = 0.850:0.005:1.000 was used.');
end

% Baseline policy.
if isfield(S, 'opt_k') && isfield(S, 'opt_T1') && isfield(S, 'opt_T2')

 opt_k = S.opt_k;
 opt_T1 = S.opt_T1;
 opt_T2 = S.opt_T2;

elseif isfield(S, 'Fixed_Total_Cost') && ...
 isfield(S, 'T1_base') && ...
 isfield(S, 'T2_base')

 [~, idx0] = min(S.Fixed_Total_Cost);

 opt_k = k_vals(idx0);
 opt_T1 = S.T1_base(idx0);
 opt_T2 = S.T2_base(idx0);

else

 error(['Baseline policy not found. Required variables are opt_k/opt_T1/opt_T2, ' ...
 'or Fixed_Total_Cost/T1_base/T2_base.']);
end

Information_cost_fixed = opt_k * c_pack + c_train;

fprintf('Updated fixed-scale LFP workspace loaded.\n');
fprintf('Baseline policy: k* = %d, T1* = %.4f, T2* = %.4f\n', ...
 opt_k, opt_T1, opt_T2);
fprintf('Baseline Eta_1 = %.4f, Eta_2 = %.4f\n', Eta_1_base, Eta_2_base);
fprintf('Lambda_A = %.4f, Lambda_R = %.4f\n', Lambda_A, Lambda_R);
fprintf('Fixed deployment scale N = %d packs\n', Fixed_Scale_N);
fprintf('Re-optimization grid: %d k values, %d T1 values, %d T2 values\n', ...
 numel(k_vals), numel(T1_grid), numel(T2_grid));

%% 3) Use the saved optimal-policy decision population from the updated TEA workspace

% Predicted SOH under the optimized baseline policy.
if isfield(S, 's_pred_opt')
 s_pred_fixed = S.s_pred_opt(:);
else
 s_pred_fixed = nan(N_sim, 1);
 warning('s_pred_opt was not found. Sup19 will continue without predicted-SOH diagnostics.');
end

if numel(s_pred_fixed) ~= N_sim
 error('s_pred_opt must have length N_sim.');
end

% Predicted action under the optimized baseline policy.
if isfield(S, 'Pred_Action_opt')

 Pred_Action_fixed = S.Pred_Action_opt(:);

elseif isfield(S, 's_pred_opt')

 Pred_Action_fixed = 3 * ones(N_sim, 1);
 Pred_Action_fixed(s_pred_fixed >= opt_T1 & s_pred_fixed < opt_T2) = 2;
 Pred_Action_fixed(s_pred_fixed >= opt_T2) = 1;

 warning('Pred_Action_opt was not found. It was reconstructed from s_pred_opt and the optimized thresholds.');

else

 error('Neither Pred_Action_opt nor s_pred_opt was found in the workspace.');
end

if numel(Pred_Action_fixed) ~= N_sim
 error('Pred_Action_opt must have length N_sim.');
end

% Opportunity loss under the optimized baseline policy.
if isfield(S, 'O_arr_opt')

 O_arr_fixed = S.O_arr_opt(:);

else

 idx_pred_fixed = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_fixed);
 O_arr_fixed = Pi_True_Max - Pi_True(idx_pred_fixed);

 warning('O_arr_opt was not found. It was reconstructed from Pi_True and Pred_Action_opt.');
end

if numel(O_arr_fixed) ~= N_sim
 error('O_arr_opt must have length N_sim.');
end

idx_pred_fixed = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_fixed);
Chosen_Value_fixed = Pi_True(idx_pred_fixed);

% G1: A3 <-> A2.
is_G1_error_fixed = ...
 (True_Action_i == 3 & Pred_Action_fixed == 2) | ...
 (True_Action_i == 2 & Pred_Action_fixed == 3);

% G2: A1 <-> A2.
is_G2_error_fixed = ...
 (True_Action_i == 1 & Pred_Action_fixed == 2) | ...
 (True_Action_i == 2 & Pred_Action_fixed == 1);

% Non-adjacent action mismatch.
is_any_error_fixed = Pred_Action_fixed ~= True_Action_i;
is_other_error_fixed = is_any_error_fixed & ...
 ~is_G1_error_fixed & ...
 ~is_G2_error_fixed;

% Directional decomposition within G1.
is_A3_to_A2_fixed = (True_Action_i == 3 & Pred_Action_fixed == 2);
is_A2_to_A3_fixed = (True_Action_i == 2 & Pred_Action_fixed == 3);

% Directional decomposition within G2.
is_A1_to_A2_fixed = (True_Action_i == 1 & Pred_Action_fixed == 2);
is_A2_to_A1_fixed = (True_Action_i == 2 & Pred_Action_fixed == 1);

% Over-optimistic assignment.
risk_indicator_fixed = Pred_Action_fixed < True_Action_i;

% Baseline action allocation.
A1_share_fixed = mean(Pred_Action_fixed == 1);
A2_share_fixed = mean(Pred_Action_fixed == 2);
A3_share_fixed = mean(Pred_Action_fixed == 3);

True_A1_share = mean(True_Action_i == 1);
True_A2_share = mean(True_Action_i == 2);
True_A3_share = mean(True_Action_i == 3);

fprintf('Predicted action shares: A1 = %.4f, A2 = %.4f, A3 = %.4f\n', ...
 A1_share_fixed, A2_share_fixed, A3_share_fixed);

fprintf('True optimal action shares: A1 = %.4f, A2 = %.4f, A3 = %.4f\n', ...
 True_A1_share, True_A2_share, True_A3_share);

fprintf('Mismatch rates: G1 = %.4f, G2 = %.4f, other = %.4f\n', ...
 mean(is_G1_error_fixed), mean(is_G2_error_fixed), mean(is_other_error_fixed));

%% 4) Define eta scanning ranges
Eta_1_list = [0 5 10 20 30 40 50 60 80 100 120]';
Eta_2_list = [0 5 10 20 30 40 50 60 80 100 120]';

%% 5) Scan Eta_1 under the fixed baseline policy
Result_Eta1_fixed = table();

for ii = 1:numel(Eta_1_list)

 eta1_now = Eta_1_list(ii);
 eta2_now = Eta_2_base;

 M = local_evaluate_eta_policy( ...
 eta1_now, ...
 eta2_now, ...
 O_arr_fixed, ...
 risk_indicator_fixed, ...
 is_G1_error_fixed, ...
 is_G2_error_fixed, ...
 is_other_error_fixed, ...
 is_A3_to_A2_fixed, ...
 is_A2_to_A3_fixed, ...
 is_A1_to_A2_fixed, ...
 is_A2_to_A1_fixed, ...
 Lambda_A, ...
 Lambda_R, ...
 Fixed_Scale_N, ...
 Information_cost_fixed);

 curr_row = local_build_fixed_row( ...
 eta1_now, eta2_now, opt_k, opt_T1, opt_T2, ...
 A1_share_fixed, A2_share_fixed, A3_share_fixed, M, ...
 "Eta1");

 Result_Eta1_fixed = [Result_Eta1_fixed; curr_row]; %#ok<AGROW>
end

%% 6) Scan Eta_2 under the fixed baseline policy
Result_Eta2_fixed = table();

for ii = 1:numel(Eta_2_list)

 eta1_now = Eta_1_base;
 eta2_now = Eta_2_list(ii);

 M = local_evaluate_eta_policy( ...
 eta1_now, ...
 eta2_now, ...
 O_arr_fixed, ...
 risk_indicator_fixed, ...
 is_G1_error_fixed, ...
 is_G2_error_fixed, ...
 is_other_error_fixed, ...
 is_A3_to_A2_fixed, ...
 is_A2_to_A3_fixed, ...
 is_A1_to_A2_fixed, ...
 is_A2_to_A1_fixed, ...
 Lambda_A, ...
 Lambda_R, ...
 Fixed_Scale_N, ...
 Information_cost_fixed);

 curr_row = local_build_fixed_row( ...
 eta1_now, eta2_now, opt_k, opt_T1, opt_T2, ...
 A1_share_fixed, A2_share_fixed, A3_share_fixed, M, ...
 "Eta2");

 Result_Eta2_fixed = [Result_Eta2_fixed; curr_row]; %#ok<AGROW>
end

%% 7) Re-optimize k, T1, and T2 under each eta setting
Result_Eta1_reopt = table();
Result_Eta2_reopt = table();

if cfg.do_reoptimize

 fprintf('\n================ Re-optimization under eta sensitivity ================\n');

 for ii = 1:numel(Eta_1_list)

 eta1_now = Eta_1_list(ii);
 eta2_now = Eta_2_base;

 fprintf('[Eta1 reopt] %d / %d | eta_1 = %.2f, eta_2 = %.2f\n', ...
 ii, numel(Eta_1_list), eta1_now, eta2_now);

 R = local_reoptimize_policy( ...
 eta1_now, eta2_now, ...
 s_true, Pi_True, Pi_True_Max, True_Action_i, ...
 k_vals, T1_grid, T2_grid, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, ...
 base_u, base_z, base_pick, base_bridge, ...
 Lambda_A, Lambda_R, ...
 Fixed_Scale_N, c_pack, c_train);

 curr_row = table( ...
 eta1_now, ...
 eta2_now, ...
 R.k_star, ...
 R.T1_star, ...
 R.T2_star, ...
 R.A1_share, ...
 R.A2_share, ...
 R.A3_share, ...
 R.Opportunity_loss_USD, ...
 R.Verification_cost_USD, ...
 R.Risk_penalty_USD, ...
 R.Information_cost_USD, ...
 R.Total_cost_USD, ...
 R.Total_cost_per_pack_USD, ...
 R.Decision_loss_per_pack_USD, ...
 'VariableNames', { ...
 'Eta_1', ...
 'Eta_2_fixed', ...
 'k_star', ...
 'T1_star', ...
 'T2_star', ...
 'A1_share', ...
 'A2_share', ...
 'A3_share', ...
 'Opportunity_loss_USD', ...
 'Verification_cost_USD', ...
 'Risk_penalty_USD', ...
 'Information_cost_USD', ...
 'Total_cost_USD', ...
 'Total_cost_per_pack_USD', ...
 'Decision_loss_per_pack_USD'});

 Result_Eta1_reopt = [Result_Eta1_reopt; curr_row]; %#ok<AGROW>
 end

 for ii = 1:numel(Eta_2_list)

 eta1_now = Eta_1_base;
 eta2_now = Eta_2_list(ii);

 fprintf('[Eta2 reopt] %d / %d | eta_1 = %.2f, eta_2 = %.2f\n', ...
 ii, numel(Eta_2_list), eta1_now, eta2_now);

 R = local_reoptimize_policy( ...
 eta1_now, eta2_now, ...
 s_true, Pi_True, Pi_True_Max, True_Action_i, ...
 k_vals, T1_grid, T2_grid, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, ...
 base_u, base_z, base_pick, base_bridge, ...
 Lambda_A, Lambda_R, ...
 Fixed_Scale_N, c_pack, c_train);

 curr_row = table( ...
 eta1_now, ...
 eta2_now, ...
 R.k_star, ...
 R.T1_star, ...
 R.T2_star, ...
 R.A1_share, ...
 R.A2_share, ...
 R.A3_share, ...
 R.Opportunity_loss_USD, ...
 R.Verification_cost_USD, ...
 R.Risk_penalty_USD, ...
 R.Information_cost_USD, ...
 R.Total_cost_USD, ...
 R.Total_cost_per_pack_USD, ...
 R.Decision_loss_per_pack_USD, ...
 'VariableNames', { ...
 'Eta_1_fixed', ...
 'Eta_2', ...
 'k_star', ...
 'T1_star', ...
 'T2_star', ...
 'A1_share', ...
 'A2_share', ...
 'A3_share', ...
 'Opportunity_loss_USD', ...
 'Verification_cost_USD', ...
 'Risk_penalty_USD', ...
 'Information_cost_USD', ...
 'Total_cost_USD', ...
 'Total_cost_per_pack_USD', ...
 'Decision_loss_per_pack_USD'});

 Result_Eta2_reopt = [Result_Eta2_reopt; curr_row]; %#ok<AGROW>
 end
end

%% 8) Build fixed-policy versus re-optimized comparison tables
if cfg.do_reoptimize

 Compare_Eta1 = table( ...
 Result_Eta1_fixed.Eta_1, ...
 Result_Eta1_fixed.Total_cost_per_pack_USD, ...
 Result_Eta1_reopt.Total_cost_per_pack_USD, ...
 Result_Eta1_fixed.Fixed_k, ...
 Result_Eta1_reopt.k_star, ...
 Result_Eta1_reopt.T1_star, ...
 Result_Eta1_reopt.T2_star, ...
 'VariableNames', { ...
 'Eta_1', ...
 'Fixed_policy_cost_per_pack_USD', ...
 'Reoptimized_cost_per_pack_USD', ...
 'Fixed_k', ...
 'Reoptimized_k_star', ...
 'Reoptimized_T1_star', ...
 'Reoptimized_T2_star'});

 Compare_Eta2 = table( ...
 Result_Eta2_fixed.Eta_2, ...
 Result_Eta2_fixed.Total_cost_per_pack_USD, ...
 Result_Eta2_reopt.Total_cost_per_pack_USD, ...
 Result_Eta2_fixed.Fixed_k, ...
 Result_Eta2_reopt.k_star, ...
 Result_Eta2_reopt.T1_star, ...
 Result_Eta2_reopt.T2_star, ...
 'VariableNames', { ...
 'Eta_2', ...
 'Fixed_policy_cost_per_pack_USD', ...
 'Reoptimized_cost_per_pack_USD', ...
 'Fixed_k', ...
 'Reoptimized_k_star', ...
 'Reoptimized_T1_star', ...
 'Reoptimized_T2_star'});
else
 Compare_Eta1 = table();
 Compare_Eta2 = table();
end

%% 9) Save result tables
writetable(Result_Eta1_fixed, cfg.eta1_fixed_csv);
writetable(Result_Eta2_fixed, cfg.eta2_fixed_csv);

fprintf('Eta1 fixed-policy table saved: %s\n', cfg.eta1_fixed_csv);
fprintf('Eta2 fixed-policy table saved: %s\n', cfg.eta2_fixed_csv);

if cfg.do_reoptimize
 writetable(Result_Eta1_reopt, cfg.eta1_reopt_csv);
 writetable(Result_Eta2_reopt, cfg.eta2_reopt_csv);
 writetable(Compare_Eta1, cfg.eta1_compare_csv);
 writetable(Compare_Eta2, cfg.eta2_compare_csv);

 fprintf('Eta1 re-optimized table saved: %s\n', cfg.eta1_reopt_csv);
 fprintf('Eta2 re-optimized table saved: %s\n', cfg.eta2_reopt_csv);
 fprintf('Eta1 comparison table saved: %s\n', cfg.eta1_compare_csv);
 fprintf('Eta2 comparison table saved: %s\n', cfg.eta2_compare_csv);
end

%% 10) Generate and save figures
eta_xlim = [0 120];
eta_ticks = 0:20:120;

%% Supplementary Fig. 19a: Eta_1 severe-trigger rate composition
fig1 = figure( ...
 'Name', 'SupFig19a_LFP_gray_zone_Eta1_trigger_rate_composition', ...
 'Color', 'w', ...
 'Position', [100, 80, 760, 560]);

x = Result_Eta1_fixed.Eta_1;

Ybar = [ ...
 Result_Eta1_fixed.A3toA2_trigger_rate_total, ...
 Result_Eta1_fixed.A2toA3_trigger_rate_total];

Ytotal = Result_Eta1_fixed.G1_trigger_rate_total;
Ycond = Result_Eta1_fixed.G1_trigger_rate_conditional;

yyaxis left

b = bar(x, Ybar, 'stacked', ...
 'EdgeColor', 'none', ...
 'BarWidth', 0.70);

hold on;

b(1).FaceColor = [0.18 0.50 0.78];
b(2).FaceColor = [0.90 0.38 0.12];

hTotal = plot(x, Ytotal, '-k', ...
 'LineWidth', 2.4, ...
 'Marker', 'o', ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

ylabel('Severe-trigger rate among all packs');

yl = max(Ytotal(x <= eta_xlim(2))) * 1.25;

if yl <= 0
 yl = 0.01;
end

ylim([0 yl]);

yyaxis right

hCond = plot(x, Ycond, '--', ...
 'Color', [0.35 0.35 0.35], ...
 'LineWidth', 1.8, ...
 'Marker', 'd', ...
 'MarkerSize', 5, ...
 'MarkerFaceColor', 'w');

ylabel('Severe-trigger rate among G1 errors');
ylim([0 1.05]);

xline(Eta_1_base, '--', 'Baseline', ...
 'LineWidth', 1.2, ...
 'LabelVerticalAlignment', 'bottom', ...
 'HandleVisibility', 'off');

grid on;
box on;

xlabel('\eta_1');
title('G1 severe-trigger rate under \eta_1 sensitivity');

legend([b(1), b(2), hTotal, hCond], ...
 {'A3 \rightarrow A2', ...
 'A2 \rightarrow A3', ...
 'Total severe G1 triggers / all packs', ...
 'Severe G1 triggers / all G1 errors'}, ...
 'Location', 'northeast', ...
 'Box', 'off');

xlim(eta_xlim);
xticks(eta_ticks);

set(gca, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0);

local_save_figure(fig1, cfg.fig_eta1_trigger, cfg.png_eta1_trigger, cfg.png_resolution);

%% Supplementary Fig. 19b: Eta_1 penalty-cost composition
fig2 = figure( ...
 'Name', 'SupFig19b_LFP_gray_zone_Eta1_penalty_cost_composition', ...
 'Color', 'w', ...
 'Position', [140, 100, 760, 560]);

x = Result_Eta1_fixed.Eta_1;

Ybar_cost = [ ...
 Result_Eta1_fixed.A3toA2_penalty_cost_USD, ...
 Result_Eta1_fixed.A2toA3_penalty_cost_USD] ./ 1e4;

Ytotal_cost = (Result_Eta1_fixed.Verification_cost_USD + ...
 Result_Eta1_fixed.Risk_penalty_USD) ./ 1e4;

Yveri = Result_Eta1_fixed.Verification_cost_USD ./ 1e4;
Yrisk = Result_Eta1_fixed.Risk_penalty_USD ./ 1e4;

yyaxis left

b = bar(x, Ybar_cost, 'stacked', ...
 'EdgeColor', 'none', ...
 'BarWidth', 0.70);

hold on;

b(1).FaceColor = [0.18 0.50 0.78];
b(2).FaceColor = [0.90 0.38 0.12];

hTotal = plot(x, Ytotal_cost, '-k', ...
 'LineWidth', 2.4, ...
 'Marker', 'o', ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

ylabel('Penalty-related cost (10^4 USD)');

yl = max(Ytotal_cost(x <= eta_xlim(2))) * 1.25;

if yl <= 0
 yl = 0.01;
end

ylim([0 yl]);

yyaxis right

hV = plot(x, Yveri, '--', ...
 'LineWidth', 1.6, ...
 'Marker', 's', ...
 'MarkerSize', 5, ...
 'MarkerFaceColor', 'w');

hold on;

hR = plot(x, Yrisk, ':', ...
 'LineWidth', 1.8, ...
 'Marker', '^', ...
 'MarkerSize', 5, ...
 'MarkerFaceColor', 'w');

ylabel('Verification / risk cost (10^4 USD)');

yl2 = max([Yveri(x <= eta_xlim(2)); Yrisk(x <= eta_xlim(2))]) * 1.25;

if yl2 <= 0
 yl2 = 0.01;
end

ylim([0 yl2]);

xline(Eta_1_base, '--', 'Baseline', ...
 'LineWidth', 1.2, ...
 'LabelVerticalAlignment', 'bottom', ...
 'HandleVisibility', 'off');

grid on;
box on;

xlabel('\eta_1');
title('Penalty-related cost under \eta_1 sensitivity');

legend([b(1), b(2), hTotal, hV, hR], ...
 {'A3 \rightarrow A2 penalty', ...
 'A2 \rightarrow A3 penalty', ...
 'Total verification + risk cost', ...
 'Verification cost', ...
 'Risk penalty'}, ...
 'Location', 'northeast', ...
 'Box', 'off');

xlim(eta_xlim);
xticks(eta_ticks);

set(gca, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0);

local_save_figure(fig2, cfg.fig_eta1_cost, cfg.png_eta1_cost, cfg.png_resolution);

%% Supplementary Fig. 19c: Eta_2 severe-trigger rate composition
fig3 = figure( ...
 'Name', 'SupFig19c_LFP_gray_zone_Eta2_trigger_rate_composition', ...
 'Color', 'w', ...
 'Position', [180, 120, 760, 560]);

x = Result_Eta2_fixed.Eta_2;

Ybar = [ ...
 Result_Eta2_fixed.A1toA2_trigger_rate_total, ...
 Result_Eta2_fixed.A2toA1_trigger_rate_total];

Ytotal = Result_Eta2_fixed.G2_trigger_rate_total;
Ycond = Result_Eta2_fixed.G2_trigger_rate_conditional;

yyaxis left

b = bar(x, Ybar, 'stacked', ...
 'EdgeColor', 'none', ...
 'BarWidth', 0.70);

hold on;

b(1).FaceColor = [0.18 0.50 0.78];
b(2).FaceColor = [0.90 0.38 0.12];

hTotal = plot(x, Ytotal, '-k', ...
 'LineWidth', 2.4, ...
 'Marker', 'o', ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

ylabel('Severe-trigger rate among all packs');

yl = max(Ytotal(x <= eta_xlim(2))) * 1.25;

if yl <= 0
 yl = 0.01;
end

ylim([0 yl]);

yyaxis right

hCond = plot(x, Ycond, '--', ...
 'Color', [0.35 0.35 0.35], ...
 'LineWidth', 1.8, ...
 'Marker', 'd', ...
 'MarkerSize', 5, ...
 'MarkerFaceColor', 'w');

ylabel('Severe-trigger rate among G2 errors');
ylim([0 1.05]);

xline(Eta_2_base, '--', 'Baseline', ...
 'LineWidth', 1.2, ...
 'LabelVerticalAlignment', 'bottom', ...
 'HandleVisibility', 'off');

grid on;
box on;

xlabel('\eta_2');
title('G2 severe-trigger rate under \eta_2 sensitivity');

legend([b(1), b(2), hTotal, hCond], ...
 {'A1 \rightarrow A2', ...
 'A2 \rightarrow A1', ...
 'Total severe G2 triggers / all packs', ...
 'Severe G2 triggers / all G2 errors'}, ...
 'Location', 'northeast', ...
 'Box', 'off');

xlim(eta_xlim);
xticks(eta_ticks);

set(gca, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0);

local_save_figure(fig3, cfg.fig_eta2_trigger, cfg.png_eta2_trigger, cfg.png_resolution);

%% Supplementary Fig. 19d: Eta_2 penalty-cost composition
fig4 = figure( ...
 'Name', 'SupFig19d_LFP_gray_zone_Eta2_penalty_cost_composition', ...
 'Color', 'w', ...
 'Position', [220, 140, 760, 560]);

x = Result_Eta2_fixed.Eta_2;

Ybar_cost = [ ...
 Result_Eta2_fixed.A1toA2_penalty_cost_USD, ...
 Result_Eta2_fixed.A2toA1_penalty_cost_USD] ./ 1e4;

Ytotal_cost = (Result_Eta2_fixed.Verification_cost_USD + ...
 Result_Eta2_fixed.Risk_penalty_USD) ./ 1e4;

Yveri = Result_Eta2_fixed.Verification_cost_USD ./ 1e4;
Yrisk = Result_Eta2_fixed.Risk_penalty_USD ./ 1e4;

yyaxis left

b = bar(x, Ybar_cost, 'stacked', ...
 'EdgeColor', 'none', ...
 'BarWidth', 0.70);

hold on;

b(1).FaceColor = [0.18 0.50 0.78];
b(2).FaceColor = [0.90 0.38 0.12];

hTotal = plot(x, Ytotal_cost, '-k', ...
 'LineWidth', 2.4, ...
 'Marker', 'o', ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

ylabel('Penalty-related cost (10^4 USD)');

yl = max(Ytotal_cost(x <= eta_xlim(2))) * 1.25;

if yl <= 0
 yl = 0.01;
end

ylim([0 yl]);

yyaxis right

hV = plot(x, Yveri, '--', ...
 'LineWidth', 1.6, ...
 'Marker', 's', ...
 'MarkerSize', 5, ...
 'MarkerFaceColor', 'w');

hold on;

hR = plot(x, Yrisk, ':', ...
 'LineWidth', 1.8, ...
 'Marker', '^', ...
 'MarkerSize', 5, ...
 'MarkerFaceColor', 'w');

ylabel('Verification / risk cost (10^4 USD)');

yl2 = max([Yveri(x <= eta_xlim(2)); Yrisk(x <= eta_xlim(2))]) * 1.25;

if yl2 <= 0
 yl2 = 0.01;
end

ylim([0 yl2]);

xline(Eta_2_base, '--', 'Baseline', ...
 'LineWidth', 1.2, ...
 'LabelVerticalAlignment', 'bottom', ...
 'HandleVisibility', 'off');

grid on;
box on;

xlabel('\eta_2');
title('Penalty-related cost under \eta_2 sensitivity');

legend([b(1), b(2), hTotal, hV, hR], ...
 {'A1 \rightarrow A2 penalty', ...
 'A2 \rightarrow A1 penalty', ...
 'Total verification + risk cost', ...
 'Verification cost', ...
 'Risk penalty'}, ...
 'Location', 'northeast', ...
 'Box', 'off');

xlim(eta_xlim);
xticks(eta_ticks);

set(gca, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0);

local_save_figure(fig4, cfg.fig_eta2_cost, cfg.png_eta2_cost, cfg.png_resolution);

%% Supplementary Fig. 19e: Fixed-policy versus re-optimized policy under eta_1
if cfg.do_reoptimize

 fig5a = figure( ...
 'Name', 'SupFig19e_LFP_gray_zone_fixed_vs_reoptimized_Eta1', ...
 'Color', 'w', ...
 'Position', [260, 160, 760, 560]);

 plot(Compare_Eta1.Eta_1, Compare_Eta1.Fixed_policy_cost_per_pack_USD, '-o', ...
 'LineWidth', 2.0, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

 hold on;

 plot(Compare_Eta1.Eta_1, Compare_Eta1.Reoptimized_cost_per_pack_USD, '-s', ...
 'LineWidth', 2.0, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

 xline(Eta_1_base, '--', 'Baseline', ...
 'LineWidth', 1.2, ...
 'LabelVerticalAlignment', 'bottom', ...
 'HandleVisibility', 'off');

 grid on;
 box on;

 xlabel('\eta_1');
 ylabel('Total cost (USD per pack)');
 title('Fixed baseline policy vs re-optimized policy under \eta_1 sensitivity');

 legend({'Fixed baseline policy', 'Re-optimized policy'}, ...
 'Location', 'best', ...
 'Box', 'off');

 xlim(eta_xlim);
 xticks(eta_ticks);

 set(gca, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0);

 local_save_figure(fig5a, cfg.fig_eta1_compare, cfg.png_eta1_compare, cfg.png_resolution);

 %% Supplementary Fig. 19f: Fixed-policy versus re-optimized policy under eta_2
 fig5b = figure( ...
 'Name', 'SupFig19f_LFP_gray_zone_fixed_vs_reoptimized_Eta2', ...
 'Color', 'w', ...
 'Position', [300, 180, 760, 560]);

 plot(Compare_Eta2.Eta_2, Compare_Eta2.Fixed_policy_cost_per_pack_USD, '-o', ...
 'LineWidth', 2.0, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

 hold on;

 plot(Compare_Eta2.Eta_2, Compare_Eta2.Reoptimized_cost_per_pack_USD, '-s', ...
 'LineWidth', 2.0, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w');

 xline(Eta_2_base, '--', 'Baseline', ...
 'LineWidth', 1.2, ...
 'LabelVerticalAlignment', 'bottom', ...
 'HandleVisibility', 'off');

 grid on;
 box on;

 xlabel('\eta_2');
 ylabel('Total cost (USD per pack)');
 title('Fixed baseline policy vs re-optimized policy under \eta_2 sensitivity');

 legend({'Fixed baseline policy', 'Re-optimized policy'}, ...
 'Location', 'best', ...
 'Box', 'off');

 xlim(eta_xlim);
 xticks(eta_ticks);

 set(gca, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0);

 local_save_figure(fig5b, cfg.fig_eta2_compare, cfg.png_eta2_compare, cfg.png_resolution);
end

drawnow;

%% 11) Save MAT result file
save(cfg.result_mat, ...
 'cfg', ...
 'Result_Eta1_fixed', ...
 'Result_Eta2_fixed', ...
 'Result_Eta1_reopt', ...
 'Result_Eta2_reopt', ...
 'Compare_Eta1', ...
 'Compare_Eta2', ...
 'Eta_1_list', ...
 'Eta_2_list', ...
 'Eta_1_base', ...
 'Eta_2_base', ...
 'Lambda_A', ...
 'Lambda_R', ...
 'opt_k', ...
 'opt_T1', ...
 'opt_T2', ...
 'A1_share_fixed', ...
 'A2_share_fixed', ...
 'A3_share_fixed', ...
 'True_A1_share', ...
 'True_A2_share', ...
 'True_A3_share', ...
 'Fixed_Scale_N', ...
 'Information_cost_fixed', ...
 's_true', ...
 's_pred_fixed', ...
 'Pred_Action_fixed', ...
 'True_Action_i', ...
 'O_arr_fixed', ...
 'Chosen_Value_fixed', ...
 'is_G1_error_fixed', ...
 'is_G2_error_fixed', ...
 'is_other_error_fixed', ...
 '-v7.3');

fprintf('\n>>> P4 Exp10 LFP gray-zone tolerance mechanism completed.\n');
fprintf('>>> Eta1 fixed-policy table saved: %s\n', cfg.eta1_fixed_csv);
fprintf('>>> Eta2 fixed-policy table saved: %s\n', cfg.eta2_fixed_csv);

if cfg.do_reoptimize
 fprintf('>>> Eta1 re-optimized table saved: %s\n', cfg.eta1_reopt_csv);
 fprintf('>>> Eta2 re-optimized table saved: %s\n', cfg.eta2_reopt_csv);
 fprintf('>>> Eta1 comparison table saved: %s\n', cfg.eta1_compare_csv);
 fprintf('>>> Eta2 comparison table saved: %s\n', cfg.eta2_compare_csv);
end

fprintf('>>> MAT result file saved: %s\n', cfg.result_mat);
fprintf('>>> Figures saved in: %s\n', cfg.supp_fig_dir);
fprintf('================ P4 Exp10 completed ================\n');

%% Local helper functions
function M = local_evaluate_eta_policy( ...
 eta1_now, ...
 eta2_now, ...
 O_arr, ...
 risk_indicator, ...
 is_G1_error, ...
 is_G2_error, ...
 is_other_error, ...
 is_A3_to_A2, ...
 is_A2_to_A3, ...
 is_A1_to_A2, ...
 is_A2_to_A1, ...
 Lambda_A, ...
 Lambda_R, ...
 Fixed_Scale_N, ...
 Information_cost)
% Evaluate trigger rates and cost terms for a fixed decision population.

N_sim = numel(O_arr);

Current_Eta = zeros(N_sim, 1);
Current_Eta(is_G1_error) = eta1_now;
Current_Eta(is_G2_error) = eta2_now;

trigger_penalty = O_arr > Current_Eta;
Excess_Loss = max(0, O_arr - Current_Eta);

A_arr = trigger_penalty .* Lambda_A;
R_arr = risk_indicator .* trigger_penalty .* (Lambda_R .* Excess_Loss);

penalty_cost_arr = A_arr + R_arr;

M = struct();

% Error rates.
M.G1_error_rate_total = mean(is_G1_error);
M.G2_error_rate_total = mean(is_G2_error);
M.Other_error_rate_total = mean(is_other_error);

% Trigger rates.
M.G1_trigger_rate_total = mean(is_G1_error & trigger_penalty);
M.G2_trigger_rate_total = mean(is_G2_error & trigger_penalty);
M.Other_trigger_rate_total = mean(is_other_error & trigger_penalty);

M.G1_trigger_rate_conditional = local_conditional_rate(is_G1_error, trigger_penalty);
M.G2_trigger_rate_conditional = local_conditional_rate(is_G2_error, trigger_penalty);

M.A3toA2_trigger_rate_total = mean(is_A3_to_A2 & trigger_penalty);
M.A2toA3_trigger_rate_total = mean(is_A2_to_A3 & trigger_penalty);
M.A1toA2_trigger_rate_total = mean(is_A1_to_A2 & trigger_penalty);
M.A2toA1_trigger_rate_total = mean(is_A2_to_A1 & trigger_penalty);

M.A3toA2_trigger_rate_conditional = local_conditional_rate(is_A3_to_A2, trigger_penalty);
M.A2toA3_trigger_rate_conditional = local_conditional_rate(is_A2_to_A3, trigger_penalty);
M.A1toA2_trigger_rate_conditional = local_conditional_rate(is_A1_to_A2, trigger_penalty);
M.A2toA1_trigger_rate_conditional = local_conditional_rate(is_A2_to_A1, trigger_penalty);

M.Overall_trigger_rate = mean(trigger_penalty);
M.Risk_trigger_rate = mean(risk_indicator & trigger_penalty);

% Cost terms.
M.Opportunity_loss_USD = Fixed_Scale_N * mean(O_arr);
M.Verification_cost_USD = Fixed_Scale_N * mean(A_arr);
M.Risk_penalty_USD = Fixed_Scale_N * mean(R_arr);

M.A3toA2_penalty_cost_USD = Fixed_Scale_N * mean(penalty_cost_arr .* is_A3_to_A2);
M.A2toA3_penalty_cost_USD = Fixed_Scale_N * mean(penalty_cost_arr .* is_A2_to_A3);
M.A1toA2_penalty_cost_USD = Fixed_Scale_N * mean(penalty_cost_arr .* is_A1_to_A2);
M.A2toA1_penalty_cost_USD = Fixed_Scale_N * mean(penalty_cost_arr .* is_A2_to_A1);
M.Other_penalty_cost_USD = Fixed_Scale_N * mean(penalty_cost_arr .* is_other_error);

M.Total_decision_loss_USD = ...
 M.Opportunity_loss_USD + ...
 M.Verification_cost_USD + ...
 M.Risk_penalty_USD;

M.Information_cost_USD = Information_cost;

M.Total_cost_USD = ...
 M.Total_decision_loss_USD + ...
 M.Information_cost_USD;

M.Total_cost_per_pack_USD = M.Total_cost_USD / Fixed_Scale_N;
end

function r = local_conditional_rate(mask, trigger)
% Compute the trigger rate conditional on a specified error mask.

den = sum(mask);

if den > 0
 r = sum(mask & trigger) / den;
else
 r = NaN;
end
end

function row = local_build_fixed_row( ...
 eta1_now, eta2_now, opt_k, opt_T1, opt_T2, ...
 A1_share_fixed, A2_share_fixed, A3_share_fixed, M, mode_name)
% Build one row for the fixed-policy eta-sensitivity table.

if mode_name == "Eta1"

 row = table( ...
 eta1_now, ...
 eta2_now, ...
 opt_k, ...
 opt_T1, ...
 opt_T2, ...
 A1_share_fixed, ...
 A2_share_fixed, ...
 A3_share_fixed, ...
 M.G1_error_rate_total, ...
 M.G1_trigger_rate_total, ...
 M.G1_trigger_rate_conditional, ...
 M.A3toA2_trigger_rate_total, ...
 M.A2toA3_trigger_rate_total, ...
 M.A3toA2_trigger_rate_conditional, ...
 M.A2toA3_trigger_rate_conditional, ...
 M.G2_error_rate_total, ...
 M.G2_trigger_rate_total, ...
 M.G2_trigger_rate_conditional, ...
 M.A1toA2_trigger_rate_total, ...
 M.A2toA1_trigger_rate_total, ...
 M.A1toA2_trigger_rate_conditional, ...
 M.A2toA1_trigger_rate_conditional, ...
 M.Other_error_rate_total, ...
 M.Other_trigger_rate_total, ...
 M.Overall_trigger_rate, ...
 M.Risk_trigger_rate, ...
 M.Opportunity_loss_USD, ...
 M.Verification_cost_USD, ...
 M.Risk_penalty_USD, ...
 M.A3toA2_penalty_cost_USD, ...
 M.A2toA3_penalty_cost_USD, ...
 M.A1toA2_penalty_cost_USD, ...
 M.A2toA1_penalty_cost_USD, ...
 M.Other_penalty_cost_USD, ...
 M.Total_decision_loss_USD, ...
 M.Information_cost_USD, ...
 M.Total_cost_USD, ...
 M.Total_cost_per_pack_USD, ...
 'VariableNames', { ...
 'Eta_1', ...
 'Eta_2_fixed', ...
 'Fixed_k', ...
 'Fixed_T1', ...
 'Fixed_T2', ...
 'A1_share', ...
 'A2_share', ...
 'A3_share', ...
 'G1_error_rate_total', ...
 'G1_trigger_rate_total', ...
 'G1_trigger_rate_conditional', ...
 'A3toA2_trigger_rate_total', ...
 'A2toA3_trigger_rate_total', ...
 'A3toA2_trigger_rate_conditional', ...
 'A2toA3_trigger_rate_conditional', ...
 'G2_error_rate_total', ...
 'G2_trigger_rate_total', ...
 'G2_trigger_rate_conditional', ...
 'A1toA2_trigger_rate_total', ...
 'A2toA1_trigger_rate_total', ...
 'A1toA2_trigger_rate_conditional', ...
 'A2toA1_trigger_rate_conditional', ...
 'Other_error_rate_total', ...
 'Other_trigger_rate_total', ...
 'Overall_trigger_rate', ...
 'Risk_trigger_rate', ...
 'Opportunity_loss_USD', ...
 'Verification_cost_USD', ...
 'Risk_penalty_USD', ...
 'A3toA2_penalty_cost_USD', ...
 'A2toA3_penalty_cost_USD', ...
 'A1toA2_penalty_cost_USD', ...
 'A2toA1_penalty_cost_USD', ...
 'Other_penalty_cost_USD', ...
 'Total_decision_loss_USD', ...
 'Information_cost_USD', ...
 'Total_cost_USD', ...
 'Total_cost_per_pack_USD'});

else

 row = table( ...
 eta1_now, ...
 eta2_now, ...
 opt_k, ...
 opt_T1, ...
 opt_T2, ...
 A1_share_fixed, ...
 A2_share_fixed, ...
 A3_share_fixed, ...
 M.G1_error_rate_total, ...
 M.G1_trigger_rate_total, ...
 M.G1_trigger_rate_conditional, ...
 M.A3toA2_trigger_rate_total, ...
 M.A2toA3_trigger_rate_total, ...
 M.A3toA2_trigger_rate_conditional, ...
 M.A2toA3_trigger_rate_conditional, ...
 M.G2_error_rate_total, ...
 M.G2_trigger_rate_total, ...
 M.G2_trigger_rate_conditional, ...
 M.A1toA2_trigger_rate_total, ...
 M.A2toA1_trigger_rate_total, ...
 M.A1toA2_trigger_rate_conditional, ...
 M.A2toA1_trigger_rate_conditional, ...
 M.Other_error_rate_total, ...
 M.Other_trigger_rate_total, ...
 M.Overall_trigger_rate, ...
 M.Risk_trigger_rate, ...
 M.Opportunity_loss_USD, ...
 M.Verification_cost_USD, ...
 M.Risk_penalty_USD, ...
 M.A3toA2_penalty_cost_USD, ...
 M.A2toA3_penalty_cost_USD, ...
 M.A1toA2_penalty_cost_USD, ...
 M.A2toA1_penalty_cost_USD, ...
 M.Other_penalty_cost_USD, ...
 M.Total_decision_loss_USD, ...
 M.Information_cost_USD, ...
 M.Total_cost_USD, ...
 M.Total_cost_per_pack_USD, ...
 'VariableNames', { ...
 'Eta_1_fixed', ...
 'Eta_2', ...
 'Fixed_k', ...
 'Fixed_T1', ...
 'Fixed_T2', ...
 'A1_share', ...
 'A2_share', ...
 'A3_share', ...
 'G1_error_rate_total', ...
 'G1_trigger_rate_total', ...
 'G1_trigger_rate_conditional', ...
 'A3toA2_trigger_rate_total', ...
 'A2toA3_trigger_rate_total', ...
 'A3toA2_trigger_rate_conditional', ...
 'A2toA3_trigger_rate_conditional', ...
 'G2_error_rate_total', ...
 'G2_trigger_rate_total', ...
 'G2_trigger_rate_conditional', ...
 'A1toA2_trigger_rate_total', ...
 'A2toA1_trigger_rate_total', ...
 'A1toA2_trigger_rate_conditional', ...
 'A2toA1_trigger_rate_conditional', ...
 'Other_error_rate_total', ...
 'Other_trigger_rate_total', ...
 'Overall_trigger_rate', ...
 'Risk_trigger_rate', ...
 'Opportunity_loss_USD', ...
 'Verification_cost_USD', ...
 'Risk_penalty_USD', ...
 'A3toA2_penalty_cost_USD', ...
 'A2toA3_penalty_cost_USD', ...
 'A1toA2_penalty_cost_USD', ...
 'A2toA1_penalty_cost_USD', ...
 'Other_penalty_cost_USD', ...
 'Total_decision_loss_USD', ...
 'Information_cost_USD', ...
 'Total_cost_USD', ...
 'Total_cost_per_pack_USD'});
end
end

function R = local_reoptimize_policy( ...
 eta1_now, eta2_now, ...
 s_true, Pi_True, Pi_True_Max, True_Action_i, ...
 k_vals, T1_grid, T2_grid, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, ...
 base_u, base_z, base_pick, base_bridge, ...
 Lambda_A, Lambda_R, ...
 Fixed_Scale_N, c_pack, c_train)
% Re-optimize k, T1, and T2 for one eta setting.

N_sim = numel(s_true);

best_total_cost = inf;

R = struct();
R.k_star = NaN;
R.T1_star = NaN;
R.T2_star = NaN;
R.A1_share = NaN;
R.A2_share = NaN;
R.A3_share = NaN;
R.Opportunity_loss_USD = NaN;
R.Verification_cost_USD = NaN;
R.Risk_penalty_USD = NaN;
R.Information_cost_USD = NaN;
R.Total_cost_USD = NaN;
R.Total_cost_per_pack_USD = NaN;
R.Decision_loss_per_pack_USD = NaN;

for kk = 1:numel(k_vals)

 k_current = k_vals(kk);

 sampled_noise = local_build_noise_by_k( ...
 k_current, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

 s_pred = min(max(s_true + sampled_noise, 0), 1.0);

 best_decision_loss_k = inf;

 best_T1_k = NaN;
 best_T2_k = NaN;
 best_O_k = NaN;
 best_A_k = NaN;
 best_R_k = NaN;
 best_Pred_Action_k = [];

 for i_t1 = 1:numel(T1_grid)

 T1 = T1_grid(i_t1);

 for i_t2 = 1:numel(T2_grid)

 T2 = T2_grid(i_t2);

 if T1 >= T2
 continue;
 end

 Pred_Action = 3 * ones(N_sim, 1);
 Pred_Action(s_pred >= T1 & s_pred < T2) = 2;
 Pred_Action(s_pred >= T2) = 1;

 idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action);
 O_arr = Pi_True_Max - Pi_True(idx_pred);

 is_G1_error = ...
 (True_Action_i == 3 & Pred_Action == 2) | ...
 (True_Action_i == 2 & Pred_Action == 3);

 is_G2_error = ...
 (True_Action_i == 1 & Pred_Action == 2) | ...
 (True_Action_i == 2 & Pred_Action == 1);

 Current_Eta = zeros(N_sim, 1);
 Current_Eta(is_G1_error) = eta1_now;
 Current_Eta(is_G2_error) = eta2_now;

 trigger_penalty = O_arr > Current_Eta;
 Excess_Loss = max(0, O_arr - Current_Eta);

 A_arr = trigger_penalty .* Lambda_A;
 R_arr = (Pred_Action < True_Action_i) .* ...
 trigger_penalty .* (Lambda_R .* Excess_Loss);

 decision_loss = mean(O_arr + A_arr + R_arr);

 if decision_loss < best_decision_loss_k

 best_decision_loss_k = decision_loss;
 best_T1_k = T1;
 best_T2_k = T2;

 best_O_k = mean(O_arr);
 best_A_k = mean(A_arr);
 best_R_k = mean(R_arr);
 best_Pred_Action_k = Pred_Action;
 end
 end
 end

 information_cost_k = k_current * c_pack + c_train;

 total_cost_k = ...
 Fixed_Scale_N * best_decision_loss_k + ...
 information_cost_k;

 if total_cost_k < best_total_cost

 best_total_cost = total_cost_k;

 R.k_star = k_current;
 R.T1_star = best_T1_k;
 R.T2_star = best_T2_k;

 R.A1_share = mean(best_Pred_Action_k == 1);
 R.A2_share = mean(best_Pred_Action_k == 2);
 R.A3_share = mean(best_Pred_Action_k == 3);

 R.Opportunity_loss_USD = Fixed_Scale_N * best_O_k;
 R.Verification_cost_USD = Fixed_Scale_N * best_A_k;
 R.Risk_penalty_USD = Fixed_Scale_N * best_R_k;
 R.Information_cost_USD = information_cost_k;

 R.Total_cost_USD = best_total_cost;
 R.Total_cost_per_pack_USD = best_total_cost / Fixed_Scale_N;
 R.Decision_loss_per_pack_USD = best_decision_loss_k;
 end
end
end

function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
 mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end