%% P4_Exp03_chemistry_comparison_summary_plots.m
% Purpose:
% This script generates chemistry-comparison summary plots for fixed-scale
% LFP and NMC recertification economics.
%
% It reads the fixed-scale LFP and NMC optimization results generated by
% P4_Exp01 and P4_Exp02, compares the refurbishment-recycling value gap
% between chemistries, and visualizes the chemistry-driven pathway
% reallocation between LFP and NMC economics.

clear; clc; close all;

%% 1) Configuration and path setup
cfg = struct();

% Use the current script folder as the Part4 root folder.
script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

% Part4 folders.
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.main_fig_dir = fullfile(cfg.figure_root, 'Main');

% Input result files generated by Part4 Exp01 and Exp02.
cfg.lfp_result_mat = fullfile(cfg.results_dir, ...
    'P4_Exp01_FixedScale_LFP_Results.mat');

cfg.nmc_result_mat = fullfile(cfg.results_dir, ...
    'P4_Exp02_FixedScale_NMC_Results.mat');

% Legacy fallback files.
cfg.lfp_result_mat_legacy = fullfile(cfg.output_dir, ...
    'Result01_FixedScale_LFP_Results.mat');

cfg.nmc_result_mat_legacy = fullfile(cfg.output_dir, ...
    'Result02_FixedScale_NMC_Results.mat');

if ~exist(cfg.lfp_result_mat, 'file') && exist(cfg.lfp_result_mat_legacy, 'file')
    cfg.lfp_result_mat = cfg.lfp_result_mat_legacy;
end

if ~exist(cfg.nmc_result_mat, 'file') && exist(cfg.nmc_result_mat_legacy, 'file')
    cfg.nmc_result_mat = cfg.nmc_result_mat_legacy;
end

if ~exist(cfg.lfp_result_mat, 'file')
    error('LFP fixed-scale result file not found: %s', cfg.lfp_result_mat);
end

if ~exist(cfg.nmc_result_mat, 'file')
    error('NMC fixed-scale result file not found: %s', cfg.nmc_result_mat);
end

% Output tables generated by Part4 Exp03.
cfg.boundary_gap_csv = fullfile(cfg.results_dir, ...
    'P4_Exp03_ChemistryComparison_BoundaryGapZeroCrossings.csv');

cfg.representative_soh_csv = fullfile(cfg.results_dir, ...
    'P4_Exp03_ChemistryComparison_RepresentativeSOH.csv');

cfg.transition_csv = fullfile(cfg.results_dir, ...
    'P4_Exp03_ChemistryComparison_ActionTransitionMatrix.csv');

cfg.action_share_csv = fullfile(cfg.results_dir, ...
    'P4_Exp03_ChemistryComparison_ActionShares.csv');

% Output figure files for Main Fig. 3.
cfg.fig_value_gap = fullfile(cfg.main_fig_dir, ...
    'MainFig03d_refurbishment_recycling_value_gap.fig');

cfg.png_value_gap = fullfile(cfg.main_fig_dir, ...
    'MainFig03d_refurbishment_recycling_value_gap.png');

cfg.fig_alluvial = fullfile(cfg.main_fig_dir, ...
    'MainFig03c_LFP_NMC_action_share_reallocation.fig');

cfg.png_alluvial = fullfile(cfg.main_fig_dir, ...
    'MainFig03c_LFP_NMC_action_share_reallocation.png');

% Export settings.
cfg.png_resolution = 600;

% Create required folders.
folder_list = { ...
    cfg.output_dir, ...
    cfg.results_dir, ...
    cfg.figure_root, ...
    cfg.main_fig_dir};

for ii = 1:numel(folder_list)
    if ~exist(folder_list{ii}, 'dir')
        mkdir(folder_list{ii});
    end
end

fprintf('================ Part4 Exp03 chemistry-comparison summary plots ================\n');
fprintf('LFP fixed-scale result file: %s\n', cfg.lfp_result_mat);
fprintf('NMC fixed-scale result file: %s\n', cfg.nmc_result_mat);
fprintf('Main figure folder:          %s\n', cfg.main_fig_dir);

%% 2) Load fixed-scale optimization results
S_LFP = load(cfg.lfp_result_mat, 'LFP_fixed_result');
S_NMC = load(cfg.nmc_result_mat, 'NMC_fixed_result');

lfp = S_LFP.LFP_fixed_result;
nmc = S_NMC.NMC_fixed_result;

%% 3) Extract LFP action-value curves
if isfield(lfp, 'J_curve_net_value')
    V_LFP_raw = double(lfp.J_curve_net_value);
else
    error('J_curve_net_value was not found in LFP_fixed_result.');
end

if isfield(lfp, 'x_grid_net_value')
    s_LFP_raw = double(lfp.x_grid_net_value(:));
else
    s_LFP_raw = linspace(0.40, 1.00, size(V_LFP_raw, 2)).';
end

if size(V_LFP_raw, 1) ~= 3 && size(V_LFP_raw, 2) == 3
    V_LFP_raw = V_LFP_raw.';
end

%% 4) Extract NMC action-value curves
if isfield(nmc, 'G')
    V_NMC_raw = double(nmc.G);
elseif isfield(nmc, 'J_curve_net_value')
    V_NMC_raw = double(nmc.J_curve_net_value);
else
    error('Neither G nor J_curve_net_value was found in NMC_fixed_result.');
end

if isfield(nmc, 's_hat_grid')
    s_NMC_raw = double(nmc.s_hat_grid(:));
elseif isfield(nmc, 'x_grid_net_value')
    s_NMC_raw = double(nmc.x_grid_net_value(:));
else
    s_NMC_raw = linspace(0.40, 1.00, size(V_NMC_raw, 2)).';
end

if size(V_NMC_raw, 1) ~= 3 && size(V_NMC_raw, 2) == 3
    V_NMC_raw = V_NMC_raw.';
end

%% 5) Align SOH grids
s_min = max([0.40, min(s_LFP_raw), min(s_NMC_raw)]);
s_max = min([1.00, max(s_LFP_raw), max(s_NMC_raw)]);
s_common = (s_min:0.001:s_max).';

V_LFP = nan(numel(s_common), 3);
V_NMC = nan(numel(s_common), 3);

for ia = 1:3
    y_lfp = V_LFP_raw(ia, :).';
    idx_lfp = isfinite(s_LFP_raw) & isfinite(y_lfp);
    V_LFP(:, ia) = interp1(s_LFP_raw(idx_lfp), y_lfp(idx_lfp), ...
                           s_common, 'linear', nan);

    y_nmc = V_NMC_raw(ia, :).';
    idx_nmc = isfinite(s_NMC_raw) & isfinite(y_nmc);
    V_NMC(:, ia) = interp1(s_NMC_raw(idx_nmc), y_nmc(idx_nmc), ...
                           s_common, 'linear', nan);
end

%% 6) Compute adjacent-pathway value gaps
% A3/A2 boundary:
D32_LFP = V_LFP(:, 3) - V_LFP(:, 2);
D32_NMC = V_NMC(:, 3) - V_NMC(:, 2);

D12_LFP = V_LFP(:, 1) - V_LFP(:, 2);
D12_NMC = V_NMC(:, 1) - V_NMC(:, 2);

Shift_D32 = D32_NMC - D32_LFP;
Shift_D12 = D12_NMC - D12_LFP;

%% 7) Locate zero crossings of value-gap curves
curve_names = {'LFP D32 = A3-A2', 'NMC D32 = A3-A2', ...
               'LFP D12 = A1-A2', 'NMC D12 = A1-A2'};
curve_data = {D32_LFP, D32_NMC, D12_LFP, D12_NMC};

cross_info = cell(numel(curve_data), 2);

fprintf('\n========== Zero crossings of adjacent-pathway value gaps ==========\n');

for ic = 1:numel(curve_data)
    y = curve_data{ic};
    s_cross = [];

    for ii = 1:(numel(s_common) - 1)
        y1 = y(ii);
        y2 = y(ii + 1);

        if ~isfinite(y1) || ~isfinite(y2)
            continue;
        end

        if y1 == 0
            s0 = s_common(ii);
            s_cross = [s_cross, s0]; %#ok<AGROW>
        elseif y1 * y2 < 0
            s0 = s_common(ii) - y1 * (s_common(ii + 1) - s_common(ii)) / (y2 - y1);
            s_cross = [s_cross, s0]; %#ok<AGROW>
        end
    end

    s_cross = unique(round(s_cross, 4));

    if isempty(s_cross)
        cross_str = 'No zero crossing';
    else
        cross_str = strjoin(arrayfun(@(x) sprintf('%.4f', x), s_cross, 'UniformOutput', false), ', ');
    end

    cross_info{ic, 1} = curve_names{ic};
    cross_info{ic, 2} = cross_str;

    fprintf('%s: %s\n', curve_names{ic}, cross_str);
end

T_cross = cell2table(cross_info, 'VariableNames', {'Curve', 'ZeroCrossings_SOH'});
writetable(T_cross, cfg.boundary_gap_csv);

%% 8) Export boundary-gap values at representative SOH points
soh_rep = (0.4:0.1:1.0).';

D32_LFP_rep = interp1(s_common, D32_LFP, soh_rep, 'linear', nan);
D32_NMC_rep = interp1(s_common, D32_NMC, soh_rep, 'linear', nan);
Shift_D32_rep = interp1(s_common, Shift_D32, soh_rep, 'linear', nan);

D12_LFP_rep = interp1(s_common, D12_LFP, soh_rep, 'linear', nan);
D12_NMC_rep = interp1(s_common, D12_NMC, soh_rep, 'linear', nan);
Shift_D12_rep = interp1(s_common, Shift_D12, soh_rep, 'linear', nan);

T_rep = table(soh_rep, ...
              D32_LFP_rep, D32_NMC_rep, Shift_D32_rep, ...
              D12_LFP_rep, D12_NMC_rep, Shift_D12_rep, ...
              'VariableNames', {'SOH', ...
              'D32_LFP_A3minusA2', 'D32_NMC_A3minusA2', 'Shift_D32_NMCminusLFP', ...
              'D12_LFP_A1minusA2', 'D12_NMC_A1minusA2', 'Shift_D12_NMCminusLFP'});

disp(' ');
disp('========== Boundary gaps at representative SOH values ==========');
disp(T_rep);

writetable(T_rep, cfg.representative_soh_csv);

%% 9) Plot the recycling-refurbishment value gap
color_LFP = [0.000, 0.447, 0.741];
color_NMC = [0.850, 0.325, 0.098];
color_fill = [0.85, 0.85, 0.85];

%% 9.1 Locate the D32 zero crossings
s_T1_LFP = NaN;
s_T1_NMC = NaN;

for ii = 1:(numel(s_common) - 1)
    y1 = D32_LFP(ii);
    y2 = D32_LFP(ii + 1);

    if isfinite(y1) && isfinite(y2) && y1 * y2 <= 0
        s_T1_LFP = s_common(ii) - y1 * (s_common(ii + 1) - s_common(ii)) / (y2 - y1);
        break;
    end
end

for ii = 1:(numel(s_common) - 1)
    y1 = D32_NMC(ii);
    y2 = D32_NMC(ii + 1);

    if isfinite(y1) && isfinite(y2) && y1 * y2 <= 0
        s_T1_NMC = s_common(ii) - y1 * (s_common(ii + 1) - s_common(ii)) / (y2 - y1);
        break;
    end
end

delta_T1 = s_T1_NMC - s_T1_LFP;

%% 9.2 Plot the value-gap figure
fig_D32 = figure('Color', 'w', ...
                 'Name', 'MainFig03d_refurbishment_recycling_value_gap', ...
                 'Position', [100, 80, 920, 620]);

hold on; box on; grid on;


x_fill = [s_common(:); flipud(s_common(:))];
y_fill = [D32_NMC(:); flipud(D32_LFP(:))];

h_fill = fill(x_fill, y_fill, color_fill, ...
              'EdgeColor', 'none', ...
              'FaceAlpha', 0.35);

h_lfp = plot(s_common, D32_LFP, ...
             'LineWidth', 2.8, ...
             'Color', color_LFP);
h_nmc = plot(s_common, D32_NMC, ...
             'LineWidth', 2.8, ...
             'Color', color_NMC);

yline(0, 'k-', 'LineWidth', 1.3);

if isfinite(s_T1_LFP)
    xline(s_T1_LFP, '--', ...
          'Color', color_LFP, ...
          'LineWidth', 1.7);

    scatter(s_T1_LFP, 0, 70, ...
            'MarkerFaceColor', color_LFP, ...
            'MarkerEdgeColor', 'w', ...
            'LineWidth', 1.0);

    text(s_T1_LFP + 0.01, 450, ...
         sprintf('T_{1,true}^{LFP}=%.3f', s_T1_LFP), ...
         'Color', color_LFP, ...
         'FontName', 'Arial', ...
         'FontSize', 12, ...
         'FontWeight', 'bold');
end

if isfinite(s_T1_NMC)
    xline(s_T1_NMC, '--', ...
          'Color', color_NMC, ...
          'LineWidth', 1.7);

    scatter(s_T1_NMC, 0, 70, ...
            'MarkerFaceColor', color_NMC, ...
            'MarkerEdgeColor', 'w', ...
            'LineWidth', 1.0);

    text(s_T1_NMC + 0.01, 450, ...
         sprintf('T_{1,true}^{NMC}=%.3f', s_T1_NMC), ...
         'Color', color_NMC, ...
         'FontName', 'Arial', ...
         'FontSize', 12, ...
         'FontWeight', 'bold');
end

if isfinite(s_T1_LFP) && isfinite(s_T1_NMC)
    y_arrow = 5200;

    plot([s_T1_LFP, s_T1_NMC], [y_arrow, y_arrow], ...
         'k-', 'LineWidth', 1.5);

    scatter([s_T1_LFP, s_T1_NMC], [y_arrow, y_arrow], ...
            35, 'k', 'filled');

    text(mean([s_T1_LFP, s_T1_NMC]), y_arrow + 260, ...
         sprintf('\\DeltaT_{1,true}=%.3f SOH', delta_T1), ...
         'HorizontalAlignment', 'center', ...
         'FontName', 'Arial', ...
         'FontSize', 12, ...
         'FontWeight', 'bold');
end

text(0.43, 5550, ...
     'A3 more competitive than A2', ...
     'FontName', 'Arial', ...
     'FontSize', 12, ...
     'FontWeight', 'bold');

text(0.72, -5150, ...
     'A2 more competitive than A3', ...
     'FontName', 'Arial', ...
     'FontSize', 12, ...
     'FontWeight', 'bold');

text(0.58, 3000, ...
     {'NMC maintains a larger', 'A3-A2 value gap'}, ...
     'FontName', 'Arial', ...
     'FontSize', 12, ...
     'Color', color_NMC, ...
     'FontWeight', 'bold');

xlabel('Observed SOH');
ylabel('V_{A3} - V_{A2} (USD per pack)');
title('Recycling-refurbishment value gap');

legend([h_lfp, h_nmc, h_fill], ...
       {'LFP', 'NMC', 'NMC-LFP gap'}, ...
       'Location', 'northeast', ...
       'Box', 'off');

xlim([0.40, 1.00]);
ylim([-6000, 6000]);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 14, ...
    'LineWidth', 1.2);


savefig(fig_D32, cfg.fig_value_gap);
exportgraphics(fig_D32, cfg.png_value_gap, ...
    'Resolution', cfg.png_resolution);

fprintf('Saved Main Fig. 3d value-gap figure: %s\n', cfg.png_value_gap);


%% 10) Plot the alluvial-style pathway reallocation figure
if ~isfield(lfp, 's_pred_opt')
    error('s_pred_opt was not found in LFP_fixed_result.');
end

s_common_pred = double(lfp.s_pred_opt(:));
s_common_pred = s_common_pred(isfinite(s_common_pred));
s_common_pred = min(max(s_common_pred, 0), 1);

if isempty(s_common_pred)
    error('The common predicted-SOH population is empty.');
end
N_common = numel(s_common_pred);

if isfield(lfp, 'opt_T1')
    T1_LFP = double(lfp.opt_T1);
elseif exist('s_T1_LFP', 'var')
    T1_LFP = s_T1_LFP;
else
    error('Unable to find T1 for LFP.');
end

if isfield(lfp, 'opt_T2')
    T2_LFP = double(lfp.opt_T2);
elseif exist('s_T2_LFP', 'var')
    T2_LFP = s_T2_LFP;
else
   error('Unable to find T2 for LFP.');
end

if isfield(nmc, 'best_T1_refined')
    T1_NMC = double(nmc.best_T1_refined);
elseif exist('s_T1_NMC', 'var')
    T1_NMC = s_T1_NMC;
else
    error('Unable to find T1 for NMC.');
end

if isfield(nmc, 'best_T2_refined')
    T2_NMC = double(nmc.best_T2_refined);
elseif exist('s_T2_NMC', 'var')
    T2_NMC = s_T2_NMC;
else
    error('Unable to find T2 for NMC.');
end

fprintf('\n========== Thresholds used for action-reallocation analysis ==========\n');
fprintf('LFP: T1 = %.4f, T2 = %.4f\n', T1_LFP, T2_LFP);
fprintf('NMC: T1 = %.4f, T2 = %.4f\n', T1_NMC, T2_NMC);

act_LFP_common = 3 * ones(N_common, 1);   
act_LFP_common(s_common_pred >= T1_LFP & s_common_pred < T2_LFP) = 2;
act_LFP_common(s_common_pred >= T2_LFP) = 1;

act_NMC_common = 3 * ones(N_common, 1);  
act_NMC_common(s_common_pred >= T1_NMC & s_common_pred < T2_NMC) = 2;
act_NMC_common(s_common_pred >= T2_NMC) = 1;

disp_order = [3, 2, 1];
disp_names = {'A3: Recycle', 'A2: Refurbish', 'A1: Direct reuse'};
disp_short = {'A3', 'A2', 'A1'};

M_count = zeros(3, 3);
for i = 1:3
    for j = 1:3
        M_count(i, j) = sum(act_LFP_common == disp_order(i) & act_NMC_common == disp_order(j));
    end
end

M_share = 100 * M_count / N_common;

left_share  = sum(M_share, 2);  
right_share = sum(M_share, 1); 

row_list = {};
col_list = {};
count_list = [];
share_list = [];

for i = 1:3
    for j = 1:3
        if M_count(i, j) > 0
            row_list{end+1,1} = disp_short{i};
            col_list{end+1,1} = disp_short{j};
            count_list(end+1,1) = M_count(i, j);
            share_list(end+1,1) = M_share(i, j);
        end
    end
end

T_transition = table(row_list, col_list, count_list, share_list, ...
    'VariableNames', {'Action_under_LFP', 'Action_under_NMC', 'Count', 'Share_percent'});

disp(' ');
disp('========== LFP -> NMC action transition matrix ==========');
disp(T_transition);

writetable(T_transition, cfg.transition_csv);


T_share = table(disp_short(:), left_share, right_share(:), ...
    'VariableNames', {'Action', 'LFP_share_percent', 'NMC_share_percent'});

disp(' ');
disp('========== Action shares on the LFP and NMC sides ==========');
disp(T_share);

writetable(T_share, cfg.action_share_csv);


color_A3 = [0.850, 0.325, 0.098];   % A3 recycling
color_A2 = [0.466, 0.674, 0.188];   % A2 refurbishment
color_A1 = [0.000, 0.447, 0.741];   % A1 direct reuse
color_map = [color_A3; color_A2; color_A1];

fig = figure('Color', 'w', ...
    'Name', 'MainFig03c_LFP_NMC_action_share_reallocation', ...
    'Position', [120, 80, 980, 620]);

ax = axes('Parent', fig);
hold(ax, 'on');
axis(ax, [0 1 0 1]);
axis(ax, 'off');
xL0 = 0.16;     
xL1 = 0.22;     
xR0 = 0.78;     
xR1 = 0.84;    
H_total = 0.72;
top_y = 0.86;
gap_y = 0.03;
scale_y = H_total / 100;

left_y0 = zeros(3,1);
left_y1 = zeros(3,1);
right_y0 = zeros(3,1);
right_y1 = zeros(3,1);


y_top = top_y;
for i = 1:3
    h = left_share(i) * scale_y;
    left_y1(i) = y_top;
    left_y0(i) = y_top - h;
    y_top = left_y0(i) - gap_y;
end


y_top = top_y;
for i = 1:3
    h = right_share(i) * scale_y;
    right_y1(i) = y_top;
    right_y0(i) = y_top - h;
    y_top = right_y0(i) - gap_y;
end


for i = 1:3
    rectangle(ax, ...
        'Position', [xL0, left_y0(i), xL1-xL0, left_y1(i)-left_y0(i)], ...
        'FaceColor', color_map(i,:), ...
        'EdgeColor', 'w', ...
        'LineWidth', 1.0);
    rectangle(ax, ...
        'Position', [xR0, right_y0(i), xR1-xR0, right_y1(i)-right_y0(i)], ...
        'FaceColor', color_map(i,:), ...
        'EdgeColor', 'w', ...
        'LineWidth', 1.0);
end

for i = 1:3
    text(ax, xL0 - 0.015, 0.5*(left_y0(i)+left_y1(i)), ...
        sprintf('%s\n%.1f%%', disp_names{i}, left_share(i)), ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'FontWeight', 'bold');

    text(ax, xR1 + 0.015, 0.5*(right_y0(i)+right_y1(i)), ...
        sprintf('%s\n%.1f%%', disp_names{i}, right_share(i)), ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'FontWeight', 'bold');
end

text(ax, 0.50, 0.95, 'Reallocation of final actions under LFP and NMC economics', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom', ...
    'FontName', 'Arial', ...
    'FontSize', 19, ...
    'FontWeight', 'bold');

text(ax, 0.19, 0.90, 'LFP economics', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom', ...
    'FontName', 'Arial', ...
    'FontSize', 14, ...
    'FontWeight', 'bold');

text(ax, 0.81, 0.90, 'NMC economics', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom', ...
    'FontName', 'Arial', ...
    'FontSize', 14, ...
    'FontWeight', 'bold');

left_cursor = left_y1;   
right_cursor = right_y1;

flow_list = [];
for i = 1:3
    for j = 1:3
        if M_share(i,j) > 0
            flow_list = [flow_list; M_share(i,j), i, j];
        end
    end
end
flow_list = sortrows(flow_list, -1);

for k = 1:size(flow_list, 1)
    val = flow_list(k, 1);
    i = flow_list(k, 2);
    j = flow_list(k, 3);

    h = val * scale_y;

    yL_top = left_cursor(i);
    yL_bot = yL_top - h;
    left_cursor(i) = yL_bot;

    yR_top = right_cursor(j);
    yR_bot = yR_top - h;
    right_cursor(j) = yR_bot;

    t = linspace(0, 1, 80);

    x_top = (1-t).^3 * xL1 ...
          + 3*(1-t).^2.*t * (xL1 + 0.18) ...
          + 3*(1-t).*t.^2 * (xR0 - 0.18) ...
          + t.^3 * xR0;

    y_top = (1-t).^3 * yL_top ...
          + 3*(1-t).^2.*t * yL_top ...
          + 3*(1-t).*t.^2 * yR_top ...
          + t.^3 * yR_top;

    x_bot = (1-t).^3 * xR0 ...
          + 3*(1-t).^2.*t * (xR0 - 0.18) ...
          + 3*(1-t).*t.^2 * (xL1 + 0.18) ...
          + t.^3 * xL1;

    y_bot = (1-t).^3 * yR_bot ...
          + 3*(1-t).^2.*t * yR_bot ...
          + 3*(1-t).*t.^2 * yL_bot ...
          + t.^3 * yL_bot;

    patch(ax, [x_top, x_bot], [y_top, y_bot], color_map(j,:), ...
        'FaceAlpha', 0.42, ...
        'EdgeColor', 'none');

    if val >= 12
        x_mid = 0.50;
        y_mid = 0.25*(yL_top + yL_bot + yR_top + yR_bot);
        text(ax, x_mid, y_mid, sprintf('%.1f%%', val), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Arial', ...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'Color', [0 0 0]);
    end
end

key_share = M_share(2,1);
if key_share > 0
    text(ax, 0.50, 0.20, ...
        sprintf('Dominant reallocation: A2 \\rightarrow A3 = %.1f%%', key_share), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', [0.48 0.25 0.63]);
end

text(ax, 0.50, 0.10, ...
    'Ribbon width represents the share of the same predicted-SOH population', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontName', 'Arial', ...
    'FontSize', 10.5, ...
    'FontAngle', 'italic', ...
    'Color', [0.25 0.25 0.25]);

savefig(fig, cfg.fig_alluvial);
exportgraphics(fig, cfg.png_alluvial, ...
    'Resolution', cfg.png_resolution);

fprintf('Saved Main Fig. 3c action-share reallocation figure: %s\n', cfg.png_alluvial);


%% 11) Print a brief diagnostic summary
mean_abs_shift_D32 = mean(abs(Shift_D32_rep), 'omitnan');
mean_abs_shift_D12 = mean(abs(Shift_D12_rep), 'omitnan');

fprintf('\n========== Brief diagnostic summary ==========\n');
fprintf('Mean |Shift_D32| at representative SOH values = %.2f USD/pack\n', mean_abs_shift_D32);
fprintf('Mean |Shift_D12| at representative SOH values = %.2f USD/pack\n', mean_abs_shift_D12);

if mean_abs_shift_D32 > mean_abs_shift_D12
    fprintf('The A3/A2 boundary gap shows the larger chemistry-driven shift, supporting the recycling-refurbishment explanation for the T1 shift.\n');
else
    fprintf('The A1/A2 boundary gap shows a comparable or larger chemistry-driven shift, so the T2-side explanation should also be checked.\n');
end

fprintf('\nPart4 Exp03 outputs saved to:\n%s\n', cfg.results_dir);
fprintf('================ Part4 Exp03 completed ================\n');