%% P4_Exp02_fixed_scale_NMC_optimization.m
% Purpose:
% This script implements the fixed-scale NMC recertification optimization
% under a scaled proxy prediction-error scenario.
%
% It constructs SOH-dependent action-value functions for direct reuse,
% refurbishment, and NMC direct recycling. It then reads the k-dependent
% residual-error model generated by Part3, applies the NMC residual-scaling
% factor rho, optimizes the labelling investment k and predicted-SOH
% thresholds T1 and T2, and exports NMC fixed-scale results for the
% chemistry-specific recertification analysis.

clear; clc; close all;

%% 1) Configuration and path setup
cfg = struct();

% Use the current script folder as the Part4 root folder.
script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
 script_dir = pwd;
end

% Use the parent folder as the project root.
project_root = fileparts(script_dir);

% Part4 folders.
cfg.input_dir = fullfile(script_dir, 'Input');
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.main_fig_dir = fullfile(cfg.figure_root, 'Main');
cfg.extended_fig_dir = fullfile(cfg.figure_root, 'Extended');
cfg.supplementary_fig_dir = fullfile(cfg.figure_root, 'Supplementary');

cfg.function_dir = fullfile(script_dir, 'Function');

% Input files.
cfg.nmc_soh_mat = fullfile(cfg.input_dir, 'NMC_SOH_Table.mat');

% Primary Part3 residual-error model path using the new naming convention.
cfg.error_model_mat_primary = fullfile(project_root, ...
 'Part3_Prediction error extrapolation', ...
 'Output', ...
 'Results', ...
 'P3_Exp03_ResidualExtrapolation_Model.mat');

% Legacy fallback path for the old Part3 Main03 output.
cfg.error_model_mat_legacy = fullfile(project_root, ...
 'Part3_Prediction error extrapolation', ...
 'Output', ...
 'Result03_ResidualExtrapolation_Model.mat');

if exist(cfg.error_model_mat_primary, 'file')
 cfg.error_model_mat = cfg.error_model_mat_primary;
elseif exist(cfg.error_model_mat_legacy, 'file')
 cfg.error_model_mat = cfg.error_model_mat_legacy;
else
 error('Part3 residual-error model file not found. Checked:\n%s\n%s', ...
 cfg.error_model_mat_primary, cfg.error_model_mat_legacy);
end

% Output files generated by Part4 Exp02.
cfg.workspace_mat = fullfile(cfg.results_dir, 'P4_Exp02_FixedScale_NMC_Workspace.mat');

cfg.result_mat = fullfile(cfg.results_dir, 'P4_Exp02_FixedScale_NMC_Results.mat');

cfg.summary_csv = fullfile(cfg.results_dir, 'P4_Exp02_FixedScale_NMC_Summary.csv');

% Figure files for Supplementary Fig. 15.
cfg.fig_cost_breakdown = fullfile(cfg.supplementary_fig_dir, 'SupFig15_NMC_fixed_scale_cost_decomposition.fig');
cfg.png_cost_breakdown = fullfile(cfg.supplementary_fig_dir, 'SupFig15_NMC_fixed_scale_cost_decomposition.png');

% Figure files for Main Fig. 3.
cfg.fig_net_utility = fullfile(cfg.main_fig_dir, 'MainFig03c_NMC_net_value_curves.fig');
cfg.png_net_utility = fullfile(cfg.main_fig_dir, 'MainFig03c_NMC_net_value_curves.png');
cfg.fig_A3_breakdown = fullfile(cfg.main_fig_dir, 'MainFig03d_NMC_recycling_breakdown.fig');
cfg.png_A3_breakdown = fullfile(cfg.main_fig_dir, 'MainFig03d_NMC_recycling_breakdown.png');

% Simulation settings.
cfg.N_sim = 100000;
cfg.random_seed = 42;
cfg.png_resolution = 600;

% NMC proxy-error scenario settings.
cfg.rho = 0.8;

% Create required folders.
folder_list = { ...
 cfg.input_dir, ...
 cfg.output_dir, ...
 cfg.results_dir, ...
 cfg.figure_root, ...
 cfg.main_fig_dir, ...
 cfg.extended_fig_dir, ...
 cfg.supplementary_fig_dir, ...
 cfg.function_dir};

for ii = 1:numel(folder_list)
 if ~exist(folder_list{ii}, 'dir')
 mkdir(folder_list{ii});
 end
end

addpath(cfg.function_dir);

if exist('local_build_noise_by_k', 'file') ~= 2
 error('Function local_build_noise_by_k.m was not found in: %s', cfg.function_dir);
end

fprintf('================ Part4 Exp02 fixed-scale NMC optimization ================\n');
fprintf('NMC SOH input file: %s\n', cfg.nmc_soh_mat);
fprintf('Part3 error model file: %s\n', cfg.error_model_mat);
fprintf('Output result file: %s\n', cfg.result_mat);
fprintf('Output workspace file: %s\n', cfg.workspace_mat);
fprintf('Summary CSV file: %s\n', cfg.summary_csv);
fprintf('Main figure folder: %s\n', cfg.main_fig_dir);
fprintf('Residual scaling rho: %.2f\n', cfg.rho);
fprintf('Random seed: %d\n', cfg.random_seed);

%% 2) Load NMC SOH trajectory data
if ~exist(cfg.nmc_soh_mat, 'file')
 error('NMC SOH data file not found: %s', cfg.nmc_soh_mat);
end

S_soh = load(cfg.nmc_soh_mat);
SOH_data = local_extract_nmc_soh_from_mat(S_soh, cfg.nmc_soh_mat);

fprintf('NMC SOH trajectory loaded. Number of SOH points = %d\n', numel(SOH_data));
fprintf('NMC SOH range: %.4f - %.4f\n', min(SOH_data), max(SOH_data));

%% 3) Basic physical and economic parameters for NMC
Q_pack = 25.3;
r = 0.05;
beta_refurbish = 0.09;

% Shenzhen tier-2 residential peak-valley electricity prices, RMB/kWh.
ExchangeRate_RMB_USD = 7.04;
p_high_RMB = 1.1621;
p_low_RMB = 0.2986;

% Convert electricity prices to USD/kWh.
p_high = p_high_RMB / ExchangeRate_RMB_USD;
p_low = p_low_RMB / ExchangeRate_RMB_USD;

c_pack = 300;
c_train = 100;
Fixed_Scale_N = 2500;

% G1 and G2 gray-zone value-loss tolerances.
Eta_1 = 40;
Eta_2 = 40;

C0 = 43;
C1 = 80;
gamma = 3;

% Risk and mismatch-handling/rework coefficients.
Lambda_R = 15;
Lambda_H = 12;

% Legacy alias retained temporarily so older downstream scripts can still
% read the previous field name. New code should use Lambda_H.
Lambda_A = Lambda_H;

% Extra process costs for A1 and A2.
C_A1_extra = 10;
C_A2_extra = 15;

% NMC direct-recycling physicochemical parameters.
M_pack = 173.25;
Exchange_Rate = 1;

PosAcMass = 0.2314;
PosCCMass = 0.0700;
NegAcMass = 0.1425;
NegCCMass = 0.1700;

M_NMC622 = 96.93;
M_Li2CO3 = 73.89;

% Direct-recycling recovery efficiencies.
Rec_Rate_Cathode = 0.90;
Rec_Rate_Graphite = 0.90;
Rec_Rate_Al = 0.90;
Rec_Rate_Cu = 0.90;

% Material prices, USD/kg.
P_NMC622 = 29.17;
P_Li2CO3 = 27.20;
P_Graphite = 3.84;
P_Al = 3.42;
P_Cu = 14.79;

% Retired NMC feedstock cost, USD/kg cathode active material.
C_Degraded = 17.34;

% Fixed operating cost for direct recycling, USD/kg battery pack.
C_Electricity_direct = 300 * 0.111 / 1000;
C_Labor_direct = 223.79 / 1000;
C_Disassemble_direct = 143.00 / 1000;
C_Equip_direct = 57.57 / 1000;
C_Sewage_direct = 100.29 / 1000;

Fixed_Op_Cost = C_Electricity_direct + C_Labor_direct + ...
 C_Disassemble_direct + C_Equip_direct + C_Sewage_direct;

%% 4) SOH-dependent action-value functions for NMC
valid_end_idx = find(SOH_data >= 0.4);

if isempty(valid_end_idx)
 error('The NMC SOH trajectory does not contain values above 0.4.');
end

end_idx = valid_end_idx(end);

start_indices = find(SOH_data <= 1.0 & SOH_data >= 0.4);
num_cases = length(start_indices);

a = zeros(num_cases, 1);
V1 = zeros(num_cases, 1);

for kk = 1:num_cases

 start_idx = start_indices(kk);

 SOH_slice = SOH_data(start_idx:end_idx);
 a(kk) = SOH_slice(1);

 days_elapsed = (0:length(SOH_slice)-1)';

 % NMC efficiency function: eta(SOH) = -0.2303 * (1 - SOH) + 0.9582.
 SOH_diff = 1 - SOH_slice;
 Poly_term = -0.2303 .* SOH_diff + 0.9582;

 Daily_Value_Raw = Q_pack .* SOH_slice .* (Poly_term .* p_high - p_low);

 Discount_Factor = 1 ./ ((1 + r) .^ (days_elapsed / 365));
 V1(kk) = sum(Daily_Value_Raw .* Discount_Factor);
end

[a, sort_idx] = sort(a);
V1 = V1(sort_idx);

[a, ia] = unique(a, 'last');
V1 = V1(ia);

if max(a) < 1.0

 a_old = a;
 V1_old = V1;

 slope = (V1_old(end) - V1_old(end - 1)) / ...
 (a_old(end) - a_old(end - 1));

 V1_at_1 = V1_old(end) + slope * (1.0 - a_old(end));

 a = [a_old; 1.0];
 V1 = [V1_old; V1_at_1];
end

% A1: direct reuse.
calc_V_reuse_base = @(soh) interp1(a, V1, soh, 'linear', 'extrap');
calc_V_reuse = @(soh) calc_V_reuse_base(soh) - C_A1_extra;

% A2: refurbishment followed by reuse.
calc_C_refurbish = @(soh) C0 + C1 .* (1 - soh).^gamma;

calc_V_refurbish_base = @(soh) ...
 calc_V_reuse_base(min(soh + beta_refurbish .* (1 - soh), 1.0)) ...
 - calc_C_refurbish(soh);

calc_V_refurbish = @(soh) calc_V_refurbish_base(soh) ...
 - C_A1_extra - C_A2_extra;

% A3: NMC direct recycling.
Base_Y_NMC622 = PosAcMass * Rec_Rate_Cathode;
Base_Y_Graphite = NegAcMass * Rec_Rate_Graphite;
Base_Y_Al = PosCCMass * Rec_Rate_Al;
Base_Y_Cu = NegCCMass * Rec_Rate_Cu;

Y_Li2CO3_in_func = @(soh) ...
 (PosAcMass ./ M_NMC622) .* ((1 - soh) ./ 2) .* M_Li2CO3;

calc_V_recycle = @(soh) M_pack .* Exchange_Rate .* ( ...
 (Base_Y_NMC622 .* P_NMC622 + ...
 Base_Y_Graphite .* P_Graphite + ...
 Base_Y_Al .* P_Al + ...
 Base_Y_Cu .* P_Cu) ...
 - (Y_Li2CO3_in_func(soh) .* P_Li2CO3) ...
 - (PosAcMass .* C_Degraded + Fixed_Op_Cost));

%% 5) Load k-dependent residual-error extrapolation model

error_model_file = cfg.error_model_mat;

if ~exist(error_model_file, 'file')
 error('Part3 residual-error model file not found: %s', error_model_file);
end

ErrorModel = load(error_model_file);

required_error_vars = { ...
 'k_emp', ...
 'k_vals', ...
 'err_cell', ...
 'rmse_target', ...
 'w_curve', ...
 'PM_curve', ...
 'muM_curve', ...
 'sigM_curve', ...
 'muR_curve', ...
 'sigR_curve', ...
 'region', ...
 'cfg'};

for ii = 1:numel(required_error_vars)
 if ~isfield(ErrorModel, required_error_vars{ii})
 error('Required variable "%s" was not found in %s.', ...
 required_error_vars{ii}, error_model_file);
 end
end

k_emp = ErrorModel.k_emp(:);
k_vals = ErrorModel.k_vals(:);
err_cell = ErrorModel.err_cell;

rmse_target = ErrorModel.rmse_target(:);
w_curve = ErrorModel.w_curve(:);
PM_curve = ErrorModel.PM_curve(:);
muM_curve = ErrorModel.muM_curve(:);
sigM_curve = ErrorModel.sigM_curve(:);
muR_curve = ErrorModel.muR_curve(:);
sigR_curve = ErrorModel.sigR_curve(:);

region = ErrorModel.region;

if isfield(ErrorModel.cfg, 'k_anchor')
 k_anchor = ErrorModel.cfg.k_anchor;
else
 k_anchor = 21;
end

if isfield(ErrorModel.cfg, 'k_bridge_end')
 k_bridge_end = ErrorModel.cfg.k_bridge_end;
else
 k_bridge_end = 26;
end

if numel(k_vals) ~= numel(rmse_target) || ...
 numel(k_vals) ~= numel(w_curve) || ...
 numel(k_vals) ~= numel(PM_curve) || ...
 numel(k_vals) ~= numel(muM_curve) || ...
 numel(k_vals) ~= numel(sigM_curve) || ...
 numel(k_vals) ~= numel(muR_curve) || ...
 numel(k_vals) ~= numel(sigR_curve)
 error('The loaded residual-error model has inconsistent curve lengths.');
end

fprintf('Residual-error model loaded from: %s\n', error_model_file);
fprintf('Loaded k range: %d to %d\n', min(k_vals), max(k_vals));

N_sim = cfg.N_sim;
rng(cfg.random_seed);

% Common random numbers reused across k values.
base_u = rand(N_sim, 1);
base_z = randn(N_sim, 1);
base_pick = rand(N_sim, 1);

% Use an independent stream for the Bernoulli bridge selector so that
% introducing the probability-mixture bridge does not shift the
% original SOH Monte Carlo sequence.
bridge_stream = RandStream('mt19937ar', ...
 'Seed', cfg.random_seed + 1001);
base_bridge = rand(bridge_stream, N_sim, 1);

fprintf('Residual-error template loaded from Part3 model.\n');

%% 6) NMC k-dependent proxy-error optimization

rho = cfg.rho;

s_true = 0.4 + 0.6 * rand(N_sim, 1);

Pi_True = [
 calc_V_reuse(s_true), ...
 calc_V_refurbish(s_true), ...
 calc_V_recycle(s_true)];

[Pi_True_Max, PerfectInfo_Action_i] = max(Pi_True, [], 2);
% Legacy alias retained for compatibility with older result readers.
True_Action_i = PerfectInfo_Action_i; 

T1_grid = 0.73:0.001:0.80;
T2_grid = 0.90:0.001:0.98;

E_L_base = nan(numel(k_vals), 1);
O_base = nan(numel(k_vals), 1);
H_base = nan(numel(k_vals), 1);
R_base = nan(numel(k_vals), 1);
T1_base = nan(numel(k_vals), 1);
T2_base = nan(numel(k_vals), 1);

fprintf('>>> Running NMC k-grid search from k = %d to %d under rho = %.2f...\n', ...
 min(k_vals), max(k_vals), rho);

% Diagnostics verify the inherited LFP residual template, the % empirical/bridge/extrapolated construction, and the mean-centred NMC
% scaling actually used in this optimization.
noise_source_type = strings(numel(k_vals), 1);
noise_template_RMSE_target = rmse_target;
noise_template_RMSE_generated = nan(numel(k_vals), 1);
noise_template_bias_generated = nan(numel(k_vals), 1);
noise_NMC_RMSE_generated = nan(numel(k_vals), 1);
noise_NMC_bias_generated = nan(numel(k_vals), 1);
noise_bridge_alpha = zeros(numel(k_vals), 1);
noise_bridge_RMSE_scale = ones(numel(k_vals), 1);
noise_parametric_fraction = nan(numel(k_vals), 1);

for kk = 1:numel(k_vals)

 k_current = k_vals(kk);

 [noise_raw, noise_diag] = local_build_noise_by_k( ...
 k_current, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

 % NMC has no independent pack-level residual dataset. The LFP-derived
 % template is therefore mean-centred before scaling so that rho modifies
 % stochastic dispersion without transferring the LFP-specific bias.
 eps_k = noise_raw - mean(noise_raw);
 sampled_noise_k = rho .* eps_k;

 noise_source_type(kk) = string(noise_diag.source_type);
 noise_template_RMSE_generated(kk) = noise_diag.generated_RMSE;
 noise_template_bias_generated(kk) = mean(noise_raw);
 noise_NMC_RMSE_generated(kk) = sqrt(mean(sampled_noise_k.^2));
 noise_NMC_bias_generated(kk) = mean(sampled_noise_k);
 noise_bridge_alpha(kk) = noise_diag.bridge_alpha;
 noise_bridge_RMSE_scale(kk) = noise_diag.bridge_RMSE_scale;
 noise_parametric_fraction(kk) = noise_diag.parametric_fraction_realized;

 s_pred_k = min(max(s_true + sampled_noise_k, 0), 1.0);

 min_L_k = inf;
 best_T1_k = NaN;
 best_T2_k = NaN;

 best_O_k = NaN;
 best_H_k = NaN;
 best_R_k = NaN;

 for T1 = T1_grid

 for T2 = T2_grid

 if T1 >= T2
 continue;
 end

 Pred_Action_j = 3 * ones(N_sim, 1);
 Pred_Action_j(s_pred_k >= T1 & s_pred_k < T2) = 2;
 Pred_Action_j(s_pred_k >= T2) = 1;

 idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_j);

 O_arr = max(Pi_True_Max - Pi_True(idx_pred), 0);

 is_G1_error = (PerfectInfo_Action_i == 3 & Pred_Action_j == 2) | ...
 (PerfectInfo_Action_i == 2 & Pred_Action_j == 3);

 is_G2_error = (PerfectInfo_Action_i == 1 & Pred_Action_j == 2) | ...
 (PerfectInfo_Action_i == 2 & Pred_Action_j == 1);

 Current_Eta = zeros(N_sim, 1);
 Current_Eta(is_G1_error) = Eta_1;
 Current_Eta(is_G2_error) = Eta_2;

 consequential_mismatch = ...
 (Pred_Action_j ~= PerfectInfo_Action_i) & ...
 (O_arr > Current_Eta);
 Excess_Loss = max(0, O_arr - Current_Eta);

 H_arr = consequential_mismatch .* Lambda_H;

 R_arr = (Pred_Action_j < PerfectInfo_Action_i) .* ...
 consequential_mismatch .* (Lambda_R .* Excess_Loss);

 E_L = mean(O_arr + H_arr + R_arr);

 if E_L < min_L_k

 min_L_k = E_L;
 best_T1_k = T1;
 best_T2_k = T2;

 best_O_k = mean(O_arr);
 best_H_k = mean(H_arr);
 best_R_k = mean(R_arr);
 end
 end
 end

 E_L_base(kk) = min_L_k;
 O_base(kk) = best_O_k;
 H_base(kk) = best_H_k;
 R_base(kk) = best_R_k;
 T1_base(kk) = best_T1_k;
 T2_base(kk) = best_T2_k;
end

Fixed_O = O_base * Fixed_Scale_N;
Fixed_H = H_base * Fixed_Scale_N;
Fixed_R = R_base * Fixed_Scale_N;
Fixed_Model = k_vals .* c_pack + c_train;
Fixed_Total_Cost = Fixed_O + Fixed_H + Fixed_R + Fixed_Model;

% Legacy aliases retained for older downstream scripts.
A_base = H_base; %#ok<NASGU>
Fixed_A = Fixed_H; %#ok<NASGU>

[~, opt_k_idx] = min(Fixed_Total_Cost);

opt_k_NMC = k_vals(opt_k_idx);
opt_T1_NMC = T1_base(opt_k_idx);
opt_T2_NMC = T2_base(opt_k_idx);

if opt_k_idx == 1 || opt_k_idx == numel(k_vals)
 warning('Optimal k is on the search boundary (k = %d). Consider extending k_vals.', ...
 opt_k_NMC);
end

if opt_T1_NMC == T1_grid(1) || opt_T1_NMC == T1_grid(end) || ...
 opt_T2_NMC == T2_grid(1) || opt_T2_NMC == T2_grid(end)
 warning(['An optimal threshold is on the search boundary ' ...
 '(T1 = %.4f, T2 = %.4f). Consider extending the threshold grids.'], ...
 opt_T1_NMC, opt_T2_NMC);
end

min_L = E_L_base(opt_k_idx);

best_T1_init = opt_T1_NMC;
best_T2_init = opt_T2_NMC;
best_T1_refined = opt_T1_NMC;
best_T2_refined = opt_T2_NMC;

best_O_mean = O_base(opt_k_idx);
best_H_mean = H_base(opt_k_idx);
best_R_mean = R_base(opt_k_idx);

fprintf('NMC k-dependent optimization completed.\n');
fprintf('Optimal NMC k* = %d\n', opt_k_NMC);
fprintf('Optimal thresholds: T1 = %.4f, T2 = %.4f\n', ...
 opt_T1_NMC, opt_T2_NMC);
fprintf('Expected decision loss per pack: %.4f USD\n', min_L);
fprintf('Total expected fixed-scale cost: %.4f USD\n', ...
 Fixed_Total_Cost(opt_k_idx));

%% 7) Figure: fixed-scale NMC cost decomposition

fig_cost_breakdown = figure( ...
 'Name', sprintf('P4_Exp02_FixedScale_NMC_cost_decomposition_N%d_rho%.2f', ...
 Fixed_Scale_N, rho), ...
 'Color', 'w', ...
 'Position', [100, 450, 700, 500]);

bar_data = [Fixed_O, Fixed_H, Fixed_R, Fixed_Model] / 1e4;

b = bar(k_vals, bar_data, 'stacked', 'EdgeColor', 'none');
hold on;

% Colors
b(1).FaceColor = [0.93, 0.69, 0.13]; % Opportunity loss
b(2).FaceColor = [0.49, 0.18, 0.56]; % Mismatch handling and rework cost
b(3).FaceColor = [0.85, 0.33, 0.10]; % Risk penalty
b(4).FaceColor = [0.00, 0.45, 0.74]; % SOH labelling and adaptation cost

% Total cost curve
h_total = plot(k_vals, Fixed_Total_Cost / 1e4, '-k', ...
 'LineWidth', 2.8, ...
 'DisplayName', 'Total cost');

% Optimal k
h_star = plot(opt_k_NMC, Fixed_Total_Cost(opt_k_idx) / 1e4, 'rp', ...
 'MarkerSize', 16, ...
 'MarkerFaceColor', 'r', ...
 'DisplayName', 'Optimal k^*');

xline(opt_k_NMC, 'r--', ...
 'LineWidth', 1.5, ...
 'HandleVisibility', 'off');

uistack(h_total, 'top');
uistack(h_star, 'top');

xlabel('Number of labelled target packs, k');
ylabel('Cost (10^4 USD)');
title(sprintf('NMC fixed-scale cost decomposition (\\rho = %.1f)', rho));

grid on;
box on;

legend([b(4), b(3), b(2), b(1), h_total, h_star], ...
 {'SOH labelling and adaptation cost', ...
 'Risk penalty', ...
 'Mismatch handling and rework cost', ...
 'Opportunity loss', ...
 'Total cost', ...
 'Optimal k^*'}, ...
 'Location', 'NorthEast');

local_save_figure(fig_cost_breakdown, ...
 cfg.fig_cost_breakdown, ...
 cfg.png_cost_breakdown, ...
 cfg.png_resolution);


%% 8) Reconstruct optimal NMC prediction and action allocation

noise_opt_raw = local_build_noise_by_k( ...
 opt_k_NMC, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

% Center the inherited LFP-derived residual template before NMC scaling.
eps_opt = noise_opt_raw - mean(noise_opt_raw);
sampled_noise_opt = rho .* eps_opt;
s_pred_opt = min(max(s_true + sampled_noise_opt, 0), 1.0);

% Keep these aliases for downstream plotting and saving sections.
sampled_noise = sampled_noise_opt;
s_pred = s_pred_opt;

%% 9) Cost-consistent NMC net-value curves
J = zeros(N_sim, 3);

for a_idx = 1:3

 ch_v = Pi_True(:, a_idx);
 O_tmp = max(Pi_True_Max - ch_v, 0);

 iG1 = ((PerfectInfo_Action_i == 3) & (a_idx == 2)) | ...
 ((PerfectInfo_Action_i == 2) & (a_idx == 3));

 iG2 = ((PerfectInfo_Action_i == 1) & (a_idx == 2)) | ...
 ((PerfectInfo_Action_i == 2) & (a_idx == 1));

 Eta_tmp = zeros(N_sim, 1);
 Eta_tmp(iG1) = Eta_1;
 Eta_tmp(iG2) = Eta_2;

 consequential_mismatch_tmp = ...
 (a_idx ~= PerfectInfo_Action_i) & (O_tmp > Eta_tmp);
 Excess_tmp = max(0, O_tmp - Eta_tmp);

 H_tmp = consequential_mismatch_tmp .* Lambda_H;
 R_tmp = (a_idx < PerfectInfo_Action_i) .* ...
 consequential_mismatch_tmp .* (Lambda_R .* Excess_tmp);

 % The selected-action value already reflects opportunity loss.
 J(:, a_idx) = ch_v - H_tmp - R_tmp;
end

s_hat_grid = (0.40:0.001:1.00)';
G = zeros(length(s_hat_grid), 3);

h = 0.008;

for ii = 1:length(s_hat_grid)

 w = exp(-0.5 * ((s_pred - s_hat_grid(ii)) / h).^2);
 sw = sum(w);

 if sw > 1e-12
 G(ii, :) = (w' * J) / sw;
 end
end

[G_env, ~] = max(G, [], 2);

fig_net = figure( ...
 'Name', 'MainFig03c_NMC_net_value_curves', ...
 'Color', 'w', ...
 'Position', [180, 120, 800, 520]);

colors = lines(3);

hold on;

for a_idx = 1:3
 plot(s_hat_grid, G(:, a_idx), ...
 'LineWidth', 2.2, ...
 'Color', colors(a_idx, :));
end

plot(s_hat_grid, G_env, 'k--', ...
 'LineWidth', 2.4);

xline(best_T1_refined, '--r', ...
 'LineWidth', 1.5, ...
 'HandleVisibility', 'off');

xline(best_T2_refined, '--b', ...
 'LineWidth', 1.5, ...
 'HandleVisibility', 'off');

grid on;
box on;

ylim([0, 2500]);

xlabel('Predicted SOH');
ylabel('Expected net value per pack (USD)');
title(sprintf('NMC net-value curves under scaled residual error (\\rho = %.1f)', rho));

legend({'A_1 direct reuse', 'A_2 refurbishment', 'A_3 recycling', 'Optimal envelope'}, ...
 'Location', 'best');

local_save_figure(fig_net, ...
 cfg.fig_net_utility, ...
 cfg.png_net_utility, ...
 cfg.png_resolution);

fprintf('NMC net-value figure saved: %s\n', cfg.png_net_utility);

%% 10) NMC A3 direct-recycling revenue-cost contribution
Pred_Action_opt = 3 * ones(N_sim, 1);
Pred_Action_opt(s_pred >= best_T1_refined & s_pred < best_T2_refined) = 2;
Pred_Action_opt(s_pred >= best_T2_refined) = 1;

idx_pred_opt = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_opt);

O_arr_opt = max(Pi_True_Max - Pi_True(idx_pred_opt), 0);

is_G1_opt = (PerfectInfo_Action_i == 3 & Pred_Action_opt == 2) | ...
 (PerfectInfo_Action_i == 2 & Pred_Action_opt == 3);

is_G2_opt = (PerfectInfo_Action_i == 1 & Pred_Action_opt == 2) | ...
 (PerfectInfo_Action_i == 2 & Pred_Action_opt == 1);

Eta_opt = zeros(N_sim, 1);
Eta_opt(is_G1_opt) = Eta_1;
Eta_opt(is_G2_opt) = Eta_2;

consequential_mismatch_opt = ...
 (Pred_Action_opt ~= PerfectInfo_Action_i) & ...
 (O_arr_opt > Eta_opt);
Excess_opt = max(0, O_arr_opt - Eta_opt);

H_arr_opt = consequential_mismatch_opt .* Lambda_H;

R_arr_opt = (Pred_Action_opt < PerfectInfo_Action_i) .* ...
 consequential_mismatch_opt .* (Lambda_R .* Excess_opt);

Total_Loss_opt = O_arr_opt + H_arr_opt + R_arr_opt;

% The executed pathway value already reflects opportunity loss relative to
% the perfect-information pathway; do not subtract O_arr_opt a second time.
Executed_Pathway_Value_opt = Pi_True(idx_pred_opt);
PerfectInfo_Pathway_Value_opt = Pi_True_Max;
Net_Realized_Value_opt = Executed_Pathway_Value_opt ...
 - H_arr_opt - R_arr_opt;
Net_Realized_Value_check = PerfectInfo_Pathway_Value_opt ...
 - O_arr_opt - H_arr_opt - R_arr_opt;

accounting_gap = max(abs( ...
 Net_Realized_Value_opt - Net_Realized_Value_check));
assert(accounting_gap < 1e-8, ...
 'Net-value accounting identity failed. Maximum gap = %.3e.', ...
 accounting_gap);

% Legacy aliases retained for older scripts.
A_arr_opt = H_arr_opt; %#ok<NASGU>
Net_Revenue_opt = Net_Realized_Value_opt;

Action_Ratio_opt = [
 mean(Pred_Action_opt == 1), ...
 mean(Pred_Action_opt == 2), ...
 mean(Pred_Action_opt == 3)];

PerfectInfo_Action_Ratio = [
 mean(PerfectInfo_Action_i == 1), ...
 mean(PerfectInfo_Action_i == 2), ...
 mean(PerfectInfo_Action_i == 3)];

% Legacy alias retained for compatibility.
True_Action_Ratio = PerfectInfo_Action_Ratio;

mean_soh_rec = mean(s_true(Pred_Action_opt == 3));

if isnan(mean_soh_rec)
 mean_soh_rec = 0.5;
end

% Material outputs and inputs, kg/pack.
Y_NMC622 = M_pack * Base_Y_NMC622;
Y_Graph = M_pack * Base_Y_Graphite;
Y_Al = M_pack * Base_Y_Al;
Y_Cu = M_pack * Base_Y_Cu;

% Lithium-compensation input as a cost component varying with SOH.
Y_Li2CO3_in = M_pack * Y_Li2CO3_in_func(mean_soh_rec);

% Revenue components, USD/pack.
Rev_NMC622 = Y_NMC622 * P_NMC622 * Exchange_Rate;
Rev_Graph = Y_Graph * P_Graphite * Exchange_Rate;
Rev_Al = Y_Al * P_Al * Exchange_Rate;
Rev_Cu = Y_Cu * P_Cu * Exchange_Rate;

% Cost components, USD/pack.
Cost_Li2CO3_in = Y_Li2CO3_in * P_Li2CO3 * Exchange_Rate;
Cost_Feedstock = M_pack * PosAcMass * C_Degraded * Exchange_Rate;
Cost_Op = M_pack * Fixed_Op_Cost * Exchange_Rate;

labels_A3 = { ...
 'NMC622', ...
 'Graphite', ...
 'Al', ...
 'Cu', ...
 'Li_2CO_3 input', ...
 'Degraded NMC feedstock', ...
 'Operating cost', ...
 'Net value'};

vals = [
 Rev_NMC622, ...
 Rev_Graph, ...
 Rev_Al, ...
 Rev_Cu, ...
 -Cost_Li2CO3_in, ...
 -Cost_Feedstock, ...
 -Cost_Op];

net_value_A3 = sum(vals);
vals_full = [vals, net_value_A3];

% Save a residual diagnostic table for the exact NMC proxy samples used.
Noise_Diagnostic_Table = table( ...
 k_vals, ...
 noise_source_type, ...
 noise_template_RMSE_target, ...
 noise_template_RMSE_generated, ...
 noise_template_bias_generated, ...
 noise_NMC_RMSE_generated, ...
 noise_NMC_bias_generated, ...
 noise_bridge_alpha, ...
 noise_bridge_RMSE_scale, ...
 noise_parametric_fraction, ...
 'VariableNames', { ...
 'k', ...
 'Residual_source', ...
 'LFP_template_RMSE_target', ...
 'LFP_template_RMSE_generated', ...
 'LFP_template_bias_generated', ...
 'NMC_scaled_RMSE_generated', ...
 'NMC_scaled_bias_generated', ...
 'Bridge_alpha', ...
 'Bridge_RMSE_scale', ...
 'Parametric_fraction_realized'});

% Save the full workspace before figure generation is completed.
save(cfg.workspace_mat, '-v7.3');

fprintf('>>> Full fixed-scale NMC workspace saved to: %s\n', cfg.workspace_mat);

fig_A3 = figure( ...
 'Name', 'MainFig03d_NMC_recycling_breakdown', ...
 'Color', 'w', ...
 'Position', [220, 120, 980, 560]);

b = barh(vals_full, ...
 'FaceColor', 'flat', ...
 'EdgeColor', 'none');

hold on;

for ii = 1:numel(vals_full)

 if ii == numel(vals_full)
 b.CData(ii, :) = [0.15, 0.15, 0.15];
 elseif vals_full(ii) >= 0
 b.CData(ii, :) = [0.16, 0.47, 0.78];
 else
 b.CData(ii, :) = [0.85, 0.33, 0.10];
 end
end

xline(0, 'k-', ...
 'LineWidth', 1.0);

set(gca, ...
 'YTick', 1:numel(labels_A3), ...
 'YTickLabel', labels_A3, ...
 'YDir', 'reverse', ...
 'FontSize', 11, ...
 'FontName', 'Arial');

xlabel('Value / cost (USD per pack)');

title(sprintf('NMC A_3 recycling pathway breakdown at representative SOH = %.3f', ...
 mean_soh_rec));

grid on;
box on;

xmax = max(vals_full);
xmin = min(vals_full);
xr = xmax - xmin;

if xr < 1e-6
 xr = 1;
end

for ii = 1:numel(vals_full)

 v = vals_full(ii);

 if v >= 0
 text(v + 0.02 * xr, ii, sprintf('%.1f', v), ...
 'HorizontalAlignment', 'left', ...
 'VerticalAlignment', 'middle', ...
 'FontSize', 10, ...
 'FontName', 'Arial');
 else
 text(v - 0.02 * xr, ii, sprintf('%.1f', v), ...
 'HorizontalAlignment', 'right', ...
 'VerticalAlignment', 'middle', ...
 'FontSize', 10, ...
 'FontName', 'Arial');
 end
end

xlim([xmin - 0.12 * xr, xmax + 0.18 * xr]);

hold off;

local_save_figure(fig_A3, ...
 cfg.fig_A3_breakdown, ...
 cfg.png_A3_breakdown, ...
 cfg.png_resolution);

fprintf('NMC A3 recycling breakdown figure saved: %s\n', cfg.png_A3_breakdown);

%% 11) Save structured fixed-scale NMC results
NMC_fixed_result = struct();

% Configuration and paths.
NMC_fixed_result.cfg_part4 = cfg;
NMC_fixed_result.input_nmc_soh_mat = cfg.nmc_soh_mat;
NMC_fixed_result.input_error_model_mat = cfg.error_model_mat;

% Basic settings.
NMC_fixed_result.Fixed_Scale_N = Fixed_Scale_N;
NMC_fixed_result.N_sim = N_sim;
NMC_fixed_result.opt_k_idx = opt_k_idx;
NMC_fixed_result.opt_k = opt_k_NMC;
NMC_fixed_result.opt_T1 = opt_T1_NMC;
NMC_fixed_result.opt_T2 = opt_T2_NMC;
NMC_fixed_result.opt_total_cost = Fixed_Total_Cost(opt_k_idx);
NMC_fixed_result.opt_cost_per_pack = Fixed_Total_Cost(opt_k_idx) / Fixed_Scale_N;
NMC_fixed_result.rho = rho;
NMC_fixed_result.c_pack = c_pack;
NMC_fixed_result.c_train = c_train;
NMC_fixed_result.Eta_1 = Eta_1;
NMC_fixed_result.Eta_2 = Eta_2;
NMC_fixed_result.Lambda_H = Lambda_H;
NMC_fixed_result.Lambda_A = Lambda_H; % legacy alias
NMC_fixed_result.Lambda_R = Lambda_R;

% Economic parameters.
NMC_fixed_result.Q_pack = Q_pack;
NMC_fixed_result.r = r;
NMC_fixed_result.beta_refurbish = beta_refurbish;
NMC_fixed_result.C_A1_extra = C_A1_extra;
NMC_fixed_result.C_A2_extra = C_A2_extra;
NMC_fixed_result.M_pack = M_pack;
NMC_fixed_result.C_Degraded = C_Degraded;

% SOH and action-value samples.
NMC_fixed_result.s_true = s_true;
NMC_fixed_result.s_pred = s_pred;
NMC_fixed_result.sampled_noise = sampled_noise;
NMC_fixed_result.Pi_True = Pi_True;
NMC_fixed_result.Pi_True_Max = Pi_True_Max;
NMC_fixed_result.PerfectInfo_Action_i = PerfectInfo_Action_i;
NMC_fixed_result.True_Action_i = PerfectInfo_Action_i; % legacy alias

% Threshold search results.
NMC_fixed_result.T1_grid = T1_grid;
NMC_fixed_result.T2_grid = T2_grid;
NMC_fixed_result.best_T1_init = best_T1_init;
NMC_fixed_result.best_T2_init = best_T2_init;
NMC_fixed_result.best_T1_refined = best_T1_refined;
NMC_fixed_result.best_T2_refined = best_T2_refined;
NMC_fixed_result.expected_decision_loss_per_pack = min_L;

NMC_fixed_result.best_O_mean = best_O_mean;
NMC_fixed_result.best_H_mean = best_H_mean;
NMC_fixed_result.best_A_mean = best_H_mean; % legacy alias
NMC_fixed_result.best_R_mean = best_R_mean;

% k-dependent cost curves.
NMC_fixed_result.E_L_base = E_L_base;
NMC_fixed_result.O_base = O_base;
NMC_fixed_result.H_base = H_base;
NMC_fixed_result.A_base = H_base; % legacy alias
NMC_fixed_result.R_base = R_base;
NMC_fixed_result.Fixed_O = Fixed_O;
NMC_fixed_result.Fixed_H = Fixed_H;
NMC_fixed_result.Fixed_A = Fixed_H; % legacy alias
NMC_fixed_result.Fixed_R = Fixed_R;
NMC_fixed_result.Fixed_Model = Fixed_Model;
NMC_fixed_result.Fixed_Total_Cost = Fixed_Total_Cost;
NMC_fixed_result.T1_base = T1_base;
NMC_fixed_result.T2_base = T2_base;

% Final action allocation and losses.
NMC_fixed_result.Pred_Action_opt = Pred_Action_opt;
NMC_fixed_result.Action_Ratio_opt = Action_Ratio_opt;
NMC_fixed_result.PerfectInfo_Action_Ratio = PerfectInfo_Action_Ratio;
NMC_fixed_result.True_Action_Ratio = PerfectInfo_Action_Ratio; % legacy alias
NMC_fixed_result.O_arr_opt = O_arr_opt;
NMC_fixed_result.H_arr_opt = H_arr_opt;
NMC_fixed_result.A_arr_opt = H_arr_opt; % legacy alias
NMC_fixed_result.R_arr_opt = R_arr_opt;
NMC_fixed_result.Total_Loss_opt = Total_Loss_opt;
NMC_fixed_result.Executed_Pathway_Value_opt = Executed_Pathway_Value_opt;
NMC_fixed_result.PerfectInfo_Pathway_Value_opt = PerfectInfo_Pathway_Value_opt;
NMC_fixed_result.Net_Realized_Value_opt = Net_Realized_Value_opt;
NMC_fixed_result.Net_Revenue_opt = Net_Realized_Value_opt; % legacy alias

% NMC net-utility curves.
NMC_fixed_result.s_hat_grid = s_hat_grid;
NMC_fixed_result.G = G;
NMC_fixed_result.G_env = G_env;
NMC_fixed_result.J = J;

% Residual-error template.
NMC_fixed_result.k_emp = k_emp;
NMC_fixed_result.k_vals = k_vals;
NMC_fixed_result.k_anchor = k_anchor;
NMC_fixed_result.k_bridge_end = k_bridge_end;
NMC_fixed_result.rmse_target = rmse_target;
NMC_fixed_result.w_curve = w_curve;
NMC_fixed_result.PM_curve = PM_curve;
NMC_fixed_result.muM_curve = muM_curve;
NMC_fixed_result.sigM_curve = sigM_curve;
NMC_fixed_result.muR_curve = muR_curve;
NMC_fixed_result.sigR_curve = sigR_curve;
NMC_fixed_result.Noise_Diagnostic_Table = Noise_Diagnostic_Table;
NMC_fixed_result.residual_scaling_definition = ...
 'e_NMC(k) = rho * [e_LFP(k) - mean(e_LFP(k))]';

% A3 recycling decomposition.
NMC_fixed_result.mean_soh_rec = mean_soh_rec;
NMC_fixed_result.A3_recycling_contribution_values = vals_full;
NMC_fixed_result.A3_recycling_contribution_labels = labels_A3;
NMC_fixed_result.A3_net_value = net_value_A3;

save(cfg.result_mat, 'NMC_fixed_result', '-v7.3');

Summary_Table = table( ...
 rho, ...
 opt_k_NMC, ...
 opt_T1_NMC, ...
 opt_T2_NMC, ...
 Fixed_Total_Cost(opt_k_idx), ...
 Fixed_Total_Cost(opt_k_idx) / Fixed_Scale_N, ...
 min_L, ...
 min_L * Fixed_Scale_N, ...
 best_O_mean * Fixed_Scale_N, ...
 best_H_mean * Fixed_Scale_N, ...
 best_R_mean * Fixed_Scale_N, ...
 Fixed_Model(opt_k_idx), ...
 Action_Ratio_opt(1), ...
 Action_Ratio_opt(2), ...
 Action_Ratio_opt(3), ...
 mean_soh_rec, ...
 net_value_A3, ...
 'VariableNames', { ...
 'rho', ...
 'opt_k', ...
 'opt_T1', ...
 'opt_T2', ...
 'opt_total_cost_USD', ...
 'opt_cost_per_pack_USD', ...
 'expected_decision_loss_per_pack_USD', ...
 'expected_decision_loss_total_USD', ...
 'opportunity_loss_total_USD', ...
 'mismatch_handling_rework_cost_total_USD', ...
 'risk_penalty_total_USD', ...
 'SOH_labelling_adaptation_cost_USD', ...
 'A1_predicted_share', ...
 'A2_predicted_share', ...
 'A3_predicted_share', ...
 'representative_A3_SOH', ...
 'A3_net_value_USD_per_pack'});

writetable(Summary_Table, cfg.summary_csv);

fprintf('>>> Fixed-scale NMC results saved to: %s\n', cfg.result_mat);
fprintf('>>> Fixed-scale NMC summary saved to: %s\n', cfg.summary_csv);
fprintf('================ Part4 Exp02 completed ================\n');

%% Local helper functions
function SOH_data = local_extract_nmc_soh_from_mat(SOH_file, input_file)
% Extract a numeric NMC SOH vector from a MAT-file structure.

if isfield(SOH_file, 'SOH_table')
 SOH_raw = SOH_file.SOH_table;
 if isfield(SOH_file, 'day')
 day_count = SOH_file.day;
 SOH_raw = SOH_raw(1:day_count);
 end

elseif isfield(SOH_file, 'NMC_SOH_Table')
 SOH_raw = SOH_file.NMC_SOH_Table;
elseif isfield(SOH_file, 'SOH_data')

 SOH_raw = SOH_file.SOH_data;
else
 var_names = fieldnames(SOH_file);
 if isempty(var_names)
 error('No variables were found in %s.', input_file);
 end
 SOH_raw = SOH_file.(var_names{1});
end

if istable(SOH_raw)

 table_vars = SOH_raw.Properties.VariableNames;
 soh_col_idx = find(contains(lower(table_vars), 'soh'), 1, 'first');

 if isempty(soh_col_idx)
 soh_col_idx = 1;
 end
 SOH_data = SOH_raw{:, soh_col_idx};
else
 SOH_data = SOH_raw;
end

SOH_data = double(SOH_data(:));
SOH_data = SOH_data(isfinite(SOH_data));

if isempty(SOH_data)
 error('No valid NMC SOH values were found in %s.', input_file);
end
end

function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);
if ~exist(out_dir, 'dir')
 mkdir(out_dir);
end
savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end
