%% P4_Exp09_FixedScale_NMC_ErrorScalingRobustness.m
% Purpose:
% This script evaluates fixed-scale NMC robustness to the residual-error scaling factor rho_NMC and generates Extended Data Fig. 8.
% The information investment is fixed at the baseline NMC optimum; for each rho_NMC, the script re-optimizes T1 and T2 but does not re-optimize k.
% For each rho_NMC value, the predicted SOH is reconstructed by scaling the
% baseline NMC proxy residual template. The SOH thresholds T1* and T2* are
% re-optimized, and prediction-error metrics, decision-loss components, net
% value retention, policy turnover, and action shares are calculated.

clear; clc; close all;

set(groot, 'DefaultFigureVisible', 'on');

%% 1) Configuration and path setup
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

cfg.part4_dir = script_dir;

cfg.output_dir = fullfile(cfg.part4_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');
cfg.input_mat = fullfile(cfg.results_dir, 'P4_Exp02_FixedScale_NMC_Workspace.mat');

cfg.figure_root = fullfile(cfg.part4_dir, 'Figures');
cfg.extended_fig_dir = fullfile(cfg.figure_root, 'Extended');

% Output tables and MAT files.
cfg.summary_csv = fullfile(cfg.results_dir, 'P4_Exp09_FixedScale_NMC_ErrorScalingRobustness_Summary.csv');

cfg.result_mat = fullfile(cfg.results_dir, 'P4_Exp09_FixedScale_NMC_ErrorScalingRobustness_Results.mat');
cfg.threshold_surface_mat = fullfile(cfg.results_dir, 'P4_Exp09_FixedScale_NMC_ErrorScalingRobustness_ThresholdSurfaces.mat');

% Output figures.
cfg.fig_error_metrics = fullfile(cfg.extended_fig_dir,'ExD08a_NMC_error_scaling_prediction_error_metrics.fig');
cfg.png_error_metrics = fullfile(cfg.extended_fig_dir, 'ExD08a_NMC_error_scaling_prediction_error_metrics.png');

cfg.fig_decision_loss = fullfile(cfg.extended_fig_dir, 'ExD08b_NMC_error_scaling_decision_loss_decomposition.fig');
cfg.png_decision_loss = fullfile(cfg.extended_fig_dir, 'ExD08b_NMC_error_scaling_decision_loss_decomposition.png');

cfg.fig_net_value = fullfile(cfg.extended_fig_dir,  'ExD08c_NMC_error_scaling_net_value_retention.fig');
cfg.png_net_value = fullfile(cfg.extended_fig_dir,  'ExD08c_NMC_error_scaling_net_value_retention.png');
cfg.fig_policy_turnover = fullfile(cfg.extended_fig_dir, 'ExD08d_NMC_error_scaling_policy_turnover.fig');
cfg.png_policy_turnover = fullfile(cfg.extended_fig_dir, 'ExD08d_NMC_error_scaling_policy_turnover.png');
cfg.fig_action_allocation = fullfile(cfg.extended_fig_dir, 'ExD08e_NMC_error_scaling_action_allocation.fig');
cfg.png_action_allocation = fullfile(cfg.extended_fig_dir, 'ExD08e_NMC_error_scaling_action_allocation.png');
cfg.fig_thresholds = fullfile(cfg.extended_fig_dir, 'ExD08f_NMC_error_scaling_optimized_thresholds.fig');
cfg.png_thresholds = fullfile(cfg.extended_fig_dir, 'ExD08f_NMC_error_scaling_optimized_thresholds.png');

cfg.png_resolution = 600;

% The fixed k must come from the baseline NMC optimization at rho = 0.8.
cfg.baseline_rho = 0.8;

folder_list = {cfg.output_dir, cfg.results_dir, cfg.figure_root, cfg.extended_fig_dir};

for ii = 1:numel(folder_list)
    if ~exist(folder_list{ii}, 'dir')
        mkdir(folder_list{ii});
    end
end

fprintf('================ P4 Exp09: fixed-scale NMC error-scaling robustness ================\n');
fprintf('Input workspace file: %s\n', cfg.input_mat);
fprintf('Output folder: %s\n', cfg.results_dir);
fprintf('Figure folder: %s\n', cfg.extended_fig_dir);

%% 2) Load the NMC fixed-scale workspace
if ~isfile(cfg.input_mat)
    error(['Input file not found: %s\n' ...
        'Please run P4_Exp02_FixedScale_NMC_Optimization.m first to generate the fixed-scale NMC workspace.'], ...
        cfg.input_mat);
end

vars_in_file = who('-file', cfg.input_mat);

safe_var_list = { ...
    'eps_ref', ...
    'eps_opt', ...
    'sampled_noise', ...
    'sampled_noise_opt', ...
    'noise_opt_raw', ...
    'rho', ...
    's_true', ...
    'Pi_True', ...
    'Eta_1', ...
    'Eta_2', ...
    'Lambda_A', ...
    'Lambda_R', ...
    'Fixed_Scale_N', ...
    'c_pack', ...
    'c_train', ...
    'opt_k_NMC', ...
    'opt_k', ...
    'k_ref_for_NMC', ...
    'T1_grid', ...
    'T2_grid', ...
    'calc_V_reuse', ...
    'calc_V_refurbish', ...
    'calc_V_recycle', ...
    'calc_V_reuse_base', ...
    'C_A1_extra', ...
    'C_A2_extra', ...
    'beta_refurbish', ...
    'C0', ...
    'C1', ...
    'gamma', ...
    'gamma_ref'};

vars_to_load = intersect(safe_var_list, vars_in_file, 'stable');

S = load(cfg.input_mat, vars_to_load{:});

close all;

required_vars = { ...
    's_true', ...
    'Eta_1', ...
    'Eta_2', ...
    'Lambda_A', ...
    'Lambda_R', ...
    'Fixed_Scale_N', ...
    'c_pack', ...
    'c_train'};

for ii = 1:numel(required_vars)
    if ~isfield(S, required_vars{ii})
        error('Required variable is missing from %s: %s', ...
            cfg.input_mat, required_vars{ii});
    end
end

s_true = S.s_true(:);

Eta_1 = S.Eta_1;
Eta_2 = S.Eta_2;

Lambda_A = S.Lambda_A;
Lambda_R = S.Lambda_R;

Fixed_Scale_N = S.Fixed_Scale_N;
c_pack = S.c_pack;
c_train = S.c_train;

N_sim = numel(s_true);

fprintf('Fixed-scale NMC workspace loaded successfully.\n');
fprintf('N_sim = %d\n', N_sim);
fprintf('Fixed scale = %d packs\n', Fixed_Scale_N);
fprintf('Eta_1 = %.4f, Eta_2 = %.4f\n', Eta_1, Eta_2);
fprintf('Lambda_A = %.4f, Lambda_R = %.4f\n', Lambda_A, Lambda_R);

if isfield(S, 'rho')
    rho_workspace = double(S.rho);

    if ~isscalar(rho_workspace) || ~isfinite(rho_workspace) || ...
            abs(rho_workspace - cfg.baseline_rho) > 1e-12
        error(['The fixed information investment must be taken from the ' ...
            'baseline NMC optimization at rho = %.1f. The loaded workspace ' ...
            'contains rho = %.6g.'], cfg.baseline_rho, rho_workspace);
    end
else
    warning(['The input workspace does not store rho. The script assumes ' ...
        'that P4 Exp02 was run at the baseline rho = %.1f.'], ...
        cfg.baseline_rho);
end

%% 3) Extract the baseline residual-error template
if isfield(S, 'eps_ref')

    eps_ref = S.eps_ref(:);
    residual_source = 'eps_ref';

elseif isfield(S, 'eps_opt')

    eps_ref = S.eps_opt(:);
    residual_source = 'eps_opt';

elseif isfield(S, 'sampled_noise_opt') && isfield(S, 'rho')

    eps_ref = S.sampled_noise_opt(:) ./ S.rho;
    residual_source = 'sampled_noise_opt / rho';

elseif isfield(S, 'sampled_noise') && isfield(S, 'rho')

    eps_ref = S.sampled_noise(:) ./ S.rho;
    residual_source = 'sampled_noise / rho';

elseif isfield(S, 'noise_opt_raw')

    eps_ref = S.noise_opt_raw(:) - mean(S.noise_opt_raw(:));
    residual_source = 'centered noise_opt_raw';

else

    error(['No residual-error template was found in %s.\n' ...
        'Expected eps_ref, eps_opt, sampled_noise_opt with rho, ' ...
        'sampled_noise with rho, or noise_opt_raw.'], ...
        cfg.input_mat);
end

if numel(eps_ref) ~= N_sim
    error('Residual template length does not match s_true length.');
end

eps_ref = eps_ref - mean(eps_ref);

fprintf('Residual-error template extracted from: %s\n', residual_source);
fprintf('Residual template mean after centering = %.4e\n', mean(eps_ref));
fprintf('Residual template std = %.6f\n', std(eps_ref));

%% 4) Determine the fixed information cost
if isfield(S, 'opt_k_NMC')

    k_ref_for_NMC = S.opt_k_NMC;

elseif isfield(S, 'k_ref_for_NMC')

    k_ref_for_NMC = S.k_ref_for_NMC;

elseif isfield(S, 'opt_k')

    k_ref_for_NMC = S.opt_k;

else

    error(['No optimized NMC label size was found in %s. ' ...
        'Run the baseline P4 Exp02 optimization before P4 Exp09.'], ...
        cfg.input_mat);
end

if ~isscalar(k_ref_for_NMC) || ~isfinite(k_ref_for_NMC) || ...
        k_ref_for_NMC <= 0 || abs(k_ref_for_NMC - round(k_ref_for_NMC)) > 1e-12
    error('The fixed NMC label count must be a positive integer.');
end

k_ref_for_NMC = round(k_ref_for_NMC);

Information_cost_USD_fixed = k_ref_for_NMC * c_pack + c_train;

fprintf('k_ref_for_NMC = %d\n', k_ref_for_NMC);
fprintf('Fixed information cost = %.2f USD\n', Information_cost_USD_fixed);

%% 5) Build or load true action-value matrix
if isfield(S, 'Pi_True')

    Pi_True = S.Pi_True;

    if size(Pi_True, 1) ~= N_sim || size(Pi_True, 2) ~= 3
        error('Loaded Pi_True has an inconsistent size.');
    end

fprintf('Pi_True loaded directly from P4 Exp02 workspace.\n');

elseif isfield(S, 'calc_V_reuse') && ...
        isfield(S, 'calc_V_refurbish') && ...
        isfield(S, 'calc_V_recycle')

    calc_V_reuse = S.calc_V_reuse;
    calc_V_refurbish = S.calc_V_refurbish;
    calc_V_recycle = S.calc_V_recycle;

    Pi_True = [ ...
        calc_V_reuse(s_true), ...
        calc_V_refurbish(s_true), ...
        calc_V_recycle(s_true)];

    fprintf('Pi_True reconstructed from saved value functions.\n');

elseif isfield(S, 'calc_V_reuse_base') && isfield(S, 'calc_V_recycle')

    calc_V_reuse_base = S.calc_V_reuse_base;
    calc_V_recycle = S.calc_V_recycle;

    if isfield(S, 'C_A1_extra')
        C_A1_extra = S.C_A1_extra;
    else
        C_A1_extra = 10;
    end

    if isfield(S, 'C_A2_extra')
        C_A2_extra = S.C_A2_extra;
    else
        C_A2_extra = 15;
    end

    if isfield(S, 'beta_refurbish')
        beta_refurbish = S.beta_refurbish;
    else
        beta_refurbish = 0.09;
    end

    if isfield(S, 'C0')
        C0 = S.C0;
    else
        C0 = 43;
    end

    if isfield(S, 'C1')
        C1 = S.C1;
    else
        C1 = 80;
    end

    if isfield(S, 'gamma')
        gamma = S.gamma;
    elseif isfield(S, 'gamma_ref')
        gamma = S.gamma_ref;
    else
        gamma = 3;
    end

    calc_C_refurbish = @(soh) C0 + C1 .* (1 - soh).^gamma;

    calc_V_reuse = @(soh) calc_V_reuse_base(soh) - C_A1_extra;

    calc_V_refurbish = @(soh) ...
        calc_V_reuse_base(min(soh + beta_refurbish .* (1 - soh), 1.0)) ...
        - calc_C_refurbish(soh) ...
        - C_A1_extra ...
        - C_A2_extra;

    Pi_True = [ ...
        calc_V_reuse(s_true), ...
        calc_V_refurbish(s_true), ...
        calc_V_recycle(s_true)];

    fprintf('Pi_True reconstructed from reuse-base and recycling functions.\n');

else

    error(['NMC action-value information is missing from %s.\n' ...
        'Expected Pi_True or value-function handles.'], ...
        cfg.input_mat);
end

Pi_True = double(Pi_True);

[Pi_True_Max, True_Action_i] = max(Pi_True, [], 2);

True_A1_share = mean(True_Action_i == 1);
True_A2_share = mean(True_Action_i == 2);
True_A3_share = mean(True_Action_i == 3);

Oracle_value_USD = Fixed_Scale_N * mean(Pi_True_Max);

fprintf('True action shares: A1 = %.4f, A2 = %.4f, A3 = %.4f\n', ...
    True_A1_share, True_A2_share, True_A3_share);
fprintf('Oracle value = %.4f USD\n', Oracle_value_USD);

%% 6) Define rho_NMC scenarios and threshold grids
rho_list = (0.4:0.1:2.0)';

n_rho = numel(rho_list);

rho_label = strings(n_rho, 1);

for rr = 1:n_rho
    if abs(rho_list(rr) - cfg.baseline_rho) < 1e-12
        rho_label(rr) = sprintf("rho = %.1f baseline", cfg.baseline_rho);
    else
        rho_label(rr) = sprintf("rho = %.1f", rho_list(rr));
    end
end

if isfield(S, 'T1_grid') && isfield(S, 'T2_grid')

    T1_grid = S.T1_grid(:)';
    T2_grid = S.T2_grid(:)';

fprintf('Threshold grids loaded from P4 Exp02 workspace.\n');

else

    T1_grid = 0.70:0.005:0.85;
    T2_grid = 0.85:0.005:0.98;

    fprintf('Threshold grids were not found in workspace. Default NMC grids are used.\n');
end

num_T1 = numel(T1_grid);
num_T2 = numel(T2_grid);

fprintf('rho range: %.1f to %.1f, with %d grid points\n', ...
    min(rho_list), max(rho_list), n_rho);
fprintf('T1 grid: %.3f to %.3f, with %d grid points\n', ...
    min(T1_grid), max(T1_grid), num_T1);
fprintf('T2 grid: %.3f to %.3f, with %d grid points\n', ...
    min(T2_grid), max(T2_grid), num_T2);

%% 7) Preallocate result arrays
T1_star = zeros(n_rho, 1);
T2_star = zeros(n_rho, 1);

A1_share = zeros(n_rho, 1);
A2_share = zeros(n_rho, 1);
A3_share = zeros(n_rho, 1);

Opportunity_loss_USD = zeros(n_rho, 1);
Verification_cost_USD = zeros(n_rho, 1);
Risk_penalty_USD = zeros(n_rho, 1);
Decision_loss_USD = zeros(n_rho, 1);
Total_cost_USD = zeros(n_rho, 1);
Total_cost_per_pack_USD = zeros(n_rho, 1);

Gross_action_value_USD = zeros(n_rho, 1);
Net_realized_value_USD = zeros(n_rho, 1);
Net_value_per_pack_USD = zeros(n_rho, 1);
Oracle_retention_percent = zeros(n_rho, 1);

RMSE_scaled = zeros(n_rho, 1);
MAE_scaled = zeros(n_rho, 1);
P95_abs_error = zeros(n_rho, 1);

Loss_Grid_all = cell(n_rho, 1);
Pred_Action_byRho = zeros(N_sim, n_rho);

Policy_turnover_rate = zeros(n_rho, 1);
A1_turnover_rate = zeros(n_rho, 1);
A2_turnover_rate = zeros(n_rho, 1);
A3_turnover_rate = zeros(n_rho, 1);

%% 8) Re-optimize T1/T2 for each rho_NMC
fprintf('\nStarting NMC residual-error scaling robustness optimization.\n');

for rr = 1:n_rho

    rho_now = rho_list(rr);

    sampled_noise = rho_now .* eps_ref;
    s_pred = min(max(s_true + sampled_noise, 0), 1.0);

    RMSE_scaled(rr) = sqrt(mean((s_pred - s_true).^2));
    MAE_scaled(rr) = mean(abs(s_pred - s_true));
    P95_abs_error(rr) = prctile(abs(s_pred - s_true), 95);

    min_L = inf;
    best_T1 = NaN;
    best_T2 = NaN;

    best_O_arr = [];
    best_A_arr = [];
    best_R_arr = [];
    best_Pred_Action = [];

    Loss_Grid = nan(num_T2, num_T1);

    for i_t1 = 1:num_T1

        T1 = T1_grid(i_t1);

        for i_t2 = 1:num_T2

            T2 = T2_grid(i_t2);

            if T1 >= T2
                continue;
            end

            Pred_Action_j = 3 * ones(N_sim, 1);
            Pred_Action_j(s_pred >= T1 & s_pred < T2) = 2;
            Pred_Action_j(s_pred >= T2) = 1;

            idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_j);
            O_arr = Pi_True_Max - Pi_True(idx_pred);

            is_G1_error = (True_Action_i == 3 & Pred_Action_j == 2) | ...
                (True_Action_i == 2 & Pred_Action_j == 3);

            is_G2_error = (True_Action_i == 1 & Pred_Action_j == 2) | ...
                (True_Action_i == 2 & Pred_Action_j == 1);

            Current_Eta = zeros(N_sim, 1);
            Current_Eta(is_G1_error) = Eta_1;
            Current_Eta(is_G2_error) = Eta_2;

            trigger_penalty = O_arr > Current_Eta;
            Excess_Loss = max(0, O_arr - Current_Eta);

            A_arr = trigger_penalty .* Lambda_A;

            R_arr = (Pred_Action_j < True_Action_i) .* ...
                trigger_penalty .* (Lambda_R .* Excess_Loss);

            E_L = mean(O_arr + A_arr + R_arr);

            Loss_Grid(i_t2, i_t1) = E_L * Fixed_Scale_N;

            if E_L < min_L

                min_L = E_L;
                best_T1 = T1;
                best_T2 = T2;

                best_O_arr = O_arr;
                best_A_arr = A_arr;
                best_R_arr = R_arr;
                best_Pred_Action = Pred_Action_j;
            end
        end
    end

    Loss_Grid_all{rr} = Loss_Grid;

    T1_star(rr) = best_T1;
    T2_star(rr) = best_T2;

    A1_share(rr) = mean(best_Pred_Action == 1);
    A2_share(rr) = mean(best_Pred_Action == 2);
    A3_share(rr) = mean(best_Pred_Action == 3);

    Pred_Action_byRho(:, rr) = best_Pred_Action;

    Opportunity_loss_USD(rr) = Fixed_Scale_N * mean(best_O_arr);
    Verification_cost_USD(rr) = Fixed_Scale_N * mean(best_A_arr);
    Risk_penalty_USD(rr) = Fixed_Scale_N * mean(best_R_arr);

    Decision_loss_USD(rr) = Opportunity_loss_USD(rr) + ...
        Verification_cost_USD(rr) + ...
        Risk_penalty_USD(rr);

    Total_cost_USD(rr) = Decision_loss_USD(rr) + Information_cost_USD_fixed;
    Total_cost_per_pack_USD(rr) = Total_cost_USD(rr) / Fixed_Scale_N;

    idx_best = sub2ind([N_sim, 3], (1:N_sim)', best_Pred_Action);

    Gross_action_value_USD(rr) = Fixed_Scale_N * mean(Pi_True(idx_best));

    Net_realized_value_USD(rr) = Fixed_Scale_N * mean( ...
        Pi_True(idx_best) - best_A_arr - best_R_arr);

    Net_value_per_pack_USD(rr) = Net_realized_value_USD(rr) / Fixed_Scale_N;

    Oracle_retention_percent(rr) = ...
        100 * Net_realized_value_USD(rr) / Oracle_value_USD;

    fprintf(['rho = %.2f | RMSE = %.4f, MAE = %.4f, P95 = %.4f | ' ...
        'T1 = %.3f, T2 = %.3f | A1 = %.3f, A2 = %.3f, A3 = %.3f | ' ...
        'cost = %.4f USD/pack | net = %.2f USD/pack | retained = %.4f%%\n'], ...
        rho_now, ...
        RMSE_scaled(rr), MAE_scaled(rr), P95_abs_error(rr), ...
        T1_star(rr), T2_star(rr), ...
        A1_share(rr), A2_share(rr), A3_share(rr), ...
        Total_cost_per_pack_USD(rr), ...
        Net_value_per_pack_USD(rr), ...
        Oracle_retention_percent(rr));
end

fprintf('NMC residual-error scaling robustness optimization completed.\n');

%% 9) Calculate policy-turnover rates relative to baseline rho = %.1f
idx_baseline_rho = find(abs(rho_list - cfg.baseline_rho) < 1e-12, 1);

if isempty(idx_baseline_rho)
    error('rho_list does not include the baseline rho = %.1f.', cfg.baseline_rho);
end

Pred_Action_baseline = Pred_Action_byRho(:, idx_baseline_rho);

idx_A1_base = Pred_Action_baseline == 1;
idx_A2_base = Pred_Action_baseline == 2;
idx_A3_base = Pred_Action_baseline == 3;

for rr = 1:n_rho

    Pred_Action_now = Pred_Action_byRho(:, rr);

    Policy_turnover_rate(rr) = mean(Pred_Action_now ~= Pred_Action_baseline);

    if any(idx_A1_base)
        A1_turnover_rate(rr) = mean(Pred_Action_now(idx_A1_base) ~= 1);
    else
        A1_turnover_rate(rr) = NaN;
    end

    if any(idx_A2_base)
        A2_turnover_rate(rr) = mean(Pred_Action_now(idx_A2_base) ~= 2);
    else
        A2_turnover_rate(rr) = NaN;
    end

    if any(idx_A3_base)
        A3_turnover_rate(rr) = mean(Pred_Action_now(idx_A3_base) ~= 3);
    else
        A3_turnover_rate(rr) = NaN;
    end
end

fprintf('Policy-turnover rates relative to baseline rho = %.1f have been calculated.\n', cfg.baseline_rho);

%% 10) Build and save summary table
Result_Table = table( ...
    rho_list, ...
    rho_label, ...
    RMSE_scaled, ...
    MAE_scaled, ...
    P95_abs_error, ...
    T1_star, ...
    T2_star, ...
    repmat(True_A1_share, n_rho, 1), ...
    repmat(True_A2_share, n_rho, 1), ...
    repmat(True_A3_share, n_rho, 1), ...
    A1_share, ...
    A2_share, ...
    A3_share, ...
    Policy_turnover_rate, ...
    A1_turnover_rate, ...
    A2_turnover_rate, ...
    A3_turnover_rate, ...
    Opportunity_loss_USD, ...
    Verification_cost_USD, ...
    Risk_penalty_USD, ...
    Decision_loss_USD, ...
    repmat(Information_cost_USD_fixed, n_rho, 1), ...
    Total_cost_USD, ...
    Total_cost_per_pack_USD, ...
    Gross_action_value_USD, ...
    Net_realized_value_USD, ...
    Net_value_per_pack_USD, ...
    repmat(Oracle_value_USD, n_rho, 1), ...
    Oracle_retention_percent, ...
    'VariableNames', { ...
    'rho_NMC', ...
    'rho_label', ...
    'RMSE_scaled', ...
    'MAE_scaled', ...
    'P95_abs_error', ...
    'T1_star', ...
    'T2_star', ...
    'True_A1_share', ...
    'True_A2_share', ...
    'True_A3_share', ...
    'Pred_A1_share', ...
    'Pred_A2_share', ...
    'Pred_A3_share', ...
    'Policy_turnover_rate', ...
    'A1_turnover_rate', ...
    'A2_turnover_rate', ...
    'A3_turnover_rate', ...
    'Opportunity_loss_USD', ...
    'Verification_cost_USD', ...
    'Risk_penalty_USD', ...
    'Decision_loss_USD', ...
    'Information_cost_USD', ...
    'Total_cost_USD', ...
    'Total_cost_per_pack_USD', ...
    'Gross_action_value_USD', ...
    'Net_realized_value_USD', ...
    'Net_value_per_pack_USD', ...
    'Oracle_value_USD', ...
    'Oracle_retention_percent'});

disp(' ');
disp('========== Extended Data Fig. 8: NMC residual-error scaling robustness ==========');
disp(Result_Table);

writetable(Result_Table, cfg.summary_csv);

save(cfg.result_mat, ...
    'cfg', ...
    'rho_list', ...
    'rho_label', ...
    'Result_Table', ...
    'Loss_Grid_all', ...
    'T1_grid', ...
    'T2_grid', ...
    'T1_star', ...
    'T2_star', ...
    'A1_share', ...
    'A2_share', ...
    'A3_share', ...
    'True_A1_share', ...
    'True_A2_share', ...
    'True_A3_share', ...
    'Pred_Action_byRho', ...
    'Policy_turnover_rate', ...
    'A1_turnover_rate', ...
    'A2_turnover_rate', ...
    'A3_turnover_rate', ...
    'Opportunity_loss_USD', ...
    'Verification_cost_USD', ...
    'Risk_penalty_USD', ...
    'Decision_loss_USD', ...
    'Information_cost_USD_fixed', ...
    'Total_cost_USD', ...
    'Total_cost_per_pack_USD', ...
    'Gross_action_value_USD', ...
    'Net_realized_value_USD', ...
    'Net_value_per_pack_USD', ...
    'Oracle_value_USD', ...
    'Oracle_retention_percent', ...
    'RMSE_scaled', ...
    'MAE_scaled', ...
    'P95_abs_error', ...
    'Fixed_Scale_N', ...
    'k_ref_for_NMC', ...
    'Eta_1', ...
    'Eta_2', ...
    'Lambda_A', ...
    'Lambda_R', ...
    'eps_ref', ...
    'residual_source', ...
    '-v7.3');

save(cfg.threshold_surface_mat, ...
    'cfg', ...
    'rho_list', ...
    'T1_grid', ...
    'T2_grid', ...
    'Loss_Grid_all', ...
    '-v7.3');

fprintf('Summary table saved: %s\n', cfg.summary_csv);
fprintf('MAT result file saved: %s\n', cfg.result_mat);
fprintf('Threshold-surface MAT file saved: %s\n', cfg.threshold_surface_mat);

%% 11) Extended Data Fig. 8a: prediction-error metrics
fig1 = figure( ...
    'Name', 'ExD08a_NMC_error_scaling_prediction_error_metrics', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 7.8, 6.0]);

plot(rho_list, RMSE_scaled, '-o', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

hold on;

plot(rho_list, MAE_scaled, '-s', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

plot(rho_list, P95_abs_error, '-^', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

xline(0.8, '--', ...
    'Baseline', ...
    'LineWidth', 1.1, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('NMC residual-error scale, \rho_{NMC}', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

ylabel('Prediction error', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Prediction-error scaling', ...
    'FontName', 'Arial', ...
    'FontSize', 9.5, ...
    'FontWeight', 'normal');

legend({'RMSE', 'MAE', '95th percentile |error|'}, ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 7.2);

xlim([min(rho_list) - 0.05, max(rho_list) + 0.05]);
xticks(0.4:0.2:2.0);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out');

local_save_figure(fig1, cfg.fig_error_metrics, cfg.png_error_metrics, cfg.png_resolution);

%% 12) Extended Data Fig. 8b: decision-loss decomposition
fig2 = figure( ...
    'Name', 'Extended_Fig7b_decision_loss_decomposition', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 8.4, 6.2]);

DecisionCostStack_1e4USD = [ ...
    Opportunity_loss_USD, ...
    Verification_cost_USD, ...
    Risk_penalty_USD] ./ 1e4;

Decision_loss_total_1e4USD = Decision_loss_USD ./ 1e4;

b = bar(rho_list, DecisionCostStack_1e4USD, 'stacked', ...
    'EdgeColor', 'none', ...
    'BarWidth', 0.75);

hold on;

hTotal = plot(rho_list, Decision_loss_total_1e4USD, '-k', ...
    'LineWidth', 2.0, ...
    'Marker', 'o', ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

xline(0.8, '--', ...
    'Baseline', ...
    'LineWidth', 1.1, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('NMC residual-error scale, \rho_{NMC}', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

ylabel('Decision-loss cost (10^4 USD)', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Decision-loss decomposition', ...
    'FontName', 'Arial', ...
    'FontSize', 9.5, ...
    'FontWeight', 'normal');

legend([b(1), b(2), b(3), hTotal], ...
    {'Opportunity loss', ...
    'Verification cost', ...
    'Risk penalty', ...
    'Total decision loss'}, ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 7.2);

xlim([min(rho_list) - 0.05, max(rho_list) + 0.05]);
xticks(0.4:0.2:2.0);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out');

local_save_figure(fig2, cfg.fig_decision_loss, cfg.png_decision_loss, cfg.png_resolution);

%% 13) Extended Data Fig. 8c: net value retention
fig3 = figure( ...
    'Name', 'ExD08c_NMC_error_scaling_net_value_retention', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 7.8, 6.0]);

yyaxis left

h1 = plot(rho_list, Net_value_per_pack_USD, '-o', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

ylabel('Net value (USD per pack)', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

yyaxis right

h2 = plot(rho_list, Oracle_retention_percent, '-s', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

ylabel('Oracle value retained (%)', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

xline(0.8, '--', ...
    'Baseline', ...
    'LineWidth', 1.1, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('NMC residual-error scale, \rho_{NMC}', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Value retention', ...
    'FontName', 'Arial', ...
    'FontSize', 9.5, ...
    'FontWeight', 'normal');

legend([h1, h2], ...
    {'Net value per pack', 'Oracle value retained'}, ...
    'Location', 'best', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 7.2);

xlim([min(rho_list) - 0.05, max(rho_list) + 0.05]);
xticks(0.4:0.2:2.0);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out');

local_save_figure(fig3, cfg.fig_net_value, cfg.png_net_value, cfg.png_resolution);

%% 14) Figure 7d: policy turnover
fig4 = figure( ...
    'Name', 'ExD08d_NMC_error_scaling_policy_turnover', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 7.8, 6.0]);

plot(rho_list, Policy_turnover_rate, '-o', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

hold on;

plot(rho_list, A1_turnover_rate, '--s', ...
    'LineWidth', 1.4, ...
    'MarkerSize', 4.8, ...
    'MarkerFaceColor', 'w');

plot(rho_list, A2_turnover_rate, '--^', ...
    'LineWidth', 1.4, ...
    'MarkerSize', 4.8, ...
    'MarkerFaceColor', 'w');

plot(rho_list, A3_turnover_rate, '--d', ...
    'LineWidth', 1.4, ...
    'MarkerSize', 4.8, ...
    'MarkerFaceColor', 'w');

xline(0.8, '--', ...
    'Baseline', ...
    'LineWidth', 1.1, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('NMC residual-error scale, \rho_{NMC}', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

ylabel('Policy turnover rate', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Policy stability relative to baseline', ...
    'FontName', 'Arial', ...
    'FontSize', 9.5, ...
    'FontWeight', 'normal');

legend({'Overall', ...
    'A_1 baseline group', ...
    'A_2 baseline group', ...
    'A_3 baseline group'}, ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 7.0);

turnover_all = [ ...
    Policy_turnover_rate; ...
    A1_turnover_rate; ...
    A2_turnover_rate; ...
    A3_turnover_rate];

turnover_all = turnover_all(isfinite(turnover_all));

if isempty(turnover_all)
    ylim([0, 1]);
else
    ylim([0, max(turnover_all) * 1.15 + eps]);
end

xlim([min(rho_list) - 0.05, max(rho_list) + 0.05]);
xticks(0.4:0.2:2.0);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out');

local_save_figure(fig4, cfg.fig_policy_turnover, cfg.png_policy_turnover, cfg.png_resolution);

%% 15) Figure 7e: action allocation
fig5 = figure( ...
    'Name', 'ExD08e_NMC_error_scaling_action_allocation', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 8.0, 6.0]);

Y_action = [A1_share, A2_share, A3_share];

bar(rho_list, Y_action, 'stacked', ...
    'EdgeColor', 'none', ...
    'BarWidth', 0.75);

hold on;

xline(0.8, '--', ...
    'Baseline', ...
    'LineWidth', 1.1, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('NMC residual-error scale, \rho_{NMC}', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

ylabel('Predicted action share', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Action allocation', ...
    'FontName', 'Arial', ...
    'FontSize', 9.5, ...
    'FontWeight', 'normal');

legend({'A_1 direct reuse', 'A_2 refurbishment', 'A_3 recycling'}, ...
    'Location', 'eastoutside', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 7.0);

ylim([0, 1]);
xlim([min(rho_list) - 0.05, max(rho_list) + 0.05]);
xticks(0.4:0.2:2.0);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out');

local_save_figure(fig5, cfg.fig_action_allocation, cfg.png_action_allocation, cfg.png_resolution);

%% 16) Figure 7f: optimized thresholds
fig6 = figure( ...
    'Name', 'ExD08f_NMC_error_scaling_optimized_thresholds', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 7.8, 6.0]);

plot(rho_list, T1_star, '-o', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

hold on;

plot(rho_list, T2_star, '-s', ...
    'LineWidth', 1.8, ...
    'MarkerSize', 5.2, ...
    'MarkerFaceColor', 'w');

xline(0.8, '--', ...
    'Baseline', ...
    'LineWidth', 1.1, ...
    'LabelVerticalAlignment', 'bottom', ...
    'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('NMC residual-error scale, \rho_{NMC}', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

ylabel('Optimized SOH threshold', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Optimized thresholds', ...
    'FontName', 'Arial', ...
    'FontSize', 9.5, ...
    'FontWeight', 'normal');

legend({'T_1^*', 'T_2^*'}, ...
    'Location', 'best', ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', 7.2);

xlim([min(rho_list) - 0.05, max(rho_list) + 0.05]);
xticks(0.4:0.2:2.0);

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out');

local_save_figure(fig6, cfg.fig_thresholds, cfg.png_thresholds, cfg.png_resolution);

fprintf('\n>>> Extended Data Fig. 8 NMC error-scaling robustness completed.\n');
fprintf('>>> Summary table saved: %s\n', cfg.summary_csv);
fprintf('>>> Figures saved in: %s\n', cfg.extended_fig_dir);
fprintf('==========================================================\n');

%% Local helper function
function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end