%% P4_Exp01_fixed_scale_LFP_optimization.m
% Purpose:
% This script implements the fixed-scale LFP recertification optimization.
%
% It combines SOH-dependent action-value functions, the k-dependent
% residual-error model generated by Part3, threshold-based action allocation,
% and decision-loss accounting to identify the optimal target-domain
% labelling investment k and the corresponding SOH thresholds T1 and T2
% under a fixed deployment scale.

clear; clc; close all;

%% 1) Configuration
cfg = struct();

% Use the current script folder as the Part4 root folder.
script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

% Use the parent folder as the project root.
project_root = fileparts(script_dir);

% Part4 folders.
cfg.input_dir = fullfile(script_dir, 'Input');
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.main_fig_dir = fullfile(cfg.figure_root, 'Main');

cfg.function_dir = fullfile(script_dir, 'Function');

% Input files.
cfg.lfp_soh_mat = fullfile(cfg.input_dir, 'LFP_SOH_Table.mat');

% Primary Part3 residual-error model path using the new naming convention.
cfg.error_model_mat_primary = fullfile(project_root, ...
    'Part3_Prediction error extrapolation', ...
    'Output', ...
    'Results', ...
    'P3_Exp03_ResidualExtrapolation_Model.mat');

% Legacy fallback path for the old Part3 Main03 output.
cfg.error_model_mat_legacy = fullfile(project_root, ...
    'Part3_Prediction error extrapolation', ...
    'Output', ...
    'Result03_ResidualExtrapolation_Model.mat');

if exist(cfg.error_model_mat_primary, 'file')
    cfg.error_model_mat = cfg.error_model_mat_primary;
elseif exist(cfg.error_model_mat_legacy, 'file')
    cfg.error_model_mat = cfg.error_model_mat_legacy;
else
    error('Part3 residual-error model file not found. Checked:\n%s\n%s', ...
        cfg.error_model_mat_primary, cfg.error_model_mat_legacy);
end

% Output files generated by Part4 Exp01.
cfg.workspace_mat = fullfile(cfg.results_dir, ...
    'P4_Exp01_FixedScale_LFP_Workspace.mat');

cfg.result_mat = fullfile(cfg.results_dir, ...
    'P4_Exp01_FixedScale_LFP_Results.mat');

cfg.summary_csv = fullfile(cfg.results_dir, ...
    'P4_Exp01_FixedScale_LFP_Summary.csv');

% Figure subfolders and figure-output paths for Main Fig. 2 and Main Fig. 3.
cfg.landscape_dir = fullfile(cfg.main_fig_dir, ...
    'MainFig02c_threshold_cost_landscapes');

cfg.confusion_dir = fullfile(cfg.main_fig_dir, ...
    'MainFig02d_confusion_matrices');

cfg.loss_matrix_dir = fullfile(cfg.main_fig_dir, ...
    'MainFig02e_value_loss_matrices');

cfg.fig_cost_breakdown = fullfile(cfg.main_fig_dir, ...
    'MainFig02b_fixed_scale_LFP_cost_decomposition.fig');
cfg.png_cost_breakdown = fullfile(cfg.main_fig_dir, ...
    'MainFig02b_fixed_scale_LFP_cost_decomposition.png');

cfg.fig_net_value = fullfile(cfg.main_fig_dir, ...
    'MainFig03a_LFP_net_value_curves.fig');
cfg.png_net_value = fullfile(cfg.main_fig_dir, ...
    'MainFig03a_LFP_net_value_curves.png');

cfg.fig_A3_breakdown = fullfile(cfg.main_fig_dir, ...
    'MainFig03b_LFP_recycling_breakdown.fig');
cfg.png_A3_breakdown = fullfile(cfg.main_fig_dir, ...
    'MainFig03b_LFP_recycling_breakdown.png');

% Simulation settings.
cfg.N_sim = 100000;
cfg.random_seed = 42;
cfg.png_resolution = 600;

% Create required folders.
folder_list = { ...
    cfg.input_dir, ...
    cfg.output_dir, ...
    cfg.results_dir, ...
    cfg.figure_root, ...
    cfg.main_fig_dir, ...
    cfg.function_dir, ...
    cfg.landscape_dir, ...
    cfg.confusion_dir, ...
    cfg.loss_matrix_dir};

for ii = 1:numel(folder_list)
    if ~exist(folder_list{ii}, 'dir')
        mkdir(folder_list{ii});
    end
end

addpath(cfg.function_dir);

if exist('local_build_noise_by_k', 'file') ~= 2
    error('Function local_build_noise_by_k.m was not found in: %s', cfg.function_dir);
end

fprintf('================ Part4 Exp01 fixed-scale LFP optimization ================\n');
fprintf('LFP SOH input file:      %s\n', cfg.lfp_soh_mat);
fprintf('Part3 error model file:  %s\n', cfg.error_model_mat);
fprintf('Output result file:      %s\n', cfg.result_mat);
fprintf('Output workspace file:   %s\n', cfg.workspace_mat);
fprintf('Summary CSV file:        %s\n', cfg.summary_csv);
fprintf('Main figure folder:      %s\n', cfg.main_fig_dir);
fprintf('Random seed:             %d\n', cfg.random_seed);

%% 2) Load LFP SOH trajectory data
if ~exist(cfg.lfp_soh_mat, 'file')
    error('LFP SOH data file not found: %s', cfg.lfp_soh_mat);
end

SOH_file = load(cfg.lfp_soh_mat);
SOH_data = local_extract_soh_from_mat(SOH_file, cfg.lfp_soh_mat);

fprintf('LFP SOH trajectory loaded. Number of SOH points = %d\n', numel(SOH_data));
fprintf('LFP SOH range: %.4f - %.4f\n', min(SOH_data), max(SOH_data));

%% 3) Basic physical and economic parameters

Q_pack = 25.3;
r = 0.05;
beta_refurbish = 0.09;

% Shenzhen tier-2 residential peak-valley electricity prices, RMB/kWh
ExchangeRate_RMB_USD = 7.04;
p_high_RMB = 1.1621;
p_low_RMB  = 0.2986;

% Convert electricity prices to USD/kWh
p_high = p_high_RMB / ExchangeRate_RMB_USD;   % 0.1651
p_low  = p_low_RMB  / ExchangeRate_RMB_USD;   % 0.0424

c_pack = 300;                 c_train = 100;                Fixed_Scale_N = 2500;
% SOH testing cost      model training cost        fixed deployment scale


Eta_1 = 40;          Eta_2 = 40;
% G1 gray-zone tolerance between recycling and refurbishment
% G2 gray-zone tolerance between reuse and refurbishment

% Refurbishment cost parameters
C0 = 92;      % baseline labor, disassembly, and inspection cost
C1 = 65;      % material replacement and deep-repair cost coefficient
gamma = 3;    % nonlinear degradation exponent for refurbishment difficulty

Lambda_R = 15;    Lambda_H = 12;
% Lambda_R scales the risk penalty for over-optimistic pathway assignment.
% Lambda_H is the fixed mismatch-handling and rework cost incurred for an
% economically consequential pathway mismatch. It does not represent an
% ex-ante review that corrects the pathway before opportunity loss occurs.
%
% Legacy alias retained for compatibility with older downstream scripts.
Lambda_A = Lambda_H;


% 1.1 Hydrometallurgical recycling economics and physicochemical parameters

M_pack = 173.25;                Exchange_Rate = 1;
% pack mass (kg)               exchange-rate multiplier

% - 1. Baseline physicochemical parameters per kg battery pack -
PosAcMass = 0.223;           PosCCMass = 0.060;          NegAcMass = 0.1235;        NegCCMass = 0.08;
% positive active material   positive current collector    negative active material       negative current collector

M_LiFePO4 = 157.76;     M_Li2CO3_half = 73.88;    M_FePO4 = 150.82;    M_H2SO4 = 98;    M_H2O2 = 34;    M_Na2CO3 = 106;
% Molar-mass parameters

% - 1.5 Recovery-efficiency parameters for the hydrometallurgical process -
Rec_Rate_Chem = 0.98;    Rec_Rate_Graphite = 0.95;        Rec_Rate_Al = 0.93;      Rec_Rate_Cu = 0.93;
% reaction conversion rate for Li2CO3 and FePO4   graphite   aluminum collector   copper collector

% - 2. Market prices of recovered products, USD/kg -
P_Li2CO3   = 27.20;     P_FePO4    = 1.91;     P_Graphite = 3.84;    P_Al = 3.42;     P_Cu = 14.79;
% Li2CO3 price   FePO4 price   graphite price   aluminum price   copper price

% - 3. Product yields independent of SOH, kg/kg battery -
Base_Y_FePO4    = (PosAcMass / M_LiFePO4) * M_FePO4 * Rec_Rate_Chem;
Base_Y_Graphite = NegAcMass * Rec_Rate_Graphite;
Base_Y_Al = PosCCMass * Rec_Rate_Al;      Base_Y_Cu  = NegCCMass * Rec_Rate_Cu;

% - 4. Feedstock and reagent prices for hydrometallurgical recycling -
C_Degraded = 2.05;     P_H2SO4    = 0.264;      P_H2O2     = 0.130;      P_Na2CO3   =  0.172;
% retired LFP feedstock cost   H2SO4 price   H2O2 price   Na2CO3 price

% - 5. LFP hydrometallurgical recycling fixed operating cost -
P_elec_recycle = 0.111;   % USD/kWh

C_Electricity_hydro = 500 * P_elec_recycle / 1000;  % USD/kg battery
C_Labor_hydro       = 307.36 / 1000;                % USD/kg battery
C_Disassemble_hydro = 12.07  / 1000;                % USD/kg battery
C_Equip_hydro       = 52.00  / 1000;                % USD/kg battery
C_Sewage_hydro      = 141.14 / 1000;                % USD/kg battery

Fixed_Op_Cost = C_Electricity_hydro + C_Labor_hydro + ...
                C_Disassemble_hydro + C_Equip_hydro + C_Sewage_hydro;


%% 4) SOH-dependent action-value functions
% 2.1 Construct the baseline reuse value curve from the empirical SOH trajectory

% Identify the endpoint where the empirical SOH trajectory remains above 0.4
valid_end_idx = find(SOH_data >= 0.4);   end_idx = valid_end_idx(end);

% Identify all starting points with SOH between 1.0 and 0.4
start_indices = find(SOH_data <= 1.0 & SOH_data >= 0.4);
num_cases = length(start_indices);
a = zeros(num_cases, 1);   V1 = zeros(num_cases, 1);

for k = 1:num_cases
    start_idx = start_indices(k);

    SOH_slice = SOH_data(start_idx : end_idx);

    a(k) = SOH_slice(1);
    days_elapsed = (0 : length(SOH_slice)-1)';

    SOH_diff = 1 - SOH_slice;
    Poly_term = -0.1532 .* (SOH_diff.^2) + 0.003923 .* SOH_diff + 0.9530;
    Daily_Value_Raw = Q_pack .* SOH_slice .* (Poly_term .* p_high - p_low);

    Discount_Factor = 1 ./ ((1 + r) .^ (days_elapsed / 365));
    V1(k) = sum(Daily_Value_Raw .* Discount_Factor);
end

[a, sort_idx] = sort(a);  V1 = V1(sort_idx);


if max(a) < 1.0
    a = [a; 1.0];
    slope = (V1(end) - V1(end-1)) / (a(end) - a(end-1));
    V1 = [V1; V1(end) + slope * (1.0 - a(end-1))];
end


% 2.2 Define dynamic action-value functions for the three recertification pathways

C_A1_extra = 10;    % extra cost for direct reuse, including transport, testing, integration, and installation
C_A2_extra = 15;    % extra cost for refurbishment, including disassembly, labor, regrouping, and retesting

% Action 3: hydrometallurgical recycling value function based on stoichiometric reactions
Y_Li2CO3_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_Li2CO3_half .* Rec_Rate_Chem;
Y_H2SO4_func  = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_H2SO4;
Y_H2O2_func   = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_H2O2;
Y_Na2CO3_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_Na2CO3;

calc_V_reuse_base = @(soh) interp1(a, V1, soh, 'linear', 'extrap');
calc_V_reuse = @(soh) calc_V_reuse_base(soh) - C_A1_extra;

calc_C_refurbish = @(soh) C0 + C1 .* (1 - soh).^gamma;
calc_V_refurbish_base = @(soh) calc_V_reuse_base(min(soh + beta_refurbish .* (1 - soh), 1.0)) - calc_C_refurbish(soh);
calc_V_refurbish = @(soh) calc_V_refurbish_base(soh) - C_A1_extra - C_A2_extra;

calc_V_recycle = @(soh) M_pack .* Exchange_Rate .* ( ...
    (Y_Li2CO3_func(soh) .* P_Li2CO3 + Base_Y_FePO4 .* P_FePO4 + Base_Y_Graphite .* P_Graphite + Base_Y_Al .* P_Al + Base_Y_Cu .* P_Cu) ...
    - (Y_H2SO4_func(soh) .* P_H2SO4 + Y_H2O2_func(soh) .* P_H2O2 + Y_Na2CO3_func(soh) .* P_Na2CO3) ...
    - (PosAcMass .* C_Degraded + Fixed_Op_Cost) ...
    );


%% 5) Load k-dependent residual-error extrapolation model

error_model_file = cfg.error_model_mat;

if ~exist(error_model_file, 'file')
    error('Part3 residual-error model file not found: %s', error_model_file);
end

ErrorModel = load(error_model_file);

required_error_vars = { ...
    'k_emp', ...
    'k_vals', ...
    'err_cell', ...
    'rmse_target', ...
    'w_curve', ...
    'muM_curve', ...
    'sigM_curve', ...
    'muR_curve', ...
    'sigR_curve', ...
    'region', ...
    'cfg'};

for ii = 1:numel(required_error_vars)
    if ~isfield(ErrorModel, required_error_vars{ii})
        error('Required variable "%s" was not found in %s.', ...
            required_error_vars{ii}, error_model_file);
    end
end

k_emp = ErrorModel.k_emp(:);
k_vals = ErrorModel.k_vals(:);
err_cell = ErrorModel.err_cell;

rmse_target = ErrorModel.rmse_target(:);
w_curve     = ErrorModel.w_curve(:);
muM_curve   = ErrorModel.muM_curve(:);
sigM_curve  = ErrorModel.sigM_curve(:);
muR_curve   = ErrorModel.muR_curve(:);
sigR_curve  = ErrorModel.sigR_curve(:);

region = ErrorModel.region;

if isfield(ErrorModel.cfg, 'k_anchor')
    k_anchor = ErrorModel.cfg.k_anchor;
else
    k_anchor = 21;
end

if isfield(ErrorModel.cfg, 'k_bridge_end')
    k_bridge_end = ErrorModel.cfg.k_bridge_end;
else
    k_bridge_end = 26;
end

if max(k_vals) < 50
    error(['The loaded residual-error model only covers k = %d to %d. ', ...
        'Please rerun P3_Exp03_label_dependent_residual_extrapolation.m with cfg.k_extrap_max = 50.'], ...
        min(k_vals), max(k_vals));
end

if numel(k_vals) ~= numel(rmse_target) || ...
        numel(k_vals) ~= numel(w_curve) || ...
        numel(k_vals) ~= numel(muM_curve) || ...
        numel(k_vals) ~= numel(sigM_curve) || ...
        numel(k_vals) ~= numel(muR_curve) || ...
        numel(k_vals) ~= numel(sigR_curve)
    error('The loaded residual-error model has inconsistent curve lengths.');
end

fprintf('Residual-error model loaded from: %s\n', error_model_file);
fprintf('Loaded k range: %d to %d\n', min(k_vals), max(k_vals));

N_sim = cfg.N_sim;
rng(cfg.random_seed);

% Common random numbers reused across k values.
base_u    = rand(N_sim, 1);
base_z    = randn(N_sim, 1);
base_pick = rand(N_sim, 1);

% Preserve the original SOH Monte Carlo sequence. The independent bridge
% selector uses a separate stream so that adding it does not shift s_true.
s_true = 0.4 + 0.6 * rand(N_sim, 1);
bridge_stream = RandStream('mt19937ar', ...
    'Seed', cfg.random_seed + 1001);
base_bridge = rand(bridge_stream, N_sim, 1);

fprintf('>>> Running dense k-grid search from k = %d to %d...\n', ...
    min(k_vals), max(k_vals));

Pi_True = [calc_V_reuse(s_true), calc_V_refurbish(s_true), calc_V_recycle(s_true)];
[Pi_True_Max, PerfectInfo_Action_i] = max(Pi_True, [], 2);
% Legacy alias retained for compatibility with existing saved workspaces.
True_Action_i = PerfectInfo_Action_i; %#ok<NASGU>

T1_grid = 0.4 : 0.005 : 0.5;
T2_grid = 0.85 : 0.005 : 1;

E_L_base = zeros(length(k_vals), 1);
O_base = zeros(length(k_vals), 1);
H_base = zeros(length(k_vals), 1);
R_base = zeros(length(k_vals), 1);
T1_base = zeros(length(k_vals), 1);
T2_base = zeros(length(k_vals), 1);

% Diagnostics verify that Part4 uses the same empirical/bridge/extrapolated
% residual construction exported by Part3 Exp03.
noise_source_type = strings(length(k_vals), 1);
noise_generated_RMSE = nan(length(k_vals), 1);
noise_target_RMSE = rmse_target;
noise_bridge_alpha = zeros(length(k_vals), 1);
noise_bridge_RMSE_scale = ones(length(k_vals), 1);
noise_parametric_fraction = nan(length(k_vals), 1);

for i = 1:length(k_vals)
    k_current = k_vals(i);

    [sampled_noise, noise_diag] = local_build_noise_by_k( ...
        k_current, ...
        k_emp, k_anchor, k_bridge_end, ...
        err_cell, ...
        w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
        base_u, base_z, base_pick, base_bridge);

    noise_source_type(i) = string(noise_diag.source_type);
    noise_generated_RMSE(i) = noise_diag.generated_RMSE;
    noise_bridge_alpha(i) = noise_diag.bridge_alpha;
    noise_bridge_RMSE_scale(i) = noise_diag.bridge_RMSE_scale;
    noise_parametric_fraction(i) = noise_diag.parametric_fraction_realized;

    s_pred = min(max(s_true + sampled_noise, 0), 1.0);

    min_L = inf;
    for T1 = T1_grid
        for T2 = T2_grid
            if T1 >= T2
                continue;
            end

            Pred_Action_j = 3 * ones(N_sim, 1);
            Pred_Action_j(s_pred >= T1 & s_pred < T2) = 2;
            Pred_Action_j(s_pred >= T2) = 1;

            idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_j);
            O_arr = max(Pi_True_Max - Pi_True(idx_pred), 0);

            is_G1_error = (PerfectInfo_Action_i == 3 & Pred_Action_j == 2) | ...
                (PerfectInfo_Action_i == 2 & Pred_Action_j == 3);
            is_G2_error = (PerfectInfo_Action_i == 1 & Pred_Action_j == 2) | ...
                (PerfectInfo_Action_i == 2 & Pred_Action_j == 1);

            Current_Eta = zeros(N_sim, 1);
            Current_Eta(is_G1_error) = Eta_1;
            Current_Eta(is_G2_error) = Eta_2;

            consequential_mismatch = (Pred_Action_j ~= PerfectInfo_Action_i) & ...
                (O_arr > Current_Eta);
            Excess_Loss = max(0, O_arr - Current_Eta);

            H_arr = consequential_mismatch .* Lambda_H;
            R_arr = (Pred_Action_j < PerfectInfo_Action_i) .* consequential_mismatch .* (Lambda_R .* Excess_Loss);

            E_L = mean(O_arr + H_arr + R_arr);

            if E_L < min_L
                min_L = E_L;
                O_base(i) = mean(O_arr);
                H_base(i) = mean(H_arr);
                R_base(i) = mean(R_arr);
                T1_base(i) = T1;
                T2_base(i) = T2;
            end
        end
    end
    E_L_base(i) = min_L;
end



%% 7) Optimal policy reconstruction at the fixed-scale optimum

Fixed_O = O_base * Fixed_Scale_N;
Fixed_H = H_base * Fixed_Scale_N;
Fixed_R = R_base * Fixed_Scale_N;
Fixed_Model = (k_vals .* c_pack + c_train);
Fixed_Total_Cost = Fixed_O + Fixed_H + Fixed_R + Fixed_Model;
[~, opt_k_idx] = min(Fixed_Total_Cost);
opt_k = k_vals(opt_k_idx);
opt_T1 = T1_base(opt_k_idx);
opt_T2 = T2_base(opt_k_idx);
Scale_Factor = Fixed_Scale_N / N_sim;

fprintf('>>> Extracting sample-level results at the optimal k* = %d...\n', opt_k);

% Reconstruct predicted SOH and assigned actions at the optimal k
noise_opt = local_build_noise_by_k( ...
    opt_k, ...
    k_emp, k_anchor, k_bridge_end, ...
    err_cell, ...
    w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
    base_u, base_z, base_pick, base_bridge);

s_pred_opt = min(max(s_true + noise_opt, 0), 1.0);

Pred_Action_opt = 3 * ones(N_sim, 1);
Pred_Action_opt(s_pred_opt >= opt_T1 & s_pred_opt < opt_T2) = 2;
Pred_Action_opt(s_pred_opt >= opt_T2) = 1;

idx_pred_opt = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_opt);
O_arr_opt = max(Pi_True_Max - Pi_True(idx_pred_opt), 0);

% Apply opportunity-loss, handling/rework and risk accounting
is_G1_opt = (PerfectInfo_Action_i == 3 & Pred_Action_opt == 2) | (PerfectInfo_Action_i == 2 & Pred_Action_opt == 3);
is_G2_opt = (PerfectInfo_Action_i == 1 & Pred_Action_opt == 2) | (PerfectInfo_Action_i == 2 & Pred_Action_opt == 1);
Eta_opt = zeros(N_sim, 1); Eta_opt(is_G1_opt) = Eta_1; Eta_opt(is_G2_opt) = Eta_2;

consequential_mismatch_opt = (Pred_Action_opt ~= PerfectInfo_Action_i) & ...
    (O_arr_opt > Eta_opt);
Excess_opt = max(0, O_arr_opt - Eta_opt);

H_arr_opt = consequential_mismatch_opt .* Lambda_H;
R_arr_opt = (Pred_Action_opt < PerfectInfo_Action_i) .* consequential_mismatch_opt .* (Lambda_R .* Excess_opt);

Total_Loss_opt = O_arr_opt + H_arr_opt + R_arr_opt;

% The executed pathway value already reflects opportunity loss relative to
% the perfect-information pathway. Therefore opportunity loss is not
% subtracted again when computing net realized value.
Executed_Pathway_Value_opt = Pi_True(idx_pred_opt);
PerfectInfo_Pathway_Value_opt = Pi_True_Max;
Net_Realized_Value_opt = Executed_Pathway_Value_opt - H_arr_opt - R_arr_opt;
Net_Realized_Value_check = PerfectInfo_Pathway_Value_opt ...
    - O_arr_opt - H_arr_opt - R_arr_opt;

accounting_gap = max(abs( ...
    Net_Realized_Value_opt - Net_Realized_Value_check));
assert(accounting_gap < 1e-8, ...
    'Net-value accounting identity failed. Maximum gap = %.3e.', ...
    accounting_gap);

% Legacy alias retained for compatibility with older plotting scripts.
Net_Revenue_opt = Net_Realized_Value_opt;

%% 8) Save the full fixed-scale LFP workspace before figure generation

Noise_Diagnostic_Table = table( ...
    k_vals, ...
    noise_source_type, ...
    noise_target_RMSE, ...
    noise_generated_RMSE, ...
    noise_bridge_alpha, ...
    noise_bridge_RMSE_scale, ...
    noise_parametric_fraction, ...
    'VariableNames', { ...
    'k', ...
    'Residual_source', ...
    'RMSE_target', ...
    'RMSE_generated_in_Part4', ...
    'Bridge_alpha', ...
    'Bridge_RMSE_scale', ...
    'Parametric_fraction_realized'});

save(cfg.workspace_mat, '-v7.3');
fprintf('>>> Full fixed-scale LFP workspace saved to: %s\n', cfg.workspace_mat);


%% 9) Figure 1: fixed-scale cost decomposition
fig_cost_breakdown = figure('Name', sprintf('MainFig02b_fixed_scale_LFP_cost_decomposition_N%d', Fixed_Scale_N), ...
    'Color', 'w', 'Position', [100, 450, 700, 500]);

bar_data = [Fixed_O, Fixed_H, Fixed_R, Fixed_Model] / 1e4;

b = bar(k_vals, bar_data, 'stacked', 'EdgeColor', 'none');
hold on;

% Colors
b(1).FaceColor = [0.93, 0.69, 0.13];   % Opportunity loss
b(2).FaceColor = [0.49, 0.18, 0.56];   % Mismatch handling and rework cost
b(3).FaceColor = [0.85, 0.33, 0.10];   % Risk penalty
b(4).FaceColor = [0.00, 0.45, 0.74];   % SOH labelling and adaptation cost

% Total cost curve
h_total = plot(k_vals, Fixed_Total_Cost/1e4, '-k', ...
    'LineWidth', 2.8, 'DisplayName', 'Total Cost');

% Optimal K*
h_star = plot(opt_k, Fixed_Total_Cost(opt_k_idx)/1e4, 'rp', ...
    'MarkerSize', 16, 'MarkerFaceColor', 'r', ...
    'DisplayName', 'Optimal k^*');

% Vertical line
xline(opt_k, 'r--', 'LineWidth', 1.5, 'HandleVisibility', 'off');

uistack(h_total, 'top');
uistack(h_star, 'top');

xlabel('Number of labelled target packs, k');
ylabel('Total cost (10^4 USD)');
title('Fixed-scale LFP cost decomposition');
grid on;
box on;

legend([b(4), b(3), b(2), b(1), h_total, h_star], ...
    {'SOH labelling and adaptation cost', ...
     'Risk penalty', ...
     'Mismatch handling and rework cost', ...
     'Opportunity loss', ...
     'Total cost', ...
     'Optimal k^*'}, ...
    'Location', 'NorthEast');

local_save_figure(fig_cost_breakdown, cfg.fig_cost_breakdown, cfg.png_cost_breakdown, cfg.png_resolution);


%% 10) Figure 2: threshold-cost landscapes at representative k values

k_samples = [7, 16, opt_k];
num_plots = numel(k_samples);

Loss_Grid_all = cell(num_plots, 1);
z_all = [];

for plot_idx = 1:num_plots
    k_curr = k_samples(plot_idx);

    noise_curr = local_build_noise_by_k( ...
        k_curr, ...
        k_emp, k_anchor, k_bridge_end, ...
        err_cell, ...
        w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
        base_u, base_z, base_pick, base_bridge);

    s_p_curr = min(max(s_true + noise_curr, 0), 1.0);

    Loss_Grid = zeros(length(T2_grid), length(T1_grid));
    for i_t1 = 1:length(T1_grid)
        for i_t2 = 1:length(T2_grid)
            t1_v = T1_grid(i_t1);
            t2_v = T2_grid(i_t2);

            if t1_v >= t2_v
                Loss_Grid(i_t2, i_t1) = NaN;
                continue;
            end

            P_A = 3 * ones(N_sim, 1);
            P_A(s_p_curr >= t1_v & s_p_curr < t2_v) = 2;
            P_A(s_p_curr >= t2_v) = 1;

            O_c = max(Pi_True_Max - Pi_True(sub2ind([N_sim, 3], (1:N_sim)', P_A)), 0);

            iG1 = (PerfectInfo_Action_i == 3 & P_A == 2) | (PerfectInfo_Action_i == 2 & P_A == 3);
            iG2 = (PerfectInfo_Action_i == 1 & P_A == 2) | (PerfectInfo_Action_i == 2 & P_A == 1);

            Eta_c = zeros(N_sim, 1);
            Eta_c(iG1) = Eta_1;
            Eta_c(iG2) = Eta_2;

            consequential_mismatch_surface = ...
                (P_A ~= PerfectInfo_Action_i) & (O_c > Eta_c);
            Exc = max(0, O_c - Eta_c);

            H_c = consequential_mismatch_surface .* Lambda_H;
            R_c = (P_A < PerfectInfo_Action_i) .* ...
                consequential_mismatch_surface .* (Lambda_R .* Exc);

            Loss_Grid(i_t2, i_t1) = mean(O_c + H_c + R_c) * Fixed_Scale_N;
        end
    end

    Loss_Grid_all{plot_idx} = Loss_Grid;

    tmp = Loss_Grid(:) / 10000;   
    tmp = tmp(~isnan(tmp));
    z_all = [z_all; tmp];
end

cmin_global = prctile(z_all, 5);
cmax_global = prctile(z_all, 95);
gamma = 0.6;

for plot_idx = 1:num_plots
    k_curr = k_samples(plot_idx);
    Loss_Grid = Loss_Grid_all{plot_idx};

fig_landscape = figure('Name', sprintf('Threshold_cost_landscape_%d_k_%d', plot_idx, k_curr), ...
        'Color', 'w', 'Position', [200+plot_idx*50, 350, 600, 450]);

    [X, Y] = meshgrid(T1_grid, T2_grid);

    Loss_show = Loss_Grid / 10000;   

    Loss_show_clip = Loss_show;
    Loss_show_clip(Loss_show_clip < cmin_global) = cmin_global;
    Loss_show_clip(Loss_show_clip > cmax_global) = cmax_global;

    Loss_show_norm = (Loss_show_clip - cmin_global) / (cmax_global - cmin_global);
    Loss_show_warp = Loss_show_norm .^ gamma;

    contourf(X, Y, Loss_show_warp, 40, 'LineColor', 'none');
    hold on;
    colormap(gca, parula);
    clim([0, 1]);
    cb = colorbar;

cb.Ticks = linspace(0, 1, 6);
phys_labels = cmin_global + (cb.Ticks .^ (1/gamma)) * (cmax_global - cmin_global);
cb.TickLabels = arrayfun(@(x) sprintf('%.1f', x), phys_labels, 'UniformOutput', false);
title(cb, '10^4 $');

% ===== Identify the optimum from the original loss grid =====
    [~, min_idx] = min(Loss_Grid(:));
    [r_min, c_min_idx] = ind2sub(size(Loss_Grid), min_idx);

    t1_opt_show = T1_grid(c_min_idx);
    t2_opt_show = T2_grid(r_min);

    plot(t1_opt_show, t2_opt_show, 'p', ...
        'MarkerSize', 14, ...
        'MarkerFaceColor', 'r', ...
        'MarkerEdgeColor', 'k', ...
        'LineWidth', 1.2);

    xline(t1_opt_show, '--k', 'LineWidth', 0.8, 'HandleVisibility', 'off');
    yline(t2_opt_show, '--k', 'LineWidth', 0.8, 'HandleVisibility', 'off');

    text(t1_opt_show + 0.004, t2_opt_show + 0.004, 'Optimal', ...
        'Color', 'k', ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom');

    xlabel('T_1');
    ylabel('T_2');
    title(sprintf('Loss Surface (k = %d)', k_curr));
    grid on;
    box on;

out_fig_landscape = fullfile(cfg.landscape_dir, sprintf('MainFig02c_threshold_cost_landscape_k%02d.fig', k_curr));

out_png_landscape = fullfile(cfg.landscape_dir, sprintf('MainFig02c_threshold_cost_landscape_k%02d.png', k_curr));
    local_save_figure(fig_landscape, out_fig_landscape, out_png_landscape, cfg.png_resolution);
end


%% 11) Figure 3: confusion matrices and value-loss matrices across representative k values

% Define the k values to be visualized
target_ks = [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25];
target_ks = unique(target_ks); 
num_plots = length(target_ks);
labels = {'A_1', 'A_2', 'A_3'};

diag_min = 0.56;  diag_max = 0.98;
blue_lo = [0.72, 0.80, 0.92];   blue_hi = [0.16, 0.33, 0.72];
off_max = 0.44;
red_lo  = [1.00, 1.00, 1.00];   red_hi  = [0.88, 0.22, 0.22];

for idx = 1:num_plots
    k_curr = target_ks(idx);

    idx_k = find(k_vals == k_curr);
    if isempty(idx_k); continue; end

    T1_c = T1_base(idx_k);
    T2_c = T2_base(idx_k);

    noise_c = local_build_noise_by_k( ...
        k_curr, ...
        k_emp, k_anchor, k_bridge_end, ...
        err_cell, ...
        w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
        base_u, base_z, base_pick, base_bridge);

    s_p_c = min(max(s_true + noise_c, 0), 1.0);

    P_A_c = 3 * ones(N_sim, 1);
    P_A_c(s_p_c >= T1_c & s_p_c < T2_c) = 2;
    P_A_c(s_p_c >= T2_c) = 1;

    idx_pred_c = sub2ind([N_sim, 3], (1:N_sim)', P_A_c);
    O_arr_c = max(Pi_True_Max - Pi_True(idx_pred_c), 0);

    iG1_c = (PerfectInfo_Action_i == 3 & P_A_c == 2) | (PerfectInfo_Action_i == 2 & P_A_c == 3);
    iG2_c = (PerfectInfo_Action_i == 1 & P_A_c == 2) | (PerfectInfo_Action_i == 2 & P_A_c == 1);
    Eta_c = zeros(N_sim, 1); Eta_c(iG1_c) = Eta_1; Eta_c(iG2_c) = Eta_2;

    consequential_mismatch_c = (P_A_c ~= PerfectInfo_Action_i) & ...
        (O_arr_c > Eta_c); Exc_c = max(0, O_arr_c - Eta_c);
    H_arr_c = consequential_mismatch_c .* Lambda_H;
    R_arr_c = (P_A_c < PerfectInfo_Action_i) .* consequential_mismatch_c .* (Lambda_R .* Exc_c);

    Total_Decision_Cost_c = O_arr_c + H_arr_c + R_arr_c; %#ok<NASGU>

    Conf_Cnt_c = zeros(3, 3); Conf_ValueLoss_c = zeros(3, 3);
    for i = 1:3
        for j = 1:3
            mask_c = (PerfectInfo_Action_i == i) & (P_A_c == j);
            Conf_Cnt_c(i, j) = sum(mask_c) * Scale_Factor;
            Conf_ValueLoss_c(i, j) = sum(O_arr_c(mask_c)) * Scale_Factor;
        end
    end

    row_sums = sum(Conf_Cnt_c, 2);
    row_sums(row_sums == 0) = 1; 
    Conf_Ratio_c = Conf_Cnt_c ./ row_sums;

    if k_curr == opt_k
tit_str = sprintf('k = %d (optimal k^*)', k_curr);
    else
        tit_str = sprintf('k = %d', k_curr);
    end

% Plot the row-normalized confusion-ratio matrix in a separate window
fig_ratio = figure('Name', sprintf('Confusion_ratio_matrix_%s', tit_str), ...
                       'Position', [50 + idx*25, 450 - idx*15, 420, 380]);
    ax1 = axes('Parent', fig_ratio);
    img_rgb_ratio = ones(3, 3, 3);

    for ii = 1:3
        for jj = 1:3
            val = Conf_Ratio_c(ii, jj);
            if ii == jj
                t = (val - diag_min) / (diag_max - diag_min);
                t = 0.25 + 0.75 * max(0, min(1, t));
                c = blue_lo + t * (blue_hi - blue_lo);
            else
                if val < 1e-4
                    c = [1.0, 1.0, 1.0];
                else
                    t = val / off_max;
                    t = 0.2 + 0.8 * (max(0, min(1, t))^0.6); 
                    c = red_lo + t * (red_hi - red_lo);
                end
            end
            img_rgb_ratio(ii, jj, :) = c;
        end
    end
    
    image(ax1, img_rgb_ratio);
    axis(ax1, 'equal'); axis(ax1, 'tight'); set(ax1, 'YDir', 'normal');
    
    set(ax1, 'XTick', 1:3, 'XTickLabel', labels, 'YTick', 1:3, 'YTickLabel', labels, ...
             'FontSize', 6, 'FontName','Arial', 'TickLabelInterpreter', 'tex');
             
    hold(ax1, 'on');
    for ii = 1:3
        for jj = 1:3
            val = Conf_Ratio_c(ii, jj);
            if val > 0.55 || (ii ~= jj && val > 0.3); txt_color = 'w'; else; txt_color = 'k'; end
            text(ax1, jj, ii, sprintf('%.3f', val), 'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', 'FontSize', 6,'FontName','Arial', 'Color', txt_color);
        end
    end
    for x = 0.5:1:3.5; plot(ax1, [x x], [0.5 3.5], 'k-', 'LineWidth', 0.5); end
    for y = 0.5:1:3.5; plot(ax1, [0.5 3.5], [y y], 'k-', 'LineWidth', 0.5); end
    hold(ax1, 'off');

    % Plot the total value-loss matrix in a separate window
fig_cost = figure('Name', sprintf('Value_loss_matrix_%s', tit_str), ...
                      'Position', [500 + idx*25, 450 - idx*15, 420, 380]);
    ax2 = axes('Parent', fig_cost);

    M_cost = Conf_ValueLoss_c / 10000; 
    cost_max = max(M_cost(:));
    if cost_max < 1e-4; cost_max = 1; end

    img_rgb_cost = ones(3, 3, 3);
    for ii = 1:3
        for jj = 1:3
            val = M_cost(ii, jj);
            if val < 1e-4
                c = [1.0, 1.0, 1.0];
            else
                t = val / cost_max;
                t = 0.15 + 0.85 * (max(0, min(1, t))^0.5); 
                c = red_lo + t * (red_hi - red_lo);
            end
            img_rgb_cost(ii, jj, :) = c;
        end
    end
    
    image(ax2, img_rgb_cost);
    axis(ax2, 'equal'); axis(ax2, 'tight'); set(ax2, 'YDir', 'normal');
    
    set(ax2, 'XTick', 1:3, 'XTickLabel', labels, 'YTick', 1:3, 'YTickLabel', labels, ...
             'FontSize', 6,'FontName','Arial', 'TickLabelInterpreter', 'tex');
             

    hold(ax2, 'on');
    for ii = 1:3
        for jj = 1:3
            val = M_cost(ii, jj);
            if val > cost_max * 0.4 || val > 10; txt_color = 'w'; else; txt_color = 'k'; end
            
            text(ax2, jj, ii, sprintf('%.3f', val), 'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', 'FontSize', 6, 'Color', txt_color, 'FontName','Arial');
        end
    end
    for x = 0.5:1:3.5; plot(ax2, [x x], [0.5 3.5], 'k-', 'LineWidth', 0.5); end
    for y = 0.5:1:3.5; plot(ax2, [0.5 3.5], [y y], 'k-', 'LineWidth', 0.5); end
    hold(ax2, 'off');

set(fig_ratio, 'Units', 'centimeters');
set(fig_ratio, 'Position', [2 2 3 3]);

set(fig_ratio, 'PaperUnits', 'centimeters');
set(fig_ratio, 'PaperPositionMode', 'manual');
set(fig_ratio, 'PaperPosition', [0 0 3 3]);
set(fig_ratio, 'PaperSize', [3 3]);

set(fig_cost, 'Units', 'centimeters');
set(fig_cost, 'Position', [2 2 3 3]);

set(fig_cost, 'PaperUnits', 'centimeters');
set(fig_cost, 'PaperPositionMode', 'manual');
set(fig_cost, 'PaperPosition', [0 0 3 3]);
set(fig_cost, 'PaperSize', [3 3]);

savefig(fig_ratio, fullfile(cfg.confusion_dir, sprintf('MainFig02d_confusion_matrix_k%02d.fig', k_curr)));
exportgraphics(fig_ratio, fullfile(cfg.confusion_dir, sprintf('MainFig02d_confusion_matrix_k%02d.png', k_curr)), 'Resolution', cfg.png_resolution);
savefig(fig_cost, fullfile(cfg.loss_matrix_dir, sprintf('MainFig02e_value_loss_matrix_k%02d.fig', k_curr)));
exportgraphics(fig_cost, fullfile(cfg.loss_matrix_dir,  sprintf('MainFig02e_value_loss_matrix_k%02d.png', k_curr)), 'Resolution', cfg.png_resolution);
   
end



%% 12) Figure 4: cost-consistent net-value curves

% 1. Calculate the net value of each action
%    J_action(:, j) denotes the sample-level net value if action j is enforced.

J_action = zeros(N_sim, 3);

for act_j = 1:3

% Baseline economic value of the selected action under the true SOH
    ch_v = Pi_True(:, act_j);

% Opportunity loss relative to the perfect-information reference action
    O_tmp = max(Pi_True_Max - ch_v, 0);

% Identify the misclassification type
    is_G1 = (PerfectInfo_Action_i == 3 & act_j == 2) | ...
            (PerfectInfo_Action_i == 2 & act_j == 3);

    is_G2 = (PerfectInfo_Action_i == 1 & act_j == 2) | ...
            (PerfectInfo_Action_i == 2 & act_j == 1);

    Eta_tmp = zeros(N_sim, 1);
    Eta_tmp(is_G1) = Eta_1;
    Eta_tmp(is_G2) = Eta_2;

% Apply the same handling/rework and risk logic as in the grid-search objective
    consequential_mismatch_tmp = (act_j ~= PerfectInfo_Action_i) & ...
        (O_tmp > Eta_tmp);
    Excess_tmp  = max(0, O_tmp - Eta_tmp);

    H_tmp = consequential_mismatch_tmp .* Lambda_H;
    R_tmp = (act_j < PerfectInfo_Action_i) .* consequential_mismatch_tmp .* (Lambda_R .* Excess_tmp);

% Net value equals executed pathway value minus handling/rework and risk costs.
% This is equivalent to maximizing Pi_True_Max - (O + H + R).
    J_action(:, act_j) = ch_v - H_tmp - R_tmp;
end


% 2. Bin samples by predicted SOH
x_grid = 0.35 : 0.0025 : 1.00;
half_width = 0.005;

J_curve = nan(numel(x_grid), 3);
N_bin   = zeros(numel(x_grid), 1);

for ii = 1:numel(x_grid)

    x0 = x_grid(ii);

    idx_bin = (s_pred_opt >= x0 - half_width) & ...
              (s_pred_opt <  x0 + half_width);

    N_bin(ii) = sum(idx_bin);

    if N_bin(ii) >= 30
        J_curve(ii, 1) = mean(J_action(idx_bin, 1), 'omitnan');
        J_curve(ii, 2) = mean(J_action(idx_bin, 2), 'omitnan');
        J_curve(ii, 3) = mean(J_action(idx_bin, 3), 'omitnan');
    end
end


% 3. Apply mild smoothing
J_plot_1 = smoothdata(J_curve(:,1), 'movmean', 3, 'omitnan');
J_plot_2 = smoothdata(J_curve(:,2), 'movmean', 3, 'omitnan');
J_plot_3 = smoothdata(J_curve(:,3), 'movmean', 3, 'omitnan');

J_env = max([J_plot_1, J_plot_2, J_plot_3], [], 2, 'omitnan');


% 4. Check the distance between curve intersections and grid-search thresholds
D32 = J_plot_2 - J_plot_3;   % A2 - A3, corresponding to T1
D12 = J_plot_1 - J_plot_2;   % A1 - A2, corresponding to T2

idx_near_T1 = find(x_grid >= opt_T1 - 0.05 & x_grid <= opt_T1 + 0.05);
idx_cross_T1 = [];

if ~isempty(idx_near_T1)
    tmp = idx_near_T1(1:end-1);
    cross_candidate = tmp(D32(tmp) .* D32(tmp+1) <= 0);
    if ~isempty(cross_candidate)
        [~, id_min] = min(abs(x_grid(cross_candidate) - opt_T1));
        idx_cross_T1 = cross_candidate(id_min);
    end
end

if isempty(idx_cross_T1)
    T1_curve_cross = NaN;
else
    i0 = idx_cross_T1;
    T1_curve_cross = x_grid(i0) - D32(i0) * ...
        (x_grid(i0+1) - x_grid(i0)) / (D32(i0+1) - D32(i0));
end

idx_near_T2 = find(x_grid >= opt_T2 - 0.05 & x_grid <= opt_T2 + 0.05);
idx_cross_T2 = [];

if ~isempty(idx_near_T2)
    tmp = idx_near_T2(1:end-1);
    cross_candidate = tmp(D12(tmp) .* D12(tmp+1) <= 0);
    if ~isempty(cross_candidate)
        [~, id_min] = min(abs(x_grid(cross_candidate) - opt_T2));
        idx_cross_T2 = cross_candidate(id_min);
    end
end

if isempty(idx_cross_T2)
    T2_curve_cross = NaN;
else
    i0 = idx_cross_T2;
    T2_curve_cross = x_grid(i0) - D12(i0) * ...
        (x_grid(i0+1) - x_grid(i0)) / (D12(i0+1) - D12(i0));
end

fprintf('\n========== Fig. 4 threshold-consistency check ==========\n');
fprintf('Grid-search opt_T1 = %.4f\n', opt_T1);
fprintf('Curve intersection T1_curve_cross = %.4f\n', T1_curve_cross);
fprintf('Grid-search opt_T2 = %.4f\n', opt_T2);
fprintf('Curve intersection T2_curve_cross = %.4f\n', T2_curve_cross);
fprintf('=======================================================\n\n');


% 5.plot
fig_net_value = figure('Name', 'MainFig03a_LFP_net_value_curves', ...
    'Color', 'w', 'Position', [500, 150, 650, 460]);

hold on;

plot(x_grid, J_plot_1, '-', ...
    'LineWidth', 1.4, ...
    'Color', [0.85 0.15 0.15], ...
    'DisplayName', 'A_1 net value');

plot(x_grid, J_plot_2, '-', ...
    'LineWidth', 1.4, ...
    'Color', [0.55 0.35 0.80], ...
    'DisplayName', 'A_2 net value');

plot(x_grid, J_plot_3, '-', ...
    'LineWidth', 1.4, ...
    'Color', [0.45 0.28 0.22], ...
    'DisplayName', 'A_3 net value');

plot(x_grid, J_env, '--', ...
    'LineWidth', 1.2, ...
    'Color', [0.10 0.10 0.10], ...
    'DisplayName', 'Envelope');

% Optimal thresholds obtained from grid search
xline(opt_T1, 'b--', sprintf('T_1^* = %.3f', opt_T1), ...
    'LineWidth', 0.8, ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');

xline(opt_T2, 'b--', sprintf('T_2^* = %.3f', opt_T2), ...
    'LineWidth', 0.8, ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');

xlabel('Predicted SOH');
ylabel('Expected net pathway value per pack (USD)');
legend('Location', 'northwest');

grid on;
box on;
xlim([0.35 1.00]);

y_all = [J_plot_1(:); J_plot_2(:); J_plot_3(:); J_env(:)];
y_all = y_all(isfinite(y_all));
ylim([max(0, min(y_all) * 0.95), max(y_all) * 1.08]);

local_save_figure(fig_net_value, cfg.fig_net_value, cfg.png_net_value, cfg.png_resolution);


%% 13) Figure 5: A3 recycling revenue-cost contribution bar chart

mean_soh_rec = mean(s_true(Pred_Action_opt == 3));
if isnan(mean_soh_rec)
    mean_soh_rec = 0.5;
end

% 1. Recovered product yields, kg/pack
Y_Li2CO3 = M_pack * Y_Li2CO3_func(mean_soh_rec);
Y_FePO4  = M_pack * Base_Y_FePO4;
Y_Graph  = M_pack * Base_Y_Graphite;
Y_Al     = M_pack * Base_Y_Al;
Y_Cu     = M_pack * Base_Y_Cu;

% 2. Revenue components, USD/pack
Rev_Li2CO3 = Y_Li2CO3 * P_Li2CO3 * Exchange_Rate;
Rev_FePO4  = Y_FePO4  * P_FePO4  * Exchange_Rate;
Rev_Graph  = Y_Graph  * P_Graphite * Exchange_Rate;
Rev_Al     = Y_Al     * P_Al     * Exchange_Rate;
Rev_Cu     = Y_Cu     * P_Cu     * Exchange_Rate;

% 3. Cost components, USD/pack
Cost_H2SO4 = M_pack * Y_H2SO4_func(mean_soh_rec)  * P_H2SO4  * Exchange_Rate;
Cost_H2O2  = M_pack * Y_H2O2_func(mean_soh_rec)   * P_H2O2   * Exchange_Rate;
Cost_Na2CO3= M_pack * Y_Na2CO3_func(mean_soh_rec) * P_Na2CO3 * Exchange_Rate;

% Retired LFP feedstock cost based on positive active material
Cost_Feedstock = M_pack * PosAcMass * C_Degraded * Exchange_Rate;

% Fixed operating cost
Cost_FixedOp = M_pack * Fixed_Op_Cost * Exchange_Rate;

% 4. Aggregate cost components
Cost_Chemicals = Cost_H2SO4 + Cost_H2O2 + Cost_Na2CO3;
Cost_Op = Cost_FixedOp;

labels = {'Li_2CO_3', 'FePO_4', 'Graphite', 'Al', 'Cu', ...
          'Chemical solvents', 'Degraded LFP feedstock', 'Operating cost', ...
          'Net Value'};

vals = [Rev_Li2CO3, Rev_FePO4, Rev_Graph, Rev_Al, Rev_Cu, ...
       -Cost_Chemicals, -Cost_Feedstock, -Cost_Op];

net_value = sum(vals);
vals_full = [vals, net_value];

% 5. Plot the revenue-cost contribution bar chart
fig_A3_breakdown = figure('Name', 'MainFig03b_LFP_recycling_breakdown', ...
    'Color', 'w', 'Position', [220, 120, 980, 560]);

b = barh(vals_full, 'FaceColor', 'flat', 'EdgeColor', 'none');
hold on;

for i = 1:numel(vals_full)
    if i == numel(vals_full)
        b.CData(i, :) = [0.15, 0.15, 0.15];
    elseif vals_full(i) >= 0
        b.CData(i, :) = [0.16, 0.47, 0.78];
    else
        b.CData(i, :) = [0.85, 0.33, 0.10];
    end
end

xline(0, 'k-', 'LineWidth', 1.0);

set(gca, 'YTick', 1:numel(labels), ...
         'YTickLabel', labels, ...
         'YDir', 'reverse', ...
         'FontSize', 11, ...
         'FontName', 'Arial');

xlabel('Value / Cost (USD per pack)');
title(sprintf('A_3 Recycling Pathway Breakdown at Representative SOH = %.3f', mean_soh_rec));

grid on;
box on;

% 6. Value labels
xmax = max(vals_full);
xmin = min(vals_full);
xr = xmax - xmin;
if xr < 1e-6
    xr = 1;
end

for i = 1:numel(vals_full)
    v = vals_full(i);
    if v >= 0
        text(v + 0.02*xr, i, sprintf('%.1f', v), ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'middle', ...
            'FontSize', 10, 'FontName', 'Arial');
    else
        text(v - 0.02*xr, i, sprintf('%.1f', v), ...
            'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'middle', ...
            'FontSize', 10, 'FontName', 'Arial');
    end
end

xlim([xmin - 0.12*xr, xmax + 0.18*xr]);
hold off;

local_save_figure(fig_A3_breakdown, cfg.fig_A3_breakdown, cfg.png_A3_breakdown, cfg.png_resolution);


%% 14) Save structured fixed-scale LFP results

LFP_fixed_result = struct();

% Basic settings
LFP_fixed_result.Fixed_Scale_N = Fixed_Scale_N;
LFP_fixed_result.N_sim = N_sim;
LFP_fixed_result.k_vals = k_vals;
LFP_fixed_result.c_pack = c_pack;
LFP_fixed_result.c_train = c_train;
LFP_fixed_result.Eta_1 = Eta_1;
LFP_fixed_result.Eta_2 = Eta_2;
LFP_fixed_result.Lambda_H = Lambda_H;
LFP_fixed_result.Lambda_A = Lambda_A; % legacy alias
LFP_fixed_result.Lambda_R = Lambda_R;

% Action-value samples and SOH samples
LFP_fixed_result.s_true = s_true;
LFP_fixed_result.Pi_True = Pi_True;
LFP_fixed_result.Pi_True_Max = Pi_True_Max;
LFP_fixed_result.PerfectInfo_Action_i = PerfectInfo_Action_i;
LFP_fixed_result.True_Action_i = PerfectInfo_Action_i; % legacy alias

% k-dependent cost results
LFP_fixed_result.O_base = O_base;
LFP_fixed_result.H_base = H_base;
LFP_fixed_result.A_base = H_base; % legacy alias
LFP_fixed_result.R_base = R_base;
LFP_fixed_result.E_L_base = E_L_base;

LFP_fixed_result.Fixed_O = Fixed_O;
LFP_fixed_result.Fixed_H = Fixed_H;
LFP_fixed_result.Fixed_A = Fixed_H; % legacy alias
LFP_fixed_result.Fixed_R = Fixed_R;
LFP_fixed_result.Fixed_Model = Fixed_Model;
LFP_fixed_result.Fixed_Total_Cost = Fixed_Total_Cost;

% Optimal fixed-scale results
LFP_fixed_result.opt_k_idx = opt_k_idx;
LFP_fixed_result.opt_k = opt_k;
LFP_fixed_result.opt_T1 = opt_T1;
LFP_fixed_result.opt_T2 = opt_T2;
LFP_fixed_result.opt_total_cost = Fixed_Total_Cost(opt_k_idx);
LFP_fixed_result.opt_cost_per_pack = Fixed_Total_Cost(opt_k_idx) / Fixed_Scale_N;

% Sample-level results under the optimal k
LFP_fixed_result.noise_opt = noise_opt;
LFP_fixed_result.s_pred_opt = s_pred_opt;
LFP_fixed_result.Pred_Action_opt = Pred_Action_opt;
LFP_fixed_result.O_arr_opt = O_arr_opt;
LFP_fixed_result.H_arr_opt = H_arr_opt;
LFP_fixed_result.A_arr_opt = H_arr_opt; % legacy alias
LFP_fixed_result.R_arr_opt = R_arr_opt;
LFP_fixed_result.Total_Loss_opt = Total_Loss_opt;
LFP_fixed_result.Executed_Pathway_Value_opt = Executed_Pathway_Value_opt;
LFP_fixed_result.PerfectInfo_Pathway_Value_opt = PerfectInfo_Pathway_Value_opt;
LFP_fixed_result.Net_Realized_Value_opt = Net_Realized_Value_opt;
LFP_fixed_result.Net_Revenue_opt = Net_Realized_Value_opt; % legacy alias

% Figure-level diagnostic outputs
if exist('T1_curve_cross', 'var')
    LFP_fixed_result.T1_curve_cross = T1_curve_cross;
end
if exist('T2_curve_cross', 'var')
    LFP_fixed_result.T2_curve_cross = T2_curve_cross;
end
if exist('J_action', 'var')
    LFP_fixed_result.J_action = J_action;
    LFP_fixed_result.x_grid_net_value = x_grid;
    LFP_fixed_result.J_curve_net_value = J_curve;
    LFP_fixed_result.J_env_net_value = J_env;
end
if exist('vals_full', 'var')
    LFP_fixed_result.A3_breakdown_values = vals_full;
    LFP_fixed_result.A3_breakdown_labels = labels;
    LFP_fixed_result.mean_soh_rec = mean_soh_rec;
end

% Threshold search grids
LFP_fixed_result.T1_grid = T1_grid;
LFP_fixed_result.T2_grid = T2_grid;
LFP_fixed_result.T1_base = T1_base;
LFP_fixed_result.T2_base = T2_base;

% Residual-error model parameters
LFP_fixed_result.k_emp = k_emp;
LFP_fixed_result.k_anchor = k_anchor;
LFP_fixed_result.k_bridge_end = k_bridge_end;
LFP_fixed_result.rmse_target = rmse_target;
LFP_fixed_result.w_curve = w_curve;
LFP_fixed_result.muM_curve = muM_curve;
LFP_fixed_result.sigM_curve = sigM_curve;
LFP_fixed_result.muR_curve = muR_curve;
LFP_fixed_result.sigR_curve = sigR_curve;
LFP_fixed_result.Noise_Diagnostic_Table = Noise_Diagnostic_Table;

LFP_fixed_result.cfg_part4 = cfg;
LFP_fixed_result.input_lfp_soh_mat = cfg.lfp_soh_mat;
LFP_fixed_result.input_error_model_mat = cfg.error_model_mat;

save(cfg.result_mat, 'LFP_fixed_result', '-v7.3');

Summary_Table = table( ...
    opt_k, ...
    opt_T1, ...
    opt_T2, ...
    Fixed_Total_Cost(opt_k_idx), ...
    Fixed_Total_Cost(opt_k_idx) / Fixed_Scale_N, ...
    Fixed_O(opt_k_idx), ...
    Fixed_H(opt_k_idx), ...
    Fixed_R(opt_k_idx), ...
    Fixed_Model(opt_k_idx), ...
    mean(Pred_Action_opt == 1), ...
    mean(Pred_Action_opt == 2), ...
    mean(Pred_Action_opt == 3), ...
    'VariableNames', { ...
    'opt_k', ...
    'opt_T1', ...
    'opt_T2', ...
    'opt_total_cost_USD', ...
    'opt_cost_per_pack_USD', ...
    'opportunity_loss_USD', ...
    'mismatch_handling_rework_cost_USD', ...
    'risk_penalty_USD', ...
    'SOH_labelling_adaptation_cost_USD', ...
    'A1_predicted_share', ...
    'A2_predicted_share', ...
    'A3_predicted_share'});

writetable(Summary_Table, cfg.summary_csv);

fprintf('>>> Fixed-scale LFP results saved to: %s\n', cfg.result_mat);
fprintf('>>> Fixed-scale LFP summary saved to: %s\n', cfg.summary_csv);
fprintf('================ Part4 Exp01 completed ================\n');

%% Local helper functions
function SOH_data = local_extract_soh_from_mat(SOH_file, input_file)
% Extract a numeric SOH vector from a MAT-file structure.

if isfield(SOH_file, 'SOH_array')
    SOH_raw = SOH_file.SOH_array;
elseif isfield(SOH_file, 'LFP_SOH_Table')
    SOH_raw = SOH_file.LFP_SOH_Table;
elseif isfield(SOH_file, 'SOH_data')
    SOH_raw = SOH_file.SOH_data;
else
    var_names = fieldnames(SOH_file);
    if isempty(var_names)
        error('No variables were found in %s.', input_file);
    end
    SOH_raw = SOH_file.(var_names{1});
end

if istable(SOH_raw)
    table_vars = SOH_raw.Properties.VariableNames;
    soh_col_idx = find(contains(lower(table_vars), 'soh'), 1, 'first');
    if isempty(soh_col_idx)
        soh_col_idx = 1;
    end
    SOH_data = SOH_raw{:, soh_col_idx};
else
    SOH_data = SOH_raw;
end

SOH_data = double(SOH_data(:));
SOH_data = SOH_data(isfinite(SOH_data));

if isempty(SOH_data)
    error('No valid SOH values were found in %s.', input_file);
end
end


function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end
