%% P5_Exp07_LFP_MarketScale_Extension.m
% Purpose:
% This script evaluates the LFP scale-dependent recertification model under
% extended market-scale throughput scenarios.
% It extends the deployment scale from the manuscript range of 10-2,000 tons
% to exploratory market-scale scenarios up to 500,000 tons. The script reports
% the scale-specific optimal k*, thresholds, cost decomposition, pathway values,
% and net value after recertification cost.

clear, clc, close all;
format compact;
format shortG;

%% 0. Path configuration
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

% Project root folder.
cfg.project_root = fileparts(script_dir);

% Part5 folders.
cfg.input_dir = fullfile(script_dir, 'Input');
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');
cfg.function_dir = fullfile(script_dir, 'Function');

% Part3 output folder.
cfg.part3_output_dir = fullfile(cfg.project_root,'Part3_Prediction error extrapolation', 'Output');

% Input SOH file for Part5.
cfg.soh_file = fullfile(cfg.input_dir, 'LFP_SOH_Table.mat');

% Primary residual-error extrapolation model generated by Part3 Exp03.
cfg.residual_file_primary = fullfile(cfg.part3_output_dir, 'Results', 'P3_Exp03_ResidualExtrapolation_Model.mat');
cfg.residual_file_legacy = fullfile(cfg.part3_output_dir, 'Result03_ResidualExtrapolation_Model.mat');
cfg.residual_file_sup01 = fullfile(cfg.part3_output_dir, 'Sup01', 'Result03_ResidualExtrapolation_Model.mat');

% Output files generated by Part5 Exp07.
cfg.market_scale_csv = fullfile(cfg.results_dir, 'P5_Exp07_LFP_MarketScale_Extension_Table.csv');
cfg.cost_breakdown_csv = fullfile(cfg.results_dir, 'P5_Exp07_LFP_MarketScale_CostBreakdown.csv');
cfg.market_only_csv = fullfile(cfg.results_dir, 'P5_Exp07_LFP_MarketScale_OnlyRows.csv');
cfg.result_mat = fullfile(cfg.results_dir, 'P5_Exp07_LFP_MarketScale_Extension_Results.mat');

% Create required local folders.
folder_list = {cfg.input_dir, cfg.output_dir, cfg.results_dir, cfg.function_dir};

for ii = 1:numel(folder_list)
    if ~exist(folder_list{ii}, 'dir')
        mkdir(folder_list{ii});
    end
end

% Add the local function folder.
if exist(cfg.function_dir, 'dir')
    addpath(cfg.function_dir);
end

% Check the LFP SOH input file.
if ~isfile(cfg.soh_file)
    error('LFP SOH input file not found: %s', cfg.soh_file);
end

% Locate the Part3 residual-error result file.
if isfile(cfg.residual_file_primary)
    cfg.residual_file = cfg.residual_file_primary;
elseif isfile(cfg.residual_file_legacy)
    cfg.residual_file = cfg.residual_file_legacy;
elseif isfile(cfg.residual_file_sup01)
    cfg.residual_file = cfg.residual_file_sup01;
else
    error(['Part3 residual-error extrapolation model file not found.\n' ...
        'Checked:\n%s\n%s\n%s\n' ...
        'Please run Part3 Exp03 first to generate the residual-error model.'], ...
        cfg.residual_file_primary, ...
        cfg.residual_file_legacy, ...
        cfg.residual_file_sup01);
end

fprintf('================ Part5 Exp07 LFP market-scale extension ================\n');
fprintf('LFP SOH input file:  %s\n', cfg.soh_file);
fprintf('Part3 residual file: %s\n', cfg.residual_file);
fprintf('Market-scale table: %s\n', cfg.market_scale_csv);
fprintf('Cost-breakdown table: %s\n', cfg.cost_breakdown_csv);
fprintf('Result MAT file: %s\n', cfg.result_mat);

% 1. Basic physical and economic parameters

if ~isfile(cfg.soh_file)
    error('LFP SOH input file not found: %s', cfg.soh_file);
end

S_input = load(cfg.soh_file);

if isfield(S_input, 'SOH_array')
    SOH_array = S_input.SOH_array;
elseif isfield(S_input, 'LFP_SOH_Table')
    SOH_array = S_input.LFP_SOH_Table;
elseif isfield(S_input, 'SOH_data')
    SOH_array = S_input.SOH_data;
else
    input_var_names = fieldnames(S_input);
    if isempty(input_var_names)
        error('No variable was found in %s.', cfg.soh_file);
    end
    SOH_array = S_input.(input_var_names{1});
end

if istable(SOH_array)
    table_vars = SOH_array.Properties.VariableNames;
    soh_col_idx = find(contains(lower(table_vars), 'soh'), 1, 'first');
    if isempty(soh_col_idx)
        soh_col_idx = 1;
    end
    SOH_data = SOH_array{:, soh_col_idx};
else
    SOH_data = SOH_array;
end

SOH_data = double(SOH_data(:));
SOH_data = SOH_data(isfinite(SOH_data));

if isempty(SOH_data)
    error('No valid LFP SOH values were found in %s.', cfg.soh_file);
end

Q_pack = 25.3;
r = 0.05;
beta_refurbish = 0.09;

ExchangeRate_RMB_USD = 7.04;
p_high_RMB = 1.1621;
p_low_RMB  = 0.2986;

p_high = p_high_RMB / ExchangeRate_RMB_USD;   % 0.1651
p_low  = p_low_RMB  / ExchangeRate_RMB_USD;   % 0.0424

c_pack = 300;                 c_train = 100;                 Fixed_Scale_N = 2500;
% SOH labeling cost      model training cost         fixed deployment scale


Eta_1 = 40;  Eta_2 = 40;
% G1 gray-zone tolerance between recycling and refurbishment
% G2 gray-zone tolerance between direct reuse and refurbishment

% Refurbishment cost parameters
C0 = 92;      % baseline labor, disassembly, and inspection cost
C1 = 65;      % material replacement and deep-repair cost coefficient
gamma = 3;    % nonlinear degradation exponent for refurbishment difficulty

Lambda_R = 15;    Lambda_A = 12;
% Risk penalty is applied to over-optimistic action assignment.
% Manual-review penalty is applied once the value-loss tolerance is exceeded.


% 1.1 Hydrometallurgical recycling economics and physicochemical parameters

M_pack = 173.25;                Exchange_Rate = 1;


% - 1. Baseline physicochemical parameters per kg battery pack -
PosAcMass = 0.223;      PosCCMass = 0.060;     NegAcMass = 0.1235;      NegCCMass = 0.08;
M_LiFePO4 = 157.76;     M_Li2CO3_half = 73.88;    M_FePO4 = 150.82;    M_H2SO4 = 98;    M_H2O2 = 34;    M_Na2CO3 = 106;

Rec_Rate_Chem = 0.98;    Rec_Rate_Graphite = 0.95;        Rec_Rate_Al = 0.93;      Rec_Rate_Cu = 0.93;
P_Li2CO3   = 27.20;  P_FePO4    = 1.91;  P_Graphite = 3.84;  P_Al       = 3.42;   P_Cu       = 14.79;
Base_Y_FePO4    = (PosAcMass / M_LiFePO4) * M_FePO4 * Rec_Rate_Chem;
Base_Y_Graphite = NegAcMass * Rec_Rate_Graphite;
Base_Y_Al = PosCCMass * Rec_Rate_Al;      Base_Y_Cu  = NegCCMass * Rec_Rate_Cu;
C_Degraded = 2.05;   P_H2SO4    = 0.264;   P_H2O2     = 0.130;   P_Na2CO3   = 0.172;
P_elec_recycle = 0.111;   % USD/kWh

C_Electricity_hydro = 500 * P_elec_recycle / 1000;  % USD/kg battery
C_Labor_hydro       = 307.36 / 1000;                % USD/kg battery
C_Disassemble_hydro = 12.07  / 1000;                % USD/kg battery
C_Equip_hydro       = 52.00  / 1000;                % USD/kg battery
C_Sewage_hydro      = 141.14 / 1000;                % USD/kg battery

Fixed_Op_Cost = C_Electricity_hydro + C_Labor_hydro + ...
    C_Disassemble_hydro + C_Equip_hydro + C_Sewage_hydro;


% 2. SOH-dependent action-value functions

% 2.1 Construct the baseline direct-reuse value curve from the empirical SOH trajectory
valid_end_idx = find(SOH_data >= 0.4);   end_idx = valid_end_idx(end);

start_indices = find(SOH_data <= 1.0 & SOH_data >= 0.4);
num_cases = length(start_indices);
a = zeros(num_cases, 1);   V1 = zeros(num_cases, 1);

for k = 1:num_cases
    start_idx = start_indices(k);

    SOH_slice = SOH_data(start_idx : end_idx);

    a(k) = SOH_slice(1);
    days_elapsed = (0 : length(SOH_slice)-1)';

    SOH_diff = 1 - SOH_slice;
    Poly_term = -0.1532 .* (SOH_diff.^2) + 0.003923 .* SOH_diff + 0.9530;
    Daily_Value_Raw = Q_pack .* SOH_slice .* (Poly_term .* p_high - p_low);

    Discount_Factor = 1 ./ ((1 + r) .^ (days_elapsed / 365));
    V1(k) = sum(Daily_Value_Raw .* Discount_Factor);
end

% Sort SOH values for subsequent interp1 interpolation
[a, sort_idx] = sort(a);  V1 = V1(sort_idx);

if max(a) < 1.0
    a = [a; 1.0];
    slope = (V1(end) - V1(end-1)) / (a(end) - a(end-1));
    V1 = [V1; V1(end) + slope * (1.0 - a(end-1))];
end


% 2.2 Define dynamic action-value functions for the three recertification pathways

C_A1_extra = 10;    % extra cost for direct reuse, including transport, testing, integration, and installation
C_A2_extra = 15;    % extra cost for refurbishment, including disassembly, labor, regrouping, and retesting


% Action 3: hydrometallurgical recycling value function based on stoichiometric reactions
Y_Li2CO3_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_Li2CO3_half .* Rec_Rate_Chem;
Y_H2SO4_func  = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_H2SO4;
Y_H2O2_func   = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_H2O2;
Y_Na2CO3_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_Na2CO3;

calc_V_reuse_base = @(soh) interp1(a, V1, soh, 'linear', 'extrap');
calc_V_reuse = @(soh) calc_V_reuse_base(soh) - C_A1_extra;

calc_C_refurbish = @(soh) C0 + C1 .* (1 - soh).^gamma;
calc_V_refurbish_base = @(soh) ...
    calc_V_reuse_base(min(soh + beta_refurbish .* (1 - soh), 1.0)) - calc_C_refurbish(soh);
calc_V_refurbish = @(soh) calc_V_refurbish_base(soh) - C_A1_extra - C_A2_extra;

calc_V_recycle = @(soh) M_pack .* Exchange_Rate .* ( ...
    (Y_Li2CO3_func(soh) .* P_Li2CO3 + Base_Y_FePO4 .* P_FePO4 + Base_Y_Graphite .* P_Graphite + Base_Y_Al .* P_Al + Base_Y_Cu .* P_Cu) ...
    - (Y_H2SO4_func(soh) .* P_H2SO4 + Y_H2O2_func(soh) .* P_H2O2 + Y_Na2CO3_func(soh) .* P_Na2CO3) ...
    - (PosAcMass .* C_Degraded + Fixed_Op_Cost) ...
    );



%% 3. Load k-dependent residual-error extrapolation model

error_model_file = cfg.residual_file;

if ~isfile(error_model_file)
    error('Part3 residual-error model file not found: %s', error_model_file);
end

ErrorModel = load(error_model_file);

required_error_vars = { ...
    'k_emp', ...
    'k_vals', ...
    'err_cell', ...
    'rmse_target', ...
    'w_curve', ...
    'muM_curve', ...
    'sigM_curve', ...
    'muR_curve', ...
    'sigR_curve', ...
    'region', ...
    'cfg'};

for ii = 1:numel(required_error_vars)
    if ~isfield(ErrorModel, required_error_vars{ii})
        error('Required variable "%s" was not found in %s.', ...
            required_error_vars{ii}, error_model_file);
    end
end

k_emp = ErrorModel.k_emp(:);
k_vals = ErrorModel.k_vals(:);
err_cell = ErrorModel.err_cell;

rmse_target = ErrorModel.rmse_target(:);
w_curve     = ErrorModel.w_curve(:);
muM_curve   = ErrorModel.muM_curve(:);
sigM_curve  = ErrorModel.sigM_curve(:);
muR_curve   = ErrorModel.muR_curve(:);
sigR_curve  = ErrorModel.sigR_curve(:);

region = ErrorModel.region;

if isfield(ErrorModel.cfg, 'k_anchor')
    k_anchor = ErrorModel.cfg.k_anchor;
else
    k_anchor = 21;
end

if isfield(ErrorModel.cfg, 'k_bridge_end')
    k_bridge_end = ErrorModel.cfg.k_bridge_end;
else
    k_bridge_end = 26;
end

if max(k_vals) < 50
    error(['The loaded residual-error model only covers k = %d to %d. ', ...
        'Please rerun P3_Exp03_label_dependent_residual_extrapolation.m with a larger cfg.k_extrap_max.'], ...
        min(k_vals), max(k_vals));
end

if numel(k_vals) ~= numel(rmse_target) || ...
        numel(k_vals) ~= numel(w_curve) || ...
        numel(k_vals) ~= numel(muM_curve) || ...
        numel(k_vals) ~= numel(sigM_curve) || ...
        numel(k_vals) ~= numel(muR_curve) || ...
        numel(k_vals) ~= numel(sigR_curve)
    error('The loaded residual-error model has inconsistent curve lengths.');
end

N_sim = 100000;
rng(42);

base_u    = rand(N_sim, 1);
base_z    = randn(N_sim, 1);
base_pick = rand(N_sim, 1);

fprintf('Residual-error model loaded from: %s\n', error_model_file);
fprintf('Loaded k range: %d to %d\n', min(k_vals), max(k_vals)); 


fprintf('>>> Running dense k-grid search from k = %d to %d...\n', ...
    min(k_vals), max(k_vals));

s_true = 0.4 + 0.6*rand(N_sim,1);

Pi_True = [calc_V_reuse(s_true), calc_V_refurbish(s_true), calc_V_recycle(s_true)];
[Pi_True_Max, True_Action_i] = max(Pi_True, [], 2);

T1_grid = 0.40 : 0.001 : 0.50;
T2_grid = 0.85 : 0.001 : 0.93;

E_L_base = zeros(length(k_vals), 1);
O_base = zeros(length(k_vals), 1);
A_base = zeros(length(k_vals), 1);
R_base = zeros(length(k_vals), 1);
T1_base = zeros(length(k_vals), 1);
T2_base = zeros(length(k_vals), 1);

for i = 1:length(k_vals)
    k_current = k_vals(i);

    sampled_noise = local_build_noise_by_k( ...
        k_current, ...
        k_emp, k_anchor, k_bridge_end, ...
        err_cell, ...
        w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
        base_u, base_z, base_pick);

    s_pred = min(max(s_true + sampled_noise, 0), 1.0);

    min_L = inf;
    for T1 = T1_grid
        for T2 = T2_grid
            if T1 >= T2
                continue;
            end

            Pred_Action_j = 3 * ones(N_sim, 1);
            Pred_Action_j(s_pred >= T1 & s_pred < T2) = 2;
            Pred_Action_j(s_pred >= T2) = 1;

            idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_j);
            O_arr = Pi_True_Max - Pi_True(idx_pred);

            is_G1_error = (True_Action_i == 3 & Pred_Action_j == 2) | ...
                (True_Action_i == 2 & Pred_Action_j == 3);
            is_G2_error = (True_Action_i == 1 & Pred_Action_j == 2) | ...
                (True_Action_i == 2 & Pred_Action_j == 1);

            Current_Eta = zeros(N_sim, 1);
            Current_Eta(is_G1_error) = Eta_1;
            Current_Eta(is_G2_error) = Eta_2;

            trigger_penalty = O_arr > Current_Eta;
            Excess_Loss = max(0, O_arr - Current_Eta);

            A_arr = trigger_penalty .* Lambda_A;
            R_arr = (Pred_Action_j < True_Action_i) .* trigger_penalty .* (Lambda_R .* Excess_Loss);

            E_L = mean(O_arr + A_arr + R_arr);

            if E_L < min_L
                min_L = E_L;
                O_base(i) = mean(O_arr);
                A_base(i) = mean(A_arr);
                R_base(i) = mean(R_arr);
                T1_base(i) = T1;
                T2_base(i) = T2;
            end
        end
    end
    E_L_base(i) = min_L;
end



% 4. Fixed-scale result extraction and recalculation at the optimal k*

Fixed_O = O_base * Fixed_Scale_N;
Fixed_A = A_base * Fixed_Scale_N;
Fixed_R = R_base * Fixed_Scale_N;
Fixed_Model = (k_vals .* c_pack + c_train);
Fixed_Total_Cost = Fixed_O + Fixed_A + Fixed_R + Fixed_Model;
[~, opt_k_idx] = min(Fixed_Total_Cost);
opt_k = k_vals(opt_k_idx);
opt_T1 = T1_base(opt_k_idx);
opt_T2 = T2_base(opt_k_idx);
Scale_Factor = Fixed_Scale_N / N_sim;

fprintf('>>> Extracting sample-level results at the optimal k* = %d...\n', opt_k);

% Reconstruct predicted SOH and assigned actions under the optimal k
noise_opt = local_build_noise_by_k( ...
    opt_k, ...
    k_emp, k_anchor, k_bridge_end, ...
    err_cell, ...
    w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
    base_u, base_z, base_pick);

s_pred_opt = min(max(s_true + noise_opt, 0), 1.0);

Pred_Action_opt = 3 * ones(N_sim, 1);
Pred_Action_opt(s_pred_opt >= opt_T1 & s_pred_opt < opt_T2) = 2;
Pred_Action_opt(s_pred_opt >= opt_T2) = 1;

idx_pred_opt = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_opt);
O_arr_opt = Pi_True_Max - Pi_True(idx_pred_opt);

is_G1_opt = (True_Action_i == 3 & Pred_Action_opt == 2) | (True_Action_i == 2 & Pred_Action_opt == 3);
is_G2_opt = (True_Action_i == 1 & Pred_Action_opt == 2) | (True_Action_i == 2 & Pred_Action_opt == 1);
Eta_opt = zeros(N_sim, 1); Eta_opt(is_G1_opt) = Eta_1; Eta_opt(is_G2_opt) = Eta_2;

trigger_opt = O_arr_opt > Eta_opt;
Excess_opt = max(0, O_arr_opt - Eta_opt);

A_arr_opt = trigger_opt .* Lambda_A;
R_arr_opt = (Pred_Action_opt < True_Action_i) .* trigger_opt .* (Lambda_R .* Excess_opt);

Total_Loss_opt = O_arr_opt + A_arr_opt + R_arr_opt;
Net_Revenue_opt = Pi_True(idx_pred_opt) - A_arr_opt - R_arr_opt;


%% ================= Market-scale definition in tons =================
% This list keeps the original 10-2000 ton range and adds market-scale
% exploratory scenarios. Edit this vector directly if you want to test other
% market sizes.
scale_ton_list = [ ...
    5000; 10000; 20000; 50000; ...
    100000; 200000; 300000; 500000];

% Convert tonnage values to pack numbers for internal calculations
N_list = max(1, round(scale_ton_list * 1000 / M_pack));

% Optional check of the actual tonnage after pack-number rounding
% scale_ton_list_actual = N_list * M_pack / 1000;

num_N = numel(N_list);
num_k = numel(k_vals);

% Precompute predicted action-allocation ratios under each k
Pred_Action_Ratio_byK = zeros(num_k, 3);

% Precompute per-pack average value contribution of the three actions under each k
A1_value_perpack_byK = zeros(num_k, 1);
A2_value_perpack_byK = zeros(num_k, 1);
A3_value_perpack_byK = zeros(num_k, 1);


for i = 1:num_k
    k_curr = k_vals(i);

    T1_curr = T1_base(i);
    T2_curr = T2_base(i);

    noise_curr = local_build_noise_by_k( ...
        k_curr, ...
        k_emp, k_anchor, k_bridge_end, ...
        err_cell, ...
        w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
        base_u, base_z, base_pick);

    s_pred_curr = min(max(s_true + noise_curr, 0), 1.0);

    Pred_Action_curr = 3 * ones(N_sim, 1);
    Pred_Action_curr(s_pred_curr >= T1_curr & s_pred_curr < T2_curr) = 2;
    Pred_Action_curr(s_pred_curr >= T2_curr) = 1;

    Pred_Action_Ratio_byK(i, 1) = mean(Pred_Action_curr == 1);
    Pred_Action_Ratio_byK(i, 2) = mean(Pred_Action_curr == 2);
    Pred_Action_Ratio_byK(i, 3) = mean(Pred_Action_curr == 3);

    A1_value_perpack_byK(i) = mean(Pi_True(:,1) .* (Pred_Action_curr == 1));
    A2_value_perpack_byK(i) = mean(Pi_True(:,2) .* (Pred_Action_curr == 2));
    A3_value_perpack_byK(i) = mean(Pi_True(:,3) .* (Pred_Action_curr == 3));
end

% Build the N-by-k cost matrix
O_Cost_NK     = zeros(num_N, num_k);
A_Cost_NK     = zeros(num_N, num_k);
R_Cost_NK     = zeros(num_N, num_k);
Model_Cost_NK = zeros(num_N, num_k);
Total_Cost_NK = zeros(num_N, num_k);

% Store optimal results under each deployment scale
opt_idx_of_N        = zeros(num_N, 1);
opt_k_of_N          = zeros(num_N, 1);
opt_T1_of_N         = zeros(num_N, 1);
opt_T2_of_N         = zeros(num_N, 1);
opt_total_cost_of_N = zeros(num_N, 1);

opt_O_of_N          = zeros(num_N, 1);
opt_A_of_N          = zeros(num_N, 1);
opt_R_of_N          = zeros(num_N, 1);
opt_Model_of_N      = zeros(num_N, 1);

opt_Action_Ratio_of_N = zeros(num_N, 3);
opt_A1_value_of_N = zeros(num_N, 1);
opt_A2_value_of_N = zeros(num_N, 1);
opt_A3_value_of_N = zeros(num_N, 1);

% Loop over deployment scales
for iN = 1:num_N
    N_curr = N_list(iN);

    % Decision-loss costs scale linearly with deployment scale
    O_Cost_NK(iN, :) = (O_base(:)' .* N_curr);
    A_Cost_NK(iN, :) = (A_base(:)' .* N_curr);
    R_Cost_NK(iN, :) = (R_base(:)' .* N_curr);

    % Model cost follows the current setting and does not scale with N
    Model_Cost_NK(iN, :) = (k_vals(:)' .* c_pack + c_train);

    % Total cost
    Total_Cost_NK(iN, :) = O_Cost_NK(iN, :) + ...
        A_Cost_NK(iN, :) + ...
        R_Cost_NK(iN, :) + ...
        Model_Cost_NK(iN, :);

    % Identify the optimal k* under the current deployment scale
    [opt_total_cost_of_N(iN), idx_best] = min(Total_Cost_NK(iN, :));

    opt_idx_of_N(iN) = idx_best;
    opt_k_of_N(iN)   = k_vals(idx_best);


    opt_T1_of_N(iN) = T1_base(idx_best);
    opt_T2_of_N(iN) = T2_base(idx_best);

    % Store the cost decomposition at the scale-specific optimum
    opt_O_of_N(iN)     = O_Cost_NK(iN, idx_best);
    opt_A_of_N(iN)     = A_Cost_NK(iN, idx_best);
    opt_R_of_N(iN)     = R_Cost_NK(iN, idx_best);
    opt_Model_of_N(iN) = Model_Cost_NK(iN, idx_best);
    opt_Action_Ratio_of_N(iN, :) = Pred_Action_Ratio_byK(idx_best, :);
    opt_A1_value_of_N(iN) = N_curr * A1_value_perpack_byK(idx_best);
    opt_A2_value_of_N(iN) = N_curr * A2_value_perpack_byK(idx_best);
    opt_A3_value_of_N(iN) = N_curr * A3_value_perpack_byK(idx_best);

end

% Per-pack optimal cost
opt_cost_per_pack_of_N = opt_total_cost_of_N ./ N_list;

fprintf('\n>>> Scale-effect analysis completed.\n');
fprintf('>>> Pack-number range: %d to %d\n', min(N_list), max(N_list));
fprintf('>>> k* range: %d to %d\n', min(opt_k_of_N), max(opt_k_of_N));




%% ================= Result-only market-scale summary =================

% Total pathway value and net value after recertification cost.
Total_action_value_of_N = opt_A1_value_of_N + opt_A2_value_of_N + opt_A3_value_of_N;
Net_value_after_cost_of_N = Total_action_value_of_N - opt_total_cost_of_N;
Label_density_per_ton = opt_k_of_N ./ scale_ton_list;

% Cost components at the scale-specific optimum.
Opportunity_loss_total_USD = opt_O_of_N;
Manual_review_total_USD   = opt_A_of_N;
Risk_penalty_total_USD    = opt_R_of_N;
Info_cost_total_USD       = opt_Model_of_N;
Decision_cost_total_USD   = Opportunity_loss_total_USD + Manual_review_total_USD + Risk_penalty_total_USD;

% Per-pack cost components.
Opportunity_loss_per_pack_USD = Opportunity_loss_total_USD ./ N_list;
Manual_review_per_pack_USD   = Manual_review_total_USD   ./ N_list;
Risk_penalty_per_pack_USD    = Risk_penalty_total_USD    ./ N_list;
Info_cost_per_pack_USD       = Info_cost_total_USD       ./ N_list;
Decision_cost_per_pack_USD   = Decision_cost_total_USD   ./ N_list;

% Component shares in the total recertification cost.
Opportunity_loss_share_percent = 100 .* Opportunity_loss_total_USD ./ opt_total_cost_of_N;
Manual_review_share_percent   = 100 .* Manual_review_total_USD   ./ opt_total_cost_of_N;
Risk_penalty_share_percent    = 100 .* Risk_penalty_total_USD    ./ opt_total_cost_of_N;
Info_cost_share_percent       = 100 .* Info_cost_total_USD       ./ opt_total_cost_of_N;
Decision_cost_share_percent   = 100 .* Decision_cost_total_USD   ./ opt_total_cost_of_N;

MarketScale_Table = table( ...
    scale_ton_list(:), ...
    N_list(:), ...
    opt_k_of_N(:), ...
    Label_density_per_ton(:), ...
    opt_T1_of_N(:), ...
    opt_T2_of_N(:), ...
    opt_total_cost_of_N(:), ...
    opt_cost_per_pack_of_N(:), ...
    Opportunity_loss_total_USD(:), ...
    Manual_review_total_USD(:), ...
    Risk_penalty_total_USD(:), ...
    Info_cost_total_USD(:), ...
    Decision_cost_total_USD(:), ...
    Opportunity_loss_per_pack_USD(:), ...
    Manual_review_per_pack_USD(:), ...
    Risk_penalty_per_pack_USD(:), ...
    Info_cost_per_pack_USD(:), ...
    Decision_cost_per_pack_USD(:), ...
    Opportunity_loss_share_percent(:), ...
    Manual_review_share_percent(:), ...
    Risk_penalty_share_percent(:), ...
    Info_cost_share_percent(:), ...
    Decision_cost_share_percent(:), ...
    opt_Action_Ratio_of_N(:, 1), ...
    opt_Action_Ratio_of_N(:, 2), ...
    opt_Action_Ratio_of_N(:, 3), ...
    opt_A1_value_of_N(:), ...
    opt_A2_value_of_N(:), ...
    opt_A3_value_of_N(:), ...
    Total_action_value_of_N(:), ...
    Net_value_after_cost_of_N(:), ...
    Total_action_value_of_N(:) ./ 1e9, ...
    Net_value_after_cost_of_N(:) ./ 1e9, ...
    'VariableNames', { ...
    'Scale_ton', ...
    'Pack_number', ...
    'Optimal_k', ...
    'Label_density_per_ton', ...
    'T1_star', ...
    'T2_star', ...
    'Total_recertification_cost_USD', ...
    'Total_recertification_cost_per_pack_USD', ...
    'Opportunity_loss_USD', ...
    'Manual_review_cost_USD', ...
    'Risk_penalty_USD', ...
    'SOH_labeling_training_cost_USD', ...
    'Decision_cost_USD', ...
    'Opportunity_loss_per_pack_USD', ...
    'Manual_review_cost_per_pack_USD', ...
    'Risk_penalty_per_pack_USD', ...
    'SOH_labeling_training_cost_per_pack_USD', ...
    'Decision_cost_per_pack_USD', ...
    'Opportunity_loss_share_percent', ...
    'Manual_review_cost_share_percent', ...
    'Risk_penalty_share_percent', ...
    'SOH_labeling_training_cost_share_percent', ...
    'Decision_cost_share_percent', ...
    'A1_direct_reuse_share', ...
    'A2_refurbishment_share', ...
    'A3_recycling_share', ...
    'A1_direct_reuse_value_USD', ...
    'A2_refurbishment_value_USD', ...
    'A3_recycling_value_USD', ...
    'Total_pathway_value_USD', ...
    'Net_value_after_recertification_cost_USD', ...
    'Total_pathway_value_billion_USD', ...
    'Net_value_after_recertification_cost_billion_USD'});

CostBreakdown_Table = table( ...
    scale_ton_list(:), ...
    N_list(:), ...
    opt_k_of_N(:), ...
    opt_T1_of_N(:), ...
    opt_T2_of_N(:), ...
    opt_total_cost_of_N(:) ./ 1e6, ...
    Opportunity_loss_total_USD(:) ./ 1e6, ...
    Manual_review_total_USD(:) ./ 1e6, ...
    Risk_penalty_total_USD(:) ./ 1e6, ...
    Info_cost_total_USD(:) ./ 1e6, ...
    Decision_cost_total_USD(:) ./ 1e6, ...
    opt_cost_per_pack_of_N(:), ...
    Opportunity_loss_per_pack_USD(:), ...
    Manual_review_per_pack_USD(:), ...
    Risk_penalty_per_pack_USD(:), ...
    Info_cost_per_pack_USD(:), ...
    Decision_cost_per_pack_USD(:), ...
    Opportunity_loss_share_percent(:), ...
    Manual_review_share_percent(:), ...
    Risk_penalty_share_percent(:), ...
    Info_cost_share_percent(:), ...
    Decision_cost_share_percent(:), ...
    'VariableNames', { ...
    'Scale_ton', ...
    'Pack_number', ...
    'Optimal_k', ...
    'T1_star', ...
    'T2_star', ...
    'Total_cost_MUSD', ...
    'Opportunity_loss_MUSD', ...
    'Manual_review_cost_MUSD', ...
    'Risk_penalty_MUSD', ...
    'SOH_labeling_training_cost_MUSD', ...
    'Decision_cost_MUSD', ...
    'Total_cost_per_pack_USD', ...
    'Opportunity_loss_per_pack_USD', ...
    'Manual_review_cost_per_pack_USD', ...
    'Risk_penalty_per_pack_USD', ...
    'SOH_labeling_training_cost_per_pack_USD', ...
    'Decision_cost_per_pack_USD', ...
    'Opportunity_loss_share_percent', ...
    'Manual_review_cost_share_percent', ...
    'Risk_penalty_share_percent', ...
    'SOH_labeling_training_cost_share_percent', ...
    'Decision_cost_share_percent'});




% Save formal Part5 Exp07 outputs.
idx_market = scale_ton_list >= 5000;

MarketScale_Only_Table = MarketScale_Table(idx_market, :);
CostBreakdown_Only_Table = CostBreakdown_Table(idx_market, :);

writetable(MarketScale_Table, cfg.market_scale_csv);
writetable(CostBreakdown_Table, cfg.cost_breakdown_csv);
writetable(MarketScale_Only_Table, cfg.market_only_csv);

LFP_MarketScale_Extension_Result = struct();

LFP_MarketScale_Extension_Result.scale_ton_list = scale_ton_list;
LFP_MarketScale_Extension_Result.N_list = N_list;
LFP_MarketScale_Extension_Result.k_vals = k_vals;

LFP_MarketScale_Extension_Result.opt_k_of_N = opt_k_of_N;
LFP_MarketScale_Extension_Result.opt_T1_of_N = opt_T1_of_N;
LFP_MarketScale_Extension_Result.opt_T2_of_N = opt_T2_of_N;
LFP_MarketScale_Extension_Result.opt_total_cost_of_N = opt_total_cost_of_N;
LFP_MarketScale_Extension_Result.opt_cost_per_pack_of_N = opt_cost_per_pack_of_N;

LFP_MarketScale_Extension_Result.opt_O_of_N = opt_O_of_N;
LFP_MarketScale_Extension_Result.opt_A_of_N = opt_A_of_N;
LFP_MarketScale_Extension_Result.opt_R_of_N = opt_R_of_N;
LFP_MarketScale_Extension_Result.opt_Model_of_N = opt_Model_of_N;

LFP_MarketScale_Extension_Result.opt_Action_Ratio_of_N = opt_Action_Ratio_of_N;
LFP_MarketScale_Extension_Result.opt_A1_value_of_N = opt_A1_value_of_N;
LFP_MarketScale_Extension_Result.opt_A2_value_of_N = opt_A2_value_of_N;
LFP_MarketScale_Extension_Result.opt_A3_value_of_N = opt_A3_value_of_N;

LFP_MarketScale_Extension_Result.Total_action_value_of_N = Total_action_value_of_N;
LFP_MarketScale_Extension_Result.Net_value_after_cost_of_N = Net_value_after_cost_of_N;

LFP_MarketScale_Extension_Result.MarketScale_Table = MarketScale_Table;
LFP_MarketScale_Extension_Result.CostBreakdown_Table = CostBreakdown_Table;
LFP_MarketScale_Extension_Result.MarketScale_Only_Table = MarketScale_Only_Table;
LFP_MarketScale_Extension_Result.CostBreakdown_Only_Table = CostBreakdown_Only_Table;

LFP_MarketScale_Extension_Result.cfg_part5_exp07 = cfg;

save(cfg.result_mat, ...
'LFP_MarketScale_Extension_Result', ...
'MarketScale_Table', ...
'CostBreakdown_Table', ...
'MarketScale_Only_Table', ...
'CostBreakdown_Only_Table', ...
'-v7.3');

fprintf('\nSaved market-scale table: %s\n', cfg.market_scale_csv);
fprintf('Saved cost-breakdown table: %s\n', cfg.cost_breakdown_csv);
fprintf('Saved market-only table: %s\n', cfg.market_only_csv);
fprintf('Saved result MAT: %s\n', cfg.result_mat);

% 
% 
% fprintf('\n========== Full scale-dependent result table ==========' );
% fprintf('\n');
% disp(MarketScale_Table);
% 
% fprintf('\n========== Full cost-breakdown table ==========' );
% fprintf('\n');
% disp(CostBreakdown_Table);
% 
% idx_market = scale_ton_list >= 5000;
% fprintf('\n========== Market-scale rows only, S >= 5000 tons ==========' );
% fprintf('\n');
% disp(MarketScale_Table(idx_market, :));
% 
% fprintf('\n========== Market-scale cost-breakdown rows only, S >= 5000 tons ==========' );
% fprintf('\n');
% disp(CostBreakdown_Table(idx_market, :));
% 
% fprintf('\n========== Compact market-scale summary ==========' );
% fprintf('\n');
% fprintf('%12s | %12s | %5s | %9s | %9s | %11s | %12s | %12s\n', ...
%     'Scale_ton', 'Pack_number', 'k*', 'T1*', 'T2*', 'Cost/pack', 'Value(B$)', 'Net(B$)');
% fprintf('%s\n', repmat('-', 1, 103));
% for ii = find(idx_market)'
%     fprintf('%12.0f | %12.0f | %5d | %9.3f | %9.3f | %11.4f | %12.4f | %12.4f\n', ...
%         scale_ton_list(ii), ...
%         N_list(ii), ...
%         opt_k_of_N(ii), ...
%         opt_T1_of_N(ii), ...
%         opt_T2_of_N(ii), ...
%         opt_cost_per_pack_of_N(ii), ...
%         Total_action_value_of_N(ii) / 1e9, ...
%         Net_value_after_cost_of_N(ii) / 1e9);
% end
% 
% fprintf('\n========== Compact market-scale cost breakdown ==========' );
% fprintf('\n');
% fprintf('%12s | %10s | %10s | %10s | %10s | %10s | %10s | %10s | %10s\n', ...
%     'Scale_ton', 'Total(M$)', 'Opp(M$)', 'Review(M$)', 'Risk(M$)', 'Info(M$)', ...
%     'Opp/pack', 'Info/pack', 'Total/pack');
% fprintf('%s\n', repmat('-', 1, 119));
% for ii = find(idx_market)'
%     fprintf('%12.0f | %10.4f | %10.4f | %10.4f | %10.4f | %10.4f | %10.4f | %10.4f | %10.4f\n', ...
%         scale_ton_list(ii), ...
%         opt_total_cost_of_N(ii) / 1e6, ...
%         Opportunity_loss_total_USD(ii) / 1e6, ...
%         Manual_review_total_USD(ii) / 1e6, ...
%         Risk_penalty_total_USD(ii) / 1e6, ...
%         Info_cost_total_USD(ii) / 1e6, ...
%         Opportunity_loss_per_pack_USD(ii), ...
%         Info_cost_per_pack_USD(ii), ...
%         opt_cost_per_pack_of_N(ii));
% end
% 
% fprintf('\n========== Boundary check ==========' );
% fprintf('\n');
% fprintf('Loaded k range: %d to %d\n', min(k_vals), max(k_vals));
% fprintf('Selected k* range across all scales: %d to %d\n', min(opt_k_of_N), max(opt_k_of_N));
% 
% if any(opt_k_of_N == max(k_vals))
%     fprintf(['WARNING: At least one scale selects k* = max(k_vals) = %d.\n' ...
%         'This means the market-scale optimum may be truncated by the current k-grid.\n' ...
%         'For final manuscript numbers, extend the Part3 residual extrapolation range and rerun this test.\n'], max(k_vals));
%     disp(MarketScale_Table(opt_k_of_N == max(k_vals), {'Scale_ton', 'Pack_number', 'Optimal_k', 'Total_pathway_value_billion_USD', 'Net_value_after_recertification_cost_billion_USD'}));
% else
%     fprintf('PASS: No market-scale scenario is stuck at the upper k-grid boundary.\n');
%     fprintf('The current k-grid is sufficient for this exploratory run.\n');
% end
% 
% fprintf('\n================ Part5 Exp01b market-scale result-only test completed ================\n');
