%% P5_Exp03_NMC_error_scaling_scale_robustness.m
% Purpose:
% This script evaluates the robustness of the scale-dependent NMC
% recertification optimization under different prediction-error scaling
% factors.
%
% For each rho_NMC value, the script re-optimizes k*, T1*, and T2* across
% deployment scales and reports label density, action allocation,
% prediction-error metrics, decision-loss decomposition, and per-pack cost.

clear; clc; close all;

set(groot, 'DefaultFigureVisible', 'on');

%% 0. Path configuration
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
 script_dir = pwd;
end

% Project root folder.
cfg.project_root = fileparts(script_dir);

% Part5 folders.
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.main_fig_dir = fullfile(cfg.figure_root, 'Main');

cfg.function_dir = fullfile(script_dir, 'Function');

% Part4 fixed-scale output folder.
cfg.part4_dir = fullfile(cfg.project_root, 'Part4_Economic optimization under fixed scale');

cfg.part4_output_dir = fullfile(cfg.part4_dir, 'Output');
cfg.part4_results_dir = fullfile(cfg.part4_output_dir, 'Results');

% Primary fixed-scale NMC workspace generated by Part4 Exp02.
cfg.fixed_file_primary = fullfile(cfg.part4_results_dir, 'P4_Exp02_FixedScale_NMC_Workspace.mat');

% Legacy fallback path for the previous fixed-scale NMC workspace name.
cfg.fixed_file_legacy = fullfile(cfg.part4_output_dir, 'Result02_FixedScale_NMC_Workspace.mat');

% Primary fixed-scale LFP workspace used as a fallback source for LFP-derived residual-error variables.
cfg.lfp_residual_file_primary = fullfile(cfg.part4_results_dir, 'P4_Exp01_FixedScale_LFP_Workspace.mat');

% Legacy fallback path for the previous fixed-scale LFP workspace name.
cfg.lfp_residual_file_legacy = fullfile(cfg.part4_output_dir, ...
 'Result01_FixedScale_LFP_Workspace.mat');

% Primary scale-dependent NMC result generated by Part5 Exp02.
cfg.scale_file_primary = fullfile(cfg.results_dir, 'P5_Exp02_ScaleDependent_NMC_Results.mat');

% Legacy fallback path for the previous NMC scale-effect result name.
cfg.scale_file_legacy = fullfile(cfg.output_dir, 'Result02_ScaleEffect_NMC_Results.mat');

% Output files generated by Part5 Exp03.
cfg.full_csv = fullfile(cfg.results_dir, 'P5_Exp03_NMC_ErrorScaling_ScaleRobustness_Full.csv');
cfg.representative_csv = fullfile(cfg.results_dir, 'P5_Exp03_NMC_ErrorScaling_ScaleRobustness_Representative.csv');
cfg.result_mat = fullfile(cfg.results_dir, 'P5_Exp03_NMC_ErrorScaling_ScaleRobustness_Results.mat');

% Figure files for Main Fig. 5d-f.
cfg.fig05d = fullfile(cfg.main_fig_dir, 'MainFig05d_NMC_kstar_under_error_scaling.fig');
cfg.png05d = fullfile(cfg.main_fig_dir, 'MainFig05d_NMC_kstar_under_error_scaling.png');

cfg.fig05e = fullfile(cfg.main_fig_dir, 'MainFig05e_NMC_label_density_under_error_scaling.fig');
cfg.png05e = fullfile(cfg.main_fig_dir, 'MainFig05e_NMC_label_density_under_error_scaling.png');

cfg.fig05f = fullfile(cfg.main_fig_dir, 'MainFig05f_NMC_per_pack_cost_under_error_scaling.fig');
cfg.png05f = fullfile(cfg.main_fig_dir, 'MainFig05f_NMC_per_pack_cost_under_error_scaling.png');

cfg.png_resolution = 600;

% Create required folders.
folder_list = { ...
 cfg.output_dir, ...
 cfg.results_dir, ...
 cfg.figure_root, ...
 cfg.main_fig_dir, ...
 cfg.function_dir};

for ii = 1:numel(folder_list)

 if ~exist(folder_list{ii}, 'dir')
 mkdir(folder_list{ii});
 end
end

% Add local function folder if available.
if exist(cfg.function_dir, 'dir')
 addpath(cfg.function_dir);
end

% Use the shared residual generator that is synchronized with Part3 Exp03
% and the Part5 Exp01-Exp02 implementations.
if exist('local_build_noise_by_k', 'file') ~= 2
 error('Shared function local_build_noise_by_k.m was not found in: %s', ...
 cfg.function_dir);
end

% Locate the fixed-scale NMC workspace.
if isfile(cfg.fixed_file_primary)
 cfg.fixed_file = cfg.fixed_file_primary;
elseif isfile(cfg.fixed_file_legacy)
 cfg.fixed_file = cfg.fixed_file_legacy;
else
 error(['Fixed-scale NMC workspace not found.\n' ...
 'Checked:\n%s\n%s\n' ...
 'Please run Part4 Exp02 first.'], ...
 cfg.fixed_file_primary, ...
 cfg.fixed_file_legacy);
end

% Locate the fixed-scale LFP residual workspace.
if isfile(cfg.lfp_residual_file_primary)
 cfg.lfp_residual_file = cfg.lfp_residual_file_primary;
elseif isfile(cfg.lfp_residual_file_legacy)
 cfg.lfp_residual_file = cfg.lfp_residual_file_legacy;
else
 cfg.lfp_residual_file = '';
end

% Locate the scale-dependent NMC result.
if isfile(cfg.scale_file_primary)
 cfg.scale_file = cfg.scale_file_primary;
elseif isfile(cfg.scale_file_legacy)
 cfg.scale_file = cfg.scale_file_legacy;
else

 error(['Scale-dependent NMC result file not found.\n' ...
 'Checked:\n%s\n%s\n' ...
 'Please run Part5 Exp02 first.'], ...
 cfg.scale_file_primary, ...
 cfg.scale_file_legacy);
end

fprintf('================ Part5 Exp03 NMC error-scaling scale robustness ================\n');
fprintf('Fixed-scale NMC workspace: %s\n', cfg.fixed_file);
fprintf('Fixed-scale LFP workspace: %s\n', cfg.lfp_residual_file);
fprintf('Scale-dependent NMC file: %s\n', cfg.scale_file);
fprintf('Full CSV file: %s\n', cfg.full_csv);
fprintf('Representative CSV file: %s\n', cfg.representative_csv);
fprintf('Result MAT file: %s\n', cfg.result_mat);
fprintf('Main figure folder: %s\n', cfg.main_fig_dir);

%% 1. Load NMC fixed-scale workspace for basic TEA inputs

fixed_file = cfg.fixed_file;

if ~isfile(fixed_file)
 error(['Fixed-scale NMC workspace not found:\n%s\n' ...
 'Please run Part4 Exp02 first.'], fixed_file);
end

vars_in_file = who('-file', fixed_file);

safe_var_list = { ...
 'k_vals', ...
 's_true', ...
 'Eta_1', ...
 'Eta_2', ...
 'Lambda_A', ...
 'Lambda_R', ...
 'c_pack', ...
 'c_train', ...
 'k_emp', ...
 'k_anchor', ...
 'k_bridge_end', ...
 'err_cell', ...
 'w_curve', ...
 'muM_curve', ...
 'sigM_curve', ...
 'muR_curve', ...
 'sigR_curve', ...
 'rmse_target', ...
 'base_u', ...
 'base_z', ...
 'base_pick', ...
 'base_bridge', ...
 'calc_V_reuse_base', ...
 'calc_V_recycle', ...
 'C_A1_extra', ...
 'C_A2_extra', ...
 'beta_refurbish', ...
 'C0', ...
 'C1', ...
 'gamma'};

vars_to_load = intersect(safe_var_list, vars_in_file, 'stable');

S = load(fixed_file, vars_to_load{:});

% Remove any figure that may have been restored from the MAT file.
close all hidden force;

% If the NMC workspace does not contain the full k-dependent residual-error
% model, load the residual-error variables from the LFP fixed-scale workspace.
residual_vars = { ...
 'k_vals', 'k_emp', 'k_anchor', 'k_bridge_end', 'err_cell', ...
 'w_curve', 'muM_curve', 'sigM_curve', ...
 'muR_curve', 'sigR_curve', 'rmse_target', ...
 'base_u', 'base_z', 'base_pick', 'base_bridge'};

missing_residual_vars = {};
for ii = 1:numel(residual_vars)
 if ~isfield(S, residual_vars{ii})
 missing_residual_vars{end+1, 1} = residual_vars{ii}; %#ok<SAGROW>
 end
end

if ~isempty(missing_residual_vars)
 if ~isfile(cfg.lfp_residual_file)
 error(['Residual-error variables are missing from the NMC workspace, ' ...
 'and the LFP residual workspace was not found:\n%s'], ...
 cfg.lfp_residual_file);
 end

 S_res = load(cfg.lfp_residual_file, residual_vars{:});

 for ii = 1:numel(residual_vars)
 var_now = residual_vars{ii};
 if ~isfield(S, var_now) && isfield(S_res, var_now)
 S.(var_now) = S_res.(var_now);
 end
 end

 fprintf('>>> Missing residual-error variables were loaded from: %s\n', ...
 cfg.lfp_residual_file);
end

required_vars = { ...
 'k_vals', ...
 's_true', ...
 'Eta_1', 'Eta_2', 'Lambda_A', 'Lambda_R', ...
 'c_pack', 'c_train', ...
 'k_emp', 'k_anchor', 'k_bridge_end', 'err_cell', ...
 'w_curve', 'muM_curve', 'sigM_curve', ...
 'muR_curve', 'sigR_curve', 'rmse_target', ...
 'base_u', 'base_z', 'base_pick', 'base_bridge', ...
 'calc_V_reuse_base', 'calc_V_recycle'};

for i = 1:numel(required_vars)
 if ~isfield(S, required_vars{i})
 error('Variable missing in file %s: %s', fixed_file, required_vars{i});
 end
end

k_vals = S.k_vals(:);
s_true = S.s_true(:);

Eta_1 = S.Eta_1;
Eta_2 = S.Eta_2;
Lambda_A = S.Lambda_A;
Lambda_R = S.Lambda_R;

c_pack = S.c_pack;
c_train = S.c_train;

calc_V_reuse_base = S.calc_V_reuse_base;
calc_V_recycle = S.calc_V_recycle;

if isfield(S, 'C_A1_extra')
 C_A1_extra = S.C_A1_extra;
else
 C_A1_extra = 10;
end

if isfield(S, 'C_A2_extra')
 C_A2_extra = S.C_A2_extra;
else
 C_A2_extra = 15;
end

if isfield(S, 'beta_refurbish')
 beta_refurbish = S.beta_refurbish;
else
 beta_refurbish = 0.09;
end

if isfield(S, 'C0')
 C0 = S.C0;
else
 C0 = 43;
end

if isfield(S, 'C1')
 C1 = S.C1;
else
 C1 = 80;
end

if isfield(S, 'gamma')
 gamma = S.gamma;
else
 gamma = 3;
end

calc_C_refurbish = @(soh) C0 + C1 .* (1 - soh).^gamma;

calc_V_reuse = @(soh) calc_V_reuse_base(soh) - C_A1_extra;

calc_V_refurbish = @(soh) ...
 calc_V_reuse_base(min(soh + beta_refurbish .* (1 - soh), 1.0)) ...
 - calc_C_refurbish(soh) ...
 - C_A1_extra ...
 - C_A2_extra;

k_emp = S.k_emp(:);
k_anchor = S.k_anchor;
k_bridge_end = S.k_bridge_end;
err_cell = S.err_cell;

w_curve = S.w_curve(:);
muM_curve = S.muM_curve(:);
sigM_curve = S.sigM_curve(:);
muR_curve = S.muR_curve(:);
sigR_curve = S.sigR_curve(:);
rmse_target = S.rmse_target(:);

base_u = S.base_u(:);
base_z = S.base_z(:);
base_pick = S.base_pick(:);
base_bridge = S.base_bridge(:);

N_sim = numel(s_true);
num_k = numel(k_vals);

if numel(base_u) ~= N_sim || ...
 numel(base_z) ~= N_sim || ...
 numel(base_pick) ~= N_sim || ...
 numel(base_bridge) ~= N_sim
 error(['base_u, base_z, base_pick, and base_bridge must all have ' ...
 'the same length as s_true.']);
end

fprintf('>>> NMC fixed-scale workspace loaded.\n');
fprintf('>>> N_sim = %d, k = %d:%d\n', N_sim, min(k_vals), max(k_vals));
fprintf('>>> baseline c_pack = %.2f, c_train = %.2f\n', c_pack, c_train);
fprintf('>>> baseline rho_NMC = 0.8\n');

%% 2. Load NMC scale list and pack number

scale_file = cfg.scale_file;

if ~isfile(scale_file)
 error(['File not found: %s.\n' ...
 'Please run Part5 Exp02 first to generate the scale-dependent NMC result.'], scale_file);
end

S_scale = load(scale_file);

if isfield(S_scale, 'scale_ton_list')
 scale_ton_list = S_scale.scale_ton_list(:);
else
 error('scale_ton_list is missing in the Part5 Exp02 scale-dependent NMC result.');
end

if isfield(S_scale, 'N_list_NMC')
 N_list_NMC = S_scale.N_list_NMC(:);
else
 warning('N_list_NMC was not found. M_pack = 173.25 kg/pack will be used for conversion.');
 M_pack_default = 173.25;
 N_list_NMC = max(1, round(scale_ton_list * 1000 / M_pack_default));
end

if numel(N_list_NMC) ~= numel(scale_ton_list)
 error('The length of N_list_NMC is inconsistent with scale_ton_list.');
end

n_scale = numel(scale_ton_list);

fprintf('>>> NMC scale list loaded with %d scale points.\n', n_scale);

%% 3. Define rho_NMC scenarios: six curves

rho_list = [0.4; 0.6; 0.8; 1.0; 1.2; 1.4];

rho_label = { ...
 'rho = 0.4'; ...
 'rho = 0.6'; ...
 'rho = 0.8 baseline'; ...
 'rho = 1.0'; ...
 'rho = 1.2'; ...
 'rho = 1.4'};

n_rho = numel(rho_list);

%% 4. Threshold search grids

T1_grid = 0.74 : 0.005 : 0.82;
T2_grid = 0.94 : 0.005 : 1.00;

num_T1 = numel(T1_grid);
num_T2 = numel(T2_grid);

fprintf('>>> T1 grid: %.3f to %.3f, %d points.\n', min(T1_grid), max(T1_grid), num_T1);
fprintf('>>> T2 grid: %.3f to %.3f, %d points.\n', min(T2_grid), max(T2_grid), num_T2);

%% 5. Calculate true action values

Pi_True = [ ...
 calc_V_reuse(s_true), ...
 calc_V_refurbish(s_true), ...
 calc_V_recycle(s_true)];

[Pi_True_Max, True_Action_i] = max(Pi_True, [], 2);

True_A1_share = mean(True_Action_i == 1);
True_A2_share = mean(True_Action_i == 2);
True_A3_share = mean(True_Action_i == 3);

fprintf('>>> True action shares: A1=%.4f, A2=%.4f, A3=%.4f\n', ...
 True_A1_share, True_A2_share, True_A3_share);


%% 6. Preallocate the rho-k per-pack decision-loss landscape

EL_byRho_K = zeros(n_rho, num_k);
O_byRho_K_perpack = zeros(n_rho, num_k);
A_byRho_K_perpack = zeros(n_rho, num_k);
R_byRho_K_perpack = zeros(n_rho, num_k);

T1_byRho_K = zeros(n_rho, num_k);
T2_byRho_K = zeros(n_rho, num_k);

A1share_byRho_K = zeros(n_rho, num_k);
A2share_byRho_K = zeros(n_rho, num_k);
A3share_byRho_K = zeros(n_rho, num_k);

RMSE_byRho_K = zeros(n_rho, num_k);
MAE_byRho_K = zeros(n_rho, num_k);

%% 7. Re-optimize T1/T2 for each rho and k

fprintf('\n>>> Start NMC scale-dependent error-scaling robustness calculation.\n');

for rr = 1:n_rho

 rho_now = rho_list(rr);

 fprintf('\n>>> rho_NMC = %.2f\n', rho_now);

 for kk = 1:num_k

 k_current = k_vals(kk);

 if mod(kk, 10) == 1 || kk == num_k
 fprintf(' > Processing k = %d (%d/%d)\n', k_current, kk, num_k);
 end

 base_noise = local_build_noise_by_k( ...
 k_current, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, ...
 muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

 eps_k = base_noise - mean(base_noise);

 sampled_noise = rho_now .* eps_k;

 s_pred = min(max(s_true + sampled_noise, 0), 1.0);

 RMSE_byRho_K(rr, kk) = sqrt(mean((s_pred - s_true).^2));
 MAE_byRho_K(rr, kk) = mean(abs(s_pred - s_true));

 min_L = inf;
 best_T1 = NaN;
 best_T2 = NaN;
 best_O_mean = NaN;
 best_A_mean = NaN;
 best_R_mean = NaN;
 best_ratio = [NaN, NaN, NaN];

 for T1 = T1_grid
 for T2 = T2_grid

 if T1 >= T2
 continue;
 end

 Pred_Action_j = 3 * ones(N_sim, 1);
 Pred_Action_j(s_pred >= T1 & s_pred < T2) = 2;
 Pred_Action_j(s_pred >= T2) = 1;

 idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_j);
 O_arr = max(Pi_True_Max - Pi_True(idx_pred), 0);

 is_G1_error = (True_Action_i == 3 & Pred_Action_j == 2) | ...
 (True_Action_i == 2 & Pred_Action_j == 3);

 is_G2_error = (True_Action_i == 1 & Pred_Action_j == 2) | ...
 (True_Action_i == 2 & Pred_Action_j == 1);

 Current_Eta = zeros(N_sim, 1);
 Current_Eta(is_G1_error) = Eta_1;
 Current_Eta(is_G2_error) = Eta_2;

 trigger_penalty = O_arr > Current_Eta;
 Excess_Loss = max(0, O_arr - Current_Eta);

 A_arr = trigger_penalty .* Lambda_A;
 R_arr = (Pred_Action_j < True_Action_i) .* trigger_penalty .* ...
 (Lambda_R .* Excess_Loss);

 E_L = mean(O_arr + A_arr + R_arr);

 if E_L < min_L
 min_L = E_L;
 best_T1 = T1;
 best_T2 = T2;

 best_O_mean = mean(O_arr);
 best_A_mean = mean(A_arr);
 best_R_mean = mean(R_arr);

 best_ratio(1) = mean(Pred_Action_j == 1);
 best_ratio(2) = mean(Pred_Action_j == 2);
 best_ratio(3) = mean(Pred_Action_j == 3);
 end
 end
 end

 EL_byRho_K(rr, kk) = min_L;
 O_byRho_K_perpack(rr, kk) = best_O_mean;
 A_byRho_K_perpack(rr, kk) = best_A_mean;
 R_byRho_K_perpack(rr, kk) = best_R_mean;

 T1_byRho_K(rr, kk) = best_T1;
 T2_byRho_K(rr, kk) = best_T2;

 A1share_byRho_K(rr, kk) = best_ratio(1);
 A2share_byRho_K(rr, kk) = best_ratio(2);
 A3share_byRho_K(rr, kk) = best_ratio(3);
 end
end

fprintf('\n>>> rho-k decision landscape calculation completed.\n');

%% 8. Map to different scales: reselect k* under each rho

opt_k = zeros(n_scale, n_rho);
opt_k_idx = zeros(n_scale, n_rho);

opt_T1 = zeros(n_scale, n_rho);
opt_T2 = zeros(n_scale, n_rho);

opt_A1_share = zeros(n_scale, n_rho);
opt_A2_share = zeros(n_scale, n_rho);
opt_A3_share = zeros(n_scale, n_rho);

opt_decision_cost_USD = zeros(n_scale, n_rho);
opt_information_cost_USD = zeros(n_scale, n_rho);
opt_total_cost_USD = zeros(n_scale, n_rho);
opt_cost_per_pack_USD = zeros(n_scale, n_rho);
opt_label_density_per_ton = zeros(n_scale, n_rho);

opt_RMSE = zeros(n_scale, n_rho);
opt_MAE = zeros(n_scale, n_rho);

TotalCost_byScaleRho_K = cell(n_rho, 1);

for rr = 1:n_rho

 TotalCost_NK = zeros(n_scale, num_k);

 for nn = 1:n_scale

 N_now = N_list_NMC(nn);

 Information_cost_byK = k_vals(:)' .* c_pack + c_train;

 TotalCost_NK(nn, :) = N_now .* EL_byRho_K(rr, :) + Information_cost_byK;

 [min_cost, idx_k] = min(TotalCost_NK(nn, :));

 opt_k_idx(nn, rr) = idx_k;
 opt_k(nn, rr) = k_vals(idx_k);

 opt_T1(nn, rr) = T1_byRho_K(rr, idx_k);
 opt_T2(nn, rr) = T2_byRho_K(rr, idx_k);

 opt_A1_share(nn, rr) = A1share_byRho_K(rr, idx_k);
 opt_A2_share(nn, rr) = A2share_byRho_K(rr, idx_k);
 opt_A3_share(nn, rr) = A3share_byRho_K(rr, idx_k);

 opt_decision_cost_USD(nn, rr) = N_now .* EL_byRho_K(rr, idx_k);
 opt_information_cost_USD(nn, rr) = Information_cost_byK(idx_k);
 opt_total_cost_USD(nn, rr) = min_cost;
 opt_cost_per_pack_USD(nn, rr) = min_cost ./ N_now;
 opt_label_density_per_ton(nn, rr) = k_vals(idx_k) ./ scale_ton_list(nn);

 opt_RMSE(nn, rr) = RMSE_byRho_K(rr, idx_k);
 opt_MAE(nn, rr) = MAE_byRho_K(rr, idx_k);
 end

 TotalCost_byScaleRho_K{rr} = TotalCost_NK;
end

%% 9. Generate full table

rows = n_scale * n_rho;

Scale_ton_col = zeros(rows,1);
Pack_number_col = zeros(rows,1);
rho_col = zeros(rows,1);
rho_label_col = cell(rows,1);

k_star_col = zeros(rows,1);
T1_star_col = zeros(rows,1);
T2_star_col = zeros(rows,1);

A1_share_col = zeros(rows,1);
A2_share_col = zeros(rows,1);
A3_share_col = zeros(rows,1);

Label_density_col = zeros(rows,1);

RMSE_col = zeros(rows,1);
MAE_col = zeros(rows,1);

Decision_cost_col = zeros(rows,1);
Information_cost_col = zeros(rows,1);
Total_cost_col = zeros(rows,1);
Cost_per_pack_col = zeros(rows,1);

ridx = 0;

for rr = 1:n_rho
 for nn = 1:n_scale
 ridx = ridx + 1;

 Scale_ton_col(ridx) = scale_ton_list(nn);
 Pack_number_col(ridx) = N_list_NMC(nn);
 rho_col(ridx) = rho_list(rr);
 rho_label_col{ridx} = rho_label{rr};

 k_star_col(ridx) = opt_k(nn, rr);
 T1_star_col(ridx) = opt_T1(nn, rr);
 T2_star_col(ridx) = opt_T2(nn, rr);

 A1_share_col(ridx) = opt_A1_share(nn, rr);
 A2_share_col(ridx) = opt_A2_share(nn, rr);
 A3_share_col(ridx) = opt_A3_share(nn, rr);

 Label_density_col(ridx) = opt_label_density_per_ton(nn, rr);

 RMSE_col(ridx) = opt_RMSE(nn, rr);
 MAE_col(ridx) = opt_MAE(nn, rr);

 Decision_cost_col(ridx) = opt_decision_cost_USD(nn, rr);
 Information_cost_col(ridx) = opt_information_cost_USD(nn, rr);
 Total_cost_col(ridx) = opt_total_cost_USD(nn, rr);
 Cost_per_pack_col(ridx) = opt_cost_per_pack_USD(nn, rr);
 end
end

Result_Table = table( ...
 Scale_ton_col, ...
 Pack_number_col, ...
 rho_col, ...
 rho_label_col, ...
 RMSE_col, ...
 MAE_col, ...
 k_star_col, ...
 T1_star_col, ...
 T2_star_col, ...
 A1_share_col, ...
 A2_share_col, ...
 A3_share_col, ...
 Label_density_col, ...
 Decision_cost_col, ...
 Information_cost_col, ...
 Total_cost_col, ...
 Cost_per_pack_col, ...
 'VariableNames', { ...
 'Scale_ton', ...
 'Pack_number', ...
 'rho_NMC', ...
 'rho_label', ...
 'RMSE', ...
 'MAE', ...
 'k_star', ...
 'T1_star', ...
 'T2_star', ...
 'A1_share', ...
 'A2_share', ...
 'A3_share', ...
 'Label_density_k_per_ton', ...
 'Decision_cost_USD', ...
 'Information_cost_USD', ...
 'Total_cost_USD', ...
 'Total_cost_per_pack_USD'});

disp(' ');
disp('========== NMC scale error-scaling robustness summary preview ==========');
disp(Result_Table(1:min(12,height(Result_Table)), :));

writetable(Result_Table, cfg.full_csv);

%% 10. Save representative-scale table
rep_scale_target = [10; 50; 100; 200; 500; 900; 2000];

rep_idx = zeros(numel(rep_scale_target),1);

for ii = 1:numel(rep_scale_target)
 [~, rep_idx(ii)] = min(abs(scale_ton_list - rep_scale_target(ii)));
end

rep_scale_actual = scale_ton_list(rep_idx);
is_rep = ismember(Result_Table.Scale_ton, rep_scale_actual);

Representative_Table = Result_Table(is_rep, :);

writetable(Representative_Table, cfg.representative_csv);

%% 11. Plot figures: display figure windows only

% Plot appearance settings.
line_alpha = 0.75; % Visual line transparency: 0 = very light, 1 = original color
marker_face_alpha = 0.55; % Marker face transparency
marker_edge_alpha = 0.85; % Marker edge transparency

line_width = 2.0;
marker_size = 42;

% Y-axis limit for Figure 1.
ylim_fig01_kstar = [4, 28];

marker_list = {'o','s','^','d','v','p','h'};
color_list = lines(n_rho);

legend_text = cell(n_rho,1);
for rr = 1:n_rho
 if abs(rho_list(rr) - 0.8) < 1e-12
 legend_text{rr} = sprintf('\\rho = %.1f baseline', rho_list(rr));
 else
 legend_text{rr} = sprintf('\\rho = %.1f', rho_list(rr));
 end
end
% Blend line colors with white to emulate line transparency.
line_color_list = color_list .* line_alpha + ...
 (1 - line_alpha) .* ones(size(color_list));


% Figure 1: scale vs k*
figure('Name', 'Main Fig. 5d - NMC k* under error scaling', ...
 'Color', 'w', 'Position', [100, 80, 760, 560]);

hold on;

h_leg = gobjects(n_rho, 1);

for rr = 1:n_rho

 % Plot line with adjustable visual transparency.
 plot(scale_ton_list, opt_k(:,rr), ...
 'LineStyle', '-', ...
 'Color', line_color_list(rr,:), ...
 'LineWidth', line_width, ...
 'HandleVisibility', 'off');

 % Plot markers with true alpha control.
 scatter(scale_ton_list, opt_k(:,rr), marker_size, ...
 'Marker', marker_list{rr}, ...
 'MarkerFaceColor', color_list(rr,:), ...
 'MarkerEdgeColor', color_list(rr,:), ...
 'MarkerFaceAlpha', marker_face_alpha, ...
 'MarkerEdgeAlpha', marker_edge_alpha, ...
 'LineWidth', 1.0, ...
 'HandleVisibility', 'off');

 % Dummy handle for legend.
 h_leg(rr) = plot(nan, nan, ...
 'LineStyle', '-', ...
 'Marker', marker_list{rr}, ...
 'Color', color_list(rr,:), ...
 'LineWidth', line_width, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w', ...
 'MarkerEdgeColor', color_list(rr,:));
end


grid on; box on;
set(gca, 'XScale', 'log');
ylim(ylim_fig01_kstar);

xlabel('Battery scale (ton)');
ylabel('Optimal label size, k^*');
title('NMC scale-dependent label investment under prediction-error scaling');

legend(h_leg, legend_text, 'Location', 'northwest', 'Box', 'off');

set(gca, 'FontName', 'Arial', 'FontSize', 12);
local_save_figure(gcf, cfg.fig05d, cfg.png05d, cfg.png_resolution);
fprintf('Saved Main Fig. 5d: %s\n', cfg.png05d);


% Figure 2: scale vs label density
figure('Name', 'Main Fig. 5e - NMC label density under error scaling', ...
 'Color', 'w', 'Position', [140, 100, 760, 560]);

hold on;

h_leg = gobjects(n_rho, 1);

for rr = 1:n_rho

 % Plot line with adjustable visual transparency.
 plot(scale_ton_list, opt_label_density_per_ton(:,rr), ...
 'LineStyle', '-', ...
 'Color', line_color_list(rr,:), ...
 'LineWidth', line_width, ...
 'HandleVisibility', 'off');

 % Plot markers with true alpha control.
 scatter(scale_ton_list, opt_label_density_per_ton(:,rr), marker_size, ...
 'Marker', marker_list{rr}, ...
 'MarkerFaceColor', color_list(rr,:), ...
 'MarkerEdgeColor', color_list(rr,:), ...
 'MarkerFaceAlpha', marker_face_alpha, ...
 'MarkerEdgeAlpha', marker_edge_alpha, ...
 'LineWidth', 1.0, ...
 'HandleVisibility', 'off');

 % Dummy handle for legend.
 h_leg(rr) = plot(nan, nan, ...
 'LineStyle', '-', ...
 'Marker', marker_list{rr}, ...
 'Color', color_list(rr,:), ...
 'LineWidth', line_width, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w', ...
 'MarkerEdgeColor', color_list(rr,:));
end

grid on; box on;
set(gca, 'XScale', 'log');
xlabel('Battery scale (ton)');
ylabel('Label density, k^* per ton');
title('NMC scale-dependent SOH-labeling density under prediction-error scaling');
legend(h_leg, legend_text, 'Location', 'northeast', 'Box', 'off');
set(gca, 'FontName', 'Arial', 'FontSize', 12);
local_save_figure(gcf, cfg.fig05e, cfg.png05e, cfg.png_resolution);
fprintf('Saved Main Fig. 5e: %s\n', cfg.png05e);


% Figure 3: scale vs per-pack cost
figure('Name', 'Main Fig. 5f - NMC per-pack cost under error scaling', ...
 'Color', 'w', 'Position', [180, 120, 760, 560]);

hold on;

h_leg = gobjects(n_rho, 1);

for rr = 1:n_rho

 % Plot line with adjustable visual transparency.
 plot(scale_ton_list, opt_cost_per_pack_USD(:,rr), ...
 'LineStyle', '-', ...
 'Color', line_color_list(rr,:), ...
 'LineWidth', line_width, ...
 'HandleVisibility', 'off');

 % Plot markers with true alpha control.
 scatter(scale_ton_list, opt_cost_per_pack_USD(:,rr), marker_size, ...
 'Marker', marker_list{rr}, ...
 'MarkerFaceColor', color_list(rr,:), ...
 'MarkerEdgeColor', color_list(rr,:), ...
 'MarkerFaceAlpha', marker_face_alpha, ...
 'MarkerEdgeAlpha', marker_edge_alpha, ...
 'LineWidth', 1.0, ...
 'HandleVisibility', 'off');

 % Dummy handle for legend.
 h_leg(rr) = plot(nan, nan, ...
 'LineStyle', '-', ...
 'Marker', marker_list{rr}, ...
 'Color', color_list(rr,:), ...
 'LineWidth', line_width, ...
 'MarkerSize', 6, ...
 'MarkerFaceColor', 'w', ...
 'MarkerEdgeColor', color_list(rr,:));
end

grid on; box on;
set(gca, 'XScale', 'log');
xlabel('Battery scale (ton)');
ylabel('Total cost (USD per pack)');
title('NMC scale-dependent per-pack cost under prediction-error scaling');
legend(h_leg, legend_text, 'Location', 'northeast', 'Box', 'off');
set(gca, 'FontName', 'Arial', 'FontSize', 12);
local_save_figure(gcf, cfg.fig05f, cfg.png05f, cfg.png_resolution);
fprintf('Saved Main Fig. 5f: %s\n', cfg.png05f);

drawnow;

%% 12. Save MAT file
save(cfg.result_mat, ...
 'rho_list', ...
 'rho_label', ...
 'Result_Table', ...
 'Representative_Table', ...
 'scale_ton_list', ...
 'N_list_NMC', ...
 'k_vals', ...
 'EL_byRho_K', ...
 'O_byRho_K_perpack', ...
 'A_byRho_K_perpack', ...
 'R_byRho_K_perpack', ...
 'T1_byRho_K', ...
 'T2_byRho_K', ...
 'A1share_byRho_K', ...
 'A2share_byRho_K', ...
 'A3share_byRho_K', ...
 'RMSE_byRho_K', ...
 'MAE_byRho_K', ...
 'opt_k', ...
 'opt_k_idx', ...
 'opt_T1', ...
 'opt_T2', ...
 'opt_A1_share', ...
 'opt_A2_share', ...
 'opt_A3_share', ...
 'opt_decision_cost_USD', ...
 'opt_information_cost_USD', ...
 'opt_total_cost_USD', ...
 'opt_cost_per_pack_USD', ...
 'opt_label_density_per_ton', ...
 'opt_RMSE', ...
 'opt_MAE', ...
 'TotalCost_byScaleRho_K', ...
 'True_A1_share', ...
 'True_A2_share', ...
 'True_A3_share', ...
 'Eta_1', ...
 'Eta_2', ...
 'Lambda_A', ...
 'Lambda_R', ...
 'c_pack', ...
 'c_train', ...
 '-v7.3');

fprintf('\n>>> Part5 Exp03 NMC error-scaling scale robustness completed.\n');
fprintf('>>> Full table saved: %s\n', cfg.full_csv);
fprintf('>>> Representative table saved: %s\n', cfg.representative_csv);
fprintf('>>> MAT file saved: %s\n', cfg.result_mat);
fprintf('>>> Main figures saved in: %s\n', cfg.main_fig_dir);


%% Local functions

function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
 mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end
