%% P5_Exp07_LFP_MarketScale_Extension.m
% Purpose:
% This script extends the Part5 Exp01 LFP market-scale analysis to
% exploratory throughputs from 5,000 to 500,000 tons.
%
% The established k = 5-50 results from Part5 Exp01 are retained exactly.
% The script extends only k = 51-2000 by evaluating the fitted Part3
% residual-error equations beyond k = 50, using the same Monte Carlo
% population and common random numbers saved by Part5 Exp01.
%
% For each new k, T1 and T2 are re-optimized on a 0.005 threshold grid.
% The existing and newly evaluated k-dependent results are then combined,
% and the market-scale optimum is selected over k = 5-2000.

clear;
clc;
close all;

format compact;
format shortG;

%% 0) Path configuration
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

cfg.project_root = fileparts(script_dir);

cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');
cfg.function_dir = fullfile(script_dir, 'Function');

cfg.lfp_result_primary = fullfile(cfg.results_dir, ...
    'P5_Exp01_ScaleDependent_LFP_Results.mat');

cfg.lfp_result_legacy = fullfile(cfg.output_dir, ...
    'Result01_ScaleEffect_LFP_Results.mat');

cfg.lfp_workspace = fullfile(cfg.results_dir, ...
    'P5_Exp01_ScaleDependent_LFP_Workspace.mat');

cfg.residual_model = fullfile(cfg.project_root, ...
    'Part3_Prediction error extrapolation', ...
    'Output', 'Results', ...
    'P3_Exp03_ResidualExtrapolation_Model.mat');

cfg.market_scale_csv = fullfile(cfg.results_dir, ...
    'P5_Exp07_LFP_MarketScale_Extension_Table.csv');

cfg.cost_breakdown_csv = fullfile(cfg.results_dir, ...
    'P5_Exp07_LFP_MarketScale_CostBreakdown.csv');

cfg.market_only_csv = fullfile(cfg.results_dir, ...
    'P5_Exp07_LFP_MarketScale_OnlyRows.csv');

cfg.extra_k_csv = fullfile(cfg.results_dir, ...
    'P5_Exp07_LFP_K51_K2000_Extension.csv');

cfg.result_mat = fullfile(cfg.results_dir, ...
    'P5_Exp07_LFP_MarketScale_Extension_Results.mat');

% Established and extended k ranges.
cfg.base_k_max = 50;
cfg.extended_k_max = 2000;

% The new k = 51-2000 threshold searches use this resolution.
cfg.threshold_step = 0.005;

% Exploratory market-throughput scenarios.
cfg.scale_ton_list = [ ...
    5000; 10000; 20000; 50000; ...
    100000; 200000; 300000; 500000];

% LFP pack mass used in Part5 Exp01.
cfg.M_pack_kg = 173.25;

cfg.accounting_tolerance_abs_USD = 1e-5;
cfg.accounting_tolerance_rel = 1e-10;
cfg.parameter_continuity_tolerance = 1e-8;

if ~exist(cfg.results_dir, 'dir')
    mkdir(cfg.results_dir);
end

if exist(cfg.function_dir, 'dir')
    addpath(cfg.function_dir);
end

if exist('local_build_noise_by_k', 'file') ~= 2
    error('Function local_build_noise_by_k.m was not found in: %s', ...
        cfg.function_dir);
end

if isfile(cfg.lfp_result_primary)
    cfg.input_file = cfg.lfp_result_primary;
elseif isfile(cfg.lfp_result_legacy)
    cfg.input_file = cfg.lfp_result_legacy;
else
    error(['Part5 Exp01 LFP result was not found.\nChecked:\n%s\n%s\n' ...
        'Run Part5 Exp01 before running Exp07.'], ...
        cfg.lfp_result_primary, cfg.lfp_result_legacy);
end

if ~isfile(cfg.lfp_workspace)
    error(['Part5 Exp01 workspace was not found:\n%s\n' ...
        'Run Part5 Exp01 before running the k extension.'], ...
        cfg.lfp_workspace);
end

if ~isfile(cfg.residual_model)
    error(['Part3 residual-error model was not found:\n%s\n' ...
        'Run Part3 Exp03 before running the k extension.'], ...
        cfg.residual_model);
end

fprintf('================ Part5 Exp07 LFP market-scale k extension ================\n');
fprintf('Input Part5 Exp01 result: %s\n', cfg.input_file);
fprintf('Input Part5 Exp01 workspace: %s\n', cfg.lfp_workspace);
fprintf('Input Part3 residual model: %s\n', cfg.residual_model);
fprintf('New k range: %d to %d\n', cfg.base_k_max + 1, cfg.extended_k_max);
fprintf('New threshold-grid step: %.4f\n', cfg.threshold_step);
fprintf('Market-scale table: %s\n', cfg.market_scale_csv);
fprintf('Result MAT: %s\n', cfg.result_mat);

%% 1) Load and validate the established k = 5-50 results
S = load(cfg.input_file);
R = S;

field_names = fieldnames(S);

for ii = 1:numel(field_names)
    field_now = field_names{ii};

    if isstruct(S.(field_now)) && ...
            isfield(S.(field_now), 'k_vals') && ...
            isfield(S.(field_now), 'O_base')
        R = S.(field_now);
        fprintf('Using result structure: %s\n', field_now);
        break;
    end
end

required_fields = { ...
    'k_vals', ...
    'O_base', ...
    'A_base', ...
    'R_base', ...
    'T1_base', ...
    'T2_base', ...
    'Pred_Action_Ratio_byK', ...
    'A1_value_perpack_byK', ...
    'A2_value_perpack_byK', ...
    'A3_value_perpack_byK', ...
    'Model_Cost_NK', ...
    'rmse_target', ...
    'w_curve', ...
    'muM_curve', ...
    'sigM_curve', ...
    'muR_curve', ...
    'sigR_curve', ...
    'k_emp', ...
    'k_anchor', ...
    'k_bridge_end'};

for ii = 1:numel(required_fields)
    field_now = required_fields{ii};

    if ~isfield(R, field_now)
        error('Required Part5 Exp01 field is missing: %s', field_now);
    end
end

k_vals_base = double(R.k_vals(:));
O_base_existing = double(R.O_base(:));
A_base_existing = double(R.A_base(:));
R_base_existing = double(R.R_base(:));

T1_base_existing = double(R.T1_base(:));
T2_base_existing = double(R.T2_base(:));

Pred_Action_Ratio_existing = double(R.Pred_Action_Ratio_byK);
A1_value_existing = double(R.A1_value_perpack_byK(:));
A2_value_existing = double(R.A2_value_perpack_byK(:));
A3_value_existing = double(R.A3_value_perpack_byK(:));

rmse_existing = double(R.rmse_target(:));
w_existing = double(R.w_curve(:));
muM_existing = double(R.muM_curve(:));
sigM_existing = double(R.sigM_curve(:));
muR_existing = double(R.muR_curve(:));
sigR_existing = double(R.sigR_curve(:));

k_emp = double(R.k_emp(:));
k_anchor = double(R.k_anchor);
k_bridge_end = double(R.k_bridge_end);

Model_Cost_NK_upstream = double(R.Model_Cost_NK);

num_k_base = numel(k_vals_base);

expected_lengths = [ ...
    numel(O_base_existing), ...
    numel(A_base_existing), ...
    numel(R_base_existing), ...
    numel(T1_base_existing), ...
    numel(T2_base_existing), ...
    numel(A1_value_existing), ...
    numel(A2_value_existing), ...
    numel(A3_value_existing), ...
    numel(rmse_existing), ...
    numel(w_existing), ...
    numel(muM_existing), ...
    numel(sigM_existing), ...
    numel(muR_existing), ...
    numel(sigR_existing)];

if any(expected_lengths ~= num_k_base)
    error('The k-dependent Part5 Exp01 arrays have inconsistent lengths.');
end

if ~isequal(size(Pred_Action_Ratio_existing), [num_k_base, 3])
    error('Pred_Action_Ratio_byK must have size [num_k, 3].');
end

if any(~isfinite(k_vals_base)) || any(diff(k_vals_base) ~= 1)
    error('The established k values must be consecutive increasing integers.');
end

if max(k_vals_base) ~= cfg.base_k_max
    error(['The established Part5 Exp01 result must end at k = %d, ' ...
        'but the loaded result ends at k = %d.'], ...
        cfg.base_k_max, max(k_vals_base));
end

if any([O_base_existing; A_base_existing; R_base_existing] < -1e-10)
    error('Per-pack decision-cost components must be non-negative.');
end

% Recover the information-cost equation from the upstream cost matrix.
if size(Model_Cost_NK_upstream, 2) == num_k_base
    model_cost_by_k = Model_Cost_NK_upstream(1, :).';
elseif size(Model_Cost_NK_upstream, 1) == num_k_base
    model_cost_by_k = Model_Cost_NK_upstream(:, 1);
else
    error('Model_Cost_NK has an unexpected shape.');
end

if num_k_base < 2
    error('At least two k values are required to recover information cost.');
end

c_pack = median(diff(model_cost_by_k) ./ diff(k_vals_base));
c_train_by_k = model_cost_by_k - k_vals_base .* c_pack;
c_train = median(c_train_by_k);

model_cost_reconstruction_error = max(abs( ...
    model_cost_by_k - (k_vals_base .* c_pack + c_train)));

if model_cost_reconstruction_error > 1e-6
    error(['The upstream information-cost curve is not linear in k. ' ...
        'Inspect Model_Cost_NK before extending the k range.']);
end

fprintf('>>> Established k range loaded: %d to %d\n', ...
    min(k_vals_base), max(k_vals_base));
fprintf('>>> Recovered c_pack = %.4f USD and c_train = %.4f USD\n', ...
    c_pack, c_train);

%% 2) Load the saved Monte Carlo population and Part3 fit parameters
workspace_vars = { ...
    's_true', ...
    'Pi_True', ...
    'Pi_True_Max', ...
    'True_Action_i', ...
    'Eta_1', ...
    'Eta_2', ...
    'Lambda_A', ...
    'Lambda_R', ...
    'base_u', ...
    'base_z', ...
    'base_pick', ...
    'base_bridge', ...
    'T1_grid', ...
    'T2_grid'};

W = load(cfg.lfp_workspace, workspace_vars{:});

for ii = 1:numel(workspace_vars)
    if ~isfield(W, workspace_vars{ii})
        error('Required workspace variable is missing: %s', ...
            workspace_vars{ii});
    end
end

s_true = double(W.s_true(:));
Pi_True = double(W.Pi_True);
Pi_True_Max = double(W.Pi_True_Max(:));
True_Action_i = double(W.True_Action_i(:));

Eta_1 = double(W.Eta_1);
Eta_2 = double(W.Eta_2);
Lambda_A = double(W.Lambda_A);
Lambda_R = double(W.Lambda_R);

base_u = double(W.base_u(:));
base_z = double(W.base_z(:));
base_pick = double(W.base_pick(:));
base_bridge = double(W.base_bridge(:));

N_sim = numel(s_true);

if ~isequal(size(Pi_True), [N_sim, 3])
    error('Pi_True must have size [N_sim, 3].');
end

if numel(Pi_True_Max) ~= N_sim || numel(True_Action_i) ~= N_sim
    error('Pi_True_Max and True_Action_i must have length N_sim.');
end

if any([numel(base_u), numel(base_z), numel(base_pick), ...
        numel(base_bridge)] ~= N_sim)
    error('The saved common-random-number arrays must have length N_sim.');
end

T1_grid_extra = local_make_grid( ...
    min(double(W.T1_grid(:))), ...
    max(double(W.T1_grid(:))), ...
    cfg.threshold_step);

T2_grid_extra = local_make_grid( ...
    min(double(W.T2_grid(:))), ...
    max(double(W.T2_grid(:))), ...
    cfg.threshold_step);

E = load(cfg.residual_model);

required_model_fields = { ...
    'cfg', ...
    'region', ...
    'k_emp', ...
    'err_cell', ...
    'a_RMSE', ...
    'b_RMSE', ...
    'c_RMSE', ...
    'bR_opt', ...
    'cR_opt', ...
    'a_muM', ...
    'A_sigR', ...
    'b_sigR', ...
    'c_sigR', ...
    'P_R_fit_input', ...
    'mu_M_fit_input', ...
    'sig_R_fit_input'};

for ii = 1:numel(required_model_fields)
    if ~isfield(E, required_model_fields{ii})
        error('Required Part3 residual-model field is missing: %s', ...
            required_model_fields{ii});
    end
end

if ~isfield(E.cfg, 'min_sig_main')
    error('Part3 model cfg.min_sig_main is missing.');
end

if isfield(E.cfg, 'w_method') && ...
        ~strcmpi(E.cfg.w_method, 'region_consistent')
    error(['This extension expects the official region-consistent ' ...
        'right-component weight method. Loaded method: %s'], ...
        E.cfg.w_method);
end

if ~isequal(double(E.k_emp(:)), k_emp)
    error('The Part3 and Part5 empirical k sets are inconsistent.');
end

k_vals_extra = ((cfg.base_k_max + 1):cfg.extended_k_max).';

% Re-evaluate the saved fitted equations at k = 50 to verify that the
% extension reproduces the final point of the established model exactly.
P_check = local_evaluate_fitted_residual_parameters( ...
    cfg.base_k_max, E, k_anchor, median(muR_existing));

idx_base_end = find(k_vals_base == cfg.base_k_max, 1);

continuity_error = max(abs([ ...
    P_check.rmse_target - rmse_existing(idx_base_end), ...
    P_check.w_curve - w_existing(idx_base_end), ...
    P_check.muM_curve - muM_existing(idx_base_end), ...
    P_check.sigM_curve - sigM_existing(idx_base_end), ...
    P_check.muR_curve - muR_existing(idx_base_end), ...
    P_check.sigR_curve - sigR_existing(idx_base_end)]));

if continuity_error > cfg.parameter_continuity_tolerance
    error(['The fitted residual equations do not reproduce the saved ' ...
        'k = %d parameters. Maximum discrepancy = %.6g.'], ...
        cfg.base_k_max, continuity_error);
end

P_extra = local_evaluate_fitted_residual_parameters( ...
    k_vals_extra, E, k_anchor, median(muR_existing));

k_vals = [k_vals_base; k_vals_extra];

rmse_target = [rmse_existing; P_extra.rmse_target];
w_curve = [w_existing; P_extra.w_curve];
muM_curve = [muM_existing; P_extra.muM_curve];
sigM_curve = [sigM_existing; P_extra.sigM_curve];
muR_curve = [muR_existing; P_extra.muR_curve];
sigR_curve = [sigR_existing; P_extra.sigR_curve];

fprintf('>>> Residual parameter continuity at k = %d: %.3e\n', ...
    cfg.base_k_max, continuity_error);
fprintf('>>> Extended residual parameters generated through k = %d\n', ...
    max(k_vals));
fprintf('>>> Extra T1 grid: %.3f to %.3f, %d points\n', ...
    min(T1_grid_extra), max(T1_grid_extra), numel(T1_grid_extra));
fprintf('>>> Extra T2 grid: %.3f to %.3f, %d points\n', ...
    min(T2_grid_extra), max(T2_grid_extra), numel(T2_grid_extra));

%% 3) Evaluate and optimize only the new k = 51-2000 cases
[O_by_action, A_by_action, R_by_action, Total_by_action] = ...
    local_build_candidate_action_costs( ...
    Pi_True, Pi_True_Max, True_Action_i, ...
    Eta_1, Eta_2, Lambda_A, Lambda_R);

num_k_extra = numel(k_vals_extra);

O_extra = zeros(num_k_extra, 1);
A_extra = zeros(num_k_extra, 1);
R_extra = zeros(num_k_extra, 1);

T1_extra = zeros(num_k_extra, 1);
T2_extra = zeros(num_k_extra, 1);

Pred_Action_Ratio_extra = zeros(num_k_extra, 3);

A1_value_extra = zeros(num_k_extra, 1);
A2_value_extra = zeros(num_k_extra, 1);
A3_value_extra = zeros(num_k_extra, 1);

Generated_RMSE_extra = zeros(num_k_extra, 1);
Generated_bias_extra = zeros(num_k_extra, 1);
Generated_std_extra = zeros(num_k_extra, 1);

fprintf('\n>>> Evaluating new k values from %d to %d...\n', ...
    min(k_vals_extra), max(k_vals_extra));

extension_timer = tic;

for ii = 1:num_k_extra
    k_current = k_vals_extra(ii);

    [sampled_noise, noise_diagnostics] = local_build_noise_by_k( ...
        k_current, ...
        k_emp, k_anchor, k_bridge_end, ...
        E.err_cell, ...
        w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, ...
        rmse_target, k_vals, ...
        base_u, base_z, base_pick, base_bridge);

    s_pred = min(max(s_true + sampled_noise, 0), 1.0);

    Q = local_optimize_thresholds_fast( ...
        s_pred, ...
        Pi_True, ...
        O_by_action, ...
        A_by_action, ...
        R_by_action, ...
        Total_by_action, ...
        T1_grid_extra, ...
        T2_grid_extra);

    O_extra(ii) = Q.O_per_pack;
    A_extra(ii) = Q.A_per_pack;
    R_extra(ii) = Q.R_per_pack;

    T1_extra(ii) = Q.T1_star;
    T2_extra(ii) = Q.T2_star;

    Pred_Action_Ratio_extra(ii, :) = Q.action_share;

    A1_value_extra(ii) = Q.A1_value_perpack;
    A2_value_extra(ii) = Q.A2_value_perpack;
    A3_value_extra(ii) = Q.A3_value_perpack;

    Generated_RMSE_extra(ii) = noise_diagnostics.generated_RMSE;
    Generated_bias_extra(ii) = noise_diagnostics.generated_bias;
    Generated_std_extra(ii) = noise_diagnostics.generated_std;

    fprintf(['[k extension] %d/%d | k = %d | T1 = %.3f, T2 = %.3f | ' ...
        'decision loss = %.6f USD/pack | generated RMSE = %.6f\n'], ...
        ii, num_k_extra, k_current, ...
        Q.T1_star, Q.T2_star, ...
        Q.O_per_pack + Q.A_per_pack + Q.R_per_pack, ...
        noise_diagnostics.generated_RMSE);
end

extension_elapsed_seconds = toc(extension_timer);

fprintf('>>> k = 51-2000 extension completed in %.2f minutes.\n', ...
    extension_elapsed_seconds / 60);

ExtraK_Table = table( ...
    k_vals_extra, ...
    P_extra.rmse_target, ...
    Generated_RMSE_extra, ...
    Generated_bias_extra, ...
    Generated_std_extra, ...
    P_extra.w_curve, ...
    P_extra.muM_curve, ...
    P_extra.sigM_curve, ...
    P_extra.muR_curve, ...
    P_extra.sigR_curve, ...
    T1_extra, ...
    T2_extra, ...
    O_extra, ...
    A_extra, ...
    R_extra, ...
    O_extra + A_extra + R_extra, ...
    Pred_Action_Ratio_extra(:, 1), ...
    Pred_Action_Ratio_extra(:, 2), ...
    Pred_Action_Ratio_extra(:, 3), ...
    A1_value_extra, ...
    A2_value_extra, ...
    A3_value_extra, ...
    'VariableNames', { ...
    'k', ...
    'RMSE_target', ...
    'RMSE_generated', ...
    'Residual_bias_generated', ...
    'Residual_std_generated', ...
    'w_right_component', ...
    'mu_main', ...
    'sigma_main', ...
    'mu_right', ...
    'sigma_right', ...
    'T1_star', ...
    'T2_star', ...
    'Opportunity_loss_per_pack_USD', ...
    'Mismatch_handling_rework_per_pack_USD', ...
    'Risk_penalty_per_pack_USD', ...
    'Decision_loss_per_pack_USD', ...
    'A1_direct_reuse_share', ...
    'A2_refurbishment_share', ...
    'A3_recycling_share', ...
    'A1_direct_reuse_value_per_pack_USD', ...
    'A2_refurbishment_value_per_pack_USD', ...
    'A3_recycling_value_per_pack_USD'});

writetable(ExtraK_Table, cfg.extra_k_csv);

% Combine the established k = 5-50 results and new k = 51-2000 results.
O_base = [O_base_existing; O_extra];
A_base = [A_base_existing; A_extra];
R_base = [R_base_existing; R_extra];

T1_base = [T1_base_existing; T1_extra];
T2_base = [T2_base_existing; T2_extra];

Pred_Action_Ratio_byK = [ ...
    Pred_Action_Ratio_existing; ...
    Pred_Action_Ratio_extra];

A1_value_perpack_byK = [A1_value_existing; A1_value_extra];
A2_value_perpack_byK = [A2_value_existing; A2_value_extra];
A3_value_perpack_byK = [A3_value_existing; A3_value_extra];

num_k = numel(k_vals);

if any([ ...
        numel(O_base), numel(A_base), numel(R_base), ...
        numel(T1_base), numel(T2_base), ...
        numel(A1_value_perpack_byK), ...
        numel(A2_value_perpack_byK), ...
        numel(A3_value_perpack_byK)] ~= num_k)
    error('The combined k = 5-2000 arrays have inconsistent lengths.');
end

if ~isequal(size(Pred_Action_Ratio_byK), [num_k, 3])
    error('The combined action-ratio matrix has an inconsistent size.');
end

fprintf('>>> Combined optimization range: k = %d to %d (%d values)\n', ...
    min(k_vals), max(k_vals), num_k);

%% 5) Construct market-scale cost matrices
scale_ton_list = double(cfg.scale_ton_list(:));
N_list = max(1, round(scale_ton_list .* 1000 ./ cfg.M_pack_kg));

num_N = numel(N_list);

O_Cost_NK = N_list .* O_base.';
A_Cost_NK = N_list .* A_base.';
R_Cost_NK = N_list .* R_base.';

Model_Cost_NK = repmat( ...
 (k_vals .* c_pack + c_train).', ...
 num_N, 1);

Total_Cost_NK = ...
 O_Cost_NK + ...
 A_Cost_NK + ...
 R_Cost_NK + ...
 Model_Cost_NK;

[opt_total_cost_of_N, opt_idx_of_N] = min(Total_Cost_NK, [], 2);

opt_k_of_N = k_vals(opt_idx_of_N);
opt_T1_of_N = T1_base(opt_idx_of_N);
opt_T2_of_N = T2_base(opt_idx_of_N);

row_idx = (1:num_N).';

opt_O_of_N = O_Cost_NK(sub2ind( ...
 size(O_Cost_NK), row_idx, opt_idx_of_N));

opt_A_of_N = A_Cost_NK(sub2ind( ...
 size(A_Cost_NK), row_idx, opt_idx_of_N));

opt_R_of_N = R_Cost_NK(sub2ind( ...
 size(R_Cost_NK), row_idx, opt_idx_of_N));

opt_Model_of_N = Model_Cost_NK(sub2ind( ...
 size(Model_Cost_NK), row_idx, opt_idx_of_N));

opt_Action_Ratio_of_N = Pred_Action_Ratio_byK(opt_idx_of_N, :);

opt_A1_value_of_N = ...
 N_list .* A1_value_perpack_byK(opt_idx_of_N);

opt_A2_value_of_N = ...
 N_list .* A2_value_perpack_byK(opt_idx_of_N);

opt_A3_value_of_N = ...
 N_list .* A3_value_perpack_byK(opt_idx_of_N);

opt_cost_per_pack_of_N = ...
 opt_total_cost_of_N ./ N_list;

%% 6) Compute gross and net realized pathway value
% The action-value components are already evaluated under the executed
% predicted action. Therefore, opportunity loss must not be subtracted a
% second time from the executed pathway value.

Gross_executed_action_value_of_N = ...
 opt_A1_value_of_N + ...
 opt_A2_value_of_N + ...
 opt_A3_value_of_N;

Net_realized_value_of_N = ...
 Gross_executed_action_value_of_N ...
 - opt_A_of_N ...
 - opt_R_of_N ...
 - opt_Model_of_N;

% Equivalent perfect-information accounting.
gross_executed_per_pack_by_k = ...
 A1_value_perpack_byK + ...
 A2_value_perpack_byK + ...
 A3_value_perpack_byK;

oracle_value_per_pack_by_k = ...
 gross_executed_per_pack_by_k + O_base;

oracle_value_spread = ...
 max(oracle_value_per_pack_by_k) - ...
 min(oracle_value_per_pack_by_k);

if oracle_value_spread > 1e-6
 warning(['The reconstructed perfect-information value varies slightly ' ...
 'across k by %.6g USD per pack. This should be Monte Carlo ' ...
 'round-off only.'], oracle_value_spread);
end

Perfect_information_action_value_of_N = ...
 N_list .* oracle_value_per_pack_by_k(opt_idx_of_N);

Net_realized_value_oracle_form = ...
 Perfect_information_action_value_of_N ...
 - opt_O_of_N ...
 - opt_A_of_N ...
 - opt_R_of_N ...
 - opt_Model_of_N;

Net_value_accounting_error_USD = ...
 Net_realized_value_of_N - ...
 Net_realized_value_oracle_form;

net_value_tolerance_USD = max( ...
 cfg.accounting_tolerance_abs_USD, ...
 cfg.accounting_tolerance_rel .* ...
 max(max(abs(Net_realized_value_of_N)), 1));

if max(abs(Net_value_accounting_error_USD)) > net_value_tolerance_USD
 error(['Executed-value and perfect-information net-value accounting ' ...
 'are inconsistent. Maximum discrepancy = %.6g USD.'], ...
 max(abs(Net_value_accounting_error_USD)));
end

%% 7) Boundary diagnostics
Is_k_on_lower_boundary = opt_k_of_N == min(k_vals);
Is_k_on_upper_boundary = opt_k_of_N == max(k_vals);

if any(Is_k_on_upper_boundary)
 warning(['At least one market-scale scenario selects k* = max(k_vals) ' ...
 '= %d. The reported optimum may be truncated by the current ' ...
 'residual-extrapolation range.'], max(k_vals));
end

Label_density_per_ton = ...
 opt_k_of_N ./ scale_ton_list;

%% 8) Build output tables
Opportunity_loss_total_USD = opt_O_of_N;
Handling_rework_total_USD = opt_A_of_N;
Risk_penalty_total_USD = opt_R_of_N;
Information_cost_total_USD = opt_Model_of_N;

Decision_cost_total_USD = ...
 Opportunity_loss_total_USD + ...
 Handling_rework_total_USD + ...
 Risk_penalty_total_USD;

Opportunity_loss_per_pack_USD = ...
 Opportunity_loss_total_USD ./ N_list;

Handling_rework_per_pack_USD = ...
 Handling_rework_total_USD ./ N_list;

Risk_penalty_per_pack_USD = ...
 Risk_penalty_total_USD ./ N_list;

Information_cost_per_pack_USD = ...
 Information_cost_total_USD ./ N_list;

Decision_cost_per_pack_USD = ...
 Decision_cost_total_USD ./ N_list;

Opportunity_loss_share_percent = ...
 100 .* Opportunity_loss_total_USD ./ opt_total_cost_of_N;

Handling_rework_share_percent = ...
 100 .* Handling_rework_total_USD ./ opt_total_cost_of_N;

Risk_penalty_share_percent = ...
 100 .* Risk_penalty_total_USD ./ opt_total_cost_of_N;

Information_cost_share_percent = ...
 100 .* Information_cost_total_USD ./ opt_total_cost_of_N;

Decision_cost_share_percent = ...
 100 .* Decision_cost_total_USD ./ opt_total_cost_of_N;

MarketScale_Table = table( ...
 scale_ton_list, ...
 N_list, ...
 opt_k_of_N, ...
 Is_k_on_lower_boundary, ...
 Is_k_on_upper_boundary, ...
 Label_density_per_ton, ...
 opt_T1_of_N, ...
 opt_T2_of_N, ...
 opt_total_cost_of_N, ...
 opt_cost_per_pack_of_N, ...
 Opportunity_loss_total_USD, ...
 Handling_rework_total_USD, ...
 Risk_penalty_total_USD, ...
 Information_cost_total_USD, ...
 Decision_cost_total_USD, ...
 Opportunity_loss_per_pack_USD, ...
 Handling_rework_per_pack_USD, ...
 Risk_penalty_per_pack_USD, ...
 Information_cost_per_pack_USD, ...
 Decision_cost_per_pack_USD, ...
 Opportunity_loss_share_percent, ...
 Handling_rework_share_percent, ...
 Risk_penalty_share_percent, ...
 Information_cost_share_percent, ...
 Decision_cost_share_percent, ...
 opt_Action_Ratio_of_N(:, 1), ...
 opt_Action_Ratio_of_N(:, 2), ...
 opt_Action_Ratio_of_N(:, 3), ...
 opt_A1_value_of_N, ...
 opt_A2_value_of_N, ...
 opt_A3_value_of_N, ...
 Gross_executed_action_value_of_N, ...
 Perfect_information_action_value_of_N, ...
 Net_realized_value_of_N, ...
 Net_value_accounting_error_USD, ...
 Gross_executed_action_value_of_N ./ 1e9, ...
 Net_realized_value_of_N ./ 1e9, ...
 'VariableNames', { ...
 'Scale_ton', ...
 'Pack_number', ...
 'Optimal_k', ...
 'Is_k_on_lower_boundary', ...
 'Is_k_on_upper_boundary', ...
 'Label_density_per_ton', ...
 'T1_star', ...
 'T2_star', ...
 'Total_recertification_cost_USD', ...
 'Total_recertification_cost_per_pack_USD', ...
 'Opportunity_loss_USD', ...
 'Mismatch_handling_rework_cost_USD', ...
 'Risk_penalty_USD', ...
 'SOH_labelling_adaptation_cost_USD', ...
 'Decision_cost_USD', ...
 'Opportunity_loss_per_pack_USD', ...
 'Mismatch_handling_rework_cost_per_pack_USD', ...
 'Risk_penalty_per_pack_USD', ...
 'SOH_labelling_adaptation_cost_per_pack_USD', ...
 'Decision_cost_per_pack_USD', ...
 'Opportunity_loss_share_percent', ...
 'Mismatch_handling_rework_cost_share_percent', ...
 'Risk_penalty_share_percent', ...
 'SOH_labelling_adaptation_cost_share_percent', ...
 'Decision_cost_share_percent', ...
 'A1_direct_reuse_share', ...
 'A2_refurbishment_share', ...
 'A3_recycling_share', ...
 'A1_direct_reuse_value_USD', ...
 'A2_refurbishment_value_USD', ...
 'A3_recycling_value_USD', ...
 'Gross_executed_action_value_USD', ...
 'Perfect_information_action_value_USD', ...
 'Net_realized_value_USD', ...
 'Net_value_accounting_error_USD', ...
 'Gross_executed_action_value_billion_USD', ...
 'Net_realized_value_billion_USD'});

CostBreakdown_Table = table( ...
 scale_ton_list, ...
 N_list, ...
 opt_k_of_N, ...
 Is_k_on_upper_boundary, ...
 opt_T1_of_N, ...
 opt_T2_of_N, ...
 opt_total_cost_of_N ./ 1e6, ...
 Opportunity_loss_total_USD ./ 1e6, ...
 Handling_rework_total_USD ./ 1e6, ...
 Risk_penalty_total_USD ./ 1e6, ...
 Information_cost_total_USD ./ 1e6, ...
 Decision_cost_total_USD ./ 1e6, ...
 opt_cost_per_pack_of_N, ...
 Opportunity_loss_per_pack_USD, ...
 Handling_rework_per_pack_USD, ...
 Risk_penalty_per_pack_USD, ...
 Information_cost_per_pack_USD, ...
 Decision_cost_per_pack_USD, ...
 'VariableNames', { ...
 'Scale_ton', ...
 'Pack_number', ...
 'Optimal_k', ...
 'Is_k_on_upper_boundary', ...
 'T1_star', ...
 'T2_star', ...
 'Total_cost_MUSD', ...
 'Opportunity_loss_MUSD', ...
 'Mismatch_handling_rework_cost_MUSD', ...
 'Risk_penalty_MUSD', ...
 'SOH_labelling_adaptation_cost_MUSD', ...
 'Decision_cost_MUSD', ...
 'Total_cost_per_pack_USD', ...
 'Opportunity_loss_per_pack_USD', ...
 'Mismatch_handling_rework_cost_per_pack_USD', ...
 'Risk_penalty_per_pack_USD', ...
 'SOH_labelling_adaptation_cost_per_pack_USD', ...
 'Decision_cost_per_pack_USD'});

MarketScale_Only_Table = MarketScale_Table;
CostBreakdown_Only_Table = CostBreakdown_Table;

writetable(MarketScale_Table, cfg.market_scale_csv);
writetable(CostBreakdown_Table, cfg.cost_breakdown_csv);
writetable(MarketScale_Only_Table, cfg.market_only_csv);

%% 9) Save formal result
LFP_MarketScale_Extension_Result = struct();

LFP_MarketScale_Extension_Result.cfg = cfg;
LFP_MarketScale_Extension_Result.input_file = cfg.input_file;

LFP_MarketScale_Extension_Result.scale_ton_list = scale_ton_list;
LFP_MarketScale_Extension_Result.N_list = N_list;
LFP_MarketScale_Extension_Result.k_vals = k_vals;
LFP_MarketScale_Extension_Result.k_vals_base = k_vals_base;
LFP_MarketScale_Extension_Result.k_vals_extra = k_vals_extra;
LFP_MarketScale_Extension_Result.ExtraK_Table = ExtraK_Table;

LFP_MarketScale_Extension_Result.rmse_target = rmse_target;
LFP_MarketScale_Extension_Result.w_curve = w_curve;
LFP_MarketScale_Extension_Result.muM_curve = muM_curve;
LFP_MarketScale_Extension_Result.sigM_curve = sigM_curve;
LFP_MarketScale_Extension_Result.muR_curve = muR_curve;
LFP_MarketScale_Extension_Result.sigR_curve = sigR_curve;

LFP_MarketScale_Extension_Result.O_base = O_base;
LFP_MarketScale_Extension_Result.A_base = A_base;
LFP_MarketScale_Extension_Result.R_base = R_base;
LFP_MarketScale_Extension_Result.T1_base = T1_base;
LFP_MarketScale_Extension_Result.T2_base = T2_base;
LFP_MarketScale_Extension_Result.Pred_Action_Ratio_byK = Pred_Action_Ratio_byK;
LFP_MarketScale_Extension_Result.A1_value_perpack_byK = A1_value_perpack_byK;
LFP_MarketScale_Extension_Result.A2_value_perpack_byK = A2_value_perpack_byK;
LFP_MarketScale_Extension_Result.A3_value_perpack_byK = A3_value_perpack_byK;

LFP_MarketScale_Extension_Result.c_pack = c_pack;
LFP_MarketScale_Extension_Result.c_train = c_train;

LFP_MarketScale_Extension_Result.Total_Cost_NK = Total_Cost_NK;
LFP_MarketScale_Extension_Result.O_Cost_NK = O_Cost_NK;
LFP_MarketScale_Extension_Result.A_Cost_NK = A_Cost_NK;
LFP_MarketScale_Extension_Result.R_Cost_NK = R_Cost_NK;
LFP_MarketScale_Extension_Result.Model_Cost_NK = Model_Cost_NK;

LFP_MarketScale_Extension_Result.opt_idx_of_N = opt_idx_of_N;
LFP_MarketScale_Extension_Result.opt_k_of_N = opt_k_of_N;
LFP_MarketScale_Extension_Result.opt_T1_of_N = opt_T1_of_N;
LFP_MarketScale_Extension_Result.opt_T2_of_N = opt_T2_of_N;

LFP_MarketScale_Extension_Result.opt_total_cost_of_N = opt_total_cost_of_N;
LFP_MarketScale_Extension_Result.opt_cost_per_pack_of_N = opt_cost_per_pack_of_N;

LFP_MarketScale_Extension_Result.opt_O_of_N = opt_O_of_N;
LFP_MarketScale_Extension_Result.opt_A_of_N = opt_A_of_N;
LFP_MarketScale_Extension_Result.opt_R_of_N = opt_R_of_N;
LFP_MarketScale_Extension_Result.opt_Model_of_N = opt_Model_of_N;

LFP_MarketScale_Extension_Result.opt_Action_Ratio_of_N = ...
 opt_Action_Ratio_of_N;

LFP_MarketScale_Extension_Result.opt_A1_value_of_N = opt_A1_value_of_N;
LFP_MarketScale_Extension_Result.opt_A2_value_of_N = opt_A2_value_of_N;
LFP_MarketScale_Extension_Result.opt_A3_value_of_N = opt_A3_value_of_N;

LFP_MarketScale_Extension_Result.Gross_executed_action_value_of_N = ...
 Gross_executed_action_value_of_N;

LFP_MarketScale_Extension_Result.Perfect_information_action_value_of_N = ...
 Perfect_information_action_value_of_N;

LFP_MarketScale_Extension_Result.Net_realized_value_of_N = ...
 Net_realized_value_of_N;

% Legacy aliases retained for older table scripts.
LFP_MarketScale_Extension_Result.Total_action_value_of_N = ...
 Gross_executed_action_value_of_N;

LFP_MarketScale_Extension_Result.Net_value_after_cost_of_N = ...
 Net_realized_value_of_N;

LFP_MarketScale_Extension_Result.Net_value_accounting_error_USD = ...
 Net_value_accounting_error_USD;

LFP_MarketScale_Extension_Result.Is_k_on_upper_boundary = ...
 Is_k_on_upper_boundary;

LFP_MarketScale_Extension_Result.MarketScale_Table = MarketScale_Table;
LFP_MarketScale_Extension_Result.CostBreakdown_Table = CostBreakdown_Table;
LFP_MarketScale_Extension_Result.MarketScale_Only_Table = MarketScale_Only_Table;
LFP_MarketScale_Extension_Result.CostBreakdown_Only_Table = ...
 CostBreakdown_Only_Table;

save(cfg.result_mat, ...
 'LFP_MarketScale_Extension_Result', ...
 'MarketScale_Table', ...
 'CostBreakdown_Table', ...
 'MarketScale_Only_Table', ...
 'CostBreakdown_Only_Table', ...
 'ExtraK_Table', ...
 '-v7.3');

fprintf('\n========== Market-scale extension summary ==========\n');
disp(MarketScale_Table(:, { ...
 'Scale_ton', ...
 'Pack_number', ...
 'Optimal_k', ...
 'Is_k_on_upper_boundary', ...
 'T1_star', ...
 'T2_star', ...
 'Total_recertification_cost_per_pack_USD', ...
 'Gross_executed_action_value_billion_USD', ...
 'Net_realized_value_billion_USD'}));

fprintf('Saved market-scale table: %s\n', cfg.market_scale_csv);
fprintf('Saved cost-breakdown table: %s\n', cfg.cost_breakdown_csv);
fprintf('Saved market-only table: %s\n', cfg.market_only_csv);
fprintf('Saved k-extension table: %s\n', cfg.extra_k_csv);
fprintf('Saved result MAT: %s\n', cfg.result_mat);
fprintf('================ Part5 Exp07 completed ================\n');


%% Local helper functions

function grid_values = local_make_grid(lower_value, upper_value, step_value)
% Construct an inclusive increasing grid with a specified step.

    lower_value = double(lower_value);
    upper_value = double(upper_value);
    step_value = double(step_value);

    if ~isscalar(lower_value) || ~isscalar(upper_value) || ...
            ~isscalar(step_value) || ...
            ~isfinite(lower_value) || ~isfinite(upper_value) || ...
            ~isfinite(step_value) || step_value <= 0 || ...
            lower_value >= upper_value
        error('Invalid threshold-grid specification.');
    end

    grid_values = (lower_value:step_value:upper_value).';

    if abs(grid_values(end) - upper_value) > 1e-12
        grid_values(end + 1, 1) = upper_value;
    end

    grid_values = unique(grid_values, 'stable').';
end

function P = local_evaluate_fitted_residual_parameters( ...
        k_query, E, k_anchor, muR_constant)
% Evaluate the fitted Part3 residual equations at arbitrary k >= anchor.

    k_query = double(k_query(:));
    k_emp = double(E.k_emp(:));

    if any(~isfinite(k_query)) || any(k_query < k_anchor)
        error('Extended residual parameters require finite k >= k_anchor.');
    end

    idx_k0 = find(k_emp == min(k_emp), 1);
    PR0 = double(E.P_R_fit_input(idx_k0));
    k0 = min(k_emp);

    idx_anchor = find(k_emp == k_anchor, 1);

    if isempty(idx_anchor)
        error('k_anchor is not present in the Part3 empirical k set.');
    end

    muM_anchor = double(E.mu_M_fit_input(idx_anchor));

    sigR_input = double(E.sig_R_fit_input(:));

    mask_sigR = ...
        (k_emp >= E.cfg.k_emp_min) & ...
        (k_emp <= k_anchor) & ...
        (sigR_input > 0) & ...
        isfinite(sigR_input);

    if ~any(mask_sigR)
        error('Unable to reconstruct the sigma_R fitting origin.');
    end

    k0_sigR = min(k_emp(mask_sigR));

    P = struct();

    P.rmse_target = ...
        double(E.a_RMSE) .* k_query .^ (-double(E.b_RMSE)) + ...
        double(E.c_RMSE);

    P.PR_curve = min(max( ...
        double(E.cR_opt) + ...
        (PR0 - double(E.cR_opt)) .* ...
        exp(-double(E.bR_opt) .* (k_query - k0)), ...
        0), 0.40);

    P.muM_curve = ...
        muM_anchor .* ...
        exp(-double(E.a_muM) .* (k_query - k_anchor));

    P.muR_curve = repmat(double(muR_constant), numel(k_query), 1);

    P.sigR_curve = max( ...
        double(E.c_sigR) + ...
        double(E.A_sigR) .* ...
        exp(-double(E.b_sigR) .* (k_query - k0_sigR)), ...
        1e-6);

    P.w_curve = zeros(numel(k_query), 1);
    P.sigM_curve = zeros(numel(k_query), 1);
    P.PR_model = zeros(numel(k_query), 1);
    P.w_feasible_max = zeros(numel(k_query), 1);
    P.w_solver_status = strings(numel(k_query), 1);

    for ii = 1:numel(k_query)
        [P.w_curve(ii), ...
            P.sigM_curve(ii), ...
            P.PR_model(ii), ...
            P.w_feasible_max(ii), ...
            status_now] = local_solve_region_consistent_weight( ...
            P.PR_curve(ii), ...
            P.rmse_target(ii), ...
            P.muM_curve(ii), ...
            P.muR_curve(ii), ...
            P.sigR_curve(ii), ...
            E.region.right, ...
            E.cfg.min_sig_main);

        P.w_solver_status(ii) = string(status_now);
    end
end

function [O_by_action, A_by_action, R_by_action, Total_by_action] = ...
        local_build_candidate_action_costs( ...
        Pi_True, Pi_True_Max, True_Action_i, ...
        Eta_1, Eta_2, Lambda_A, Lambda_R)
% Precompute per-sample costs for assigning each candidate action.

    N_sim = numel(True_Action_i);

    O_by_action = zeros(N_sim, 3);
    A_by_action = zeros(N_sim, 3);
    R_by_action = zeros(N_sim, 3);

    for action_now = 1:3
        O_now = max(Pi_True_Max - Pi_True(:, action_now), 0);

        is_G1_error = ...
            (True_Action_i == 3 & action_now == 2) | ...
            (True_Action_i == 2 & action_now == 3);

        is_G2_error = ...
            (True_Action_i == 1 & action_now == 2) | ...
            (True_Action_i == 2 & action_now == 1);

        eta_now = zeros(N_sim, 1);
        eta_now(is_G1_error) = Eta_1;
        eta_now(is_G2_error) = Eta_2;

        trigger_now = O_now > eta_now;
        excess_now = max(0, O_now - eta_now);

        A_now = trigger_now .* Lambda_A;

        R_now = (action_now < True_Action_i) .* ...
            trigger_now .* (Lambda_R .* excess_now);

        O_by_action(:, action_now) = O_now;
        A_by_action(:, action_now) = A_now;
        R_by_action(:, action_now) = R_now;
    end

    Total_by_action = O_by_action + A_by_action + R_by_action;
end

function Q = local_optimize_thresholds_fast( ...
        s_pred, Pi_True, ...
        O_by_action, A_by_action, R_by_action, Total_by_action, ...
        T1_grid, T2_grid)
% Find the exact grid optimum using cumulative sums after sorting s_pred.
%
% For one threshold pair:
%   s_pred < T1        -> A3
%   T1 <= s_pred < T2  -> A2
%   s_pred >= T2       -> A1
%
% The cost of assigning each sample to A1/A2/A3 is threshold-independent.
% Therefore, cumulative sums reproduce the original brute-force objective
% exactly while avoiding sample-level recalculation for every grid pair.

    s_pred = double(s_pred(:));
    N_sim = numel(s_pred);

    [s_sorted, sort_idx] = sort(s_pred, 'ascend');
    sorted_cost = Total_by_action(sort_idx, :);

    cumulative_cost = [zeros(1, 3); cumsum(sorted_cost, 1)];

    n_below_T1 = zeros(numel(T1_grid), 1);
    n_below_T2 = zeros(numel(T2_grid), 1);

    for ii = 1:numel(T1_grid)
        n_below_T1(ii) = local_count_less_than(s_sorted, T1_grid(ii));
    end

    for jj = 1:numel(T2_grid)
        n_below_T2(jj) = local_count_less_than(s_sorted, T2_grid(jj));
    end

    best_loss = inf;
    best_T1 = NaN;
    best_T2 = NaN;

    for ii = 1:numel(T1_grid)
        T1_now = T1_grid(ii);
        n1 = n_below_T1(ii);

        for jj = 1:numel(T2_grid)
            T2_now = T2_grid(jj);

            if T1_now >= T2_now
                continue;
            end

            n2 = n_below_T2(jj);

            cost_A3 = cumulative_cost(n1 + 1, 3);
            cost_A2 = ...
                cumulative_cost(n2 + 1, 2) - ...
                cumulative_cost(n1 + 1, 2);
            cost_A1 = ...
                cumulative_cost(end, 1) - ...
                cumulative_cost(n2 + 1, 1);

            loss_now = (cost_A3 + cost_A2 + cost_A1) / N_sim;

            % Strict inequality preserves the original first-minimum
            % tie-breaking order of the nested T1/T2 loops.
            if loss_now < best_loss
                best_loss = loss_now;
                best_T1 = T1_now;
                best_T2 = T2_now;
            end
        end
    end

    if ~isfinite(best_loss)
        error('No valid T1/T2 pair was found.');
    end

    Pred_Action = 3 * ones(N_sim, 1);
    Pred_Action(s_pred >= best_T1 & s_pred < best_T2) = 2;
    Pred_Action(s_pred >= best_T2) = 1;

    idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action);

    Q = struct();
    Q.T1_star = best_T1;
    Q.T2_star = best_T2;

    Q.O_per_pack = mean(O_by_action(idx_pred));
    Q.A_per_pack = mean(A_by_action(idx_pred));
    Q.R_per_pack = mean(R_by_action(idx_pred));

    Q.action_share = [ ...
        mean(Pred_Action == 1), ...
        mean(Pred_Action == 2), ...
        mean(Pred_Action == 3)];

    Q.A1_value_perpack = ...
        mean(Pi_True(:, 1) .* (Pred_Action == 1));

    Q.A2_value_perpack = ...
        mean(Pi_True(:, 2) .* (Pred_Action == 2));

    Q.A3_value_perpack = ...
        mean(Pi_True(:, 3) .* (Pred_Action == 3));

    Q.decision_loss_per_pack = best_loss;

    accounting_error = abs( ...
        best_loss - ...
        (Q.O_per_pack + Q.A_per_pack + Q.R_per_pack));

    if accounting_error > 1e-10
        error(['Fast threshold optimization accounting mismatch: ' ...
            '%.6g USD per pack.'], accounting_error);
    end
end

function count_value = local_count_less_than(sorted_values, threshold)
% Count sorted values strictly below a threshold using binary search.

    n = numel(sorted_values);

    if n == 0 || sorted_values(1) >= threshold
        count_value = 0;
        return;
    end

    if sorted_values(end) < threshold
        count_value = n;
        return;
    end

    lower_idx = 1;
    upper_idx = n;

    while lower_idx < upper_idx
        middle_idx = floor((lower_idx + upper_idx + 1) / 2);

        if sorted_values(middle_idx) < threshold
            lower_idx = middle_idx;
        else
            upper_idx = middle_idx - 1;
        end
    end

    count_value = lower_idx;
end

function [w_opt, sigM_opt, PR_model, w_feasible_max, status] = ...
        local_solve_region_consistent_weight( ...
        PR_target, rmse_target, muM, muR, sigR, ...
        right_region, min_sigM)
% Solve the latent right-component weight while matching target RMSE and
% probability inside the fixed right-tail diagnostic interval.

    PR_target = min(max(PR_target, 0), 1);
    rmse_target = max(rmse_target, 1e-12);
    min_sigM = max(min_sigM, 1e-8);

    second_right = sigR^2 + muR^2;
    second_main_min = min_sigM^2 + muM^2;

    if rmse_target^2 <= second_main_min
        w_feasible_max = 0;
        w_opt = 0;
        sigM_opt = sqrt(max( ...
            rmse_target^2 - muM^2, min_sigM^2));
        PR_model = local_region_probability_mixture( ...
            w_opt, muM, sigM_opt, muR, sigR, right_region);
        status = 'No positive-w solution: main-mode floor active';
        return;
    end

    if second_right > second_main_min
        w_feasible_max = ...
            (rmse_target^2 - second_main_min) / ...
            (second_right - second_main_min);
    else
        w_feasible_max = 0.999;
    end

    w_feasible_max = min(max(w_feasible_max, 0), 0.999);

    if w_feasible_max <= 1e-12
        w_opt = 0;
        sigM_opt = sqrt(max( ...
            rmse_target^2 - muM^2, min_sigM^2));
        PR_model = local_region_probability_mixture( ...
            w_opt, muM, sigM_opt, muR, sigR, right_region);
        status = 'Boundary solution: w = 0';
        return;
    end

    objective = @(w) local_region_probability_error( ...
        w, PR_target, rmse_target, ...
        muM, muR, sigR, right_region, min_sigM);

    [w_opt, ~] = fminbnd( ...
        objective, 0, w_feasible_max, ...
        optimset('Display', 'off', 'TolX', 1e-10));

    sigM_opt = local_sigma_main_from_rmse( ...
        w_opt, rmse_target, muM, muR, sigR, min_sigM);

    PR_model = local_region_probability_mixture( ...
        w_opt, muM, sigM_opt, muR, sigR, right_region);

    if w_opt < 1e-7
        status = 'Boundary solution near w = 0';
    elseif abs(w_opt - w_feasible_max) < 1e-7
        status = 'Boundary solution near feasible maximum';
    else
        status = 'Interior solution';
    end
end

function value = local_region_probability_error( ...
        w, PR_target, rmse_target, ...
        muM, muR, sigR, right_region, min_sigM)
% Squared normalized discrepancy between model and target right-region mass.

    sigM = local_sigma_main_from_rmse( ...
        w, rmse_target, muM, muR, sigR, min_sigM);

    PR_model = local_region_probability_mixture( ...
        w, muM, sigM, muR, sigR, right_region);

    scale = max(PR_target, 0.01);
    value = ((PR_model - PR_target) / scale)^2;
end

function sigM = local_sigma_main_from_rmse( ...
        w, rmse_target, muM, muR, sigR, min_sigM)
% Back-calculate the main-component width from the target second moment.

    numerator = ...
        rmse_target^2 ...
        - w * (sigR^2 + muR^2) ...
        - (1 - w) * muM^2;

    denominator = max(1 - w, 1e-12);

    sigM = sqrt(max( ...
        numerator / denominator, ...
        min_sigM^2));
end

function PR_model = local_region_probability_mixture( ...
        w, muM, sigM, muR, sigR, right_region)
% Probability of the two-normal mixture inside the fixed right interval.

    lower_bound = right_region(1);
    upper_bound = right_region(2);

    q_main = ...
        normcdf(upper_bound, muM, sigM) - ...
        normcdf(lower_bound, muM, sigM);

    q_right = ...
        normcdf(upper_bound, muR, sigR) - ...
        normcdf(lower_bound, muR, sigR);

    PR_model = (1 - w) * q_main + w * q_right;
end
