%% P5_Exp01_scale_dependent_LFP_optimization.m
%
% Purpose:
% This script implements the scale-dependent LFP recertification
% optimization.
%
% It combines SOH-dependent action-value functions, the k-dependent
% residual-error model generated by Part3, scale-dependent cost
% amortization, and threshold-based recertification decisions to evaluate
% how deployment scale affects the optimal SOH-labelling investment k*,
% threshold policy, cost decomposition, action allocation, and action-value
% contribution.

clear, clc, close all;
%% 0. Path configuration
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
 script_dir = pwd;
end

% Project root folder.
cfg.project_root = fileparts(script_dir);

% Part5 folders.
cfg.input_dir = fullfile(script_dir, 'Input');
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.main_fig_dir = fullfile(cfg.figure_root, 'Main');
cfg.extended_fig_dir = fullfile(cfg.figure_root, 'Extended');

cfg.function_dir = fullfile(script_dir, 'Function');

% Part3 output folder.
cfg.part3_output_dir = fullfile(cfg.project_root, ...
 'Part3_Prediction error extrapolation', ...
 'Output');

% Input SOH file for Part5.
cfg.soh_file = fullfile(cfg.input_dir, 'LFP_SOH_Table.mat');

% Primary residual-error extrapolation model generated by Part3 Exp03.
cfg.residual_file_primary = fullfile(cfg.part3_output_dir, 'Results', 'P3_Exp03_ResidualExtrapolation_Model.mat');

cfg.residual_file_legacy = fullfile(cfg.part3_output_dir, 'Result03_ResidualExtrapolation_Model.mat');
% cfg.residual_file_sup01 = fullfile(cfg.part3_output_dir, 'Sup01', 'Result03_ResidualExtrapolation_Model.mat');

% Main output files generated by Part5 Exp01.
cfg.result_mat = fullfile(cfg.results_dir, 'P5_Exp01_ScaleDependent_LFP_Results.mat');
cfg.workspace_mat = fullfile(cfg.results_dir, 'P5_Exp01_ScaleDependent_LFP_Workspace.mat');
cfg.summary_csv = fullfile(cfg.results_dir, 'P5_Exp01_ScaleDependent_LFP_Summary.csv');
cfg.action_value_csv = fullfile(cfg.results_dir, 'P5_Exp01_ScaleDependent_LFP_ActionValueDecomposition.csv');
cfg.action_allocation_csv = fullfile(cfg.results_dir, 'P5_Exp01_ScaleDependent_LFP_ActionAllocationForExD05.csv');
cfg.a3_inset_csv = fullfile(cfg.results_dir,'P5_Exp01_ScaleDependent_LFP_A3Inset.csv');

% Figure export settings.
cfg.png_resolution = 600;

% Figure files for Main Fig. 4.
cfg.fig04a = fullfile(cfg.main_fig_dir, 'MainFig04a_LFP_kstar_total_cost_landscape.fig');
cfg.png04a = fullfile(cfg.main_fig_dir, 'MainFig04a_LFP_kstar_total_cost_landscape.png');

cfg.fig04b = fullfile(cfg.main_fig_dir,'MainFig04b_LFP_label_density_per_ton.fig');
cfg.png04b = fullfile(cfg.main_fig_dir, 'MainFig04b_LFP_label_density_per_ton.png');

cfg.fig04c = fullfile(cfg.main_fig_dir, 'MainFig04c_LFP_per_pack_cost_breakdown.fig');
cfg.png04c = fullfile(cfg.main_fig_dir,'MainFig04c_LFP_per_pack_cost_breakdown.png');

cfg.fig04d = fullfile(cfg.main_fig_dir, 'MainFig04d_LFP_per_pack_cost_reduction_decomposition.fig');
cfg.png04d = fullfile(cfg.main_fig_dir,'MainFig04d_LFP_per_pack_cost_reduction_decomposition.png');

cfg.fig04e = fullfile(cfg.main_fig_dir, 'MainFig04e_LFP_total_cost_breakdown.fig');
cfg.png04e = fullfile(cfg.main_fig_dir, 'MainFig04e_LFP_total_cost_breakdown.png');

cfg.fig04f = fullfile(cfg.main_fig_dir, 'MainFig04f_LFP_action_value_decomposition.fig');
cfg.png04f = fullfile(cfg.main_fig_dir, 'MainFig04f_LFP_action_value_decomposition.png');

cfg.fig04f_inset = fullfile(cfg.main_fig_dir,'MainFig04f_inset_LFP_A3_recycling_value.fig');
cfg.png04f_inset = fullfile(cfg.main_fig_dir, 'MainFig04f_inset_LFP_A3_recycling_value.png');

% Figure file for Extended Data Fig. 4c.
cfg.fig_ExD04c = fullfile(cfg.extended_fig_dir, 'ExD04c_LFP_scale_dependent_optimal_thresholds.fig');
cfg.png_ExD04c = fullfile(cfg.extended_fig_dir, 'ExD04c_LFP_scale_dependent_optimal_thresholds.png');


% Create required local folders.
folder_list = { cfg.input_dir, cfg.output_dir, cfg.results_dir, cfg.figure_root, cfg.main_fig_dir, cfg.extended_fig_dir, cfg.function_dir};
for ii = 1:numel(folder_list)
 if ~exist(folder_list{ii}, 'dir')
 mkdir(folder_list{ii});
 end
end

% Add the local function folder.
if exist(cfg.function_dir, 'dir')
 addpath(cfg.function_dir);
end

if exist('local_build_noise_by_k', 'file') ~= 2
 error('Function local_build_noise_by_k.m was not found in: %s', ...
 cfg.function_dir);
end

% Check the LFP SOH input file.
if ~isfile(cfg.soh_file)
 error('LFP SOH input file not found: %s', cfg.soh_file);
end

% Locate the Part3 residual-error result file.
if isfile(cfg.residual_file_primary)
 cfg.residual_file = cfg.residual_file_primary;
elseif isfile(cfg.residual_file_legacy)
 cfg.residual_file = cfg.residual_file_legacy;
% elseif isfile(cfg.residual_file_sup01)
% cfg.residual_file = cfg.residual_file_sup01;
else

 error(['Part3 residual-error extrapolation model file not found.\n' ...
 'Checked:\n%s\n%s\n' ...
 'Please run Part3 Exp03 first to generate the residual-error model.'], ...
 cfg.residual_file_primary, ...
 cfg.residual_file_legacy);
end

fprintf('================ Part5 Exp01 scale-dependent LFP optimization ================\n');
fprintf('LFP SOH input file: %s\n', cfg.soh_file);
fprintf('Part3 residual file: %s\n', cfg.residual_file);
fprintf('Output result file: %s\n', cfg.result_mat);
fprintf('Output workspace file: %s\n', cfg.workspace_mat);
fprintf('Main figure folder: %s\n', cfg.main_fig_dir);
fprintf('Extended figure folder: %s\n', cfg.extended_fig_dir);

% 1. Basic physical and economic parameters

if ~isfile(cfg.soh_file)
 error('LFP SOH input file not found: %s', cfg.soh_file);
end

S_input = load(cfg.soh_file);

if isfield(S_input, 'SOH_array')
 SOH_array = S_input.SOH_array;
elseif isfield(S_input, 'LFP_SOH_Table')
 SOH_array = S_input.LFP_SOH_Table;
elseif isfield(S_input, 'SOH_data')
 SOH_array = S_input.SOH_data;
else
 input_var_names = fieldnames(S_input);
 if isempty(input_var_names)
 error('No variable was found in %s.', cfg.soh_file);
 end
 SOH_array = S_input.(input_var_names{1});
end

if istable(SOH_array)
 table_vars = SOH_array.Properties.VariableNames;
 soh_col_idx = find(contains(lower(table_vars), 'soh'), 1, 'first');
 if isempty(soh_col_idx)
 soh_col_idx = 1;
 end
 SOH_data = SOH_array{:, soh_col_idx};
else
 SOH_data = SOH_array;
end

SOH_data = double(SOH_data(:));
SOH_data = SOH_data(isfinite(SOH_data));

if isempty(SOH_data)
 error('No valid LFP SOH values were found in %s.', cfg.soh_file);
end

Q_pack = 25.3;
r = 0.05;
beta_refurbish = 0.09;

ExchangeRate_RMB_USD = 7.04;
p_high_RMB = 1.1621;
p_low_RMB = 0.2986;

p_high = p_high_RMB / ExchangeRate_RMB_USD; % 0.1651
p_low = p_low_RMB / ExchangeRate_RMB_USD; % 0.0424

c_pack = 300; c_train = 100; Fixed_Scale_N = 2500;
% SOH labeling cost model training cost fixed deployment scale


Eta_1 = 40; Eta_2 = 40;
% G1 gray-zone tolerance between recycling and refurbishment
% G2 gray-zone tolerance between direct reuse and refurbishment

% Refurbishment cost parameters
C0 = 92; % baseline labor, disassembly, and inspection cost
C1 = 65; % material replacement and deep-repair cost coefficient
gamma = 3; % nonlinear degradation exponent for refurbishment difficulty

Lambda_R = 15; Lambda_A = 12;
% Risk penalty is applied to over-optimistic action assignment.
% Manual-review penalty is applied once the value-loss tolerance is exceeded.


% 1.1 Hydrometallurgical recycling economics and physicochemical parameters

M_pack = 173.25; Exchange_Rate = 1;


% - 1. Baseline physicochemical parameters per kg battery pack -
PosAcMass = 0.223; PosCCMass = 0.060; NegAcMass = 0.1235; NegCCMass = 0.08;
M_LiFePO4 = 157.76; M_Li2CO3_half = 73.88; M_FePO4 = 150.82; M_H2SO4 = 98; M_H2O2 = 34; M_Na2CO3 = 106;

Rec_Rate_Chem = 0.98; Rec_Rate_Graphite = 0.95; Rec_Rate_Al = 0.93; Rec_Rate_Cu = 0.93;
P_Li2CO3 = 27.20; P_FePO4 = 1.91; P_Graphite = 3.84; P_Al = 3.42; P_Cu = 14.79;
Base_Y_FePO4 = (PosAcMass / M_LiFePO4) * M_FePO4 * Rec_Rate_Chem;
Base_Y_Graphite = NegAcMass * Rec_Rate_Graphite;
Base_Y_Al = PosCCMass * Rec_Rate_Al; Base_Y_Cu = NegCCMass * Rec_Rate_Cu;
C_Degraded = 2.05; P_H2SO4 = 0.264; P_H2O2 = 0.130; P_Na2CO3 = 0.172;
P_elec_recycle = 0.111; % USD/kWh

C_Electricity_hydro = 500 * P_elec_recycle / 1000; % USD/kg battery
C_Labor_hydro = 307.36 / 1000; % USD/kg battery
C_Disassemble_hydro = 12.07 / 1000; % USD/kg battery
C_Equip_hydro = 52.00 / 1000; % USD/kg battery
C_Sewage_hydro = 141.14 / 1000; % USD/kg battery

Fixed_Op_Cost = C_Electricity_hydro + C_Labor_hydro + ...
 C_Disassemble_hydro + C_Equip_hydro + C_Sewage_hydro;


% 2. SOH-dependent action-value functions

% 2.1 Construct the baseline direct-reuse value curve from the empirical SOH trajectory
valid_end_idx = find(SOH_data >= 0.4); end_idx = valid_end_idx(end);

start_indices = find(SOH_data <= 1.0 & SOH_data >= 0.4);
num_cases = length(start_indices);
a = zeros(num_cases, 1); V1 = zeros(num_cases, 1);

for k = 1:num_cases
 start_idx = start_indices(k);

 SOH_slice = SOH_data(start_idx : end_idx);

 a(k) = SOH_slice(1);
 days_elapsed = (0 : length(SOH_slice)-1)';

 SOH_diff = 1 - SOH_slice;
 Poly_term = -0.1532 .* (SOH_diff.^2) + 0.003923 .* SOH_diff + 0.9530;
 Daily_Value_Raw = Q_pack .* SOH_slice .* (Poly_term .* p_high - p_low);

 Discount_Factor = 1 ./ ((1 + r) .^ (days_elapsed / 365));
 V1(k) = sum(Daily_Value_Raw .* Discount_Factor);
end

% Sort SOH values and remove duplicate interpolation abscissae.
[a, sort_idx] = sort(a);
V1 = V1(sort_idx);

[a, unique_idx] = unique(a, 'last');
V1 = V1(unique_idx);

if numel(a) < 2
 error('Too few unique SOH points remain for constructing the reuse-value curve.');
end

% Linearly extrapolate from the last two observed SOH points to SOH = 1.
if max(a) < 1.0
 a_old = a;
 V1_old = V1;

 slope = (V1_old(end) - V1_old(end-1)) / ...
 (a_old(end) - a_old(end-1));

 V1_at_1 = V1_old(end) + slope * (1.0 - a_old(end));

 a = [a_old; 1.0];
 V1 = [V1_old; V1_at_1];
end


% 2.2 Define dynamic action-value functions for the three recertification pathways

C_A1_extra = 10; % extra cost for direct reuse, including transport, testing, integration, and installation
C_A2_extra = 15; % extra cost for refurbishment, including disassembly, labor, regrouping, and retesting


% Action 3: hydrometallurgical recycling value function based on stoichiometric reactions
Y_Li2CO3_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_Li2CO3_half .* Rec_Rate_Chem;
Y_H2SO4_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_H2SO4;
Y_H2O2_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_H2O2;
Y_Na2CO3_func = @(soh) (PosAcMass / M_LiFePO4) .* (soh ./ 2) .* M_Na2CO3;

calc_V_reuse_base = @(soh) interp1(a, V1, soh, 'linear', 'extrap');
calc_V_reuse = @(soh) calc_V_reuse_base(soh) - C_A1_extra;

calc_C_refurbish = @(soh) C0 + C1 .* (1 - soh).^gamma;
calc_V_refurbish_base = @(soh) ...
 calc_V_reuse_base(min(soh + beta_refurbish .* (1 - soh), 1.0)) - calc_C_refurbish(soh);
calc_V_refurbish = @(soh) calc_V_refurbish_base(soh) - C_A1_extra - C_A2_extra;

calc_V_recycle = @(soh) M_pack .* Exchange_Rate .* ( ...
 (Y_Li2CO3_func(soh) .* P_Li2CO3 + Base_Y_FePO4 .* P_FePO4 + Base_Y_Graphite .* P_Graphite + Base_Y_Al .* P_Al + Base_Y_Cu .* P_Cu) ...
 - (Y_H2SO4_func(soh) .* P_H2SO4 + Y_H2O2_func(soh) .* P_H2O2 + Y_Na2CO3_func(soh) .* P_Na2CO3) ...
 - (PosAcMass .* C_Degraded + Fixed_Op_Cost) ...
 );



%% 3. Load k-dependent residual-error extrapolation model

error_model_file = cfg.residual_file;

if ~isfile(error_model_file)
 error('Part3 residual-error model file not found: %s', error_model_file);
end

ErrorModel = load(error_model_file);

required_error_vars = { ...
 'k_emp', ...
 'k_vals', ...
 'err_cell', ...
 'rmse_target', ...
 'w_curve', ...
 'muM_curve', ...
 'sigM_curve', ...
 'muR_curve', ...
 'sigR_curve', ...
 'region', ...
 'cfg'};

for ii = 1:numel(required_error_vars)
 if ~isfield(ErrorModel, required_error_vars{ii})
 error('Required variable "%s" was not found in %s.', ...
 required_error_vars{ii}, error_model_file);
 end
end

k_emp = ErrorModel.k_emp(:);
k_vals = ErrorModel.k_vals(:);
err_cell = ErrorModel.err_cell;

rmse_target = ErrorModel.rmse_target(:);
w_curve = ErrorModel.w_curve(:);
muM_curve = ErrorModel.muM_curve(:);
sigM_curve = ErrorModel.sigM_curve(:);
muR_curve = ErrorModel.muR_curve(:);
sigR_curve = ErrorModel.sigR_curve(:);

region = ErrorModel.region;

if isfield(ErrorModel.cfg, 'k_anchor')
 k_anchor = ErrorModel.cfg.k_anchor;
else
 k_anchor = 21;
end

if isfield(ErrorModel.cfg, 'k_bridge_end')
 k_bridge_end = ErrorModel.cfg.k_bridge_end;
else
 k_bridge_end = 26;
end

if max(k_vals) < 50
 error(['The loaded residual-error model only covers k = %d to %d. ', ...
 'Please rerun P3_Exp03_label_dependent_residual_extrapolation.m with a larger cfg.k_extrap_max.'], ...
 min(k_vals), max(k_vals));
end

if numel(k_vals) ~= numel(rmse_target) || ...
 numel(k_vals) ~= numel(w_curve) || ...
 numel(k_vals) ~= numel(muM_curve) || ...
 numel(k_vals) ~= numel(sigM_curve) || ...
 numel(k_vals) ~= numel(muR_curve) || ...
 numel(k_vals) ~= numel(sigR_curve)
 error('The loaded residual-error model has inconsistent curve lengths.');
end

N_sim = 100000;
rng(42);

base_u = rand(N_sim, 1);
base_z = randn(N_sim, 1);
base_pick = rand(N_sim, 1);

fprintf('Residual-error model loaded from: %s\n', error_model_file);
fprintf('Loaded k range: %d to %d\n', min(k_vals), max(k_vals)); 


fprintf('>>> Running dense k-grid search from k = %d to %d...\n', ...
 min(k_vals), max(k_vals));

s_true = 0.4 + 0.6*rand(N_sim,1);

% Independent selector for the probability bridge in the residual
% generator. A separate stream preserves the original common-random-number
% sequence used for base_u, base_z, base_pick, and s_true.
bridge_stream = RandStream('mt19937ar', 'Seed', 1043);
base_bridge = rand(bridge_stream, N_sim, 1);

Pi_True = [calc_V_reuse(s_true), calc_V_refurbish(s_true), calc_V_recycle(s_true)];
[Pi_True_Max, True_Action_i] = max(Pi_True, [], 2);

T1_grid = 0.40 : 0.001 : 0.50;
T2_grid = 0.85 : 0.001 : 0.93;

E_L_base = zeros(length(k_vals), 1);
O_base = zeros(length(k_vals), 1);
A_base = zeros(length(k_vals), 1);
R_base = zeros(length(k_vals), 1);
T1_base = zeros(length(k_vals), 1);
T2_base = zeros(length(k_vals), 1);

for i = 1:length(k_vals)
 k_current = k_vals(i);

 sampled_noise = local_build_noise_by_k( ...
 k_current, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

 s_pred = min(max(s_true + sampled_noise, 0), 1.0);

 min_L = inf;
 for T1 = T1_grid
 for T2 = T2_grid
 if T1 >= T2
 continue;
 end

 Pred_Action_j = 3 * ones(N_sim, 1);
 Pred_Action_j(s_pred >= T1 & s_pred < T2) = 2;
 Pred_Action_j(s_pred >= T2) = 1;

 idx_pred = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_j);
 O_arr = max(Pi_True_Max - Pi_True(idx_pred), 0);

 is_G1_error = (True_Action_i == 3 & Pred_Action_j == 2) | ...
 (True_Action_i == 2 & Pred_Action_j == 3);
 is_G2_error = (True_Action_i == 1 & Pred_Action_j == 2) | ...
 (True_Action_i == 2 & Pred_Action_j == 1);

 Current_Eta = zeros(N_sim, 1);
 Current_Eta(is_G1_error) = Eta_1;
 Current_Eta(is_G2_error) = Eta_2;

 trigger_penalty = O_arr > Current_Eta;
 Excess_Loss = max(0, O_arr - Current_Eta);

 A_arr = trigger_penalty .* Lambda_A;
 R_arr = (Pred_Action_j < True_Action_i) .* trigger_penalty .* (Lambda_R .* Excess_Loss);

 E_L = mean(O_arr + A_arr + R_arr);

 if E_L < min_L
 min_L = E_L;
 O_base(i) = mean(O_arr);
 A_base(i) = mean(A_arr);
 R_base(i) = mean(R_arr);
 T1_base(i) = T1;
 T2_base(i) = T2;
 end
 end
 end
 E_L_base(i) = min_L;
end



% 4. Fixed-scale result extraction and recalculation at the optimal k*

Fixed_O = O_base * Fixed_Scale_N;
Fixed_A = A_base * Fixed_Scale_N;
Fixed_R = R_base * Fixed_Scale_N;
Fixed_Model = (k_vals .* c_pack + c_train);
Fixed_Total_Cost = Fixed_O + Fixed_A + Fixed_R + Fixed_Model;
[~, opt_k_idx] = min(Fixed_Total_Cost);
opt_k = k_vals(opt_k_idx);
opt_T1 = T1_base(opt_k_idx);
opt_T2 = T2_base(opt_k_idx);
Scale_Factor = Fixed_Scale_N / N_sim;

fprintf('>>> Extracting sample-level results at the optimal k* = %d...\n', opt_k);

% Reconstruct predicted SOH and assigned actions under the optimal k
noise_opt = local_build_noise_by_k( ...
 opt_k, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

s_pred_opt = min(max(s_true + noise_opt, 0), 1.0);

Pred_Action_opt = 3 * ones(N_sim, 1);
Pred_Action_opt(s_pred_opt >= opt_T1 & s_pred_opt < opt_T2) = 2;
Pred_Action_opt(s_pred_opt >= opt_T2) = 1;

idx_pred_opt = sub2ind([N_sim, 3], (1:N_sim)', Pred_Action_opt);
O_arr_opt = max(Pi_True_Max - Pi_True(idx_pred_opt), 0);

is_G1_opt = (True_Action_i == 3 & Pred_Action_opt == 2) | (True_Action_i == 2 & Pred_Action_opt == 3);
is_G2_opt = (True_Action_i == 1 & Pred_Action_opt == 2) | (True_Action_i == 2 & Pred_Action_opt == 1);
Eta_opt = zeros(N_sim, 1); Eta_opt(is_G1_opt) = Eta_1; Eta_opt(is_G2_opt) = Eta_2;

trigger_opt = O_arr_opt > Eta_opt;
Excess_opt = max(0, O_arr_opt - Eta_opt);

A_arr_opt = trigger_opt .* Lambda_A;
R_arr_opt = (Pred_Action_opt < True_Action_i) .* trigger_opt .* (Lambda_R .* Excess_opt);

Total_Loss_opt = O_arr_opt + A_arr_opt + R_arr_opt;
Net_Revenue_opt = Pi_True(idx_pred_opt) - A_arr_opt - R_arr_opt;


%% ================= Scale definition in tons =================
scale_ton_list = [ ...
 10; 30; 50; 100; ...
 150; 200; 300; 400; 500; 700; 900; ...
 1200; 1500; 1800; 2000];

% Convert tonnage values to pack numbers for internal calculations
N_list = max(1, round(scale_ton_list * 1000 / M_pack));

% Optional check of the actual tonnage after pack-number rounding
% scale_ton_list_actual = N_list * M_pack / 1000;

num_N = numel(N_list);
num_k = numel(k_vals);

% Precompute predicted action-allocation ratios under each k
Pred_Action_Ratio_byK = zeros(num_k, 3);

% Precompute per-pack average value contribution of the three actions under each k
A1_value_perpack_byK = zeros(num_k, 1);
A2_value_perpack_byK = zeros(num_k, 1);
A3_value_perpack_byK = zeros(num_k, 1);


for i = 1:num_k
 k_curr = k_vals(i);

 T1_curr = T1_base(i);
 T2_curr = T2_base(i);

 noise_curr = local_build_noise_by_k( ...
 k_curr, ...
 k_emp, k_anchor, k_bridge_end, ...
 err_cell, ...
 w_curve, muM_curve, sigM_curve, muR_curve, sigR_curve, rmse_target, k_vals, ...
 base_u, base_z, base_pick, base_bridge);

 s_pred_curr = min(max(s_true + noise_curr, 0), 1.0);

 Pred_Action_curr = 3 * ones(N_sim, 1);
 Pred_Action_curr(s_pred_curr >= T1_curr & s_pred_curr < T2_curr) = 2;
 Pred_Action_curr(s_pred_curr >= T2_curr) = 1;

 Pred_Action_Ratio_byK(i, 1) = mean(Pred_Action_curr == 1);
 Pred_Action_Ratio_byK(i, 2) = mean(Pred_Action_curr == 2);
 Pred_Action_Ratio_byK(i, 3) = mean(Pred_Action_curr == 3);

 A1_value_perpack_byK(i) = mean(Pi_True(:,1) .* (Pred_Action_curr == 1));
 A2_value_perpack_byK(i) = mean(Pi_True(:,2) .* (Pred_Action_curr == 2));
 A3_value_perpack_byK(i) = mean(Pi_True(:,3) .* (Pred_Action_curr == 3));
end

% Build the N-by-k cost matrix
O_Cost_NK = zeros(num_N, num_k);
A_Cost_NK = zeros(num_N, num_k);
R_Cost_NK = zeros(num_N, num_k);
Model_Cost_NK = zeros(num_N, num_k);
Total_Cost_NK = zeros(num_N, num_k);

% Store optimal results under each deployment scale
opt_idx_of_N = zeros(num_N, 1);
opt_k_of_N = zeros(num_N, 1);
opt_T1_of_N = zeros(num_N, 1);
opt_T2_of_N = zeros(num_N, 1);
opt_total_cost_of_N = zeros(num_N, 1);

opt_O_of_N = zeros(num_N, 1);
opt_A_of_N = zeros(num_N, 1);
opt_R_of_N = zeros(num_N, 1);
opt_Model_of_N = zeros(num_N, 1);

opt_Action_Ratio_of_N = zeros(num_N, 3);
opt_A1_value_of_N = zeros(num_N, 1);
opt_A2_value_of_N = zeros(num_N, 1);
opt_A3_value_of_N = zeros(num_N, 1);

Gross_action_value_LFP = zeros(num_N, 1);
Net_realized_value_LFP = zeros(num_N, 1);
Oracle_action_value_LFP = zeros(num_N, 1);
Net_value_accounting_error_LFP = zeros(num_N, 1);

% Loop over deployment scales
for iN = 1:num_N
 N_curr = N_list(iN);

 % Decision-loss costs scale linearly with deployment scale
 O_Cost_NK(iN, :) = (O_base(:)' .* N_curr);
 A_Cost_NK(iN, :) = (A_base(:)' .* N_curr);
 R_Cost_NK(iN, :) = (R_base(:)' .* N_curr);

 % Model cost follows the current setting and does not scale with N
 Model_Cost_NK(iN, :) = (k_vals(:)' .* c_pack + c_train);

 % Total cost
 Total_Cost_NK(iN, :) = O_Cost_NK(iN, :) + ...
 A_Cost_NK(iN, :) + ...
 R_Cost_NK(iN, :) + ...
 Model_Cost_NK(iN, :);

 % Identify the optimal k* under the current deployment scale
 [opt_total_cost_of_N(iN), idx_best] = min(Total_Cost_NK(iN, :));

 opt_idx_of_N(iN) = idx_best;
 opt_k_of_N(iN) = k_vals(idx_best);


 opt_T1_of_N(iN) = T1_base(idx_best);
 opt_T2_of_N(iN) = T2_base(idx_best);

 % Store the cost decomposition at the scale-specific optimum
 opt_O_of_N(iN) = O_Cost_NK(iN, idx_best);
 opt_A_of_N(iN) = A_Cost_NK(iN, idx_best);
 opt_R_of_N(iN) = R_Cost_NK(iN, idx_best);
 opt_Model_of_N(iN) = Model_Cost_NK(iN, idx_best);
 opt_Action_Ratio_of_N(iN, :) = Pred_Action_Ratio_byK(idx_best, :);
 opt_A1_value_of_N(iN) = N_curr * A1_value_perpack_byK(idx_best);
 opt_A2_value_of_N(iN) = N_curr * A2_value_perpack_byK(idx_best);
 opt_A3_value_of_N(iN) = N_curr * A3_value_perpack_byK(idx_best);

 % Executed pathway value already contains the opportunity loss.
 % Therefore, net realized value subtracts only handling/rework, risk,
 % and information-acquisition costs from the executed pathway value.
 Gross_action_value_LFP(iN) = ...
 opt_A1_value_of_N(iN) + ...
 opt_A2_value_of_N(iN) + ...
 opt_A3_value_of_N(iN);

 Net_realized_value_LFP(iN) = ...
 Gross_action_value_LFP(iN) - ...
 opt_A_of_N(iN) - ...
 opt_R_of_N(iN) - ...
 opt_Model_of_N(iN);

 % Equivalent perfect-information accounting identity.
 Oracle_action_value_LFP(iN) = N_curr * mean(Pi_True_Max);

 net_from_oracle = ...
 Oracle_action_value_LFP(iN) - ...
 opt_O_of_N(iN) - ...
 opt_A_of_N(iN) - ...
 opt_R_of_N(iN) - ...
 opt_Model_of_N(iN);

 Net_value_accounting_error_LFP(iN) = ...
 Net_realized_value_LFP(iN) - net_from_oracle;
end

net_value_tolerance_LFP = max( ...
 1e-6, ...
 1e-10 * max(max(abs(Oracle_action_value_LFP)), 1));

if max(abs(Net_value_accounting_error_LFP)) > net_value_tolerance_LFP
 error(['LFP net-value accounting identity failed. Maximum absolute ' ...
 'difference = %.6g USD.'], ...
 max(abs(Net_value_accounting_error_LFP)));
end

% Per-pack optimal cost
opt_cost_per_pack_of_N = opt_total_cost_of_N ./ N_list;

fprintf('\n>>> Scale-effect analysis completed.\n');
fprintf('>>> Pack-number range: %d to %d\n', min(N_list), max(N_list));
fprintf('>>> k* range: %d to %d\n', min(opt_k_of_N), max(opt_k_of_N));



%% ================= Figure S1: scale-k total-cost landscape =================
figure('Name', 'Scale Effect - N-K Cost Landscape', ...
 'Color', 'w', 'Position', [180, 200, 900, 520]);

Z = Total_Cost_NK / 1e4;
imagesc(k_vals, 1:num_N, Z);
set(gca, 'YDir', 'normal');

lo = prctile(Z(:), 5);
hi = prctile(Z(:), 95);
clim([lo, hi]);

base = [ ...
 40, 60, 130;
 65, 125, 190;
 90, 185, 200;
 170, 220, 160;
 245, 220, 120
 ] / 255;

x0 = linspace(0,1,size(base,1));
xq = linspace(0,1,256);
cmap = interp1(x0, base, xq, 'pchip');

colormap(cmap);

cb = colorbar;
title(cb, '10^4 USD');

hold on;
plot(opt_k_of_N, 1:num_N, 'w-', 'LineWidth', 2.0);
plot(opt_k_of_N, 1:num_N, 'wo', 'MarkerSize', 4, 'MarkerFaceColor', 'w');
hold off;

xlabel('Number of target-domain training packs, k');
ylabel('Battery Scale (ton)');
title('N-K Total Cost Landscape with Optimal K^* Ridge');

tick_idx = unique(round(linspace(1, num_N, min(num_N, 6))));
set(gca, 'YTick', tick_idx, ...
 'YTickLabel', arrayfun(@(x) sprintf('%.0f', scale_ton_list(x)), tick_idx, 'UniformOutput', false));
ylabel('Battery Scale (ton)');

savefig(gcf, cfg.fig04a);
exportgraphics(gcf, cfg.png04a, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4a: %s\n', cfg.png04a);

%% ================= Figure S1b: optimal labeling intensity across scale =================
figure('Name', 'Scale Effect - Optimal Labeling Intensity', ...
 'Color', 'w', 'Position', [220, 220, 760, 500]);

ax = gca;
hold(ax, 'on');
set(ax, 'XScale', 'log');

y_raw = opt_k_of_N(:) ./ scale_ton_list(:); % packs / ton
y_label = 'Optimal Labeled Packs per ton';

x_raw = scale_ton_list(:);
k_raw = opt_k_of_N(:);

% ===== Smooth only for visualization without changing raw data =====
xq = logspace(log10(min(x_raw)), log10(max(x_raw)), 300)';
yq = interp1(log10(x_raw), y_raw, log10(xq), 'pchip');

% ===== Regime split; the transition point can be adjusted if needed =====
x_transition = 120;

yl = [0, max(y_raw)*1.15];

% Left side: label-intensive regime
patch(ax, ...
 [min(x_raw) x_transition x_transition min(x_raw)], ...
 [yl(1) yl(1) yl(2) yl(2)], ...
 [0.82, 0.89, 0.96], ...
 'EdgeColor', 'none', 'FaceAlpha', 0.45);

% Right side: low-density plateau
patch(ax, ...
 [x_transition max(x_raw) max(x_raw) x_transition], ...
 [yl(1) yl(1) yl(2) yl(2)], ...
 [0.88, 0.93, 0.84], ...
 'EdgeColor', 'none', 'FaceAlpha', 0.40);

% Right side: low-density plateau
xline(ax, x_transition, '--', ...
 'LineWidth', 1.1, ...
 'Color', [0.35, 0.35, 0.35]);

% Transition line
plot(ax, xq, yq, '-', ...
 'LineWidth', 2.4, ...
 'Color', [0.16, 0.47, 0.78]);

% ===== Map marker size to k* using square-root compression =====
kmin = min(k_raw);
kmax = max(k_raw);

ms_min = 34;
ms_max = 95;

if kmax > kmin
 ms = ms_min + (sqrt(k_raw) - sqrt(kmin)) ./ (sqrt(kmax) - sqrt(kmin)) * (ms_max - ms_min);
else
 ms = 60 * ones(size(k_raw));
end

scatter(ax, x_raw, y_raw, ms, ...
 'o', 'filled', ...
 'MarkerFaceColor', [0.45, 0.70, 0.90], ...
 'MarkerEdgeColor', [0.16, 0.47, 0.78], ...
 'LineWidth', 1.0);

key_idx = [1, find(x_raw>=x_transition,1,'first'), numel(x_raw)];
key_idx = unique(key_idx);

for ii = 1:numel(key_idx)
 i = key_idx(ii);
 text(x_raw(i), y_raw(i), sprintf(' k^*=%d', k_raw(i)), ...
 'FontSize', 10, ...
 'Color', [0.15, 0.15, 0.15], ...
 'VerticalAlignment', 'bottom');
end

text(22, 0.78*yl(2), 'Label-intensive regime', ...
 'FontSize', 12, ...
 'Color', [0.15, 0.28, 0.42], ...
 'FontWeight', 'bold');

text(260, 0.78*yl(2), 'Low-density plateau', ...
 'FontSize', 12, ...
 'Color', [0.22, 0.40, 0.18], ...
 'FontWeight', 'bold');


k_legend = [min(k_raw), round(median(k_raw)), max(k_raw)];
k_legend = unique(k_legend, 'stable');

ms_leg = ms_min + (sqrt(k_legend) - sqrt(kmin)) ./ max((sqrt(kmax) - sqrt(kmin)), eps) * (ms_max - ms_min);


x_leg = max(x_raw) / 1.7;
y_top = yl(2) * 0.94;
dy = yl(2) * 0.075;

y_leg = y_top - (0:numel(k_legend)-1) * dy;

x_boxL = x_leg / 1.22;
x_boxR = x_leg * 1.45;
y_boxT = y_top + 0.05 * yl(2);
y_boxB = y_leg(end) - 0.06 * yl(2);

patch(ax, ...
 [x_boxL x_boxR x_boxR x_boxL], ...
 [y_boxB y_boxB y_boxT y_boxT], ...
 [1 1 1], ...
 'EdgeColor', [0.7 0.7 0.7], ...
 'FaceAlpha', 0.88, ...
 'LineWidth', 0.8);

text(ax, x_leg/1.02, y_boxT - 0.03*yl(2), 'Marker size \propto k^*', ...
 'FontSize', 10, 'Color', [0.15 0.15 0.15], ...
 'Interpreter', 'tex');

scatter(ax, repmat(x_leg, size(y_leg)), y_leg, ms_leg, ...
 'o', 'filled', ...
 'MarkerFaceColor', [0.45, 0.70, 0.90], ...
 'MarkerEdgeColor', [0.16, 0.47, 0.78], ...
 'LineWidth', 1.0);

for j = 1:numel(k_legend)
 text(ax, x_leg * 1.10, y_leg(j), sprintf('k^* = %d', k_legend(j)), ...
 'FontSize', 10, ...
 'Color', [0.15 0.15 0.15], ...
 'VerticalAlignment', 'middle');
end

grid(ax, 'on');
box(ax, 'on');
xlabel(ax, 'Battery Scale (ton)');
ylabel(ax, y_label);
title(ax, 'Optimal Labeling Intensity across Battery Scale');

xlim([min(x_raw), max(x_raw)]);
ylim(yl);

hold(ax, 'off');

savefig(gcf, cfg.fig04b);
exportgraphics(gcf, cfg.png04b, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4b: %s\n', cfg.png04b);


%% ================= Figure S2: per-pack cost breakdown as stacked ribbons =================
figure('Name', 'Scale Effect - Per-Pack Cost Breakdown (Ribbon)', ...
 'Color', 'w', 'Position', [220, 180, 1100, 560]);

ax = gca;
hold(ax, 'on');
set(ax, 'XScale', 'log');

% ===== Convert total and component costs to per-pack values =====
O_perpack = opt_O_of_N ./ N_list;
A_perpack = opt_A_of_N ./ N_list;
R_perpack = opt_R_of_N ./ N_list;
Model_perpack = opt_Model_of_N ./ N_list;
Total_perpack = opt_total_cost_of_N ./ N_list;

% ===== Use the same color palette as the original figure =====
c1 = [0.93, 0.69, 0.13]; % Opportunity Loss
c2 = [0.49, 0.18, 0.56]; % Manual Review Cost
c3 = [0.85, 0.33, 0.10]; % Liability Risk Cost
c4 = [0.00, 0.45, 0.74]; % SOH Labeling Cost

% ===== Use the same color palette as the original figure =====
x_raw = scale_ton_list(:);

% ===== Interpolate in log-x space for smoother ribbon visualization only =====
xq = logspace(log10(min(x_raw)), log10(max(x_raw)), 400)';

Oq = interp1(log10(x_raw), O_perpack(:), log10(xq), 'pchip');
Aq = interp1(log10(x_raw), A_perpack(:), log10(xq), 'pchip');
Rq = interp1(log10(x_raw), R_perpack(:), log10(xq), 'pchip');
Mq = interp1(log10(x_raw), Model_perpack(:), log10(xq), 'pchip');

% Numerical safeguard to avoid tiny negative interpolated values
Oq = max(Oq, 0);
Aq = max(Aq, 0);
Rq = max(Rq, 0);
Mq = max(Mq, 0);

% ===== Construct cumulative boundaries =====
y0 = zeros(size(xq));
y1 = Oq;
y2 = Oq + Aq;
y3 = Oq + Aq + Rq;
y4 = Oq + Aq + Rq + Mq; % total

% ===== Plot continuous stacked ribbons =====
p1 = patch(ax, [xq; flipud(xq)], [y0; flipud(y1)], c1, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.70);

p2 = patch(ax, [xq; flipud(xq)], [y1; flipud(y2)], c2, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.68);

p3 = patch(ax, [xq; flipud(xq)], [y2; flipud(y3)], c3, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.68);

p4 = patch(ax, [xq; flipud(xq)], [y3; flipud(y4)], c4, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.68);

% ===== Add boundary lines between stacked ribbons =====
plot(ax, xq, y1, '-', 'Color', c1*0.85, 'LineWidth', 1.0);
plot(ax, xq, y2, '-', 'Color', c2*0.85, 'LineWidth', 1.0);
plot(ax, xq, y3, '-', 'Color', c3*0.85, 'LineWidth', 1.0);

h_total = semilogx(ax, xq, y4, '-k', 'LineWidth', 2.6);

semilogx(ax, x_raw, Total_perpack, 'o', ...
 'LineWidth', 1.0, 'MarkerSize', 5, ...
 'Color', [0.10, 0.10, 0.10], ...
 'MarkerFaceColor', [0.20, 0.55, 0.85]);

idx_anno = [1, 4, 8, 12, 15];
idx_anno = idx_anno(idx_anno <= numel(x_raw));

for ii = 1:numel(idx_anno)
 i = idx_anno(ii);
 text(x_raw(i), Total_perpack(i), sprintf(' %.1f', Total_perpack(i)), ...
 'FontSize', 9, ...
 'Color', [0.15, 0.15, 0.15], ...
 'VerticalAlignment', 'bottom');
end

grid(ax, 'on');
box(ax, 'on');
xlabel(ax, 'Battery Scale (ton)');
ylabel(ax, 'Cost per Pack (USD)');
title(ax, 'Per-Pack Cost Breakdown under the Optimal Policy');

legend([p1 p2 p3 p4 h_total], ...
 {'Opportunity Loss', ...
 'Verification Cost', ...
 'Risk penalty', ...
 'SOH Testing Cost', ...
 'Total Cost per Pack'}, ...
 'Location', 'eastoutside');

xlim([min(x_raw), max(x_raw)]);
ylim([0, max(y4)*1.08]);

hold(ax, 'off');
savefig(gcf, cfg.fig04c);
exportgraphics(gcf, cfg.png04c, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4c: %s\n', cfg.png04c);


%% ================= Figure S4: optimal T1/T2 with dual y-axes =================
figure('Name', 'Scale Effect - Optimal Thresholds', ...
 'Color', 'w', 'Position', [160, 180, 620, 420]);

yyaxis left
h1 = semilogx(scale_ton_list, opt_T1_of_N, '-o', ...
 'LineWidth', 1.8, 'MarkerSize', 5, ...
 'Color', [0.16, 0.47, 0.78], ...
 'MarkerFaceColor', [0.45, 0.70, 0.90]);
ylabel('Optimal T_1');
ylim([0.40, 0.50]);

yyaxis right
h2 = semilogx(scale_ton_list, opt_T2_of_N, '-s', ...
 'LineWidth', 1.8, 'MarkerSize', 5, ...
 'Color', [0.75, 0.20, 0.20], ...
 'MarkerFaceColor', [0.92, 0.55, 0.55]);
ylabel('Optimal T_2');
ylim([0.88, 0.94]);

grid on; box on;
xlabel('Battery Scale (ton)');
title('Optimal T_1^* and T_2^* versus Scale');
legend([h1, h2], {'T_1^*', 'T_2^*'}, 'Location', 'best');

savefig(gcf, cfg.fig_ExD04c);
exportgraphics(gcf, cfg.png_ExD04c, 'Resolution', cfg.png_resolution);
fprintf('Saved Extended Data Fig. 4c: %s\n', cfg.png_ExD04c);

%% ================= Figure S5: optimal total cost with cost breakdown =================

figure('Name', 'Scale Effect - Optimal Total Cost with Breakdown', ...
 'Color', 'w', 'Position', [220, 180, 1100, 560]);

ax = gca;
hold(ax, 'on');
set(ax, 'XScale', 'log');

show_ton_list = [10; 30; 50; 100; 200; 300; 500; 700; 900; 1200; 2000];

idx_show = find(ismember(scale_ton_list, show_ton_list));
N_show = scale_ton_list(idx_show);

O_show = opt_O_of_N(idx_show) / 1e4;
A_show = opt_A_of_N(idx_show) / 1e4;
R_show = opt_R_of_N(idx_show) / 1e4;
Model_show = opt_Model_of_N(idx_show) / 1e4;

Total_line = opt_total_cost_of_N / 1e4;

c1 = [0.93, 0.69, 0.13]; % Opportunity Loss
c2 = [0.49, 0.18, 0.56]; % Manual Review Cost
c3 = [0.85, 0.33, 0.10]; % Liability Risk Cost
c4 = [0.00, 0.45, 0.74]; % SOH Labeling Cost

wf = 1.08;

for i = 1:numel(N_show)
 x = N_show(i);
 xL = x / wf;
 xR = x * wf;

 y0 = 0;

 % 1) Opportunity Loss
 y1 = y0 + O_show(i);
 patch(ax, [xL xR xR xL], [y0 y0 y1 y1], c1, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.92);

 % 2) Manual Review Cost
 y2 = y1 + A_show(i);
 patch(ax, [xL xR xR xL], [y1 y1 y2 y2], c2, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.92);

 % 3) Liability Risk Cost
 y3 = y2 + R_show(i);
 patch(ax, [xL xR xR xL], [y2 y2 y3 y3], c3, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.92);

 % 4) SOH Labeling Cost
 y4 = y3 + Model_show(i);
 patch(ax, [xL xR xR xL], [y3 y3 y4 y4], c4, ...
 'EdgeColor', 'none', 'FaceAlpha', 0.92);
end

h_total = semilogx(ax, scale_ton_list, Total_line, '-k', ...
 'LineWidth', 2.6);

h_marker = semilogx(ax, N_show, Total_line(idx_show), 'o', ...
 'LineWidth', 1.0, ...
 'MarkerSize', 5, ...
 'Color', [0.10, 0.10, 0.10], ...
 'MarkerFaceColor', [0.20, 0.55, 0.85]);

grid(ax, 'on');
box(ax, 'on');
xlabel(ax, 'Battery Scale (ton)');
ylabel(ax, 'Cost (10^4 USD)');
title(ax, 'Optimal Total Cost with Cost Breakdown');

h1 = patch(nan, nan, c1, 'EdgeColor', 'none');
h2 = patch(nan, nan, c2, 'EdgeColor', 'none');
h3 = patch(nan, nan, c3, 'EdgeColor', 'none');
h4 = patch(nan, nan, c4, 'EdgeColor', 'none');

legend([h1 h2 h3 h4 h_total], ...
 {'Opportunity Loss', ...
 'Manual Review Cost', ...
 'Liability Risk Cost', ...
 'SOH Labeling Cost', ...
 'Optimal Total Cost'}, ...
 'Location', 'eastoutside');

hold(ax, 'off');
savefig(gcf, cfg.fig04e);
exportgraphics(gcf, cfg.png04e, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4e: %s\n', cfg.png04e);


%% ================= Export action-allocation data for Extended Data Fig. 5 =================
A1_ton = scale_ton_list .* opt_Action_Ratio_of_N(:, 1);
A2_ton = scale_ton_list .* opt_Action_Ratio_of_N(:, 2);
A3_ton = scale_ton_list .* opt_Action_Ratio_of_N(:, 3);

ActionAllocation_Table = table( ...
 scale_ton_list(:), ...
 N_list(:), ...
 opt_k_of_N(:), ...
 opt_T1_of_N(:), ...
 opt_T2_of_N(:), ...
 opt_Action_Ratio_of_N(:, 1), ...
 opt_Action_Ratio_of_N(:, 2), ...
 opt_Action_Ratio_of_N(:, 3), ...
 A1_ton(:), ...
 A2_ton(:), ...
 A3_ton(:), ...
 'VariableNames', { ...
 'Scale_ton', ...
 'Pack_number', ...
 'Optimal_k', ...
 'T1_star', ...
 'T2_star', ...
 'A1_direct_reuse_share', ...
 'A2_refurbishment_share', ...
 'A3_recycling_share', ...
 'A1_direct_reuse_ton', ...
 'A2_refurbishment_ton', ...
 'A3_recycling_ton'});

writetable(ActionAllocation_Table, cfg.action_allocation_csv);

fprintf('Action-allocation data for Extended Data Fig. 5 saved: %s\n', ...
 cfg.action_allocation_csv);


%% ================= Figure S7: per-pack cost reduction decomposition =================
% Cost amortization effect, net information gain and total cost reduction
% Reference scale: smallest scale point

idx_ref_scale = 1;

Total_perpack = opt_total_cost_of_N ./ N_list;
Model_perpack = opt_Model_of_N ./ N_list;
Decision_perpack = (opt_O_of_N + opt_A_of_N + opt_R_of_N) ./ N_list;
Total_cost_reduction = Total_perpack(idx_ref_scale) - Total_perpack;

Cost_amortization_effect = Model_perpack(idx_ref_scale) - Model_perpack;
Net_information_gain = Decision_perpack(idx_ref_scale) - Decision_perpack;
Check_sum = Cost_amortization_effect + Net_information_gain;
Max_abs_error = max(abs(Check_sum - Total_cost_reduction));

fprintf('\n>>> Cost-reduction decomposition check: max error = %.6f USD/pack\n', Max_abs_error);

figure('Name', 'Scale Effect - Per-Pack Cost Reduction Decomposition', ...
 'Color', 'w', 'Position', [220, 220, 820, 480]);

hold on;
set(gca, 'XScale', 'log');

plot(scale_ton_list, Cost_amortization_effect, '-o', ...
 'LineWidth', 2.0, ...
 'MarkerSize', 5, ...
 'Color', [0.00, 0.45, 0.74], ...
 'MarkerFaceColor', [0.45, 0.70, 0.90]);

plot(scale_ton_list, Net_information_gain, '-s', ...
 'LineWidth', 2.0, ...
 'MarkerSize', 5, ...
 'Color', [0.85, 0.33, 0.10], ...
 'MarkerFaceColor', [0.95, 0.60, 0.35]);

plot(scale_ton_list, Total_cost_reduction, '-^', ...
 'LineWidth', 2.3, ...
 'MarkerSize', 5.5, ...
 'Color', [0.10, 0.10, 0.10], ...
 'MarkerFaceColor', [0.20, 0.20, 0.20]);

yline(0, 'k--', 'LineWidth', 0.8, 'HandleVisibility', 'off');
ylim([-5,35]);
grid on;
box on;

xlabel('Battery Scale (ton)');
ylabel('Per-pack cost reduction (USD/pack)');
title('Per-Pack Cost Reduction Decomposition');

legend({'Cost amortization effect', ...
 'Net information gain', ...
 'Total cost reduction'}, ...
 'Location', 'best');

hold off;
savefig(gcf, cfg.fig04d);
exportgraphics(gcf, cfg.png04d, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4d: %s\n', cfg.png04d);

%% ================= Figure S8: stacked action-value decomposition =================


show_ton_list = [10; 50; 100; 200; 500; 900; 2000];

idx_show = find(ismember(scale_ton_list, show_ton_list));

if numel(idx_show) ~= numel(show_ton_list)
 missing_scale = setdiff(show_ton_list, scale_ton_list);
 error('The following representative scales are missing from scale_ton_list: %s', ...
 strjoin(string(missing_scale), ', '));
end

scale_show = scale_ton_list(idx_show);

A1_val_MUSD = opt_A1_value_of_N(idx_show) ./ 1e6;
A2_val_MUSD = opt_A2_value_of_N(idx_show) ./ 1e6;
A3_val_MUSD = opt_A3_value_of_N(idx_show) ./ 1e6;

Total_action_value_MUSD = A1_val_MUSD + A2_val_MUSD + A3_val_MUSD;

ActionValue_Table = table( ...
 scale_show(:), ...
 A1_val_MUSD(:), ...
 A2_val_MUSD(:), ...
 A3_val_MUSD(:), ...
 Total_action_value_MUSD(:), ...
 100 * A1_val_MUSD(:) ./ Total_action_value_MUSD(:), ...
 100 * A2_val_MUSD(:) ./ Total_action_value_MUSD(:), ...
 100 * A3_val_MUSD(:) ./ Total_action_value_MUSD(:), ...
 'VariableNames', { ...
 'Scale_ton', ...
 'A1_value_MUSD', ...
 'A2_value_MUSD', ...
 'A3_value_MUSD', ...
 'Total_action_value_MUSD', ...
 'A1_share_percent', ...
 'A2_share_percent', ...
 'A3_share_percent'});

disp(' ');
disp('========== Scale-dependent action value decomposition ==========');
disp(ActionValue_Table);

writetable(ActionValue_Table, cfg.action_value_csv);

% Color setting: A1 = blue, A2 = green, A3 = orange.
cA1 = [0.000, 0.447, 0.741];
cA2 = [0.466, 0.674, 0.188];
cA3 = [0.850, 0.325, 0.098];

x_pos = 1:numel(scale_show);
x_lab = string(scale_show);

fig_action_stack = figure('Name', 'Scale Effect - Stacked Action Value Decomposition', ...
 'Color', 'w', ...
 'Position', [120, 120, 980, 620]);

ax = axes('Parent', fig_action_stack);
hold(ax, 'on');

Y_stack = [A1_val_MUSD(:), A2_val_MUSD(:), A3_val_MUSD(:)];

b = bar(ax, x_pos, Y_stack, 0.62, ...
 'stacked', ...
 'EdgeColor', 'none');

b(1).FaceColor = cA1;
b(2).FaceColor = cA2;
b(3).FaceColor = cA3;

ymax_main = max(Total_action_value_MUSD) * 1.25;

xlim(ax, [0.45, numel(x_pos) + 0.55]);
ylim(ax, [0, ymax_main]);

% Add total action-value labels above each bar.
for ii = 1:numel(x_pos)

 text(ax, x_pos(ii), ...
 Total_action_value_MUSD(ii) + 0.035 * ymax_main, ...
 sprintf('%.2f', Total_action_value_MUSD(ii)), ...
 'HorizontalAlignment', 'center', ...
 'VerticalAlignment', 'bottom', ...
 'FontName', 'Arial', ...
 'FontSize', 11, ...
 'FontWeight', 'bold', ...
 'Color', [0.10, 0.10, 0.10]);
end

% Add A1/A2 labels.
% For small scales, labels are placed outside the bars to avoid crowding.
% For larger scales, labels are placed inside the corresponding stacked blocks.
idx_large = find(scale_show >= 200);
idx_small = find(ismember(scale_show, [10; 50; 100]));

for jj = 1:numel(idx_large)

 ii = idx_large(jj);

 if A1_val_MUSD(ii) > 0
 text(ax, x_pos(ii), ...
 0.50 * A1_val_MUSD(ii), ...
 sprintf('%.2f', A1_val_MUSD(ii)), ...
 'HorizontalAlignment', 'center', ...
 'VerticalAlignment', 'middle', ...
 'FontName', 'Arial', ...
 'FontSize', 10, ...
 'FontWeight', 'bold', ...
 'Color', 'w');
 end

 if A2_val_MUSD(ii) > 0
 text(ax, x_pos(ii), ...
 A1_val_MUSD(ii) + 0.50 * A2_val_MUSD(ii), ...
 sprintf('%.2f', A2_val_MUSD(ii)), ...
 'HorizontalAlignment', 'center', ...
 'VerticalAlignment', 'middle', ...
 'FontName', 'Arial', ...
 'FontSize', 10, ...
 'FontWeight', 'bold', ...
 'Color', 'w');
 end
end

for jj = 1:numel(idx_small)

 ii = idx_small(jj);

 y_base = Total_action_value_MUSD(ii) + 0.075 * ymax_main;

 text(ax, x_pos(ii) - 0.18, y_base, ...
 sprintf('A1 %.3f', A1_val_MUSD(ii)), ...
 'HorizontalAlignment', 'right', ...
 'VerticalAlignment', 'bottom', ...
 'FontName', 'Arial', ...
 'FontSize', 8.5, ...
 'FontWeight', 'bold', ...
 'Color', cA1);

 text(ax, x_pos(ii) + 0.18, y_base, ...
 sprintf('A2 %.3f', A2_val_MUSD(ii)), ...
 'HorizontalAlignment', 'left', ...
 'VerticalAlignment', 'bottom', ...
 'FontName', 'Arial', ...
 'FontSize', 8.5, ...
 'FontWeight', 'bold', ...
 'Color', cA2);
end

grid(ax, 'on');
box(ax, 'on');

set(ax, ...
 'XTick', x_pos, ...
 'XTickLabel', x_lab, ...
 'FontName', 'Arial', ...
 'FontSize', 13, ...
 'LineWidth', 1.1, ...
 'GridAlpha', 0.22);

xlabel(ax, 'Retired battery scale (ton)');
ylabel(ax, 'Action value (million USD)');
title(ax, 'Scale-dependent action-value decomposition');

legend(ax, b, ...
 {'A_1: Direct reuse', 'A_2: Refurbishment', 'A_3: Recycling'}, ...
 'Location', 'northwest', ...
 'Box', 'off');

hold(ax, 'off');
savefig(fig_action_stack, cfg.fig04f);
exportgraphics(fig_action_stack, cfg.png04f, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4f: %s\n', cfg.png04f);

%% ================= Figure S9: magnified A3 recycling value =================
% This separate panel magnifies the A3 recycling value because the A3
% contribution is much smaller than the A1 and A2 value components in the
% stacked action-value panel.

A3Inset_Table = table( ...
 scale_show(:), ...
 A3_val_MUSD(:), ...
 'VariableNames', { ...
 'Scale_ton', ...
 'A3_value_MUSD'});

disp(' ');
disp('========== A3 recycling value inset data ==========');
disp(A3Inset_Table);

writetable(A3Inset_Table, cfg.a3_inset_csv);

fig_A3_inset = figure('Name', 'Scale Effect - A3 Recycling Value Magnified', ...
 'Color', 'w', ...
 'Position', [150, 150, 560, 420]);

ax = axes('Parent', fig_A3_inset);
hold(ax, 'on');

bar(ax, x_pos, A3_val_MUSD, 0.62, ...
 'FaceColor', cA3, ...
 'EdgeColor', 'none');

% Use a fixed upper limit when the A3 range is small, while keeping a
% safeguard in case future runs produce a larger A3 contribution.
ymax_A3 = max(0.30, max(A3_val_MUSD) * 1.35);
ylim(ax, [0, ymax_A3]);

for ii = 1:numel(x_pos)

 y_text = A3_val_MUSD(ii) + 0.035 * ymax_A3;

 text(ax, x_pos(ii), y_text, ...
 sprintf('%.3f', A3_val_MUSD(ii)), ...
 'HorizontalAlignment', 'center', ...
 'VerticalAlignment', 'bottom', ...
 'FontName', 'Arial', ...
 'FontSize', 10, ...
 'FontWeight', 'bold', ...
 'Color', cA3);
end

grid(ax, 'on');
box(ax, 'on');

set(ax, ...
 'XTick', x_pos, ...
 'XTickLabel', x_lab, ...
 'FontName', 'Arial', ...
 'FontSize', 12, ...
 'LineWidth', 1.0, ...
 'GridAlpha', 0.20);

xlabel(ax, 'Retired battery scale (ton)');
ylabel(ax, 'A_3 value (million USD)');
title(ax, 'A_3 recycling value magnified', ...
 'FontSize', 14, ...
 'FontWeight', 'bold', ...
 'Color', cA3);

hold(ax, 'off');
savefig(fig_A3_inset, cfg.fig04f_inset);
exportgraphics(fig_A3_inset, cfg.png04f_inset, 'Resolution', cfg.png_resolution);
fprintf('Saved Main Fig. 4f inset: %s\n', cfg.png04f_inset);


%% ================= Save LFP scale-effect tables and figures =================
scale_pack_list_LFP = N_list;
k_opt_of_scale_ton_LFP = opt_k_of_N;

Summary_Table = table( ...
 scale_ton_list(:), ...
 scale_pack_list_LFP(:), ...
 opt_k_of_N(:), ...
 opt_T1_of_N(:), ...
 opt_T2_of_N(:), ...
 opt_total_cost_of_N(:), ...
 opt_cost_per_pack_of_N(:), ...
 opt_O_of_N(:), ...
 opt_A_of_N(:), ...
 opt_R_of_N(:), ...
 opt_Model_of_N(:), ...
 opt_Action_Ratio_of_N(:, 1), ...
 opt_Action_Ratio_of_N(:, 2), ...
 opt_Action_Ratio_of_N(:, 3), ...
 opt_A1_value_of_N(:), ...
 opt_A2_value_of_N(:), ...
 opt_A3_value_of_N(:), ...
 Gross_action_value_LFP(:), ...
 Net_realized_value_LFP(:), ...
 Oracle_action_value_LFP(:), ...
 Net_value_accounting_error_LFP(:), ...
 'VariableNames', { ...
 'Scale_ton', ...
 'Pack_number', ...
 'Optimal_k', ...
 'T1_star', ...
 'T2_star', ...
 'Total_cost_USD', ...
 'Total_cost_per_pack_USD', ...
 'Opportunity_loss_USD', ...
 'Manual_review_cost_USD', ...
 'Risk_penalty_USD', ...
 'SOH_labeling_training_cost_USD', ...
 'A1_direct_reuse_share', ...
 'A2_refurbishment_share', ...
 'A3_recycling_share', ...
 'A1_direct_reuse_value_USD', ...
 'A2_refurbishment_value_USD', ...
 'A3_recycling_value_USD', ...
 'Gross_executed_action_value_USD', ...
 'Net_realized_value_USD', ...
 'Perfect_information_action_value_USD', ...
 'Net_value_accounting_error_USD'});

writetable(Summary_Table, cfg.summary_csv);

fprintf('Summary table saved: %s\n', cfg.summary_csv);
fprintf('Action-value table saved: %s\n', cfg.action_value_csv);


%% ================= Save LFP scale-effect results for plotting and NMC extension =================
save(cfg.result_mat, ...
 'cfg', ...
 'Summary_Table', ...
 'ActionValue_Table', ...
 'ActionAllocation_Table', ...
 'A3Inset_Table', ...
 'scale_ton_list', ...
 'scale_pack_list_LFP', ...
 'k_opt_of_scale_ton_LFP', ...
 'k_vals', ...
 'opt_idx_of_N', ...
 'opt_k_of_N', ...
 'Total_Cost_NK', ...
 'O_Cost_NK', ...
 'A_Cost_NK', ...
 'R_Cost_NK', ...
 'Model_Cost_NK', ...
 'opt_cost_per_pack_of_N', ...
 'opt_T1_of_N', ...
 'opt_T2_of_N', ...
 'opt_total_cost_of_N', ...
 'opt_O_of_N', ...
 'opt_A_of_N', ...
 'opt_R_of_N', ...
 'opt_Model_of_N', ...
 'opt_Action_Ratio_of_N', ...
 'A1_ton', ...
 'A2_ton', ...
 'A3_ton', ...
 'opt_A1_value_of_N', ...
 'opt_A2_value_of_N', ...
 'opt_A3_value_of_N', ...
 'Gross_action_value_LFP', ...
 'Net_realized_value_LFP', ...
 'Oracle_action_value_LFP', ...
 'Net_value_accounting_error_LFP', ...
 'net_value_tolerance_LFP', ...
 'Pred_Action_Ratio_byK', ...
 'A1_value_perpack_byK', ...
 'A2_value_perpack_byK', ...
 'A3_value_perpack_byK', ...
 'O_base', ...
 'A_base', ...
 'R_base', ...
 'E_L_base', ...
 'T1_base', ...
 'T2_base', ...
 'rmse_target', ...
 'w_curve', ...
 'muM_curve', ...
 'sigM_curve', ...
 'muR_curve', ...
 'sigR_curve', ...
 'k_emp', ...
 'k_anchor', ...
 'k_bridge_end', ...
 'base_bridge', ...
 '-v7.3');

save(cfg.workspace_mat, '-v7.3');

fprintf('Result MAT file saved: %s\n', cfg.result_mat);
fprintf('Workspace MAT file saved: %s\n', cfg.workspace_mat);
fprintf('================ Part5 Exp01 completed ================\n');
