% P5_Exp04_LFP_FixedKBenchmark_Heatmap.m
%
% Purpose:
% This script generates Main Fig. 4g for the LFP scale-dependent
% fixed-k benchmark.
%
% It compares five fixed label-size policies, k = 5, 15, 25, 35, and 50,
% against the scale-dependent optimized policy under each deployment scale.


clear; clc; close all;

set(groot, 'DefaultFigureVisible', 'on');

%% 0. Path configuration

cfg = struct();

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.main_fig_dir = fullfile(cfg.figure_root, 'Main');

% Primary LFP scale-dependent result generated by Part5 Exp01.
cfg.lfp_result_primary = fullfile(cfg.results_dir, ...
    'P5_Exp01_ScaleDependent_LFP_Results.mat');

% Legacy fallback path.
cfg.lfp_result_legacy = fullfile(cfg.output_dir, ...
    'Result01_ScaleEffect_LFP_Results.mat');

% Main Fig. 4g output files.
cfg.output_table_csv = fullfile(cfg.results_dir, ...
    'P5_Exp04_LFP_FixedKBenchmark_Table.csv');

cfg.output_data_mat = fullfile(cfg.results_dir, ...
    'P5_Exp04_LFP_FixedKBenchmark_Data.mat');

cfg.output_fig = fullfile(cfg.main_fig_dir, ...
    'MainFig04g_LFP_FixedKBenchmark_Heatmap.fig');

cfg.output_png = fullfile(cfg.main_fig_dir, ...
    'MainFig04g_LFP_FixedKBenchmark_Heatmap.png');

cfg.png_resolution = 600;

% Benchmark settings.
benchmark_k = [5; 15; 25; 35; 50];

% Plot settings.
show_cell_values = false;
use_log_color = true;
color_floor_million = 1e-4;
color_ceiling_million = 2e-1;

% Use "sky" if your MATLAB version supports it.
% If your MATLAB reports an error for colormap("sky"), change this to "parula".
colormap_name = "sky";

%% 1. Create output folders

folder_list = {cfg.results_dir, cfg.figure_root, cfg.main_fig_dir};

for ii = 1:numel(folder_list)

    if ~exist(folder_list{ii}, 'dir')
        mkdir(folder_list{ii});
    end
end

%% 2. Locate and load LFP scale-dependent result

if isfile(cfg.lfp_result_primary)

    cfg.input_file = cfg.lfp_result_primary;

elseif isfile(cfg.lfp_result_legacy)

    cfg.input_file = cfg.lfp_result_legacy;

else

    error(['LFP scale-dependent result file not found.\n' ...
        'Checked:\n%s\n%s\n' ...
        'Please run Part5 Exp01 first.'], ...
        cfg.lfp_result_primary, ...
        cfg.lfp_result_legacy);
end

fprintf('================ Main Fig. 4g LFP fixed-k benchmark ================\n');
fprintf('Input file: %s\n', cfg.input_file);

S = load(cfg.input_file);

% Some result files save variables directly, while others save a result
% structure. This block tries to identify the correct source automatically.
R = S;

field_names = fieldnames(S);

for ii = 1:numel(field_names)

    field_now = field_names{ii};

    if isstruct(S.(field_now)) && ...
            isfield(S.(field_now), 'scale_ton_list') && ...
            isfield(S.(field_now), 'Total_Cost_NK')

        R = S.(field_now);
        fprintf('Using result structure: %s\n', field_now);
        break;
    end
end

%% 3. Read required variables

if isfield(R, 'scale_ton_list')
    scale_ton_list = R.scale_ton_list(:);
else
    error('scale_ton_list is missing from the LFP scale-dependent result.');
end

if isfield(R, 'k_vals')
    k_vals = R.k_vals(:);
else
    error('k_vals is missing from the LFP scale-dependent result.');
end

if isfield(R, 'N_list')
    N_list = R.N_list(:);
elseif isfield(R, 'N_list_LFP')
    N_list = R.N_list_LFP(:);
elseif isfield(R, 'scale_pack_list_LFP')
    N_list = R.scale_pack_list_LFP(:);
else
    error(['Pack-number list is missing from the LFP scale-dependent result. ' ...
        'Expected N_list, N_list_LFP, or scale_pack_list_LFP.']);
end

if isfield(R, 'Total_Cost_NK')
    Total_Cost_NK = R.Total_Cost_NK;
elseif isfield(R, 'Total_Cost_NK_LFP')
    Total_Cost_NK = R.Total_Cost_NK_LFP;
else
    error('Total_Cost_NK is missing from the LFP scale-dependent result.');
end

scale_ton_list = double(scale_ton_list);
k_vals = double(k_vals);
N_list = double(N_list);
Total_Cost_NK = double(Total_Cost_NK);

n_scale = numel(scale_ton_list);
n_k = numel(k_vals);
n_benchmark = numel(benchmark_k);

%% 4. Ensure Total_Cost_NK is scale-by-k

Total_Cost_NK = squeeze(Total_Cost_NK);

if isequal(size(Total_Cost_NK), [n_scale, n_k])

    fprintf('Cost matrix orientation: scale x k\n');

elseif isequal(size(Total_Cost_NK), [n_k, n_scale])

    Total_Cost_NK = Total_Cost_NK.';
    fprintf('Cost matrix orientation: k x scale, transposed to scale x k\n');

else

    error(['Unexpected Total_Cost_NK size: [%d, %d]. Expected [%d, %d] ' ...
        'or [%d, %d].'], ...
        size(Total_Cost_NK, 1), size(Total_Cost_NK, 2), ...
        n_scale, n_k, n_k, n_scale);
end

if numel(N_list) ~= n_scale
    error('The length of N_list is inconsistent with scale_ton_list.');
end

%% 5. Recompute optimized policy from the saved scale-by-k cost matrix

[opt_total_cost, opt_k_idx] = min(Total_Cost_NK, [], 2);

opt_k = k_vals(opt_k_idx);
opt_cost_per_pack = opt_total_cost ./ N_list;

fprintf('>>> LFP scale points: %d\n', n_scale);
fprintf('>>> k range: %.0f to %.0f\n', min(k_vals), max(k_vals));
fprintf('>>> Benchmark k values:\n');
disp(benchmark_k.');
fprintf('>>> Optimized k sequence:\n');
disp(opt_k.');

%% 6. Extract fixed-k benchmark policies

benchmark_cost = zeros(n_scale, n_benchmark);
benchmark_cost_per_pack = zeros(n_scale, n_benchmark);

additional_cost = zeros(n_scale, n_benchmark);
additional_cost_per_pack = zeros(n_scale, n_benchmark);
relative_saving_percent = zeros(n_scale, n_benchmark);

benchmark_k_idx = zeros(n_benchmark, 1);

for bb = 1:n_benchmark

    k_ref = benchmark_k(bb);

    idx_now = find(k_vals == k_ref, 1, 'first');

    if isempty(idx_now)
        error('Benchmark k = %.0f is not available in k_vals.', k_ref);
    end

    benchmark_k_idx(bb) = idx_now;

    benchmark_cost(:, bb) = Total_Cost_NK(:, idx_now);
    benchmark_cost_per_pack(:, bb) = benchmark_cost(:, bb) ./ N_list;

    additional_cost(:, bb) = benchmark_cost(:, bb) - opt_total_cost;
    additional_cost_per_pack(:, bb) = additional_cost(:, bb) ./ N_list;

    relative_saving_percent(:, bb) = ...
        100 .* additional_cost(:, bb) ./ max(benchmark_cost(:, bb), eps);
end

% Numerical cleanup.
additional_cost(abs(additional_cost) < 1e-9) = 0;
additional_cost_per_pack(abs(additional_cost_per_pack) < 1e-12) = 0;
relative_saving_percent(abs(relative_saving_percent) < 1e-10) = 0;

additional_cost_million = additional_cost ./ 1e6;

%% 7. Build formal output table

Scale_ton_col = repmat(scale_ton_list, n_benchmark, 1);
Pack_number_col = repmat(N_list, n_benchmark, 1);
Optimized_k_col = repmat(opt_k, n_benchmark, 1);
Optimized_total_cost_col = repmat(opt_total_cost, n_benchmark, 1);
Optimized_cost_per_pack_col = repmat(opt_cost_per_pack, n_benchmark, 1);

Reference_k_col = zeros(n_scale * n_benchmark, 1);
Reference_total_cost_col = zeros(n_scale * n_benchmark, 1);
Reference_cost_per_pack_col = zeros(n_scale * n_benchmark, 1);
Additional_cost_col = zeros(n_scale * n_benchmark, 1);
Additional_cost_million_col = zeros(n_scale * n_benchmark, 1);
Additional_cost_per_pack_col = zeros(n_scale * n_benchmark, 1);
Relative_saving_percent_col = zeros(n_scale * n_benchmark, 1);

row_start = 1;

for bb = 1:n_benchmark

    row_end = row_start + n_scale - 1;

    Reference_k_col(row_start:row_end) = benchmark_k(bb);
    Reference_total_cost_col(row_start:row_end) = benchmark_cost(:, bb);
    Reference_cost_per_pack_col(row_start:row_end) = benchmark_cost_per_pack(:, bb);
    Additional_cost_col(row_start:row_end) = additional_cost(:, bb);
    Additional_cost_million_col(row_start:row_end) = additional_cost_million(:, bb);
    Additional_cost_per_pack_col(row_start:row_end) = additional_cost_per_pack(:, bb);
    Relative_saving_percent_col(row_start:row_end) = relative_saving_percent(:, bb);

    row_start = row_end + 1;
end

P5_Exp04_LFP_FixedKBenchmark_Table = table( ...
    Scale_ton_col, ...
    Pack_number_col, ...
    Optimized_k_col, ...
    Optimized_total_cost_col, ...
    Optimized_cost_per_pack_col, ...
    Reference_k_col, ...
    Reference_total_cost_col, ...
    Reference_cost_per_pack_col, ...
    Additional_cost_col, ...
    Additional_cost_million_col, ...
    Additional_cost_per_pack_col, ...
    Relative_saving_percent_col, ...
    'VariableNames', { ...
    'Scale_ton', ...
    'Pack_number', ...
    'Optimized_k', ...
    'Optimized_total_cost_USD', ...
    'Optimized_cost_per_pack_USD', ...
    'Reference_k', ...
    'Reference_total_cost_USD', ...
    'Reference_cost_per_pack_USD', ...
    'Additional_cost_USD', ...
    'Additional_cost_million_USD', ...
    'Additional_cost_per_pack_USD', ...
    'Relative_saving_percent'});

disp(' ');
disp('========== Main Fig. 4g LFP fixed-k benchmark table preview ==========');
disp(P5_Exp04_LFP_FixedKBenchmark_Table( ...
    1:min(12, height(P5_Exp04_LFP_FixedKBenchmark_Table)), :));

%% 8. Prepare heat map matrix for log color scale

% Raw data are kept unchanged in additional_cost_million.
% For log-color plotting, non-positive values are replaced only in the
% plotting matrix.
plot_matrix_million = additional_cost_million.';

if use_log_color

    plot_matrix_million(plot_matrix_million <= 0) = color_floor_million;
end

%% 9. Plot Main Fig. 4g heat map

fig_heatmap = figure('Name', 'Main Fig. 4g - LFP fixed-k benchmark heat map', ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [4, 4, 18, 6.2]);

imagesc(plot_matrix_million);

ax = gca;

try
    colormap(colormap_name);
catch
    warning('Colormap "%s" is not supported. Falling back to parula.', colormap_name);
    colormap(parula);
end

cb = colorbar;
cb.Label.String = 'Total additional cost (million USD)';
cb.Label.FontName = 'Arial';
cb.FontName = 'Arial';
cb.FontSize = 9;

if use_log_color
    set(ax, 'ColorScale', 'log');
    clim([color_floor_million, color_ceiling_million]);
else
    clim([0, max(additional_cost_million(:))]);
end

set(ax, ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'LineWidth', 0.8, ...
    'TickDir', 'out');

box on;

set(ax, 'XTick', 1:n_scale);
set(ax, 'XTickLabel', arrayfun(@(x) sprintf('%.0f', x), ...
    scale_ton_list, 'UniformOutput', false));

set(ax, 'YTick', 1:n_benchmark);
set(ax, 'YTickLabel', arrayfun(@(k) sprintf('Fixed k = %d', k), ...
    benchmark_k, 'UniformOutput', false));

xlabel('Battery scale (ton)', 'FontName', 'Arial', 'FontSize', 10);
ylabel('Fixed benchmark policy', 'FontName', 'Arial', 'FontSize', 10);

title('LFP fixed-k regret benchmark', ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'normal');

xtickangle(45);

%% 10. Add optional value labels to heat map cells

if show_cell_values

    if use_log_color
        color_mid = sqrt(color_floor_million * color_ceiling_million);
    else
        color_mid = mean(clim);
    end

    for bb = 1:n_benchmark

        for ss = 1:n_scale

            value_now = additional_cost_million(ss, bb);
            plot_value_now = plot_matrix_million(bb, ss);

            if plot_value_now >= color_mid
                text_color = 'w';
            else
                text_color = 'k';
            end

            if value_now > 0 && value_now < 0.001
                label_now = '<0.001';
            else
                label_now = sprintf('%.3f', value_now);
            end

            text(ss, bb, label_now, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', ...
                'FontName', 'Arial', ...
                'FontSize', 7.5, ...
                'Color', text_color);
        end
    end
end

%% 11. Save figure and data

savefig(fig_heatmap, cfg.output_fig);
exportgraphics(fig_heatmap, cfg.output_png, 'Resolution', cfg.png_resolution);

writetable(P5_Exp04_LFP_FixedKBenchmark_Table, cfg.output_table_csv);

save(cfg.output_data_mat, ...
    'cfg', ...
    'scale_ton_list', ...
    'N_list', ...
    'k_vals', ...
    'benchmark_k', ...
    'benchmark_k_idx', ...
    'Total_Cost_NK', ...
    'opt_total_cost', ...
    'opt_cost_per_pack', ...
    'opt_k', ...
    'benchmark_cost', ...
    'benchmark_cost_per_pack', ...
    'additional_cost', ...
    'additional_cost_million', ...
    'additional_cost_per_pack', ...
    'relative_saving_percent', ...
    'plot_matrix_million', ...
    'P5_Exp04_LFP_FixedKBenchmark_Table');

%% 12. Print key values

fprintf('\n========== Main Fig. 4g LFP fixed-k benchmark key values ==========\n');

for bb = 1:n_benchmark

    [max_total_additional_cost, idx_max] = max(additional_cost(:, bb));

    fprintf('Fixed k = %d:\n', benchmark_k(bb));
    fprintf('  Maximum total additional cost: %.4f million USD at %.0f tons\n', ...
        max_total_additional_cost / 1e6, scale_ton_list(idx_max));
    fprintf('  Total additional cost at largest scale %.0f tons: %.4f million USD\n', ...
        scale_ton_list(end), additional_cost(end, bb) / 1e6);
end

fprintf('\nSaved table: %s\n', cfg.output_table_csv);
fprintf('Saved data:  %s\n', cfg.output_data_mat);
fprintf('Saved figure FIG: %s\n', cfg.output_fig);
fprintf('Saved figure PNG: %s\n', cfg.output_png);


fprintf('================ Main Fig. 4g LFP fixed-k benchmark completed ================\n');