%% P3_Exp02_label_dependent_error_summary.m
% Purpose:
% This script summarizes and visualizes the label-dependent prediction-error
% behavior from the Part3 nested-resampling experiment.
%
% It reads the final nested-resampling result generated by
% P3_Exp01_NestedResampling_ErrorEvaluation.m and exports k-dependent
% prediction-error metrics and Extended Data Fig. 2 panels.

clc; clear; close all;

%% 1) Configuration
cfg = struct();

% Use the current script folder as the Part3 root folder.
script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

% Root folders.
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_dir = fullfile(script_dir, 'Figures');
cfg.ext_fig_dir = fullfile(cfg.figure_dir, 'Extended');

% Create output folders if they do not exist.
if ~exist(cfg.output_dir, 'dir')
    mkdir(cfg.output_dir);
end

if ~exist(cfg.results_dir, 'dir')
    mkdir(cfg.results_dir);
end

if ~exist(cfg.figure_dir, 'dir')
    mkdir(cfg.figure_dir);
end

if ~exist(cfg.ext_fig_dir, 'dir')
    mkdir(cfg.ext_fig_dir);
end

% Input file generated by Part3 Exp01.
% The primary path follows the new naming convention.
cfg.input_mat_primary = fullfile(cfg.results_dir, 'P3_Exp01_NestedResampling_Final.mat');

% Legacy fallback path for the existing long-running Main01 output.
% Keep this fallback to avoid rerunning the one-week nested-resampling experiment.
cfg.input_mat_legacy = fullfile(cfg.output_dir, ...
    'Result01_NestedResampling_Final.mat');

if exist(cfg.input_mat_primary, 'file')
    cfg.input_mat = cfg.input_mat_primary;
elseif exist(cfg.input_mat_legacy, 'file')
    cfg.input_mat = cfg.input_mat_legacy;
else
    error('Input file not found. Checked:\n%s\n%s', ...
        cfg.input_mat_primary, cfg.input_mat_legacy);
end

% Output summary table generated by Part3 Exp02.
cfg.summary_csv = fullfile(cfg.results_dir, ...
    'P3_Exp02_LabelDependentErrorSummary_Metrics.csv');

% Output figure files for Extended Data Fig. 2.
cfg.fig_panel_B = fullfile(cfg.ext_fig_dir, ...
    'ExD02b_label_dependent_RMSE_MAE_decay.fig');
cfg.png_panel_B = fullfile(cfg.ext_fig_dir, ...
    'ExD02b_label_dependent_RMSE_MAE_decay.png');

cfg.fig_panel_C = fullfile(cfg.ext_fig_dir, ...
    'ExD02c_representative_RMSE_distribution.fig');
cfg.png_panel_C = fullfile(cfg.ext_fig_dir, ...
    'ExD02c_representative_RMSE_distribution.png');

cfg.fig_panel_D_few = fullfile(cfg.ext_fig_dir, ...
    'ExD02d_prediction_cloud_few_labels.fig');
cfg.png_panel_D_few = fullfile(cfg.ext_fig_dir, ...
    'ExD02d_prediction_cloud_few_labels.png');

cfg.fig_panel_D_medium = fullfile(cfg.ext_fig_dir, ...
    'ExD02e_prediction_cloud_medium_labels.fig');
cfg.png_panel_D_medium = fullfile(cfg.ext_fig_dir, ...
    'ExD02e_prediction_cloud_medium_labels.png');

cfg.fig_panel_D_large = fullfile(cfg.ext_fig_dir, ...
    'ExD02f_prediction_cloud_large_labels.fig');
cfg.png_panel_D_large = fullfile(cfg.ext_fig_dir, ...
    'ExD02f_prediction_cloud_large_labels.png');

% Export settings.
cfg.png_resolution = 600;

fprintf('================ Part3 Exp02 label-dependent error summary ================\n');
fprintf('Input result file: %s\n', cfg.input_mat);
fprintf('Summary CSV file:  %s\n', cfg.summary_csv);
fprintf('Extended figure folder: %s\n', cfg.ext_fig_dir);

%% 2) Load nested-resampling result file
if ~exist(cfg.input_mat, 'file')
    error('Input file not found: %s', cfg.input_mat);
end

D = load(cfg.input_mat);

required_vars = { ...
    'train_size_list', ...
    'res_RMSE_outer', ...
    'res_MAE_outer', ...
    'pool_y_true_per_size', ...
    'pool_y_pred_per_size'};

for i = 1:numel(required_vars)
    if ~isfield(D, required_vars{i})
        error('Required variable "%s" was not found in %s.', ...
            required_vars{i}, cfg.input_mat);
    end
end

train_size_list = D.train_size_list(:);
res_RMSE_outer = D.res_RMSE_outer;
res_MAE_outer = D.res_MAE_outer;

if isfield(D, 'res_MAPE_outer')
    res_MAPE_outer = D.res_MAPE_outer;
else
    res_MAPE_outer = nan(size(res_RMSE_outer));
end

pool_y_true_per_size = D.pool_y_true_per_size;
pool_y_pred_per_size = D.pool_y_pred_per_size;

% Determine completed outer repetitions.
if isfield(D, 'b')
    completed_repeats = min(double(D.b), size(res_RMSE_outer, 2));
else
    valid_cols = any(res_RMSE_outer ~= 0, 1);

    if any(valid_cols)
        completed_repeats = find(valid_cols, 1, 'last');
    else
        completed_repeats = size(res_RMSE_outer, 2);
    end
end

completed_repeats = max(1, completed_repeats);

res_RMSE_outer = res_RMSE_outer(:, 1:completed_repeats);
res_MAE_outer = res_MAE_outer(:, 1:completed_repeats);
res_MAPE_outer = res_MAPE_outer(:, 1:completed_repeats);

fprintf('Nested-resampling result loaded successfully.\n');
fprintf('Completed outer repetitions: %d\n', completed_repeats);
fprintf('Training label sizes k: %s\n', mat2str(train_size_list'));

%% 3) Sort k values in ascending order for visualization
[k_sorted, ord_k] = sort(train_size_list, 'ascend');

res_RMSE_sorted = res_RMSE_outer(ord_k, :);
res_MAE_sorted = res_MAE_outer(ord_k, :);
res_MAPE_sorted = res_MAPE_outer(ord_k, :);

pool_y_true_sorted = pool_y_true_per_size(ord_k);
pool_y_pred_sorted = pool_y_pred_per_size(ord_k);

n_sizes = numel(k_sorted);

% Representative k settings.
idx_few = 1;
idx_medium = round(n_sizes / 2);
idx_large = n_sizes;

rep_indices = [idx_few, idx_medium, idx_large];
rep_names = {'few', 'medium', 'large'};
rep_labels = { ...
    sprintf('Few labels (k = %d)', k_sorted(idx_few)), ...
    sprintf('Medium labels (k = %d)', k_sorted(idx_medium)), ...
    sprintf('Large labels (k = %d)', k_sorted(idx_large))};

%% 4) Export summary table
mean_RMSE = mean(res_RMSE_sorted, 2, 'omitnan');
std_RMSE = std(res_RMSE_sorted, 0, 2, 'omitnan');

mean_MAE = mean(res_MAE_sorted, 2, 'omitnan');
std_MAE = std(res_MAE_sorted, 0, 2, 'omitnan');

mean_MAPE = mean(res_MAPE_sorted, 2, 'omitnan');
std_MAPE = std(res_MAPE_sorted, 0, 2, 'omitnan');

Summary_Table = table( ...
    k_sorted(:), ...
    mean_RMSE(:), ...
    std_RMSE(:), ...
    mean_MAE(:), ...
    std_MAE(:), ...
    mean_MAPE(:), ...
    std_MAPE(:), ...
    'VariableNames', { ...
    'Train_Size_k', ...
    'Mean_RMSE', ...
    'Std_RMSE', ...
    'Mean_MAE', ...
    'Std_MAE', ...
    'Mean_MAPE', ...
    'Std_MAPE'});

writetable(Summary_Table, cfg.summary_csv);

fprintf('Summary table saved: %s\n', cfg.summary_csv);

%% 5) Panel B: RMSE and MAE decay curves
color_rmse = [0.000, 0.447, 0.741];
color_mae = [0.850, 0.325, 0.098];

fig_B = figure( ...
    'Name', 'P3_Exp02_panel_B_error_decay', ...
    'Color', 'w', ...
    'Position', [100, 100, 760, 540]);

hold on;
grid on;
box on;

x_fill = [k_sorted(:)', fliplr(k_sorted(:)')];

rmse_upper = mean_RMSE(:)' + std_RMSE(:)';
rmse_lower = max(0, mean_RMSE(:)' - std_RMSE(:)');
rmse_fill = [rmse_upper, fliplr(rmse_lower)];

mae_upper = mean_MAE(:)' + std_MAE(:)';
mae_lower = max(0, mean_MAE(:)' - std_MAE(:)');
mae_fill = [mae_upper, fliplr(mae_lower)];

fill(x_fill, rmse_fill, color_rmse, ...
    'FaceAlpha', 0.15, ...
    'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

fill(x_fill, mae_fill, color_mae, ...
    'FaceAlpha', 0.15, ...
    'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

plot(k_sorted, mean_RMSE, '-o', ...
    'Color', color_rmse, ...
    'MarkerFaceColor', color_rmse, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 2.4, ...
    'MarkerSize', 6, ...
    'DisplayName', 'RMSE');

plot(k_sorted, mean_MAE, '-s', ...
    'Color', color_mae, ...
    'MarkerFaceColor', color_mae, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 2.4, ...
    'MarkerSize', 6, ...
    'DisplayName', 'MAE');

xlabel('Number of target-domain training packs, k', ...
    'FontSize', 13, ...
    'FontName', 'Arial');

ylabel('Prediction error (SOH)', ...
    'FontSize', 13, ...
    'FontName', 'Arial');

title('Prediction error decreases with target-domain label size', ...
    'FontSize', 14, ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal');

legend('Location', 'northeast', ...
    'Box', 'off', ...
    'FontSize', 11);

xlim([min(k_sorted) - 1, max(k_sorted) + 1]);

ylim_upper = max([rmse_upper, mae_upper]) * 1.15;
ylim([0, ylim_upper]);

set(gca, ...
    'FontSize', 12, ...
    'FontName', 'Arial', ...
    'LineWidth', 1.1, ...
    'TickDir', 'out', ...
    'GridLineStyle', ':', ...
    'GridAlpha', 0.25);

local_save_figure(fig_B, cfg.fig_panel_B, cfg.png_panel_B, cfg.png_resolution);

%% 6) Panel C: RMSE distribution across representative k values
data_box = [ ...
    res_RMSE_sorted(idx_few, :)', ...
    res_RMSE_sorted(idx_medium, :)', ...
    res_RMSE_sorted(idx_large, :)'];

box_labels = { ...
    sprintf('Few\nk=%d', k_sorted(idx_few)), ...
    sprintf('Medium\nk=%d', k_sorted(idx_medium)), ...
    sprintf('Large\nk=%d', k_sorted(idx_large))};

box_colors = [
    0.000, 0.447, 0.741;
    0.466, 0.674, 0.188;
    0.850, 0.325, 0.098];

fig_C = figure( ...
    'Name', 'P3_Exp02_panel_C_RMSE_distribution', ...
    'Color', 'w', ...
    'Position', [160, 160, 460, 540]);

hold on;
grid on;
box on;

box_positions = [1, 1.65, 2.30];

for i = 1:3
    x_val = repmat(box_positions(i), size(data_box, 1), 1);

    swarmchart(x_val, data_box(:, i), 24, box_colors(i, :), 'filled', ...
        'MarkerFaceAlpha', 0.45, ...
        'XJitterWidth', 0.25);
end

h = boxplot(data_box, ...
    'Positions', box_positions, ...
    'Labels', box_labels, ...
    'Colors', 'k', ...
    'Symbol', '', ...
    'Widths', 0.28);

set(h, 'LineWidth', 1.1);

h_boxes = findobj(gca, 'Tag', 'Box');

for j = 1:length(h_boxes)
    patch_color = box_colors(end - j + 1, :);

    patch(get(h_boxes(j), 'XData'), get(h_boxes(j), 'YData'), patch_color, ...
        'FaceAlpha', 0.22, ...
        'EdgeColor', 'k', ...
        'LineWidth', 1.1);
end

uistack(h, 'top');

ylabel('RMSE across outer repetitions', ...
    'FontSize', 13, ...
    'FontName', 'Arial');

title('RMSE distribution under representative label sizes', ...
    'FontSize', 13, ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal');

xlim([min(box_positions) - 0.45, max(box_positions) + 0.45]);

ylim_upper_C = max(data_box(:)) * 1.18;
ylim([0, ylim_upper_C]);

set(gca, ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'LineWidth', 1.1, ...
    'TickDir', 'out', ...
    'GridLineStyle', ':', ...
    'GridAlpha', 0.25);

local_save_figure(fig_C, cfg.fig_panel_C, cfg.png_panel_C, cfg.png_resolution);

%% 7) Panel D: SOH prediction clouds under representative k values
cloud_colors = [
    0.000, 0.447, 0.741;
    0.466, 0.674, 0.188;
    0.850, 0.325, 0.098];

cloud_fig_files = { ...
    cfg.fig_panel_D_few, ...
    cfg.fig_panel_D_medium, ...
    cfg.fig_panel_D_large};

cloud_png_files = { ...
    cfg.png_panel_D_few, ...
    cfg.png_panel_D_medium, ...
    cfg.png_panel_D_large};

for i = 1:3

    idx_curr = rep_indices(i);

    y_true = pool_y_true_sorted{idx_curr};
    y_pred = pool_y_pred_sorted{idx_curr};

    y_true = double(y_true(:));
    y_pred = double(y_pred(:));

    if isempty(y_true) || isempty(y_pred)
        warning('Representative k = %d has empty prediction pools. Skipping panel D figure %d.', ...
            k_sorted(idx_curr), i);
        continue;
    end

    limit_min = min([y_true; y_pred]) - 0.03;
    limit_max = max([y_true; y_pred]) + 0.03;

    fig_D = figure( ...
        'Name', sprintf('P3_Exp02_prediction_cloud_%s', rep_names{i}), ...
        'Color', 'w', ...
        'Position', [220 + i * 40, 220, 500, 500]);

    hold on;
    grid on;
    box on;

    residual_line_color = 0.85 * [1, 1, 1] + 0.15 * cloud_colors(i, :);

    % Vertical residual lines.
    for j = 1:numel(y_true)
        plot([y_true(j), y_true(j)], [y_true(j), y_pred(j)], ...
            'Color', residual_line_color, ...
            'LineWidth', 0.6, ...
            'HandleVisibility', 'off');
    end

    plot([limit_min, limit_max], [limit_min, limit_max], 'k--', ...
        'LineWidth', 1.4, ...
        'DisplayName', 'Ideal');

    scatter(y_true, y_pred, 34, cloud_colors(i, :), 'filled', ...
        'MarkerFaceAlpha', 0.60, ...
        'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.5, ...
        'DisplayName', 'Predictions');

    curr_rmse = sqrt(mean((y_true - y_pred).^2));
    curr_mae = mean(abs(y_true - y_pred));
    curr_r2 = 1 - sum((y_true - y_pred).^2) / ...
        (sum((y_true - mean(y_true)).^2) + 1e-12);

    stats_str = { ...
        sprintf('RMSE: %.4f', curr_rmse), ...
        sprintf('MAE: %.4f', curr_mae), ...
        sprintf('R^2: %.4f', curr_r2)};

    text(limit_min + (limit_max - limit_min) * 0.05, ...
        limit_max - (limit_max - limit_min) * 0.12, ...
        stats_str, ...
        'FontSize', 10.5, ...
        'FontName', 'Arial', ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [1 1 1], ...
        'EdgeColor', 'none');

    xlabel('Actual SOH', ...
        'FontSize', 13, ...
        'FontName', 'Arial');

    ylabel('Estimated SOH', ...
        'FontSize', 13, ...
        'FontName', 'Arial');

    title(rep_labels{i}, ...
        'FontSize', 13, ...
        'FontName', 'Arial', ...
        'FontWeight', 'normal');

    axis square;
    xlim([limit_min, limit_max]);
    ylim([limit_min, limit_max]);

    legend('Location', 'southeast', ...
        'Box', 'off', ...
        'FontSize', 10);

    set(gca, ...
        'FontSize', 11, ...
        'FontName', 'Arial', ...
        'LineWidth', 1.1, ...
        'TickDir', 'out', ...
        'GridLineStyle', ':', ...
        'GridAlpha', 0.25);

    local_save_figure(fig_D, cloud_fig_files{i}, cloud_png_files{i}, cfg.png_resolution);
end

fprintf('>>> Saved summary table: %s\n', cfg.summary_csv);
fprintf('>>> Saved panel B:       %s\n', cfg.png_panel_B);
fprintf('>>> Saved panel C:       %s\n', cfg.png_panel_C);
fprintf('>>> Saved panel D few:   %s\n', cfg.png_panel_D_few);
fprintf('>>> Saved panel D medium:%s\n', cfg.png_panel_D_medium);
fprintf('>>> Saved panel D large: %s\n', cfg.png_panel_D_large);

%% Local helper function
function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end