%% P3_Exp03_label_dependent_residual_extrapolation.m
% Purpose:
% This script constructs the label-dependent residual-error extrapolation
% model for target-domain pack-level SOH prediction.
% It reads the nested-resampling residuals generated by
% P3_Exp01_NestedResampling_ErrorEvaluation.m, extracts empirical
% residual features for k = 5 to 21, fits k-dependent feature curves,
% extrapolates the residual-error model to k = 50, and exports the
% uncertainty model used by the fixed-scale economic optimization in Part4.

clear; clc; close all;

%% 1) Configuration
cfg = struct();

% Use the current script folder as the Part3 root folder.
script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

% Root folders.
cfg.output_dir = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_dir = fullfile(script_dir, 'Figures');
cfg.ext_fig_dir = fullfile(cfg.figure_dir, 'Extended');

% Input file generated by Part3 Exp01.
% The primary path follows the new naming convention.
cfg.input_mat_primary = fullfile(cfg.results_dir, 'P3_Exp01_NestedResampling_Final.mat');

% Legacy fallback path for the existing long-running Main01 output.
% Keep this fallback to avoid rerunning the nested-resampling experiment.
cfg.input_mat_legacy = fullfile(cfg.output_dir,  'Result01_NestedResampling_Final.mat');

if exist(cfg.input_mat_primary, 'file')
    cfg.input_mat = cfg.input_mat_primary;
elseif exist(cfg.input_mat_legacy, 'file')
    cfg.input_mat = cfg.input_mat_legacy;
else
    error('Input file not found. Checked:\n%s\n%s', ...
        cfg.input_mat_primary, cfg.input_mat_legacy);
end

% Output tables and model file generated by Part3 Exp03.
cfg.param_csv = fullfile(cfg.results_dir, 'P3_Exp03_ResidualExtrapolation_Params_k5_k50.csv');
cfg.core_region_csv = fullfile(cfg.results_dir, 'P3_Exp03_CoreRegionFeatures_PM_PR_SigmaR_k5_k50.csv');
cfg.feature_csv = fullfile(cfg.results_dir, 'P3_Exp03_ResidualExtrapolation_EmpiricalFeatures_k5_k21.csv');
cfg.model_mat = fullfile(cfg.results_dir, 'P3_Exp03_ResidualExtrapolation_Model.mat');

% Output figures for Extended Data Fig. 3.
cfg.fig_RMSE = fullfile(cfg.ext_fig_dir,'ExD03b_RMSE_scaling_fit.fig');
cfg.png_RMSE = fullfile(cfg.ext_fig_dir,  'ExD03b_RMSE_scaling_fit.png');

cfg.fig_PR = fullfile(cfg.ext_fig_dir,  'ExD03c_PR_fit.fig');
cfg.png_PR = fullfile(cfg.ext_fig_dir, 'ExD03c_PR_fit.png');

cfg.fig_PM = fullfile(cfg.ext_fig_dir, 'ExD03d_PM_fit.fig');
cfg.png_PM = fullfile(cfg.ext_fig_dir, 'ExD03d_PM_fit.png');

cfg.fig_sigR = fullfile(cfg.ext_fig_dir,  'ExD03e_sigmaR_fit.fig');
cfg.png_sigR = fullfile(cfg.ext_fig_dir, 'ExD03e_sigmaR_fit.png');

cfg.dist_dir = fullfile(cfg.ext_fig_dir, 'ExD03a_residual_distribution_k05_to_k25');

% Empirical and extrapolation settings.
cfg.k_emp_min = 5;
cfg.k_emp_max = 21;
cfg.k_extrap_max = 50;
cfg.k_anchor = 21;
cfg.k_bridge_end = 26;

% Monte Carlo and density settings.
cfg.N_sim = 100000;
cfg.kde_bw = 0.0055;
cfg.hist_bins = 70;
cfg.png_resolution = 600;

rng(42);

% Create output folders if they do not exist.
if ~exist(cfg.output_dir, 'dir')
    mkdir(cfg.output_dir);
end

if ~exist(cfg.results_dir, 'dir')
    mkdir(cfg.results_dir);
end

if ~exist(cfg.figure_dir, 'dir')
    mkdir(cfg.figure_dir);
end

if ~exist(cfg.ext_fig_dir, 'dir')
    mkdir(cfg.ext_fig_dir);
end

if ~exist(cfg.dist_dir, 'dir')
    mkdir(cfg.dist_dir);
end

fprintf('================ Part3 Exp03 residual-error extrapolation ================\n');
fprintf('Input result file: %s\n', cfg.input_mat);
fprintf('Output model file: %s\n', cfg.model_mat);
fprintf('Extended figure folder: %s\n', cfg.ext_fig_dir);

%% 2) Define residual regions
region = struct();

region.main   = [-0.012,  0.015];
region.valley = [ 0.015,  0.028];
region.right  = [ 0.028,  0.052];
region.left   = [-0.060, -0.020];

%% 3) Load nested-resampling results and pool all-inner residuals
if ~exist(cfg.input_mat, 'file')
    error('Input file not found: %s', cfg.input_mat);
end

S = load(cfg.input_mat);

required_vars = { ...
    'train_size_list', ...
    'all_inner_errs'};

for i = 1:numel(required_vars)
    if ~isfield(S, required_vars{i})
        error('Required variable "%s" was not found in %s.', ...
            required_vars{i}, cfg.input_mat);
    end
end

train_size_list = S.train_size_list(:);
all_inner_errs = S.all_inner_errs;

k_emp = (cfg.k_emp_min:cfg.k_emp_max)';
num_k_emp = numel(k_emp);

err_cell = cell(num_k_emp, 1);

num_outer_used_list = zeros(num_k_emp, 1);
num_inner_used_list = zeros(num_k_emp, 1);
num_residual_used_list = zeros(num_k_emp, 1);

for i = 1:num_k_emp

    idx_k = find(train_size_list == k_emp(i), 1);

    if isempty(idx_k)
        error('k = %d was not found in train_size_list.', k_emp(i));
    end

    err_all = [];
    num_outer_used = 0;
    num_inner_used = 0;

    for mc = 1:size(all_inner_errs, 2)

        E = all_inner_errs{idx_k, mc};

        if isempty(E)
            continue;
        end

        E = double(E);

        if isempty(E) || all(~isfinite(E(:)))
            continue;
        end

        % Each column corresponds to one inner repetition.
        % Each row corresponds to one test pack in the current outer split.
        num_outer_used = num_outer_used + 1;
        num_inner_used = num_inner_used + size(E, 2);

        E = E(isfinite(E));
        err_all = [err_all; E(:)]; %#ok<AGROW>
    end

    if isempty(err_all)
        error('No valid all-inner residual samples were found for k = %d.', k_emp(i));
    end

    err_cell{i} = double(err_all(:));

    num_outer_used_list(i) = num_outer_used;
    num_inner_used_list(i) = num_inner_used;
    num_residual_used_list(i) = numel(err_all);
end

fprintf('All-inner residuals extracted for k = %d to %d.\n', ...
    cfg.k_emp_min, cfg.k_emp_max);

%% 4) Extract empirical residual-region features
P_M = zeros(num_k_emp, 1);
P_R = zeros(num_k_emp, 1);
P_V = zeros(num_k_emp, 1);
P_L = zeros(num_k_emp, 1);

mu_M = zeros(num_k_emp, 1);
mu_R = zeros(num_k_emp, 1);

sig_M = zeros(num_k_emp, 1);
sig_R = zeros(num_k_emp, 1);

rmseK = zeros(num_k_emp, 1);

for i = 1:num_k_emp

    e = err_cell{i};

    rmseK(i) = sqrt(mean(e.^2));

    % Identify residual samples within each predefined region.
    idx_main   = (e >= region.main(1))   & (e < region.main(2));
    idx_right  = (e >= region.right(1))  & (e < region.right(2));
    idx_valley = (e >= region.valley(1)) & (e < region.valley(2));
    idx_left   = (e >= region.left(1))   & (e < region.left(2));

    P_M(i) = mean(idx_main);
    P_R(i) = mean(idx_right);
    P_V(i) = mean(idx_valley);
    P_L(i) = mean(idx_left);

    % Main residual mode.
    eM = e(idx_main);

    if isempty(eM)
        eM = e;
    end

    mu_M(i) = median(eM);

    sM = iqr(eM) / 1.349;

    if numel(eM) < 4 || sM == 0 || isnan(sM)
        sM = std(eM);
    end

    sig_M(i) = max([sM, 1e-4]);

    % Right-side residual mode.
    eR = e(idx_right);

    if ~isempty(eR)

        mu_R(i) = mean(eR);

        sR = iqr(eR) / 1.349;

        if numel(eR) < 4 || sR == 0 || isnan(sR)
            sR = std(eR);
        end

        sig_R(i) = max([sR, 1e-4]);

    else

        mu_R(i) = mean(region.right);
        sig_R(i) = 0.005;
    end
end

% Smooth empirical region features to reduce sampling noise.
P_R   = min(max(smoothdata(P_R, 'movmean', 3), 0), 0.40);
P_M   = min(max(smoothdata(P_M, 'movmean', 3), 0), 1.00);
mu_M  = smoothdata(mu_M, 'movmean', 3);
mu_R  = smoothdata(mu_R, 'movmean', 3);
sig_M = max(smoothdata(sig_M, 'movmean', 3), 1e-4);
sig_R = max(smoothdata(sig_R, 'movmean', 3), 1e-4);

EmpiricalFeatureTable = table( ...
    k_emp, ...
    num_outer_used_list, ...
    num_inner_used_list, ...
    num_residual_used_list, ...
    rmseK, ...
    P_M, ...
    P_R, ...
    P_V, ...
    P_L, ...
    mu_M, ...
    sig_M, ...
    mu_R, ...
    sig_R, ...
    'VariableNames', { ...
    'k', ...
    'N_outer_runs', ...
    'N_inner_runs_all_inner', ...
    'N_residuals_all_inner', ...
    'RMSE_empirical', ...
    'P_main', ...
    'P_right', ...
    'P_valley', ...
    'P_left', ...
    'mu_main', ...
    'sig_main', ...
    'mu_right', ...
    'sig_right'});

writetable(EmpiricalFeatureTable, cfg.feature_csv);

fprintf('Empirical feature table saved: %s\n', cfg.feature_csv);

%% 4.1 Fit RMSE scaling law for extrapolation
% Fit the power-law model: RMSE(k) = a * k^(-b) + c.
% The fitted curve is used consistently for RMSE extrapolation and plotting.

x_rmse = k_emp(:);
y_rmse = rmseK(:);

valid_rmse = isfinite(x_rmse) & isfinite(y_rmse) & (y_rmse > 0);
x_rmse = x_rmse(valid_rmse);
y_rmse = y_rmse(valid_rmse);

ft_RMSE = fittype('a * x^(-b) + c', ...
    'independent', 'x', ...
    'dependent', 'y');

opts_RMSE = fitoptions('Method', 'NonlinearLeastSquares');
opts_RMSE.Display = 'Off';
opts_RMSE.StartPoint = [0.1, 0.5, min(y_rmse)];
opts_RMSE.Lower = [0, 0, 0];

[fit_RMSE, gof_RMSE] = fit(x_rmse, y_rmse, ft_RMSE, opts_RMSE);

a_RMSE = fit_RMSE.a;
b_RMSE = fit_RMSE.b;
c_RMSE = fit_RMSE.c;
R2_RMSE = gof_RMSE.rsquare;

fprintf('\n================ RMSE scaling-law fitting ================\n');
fprintf('RMSE(k) = %.6f * k^(-%.6f) + %.6f\n', ...
    a_RMSE, b_RMSE, c_RMSE);
fprintf('RMSE scaling R2 = %.4f\n', R2_RMSE);
fprintf('==========================================================\n');

%% 5) Define robust Huber loss
huber_core = @(r, d) ...
    (abs(r) <= d) .* (0.5 * r.^2) + ...
    (abs(r) > d)  .* (d .* (abs(r) - 0.5 * d));

huber_loss = @(y, yhat) ...
    sum(huber_core(y - yhat, 1.5 * max(mad(y - yhat, 1), 1e-6)));

%% 6) Fit parametric curves for empirical distribution features
k0 = min(k_emp);

opt = optimset( ...
    'Display', 'off', ...
    'MaxFunEvals', 6000, ...
    'MaxIter', 6000);

% 6.1 Fit P_R with exponential decay toward a plateau.
PR0 = P_R(1);
cR_lb = 0.00;
cR_ub = 0.08;

bnd_cR = @(c) min(max(c, cR_lb), cR_ub);
pen_cR = @(c) ...
    1e6 * (c < cR_lb) .* (cR_lb - c).^2 + ...
    1e6 * (c > cR_ub) .* (c - cR_ub).^2;

yhat_PR = @(p, x) ...
    bnd_cR(p(2)) + ...
    (PR0 - bnd_cR(p(2))) .* exp(-exp(p(1)) .* (x - k0));

obj_PR = @(p) huber_loss(P_R, yhat_PR(p, k_emp)) + pen_cR(p(2));

p_optR = fminsearch(obj_PR, [log(0.18); min(P_R(end), 0.05)], opt);

bR_opt = exp(p_optR(1));
cR_opt = bnd_cR(p_optR(2));

% 6.2 Fit P_M with exponential growth toward saturation.
PM0 = P_M(1);

cM_lb = max(P_M);
cM_ub = max(0.95, cM_lb + 1e-4);

bnd_cM = @(c) min(max(c, cM_lb), cM_ub);
pen_cM = @(c) ...
    1e6 * (c < cM_lb) .* (cM_lb - c).^2 + ...
    1e6 * (c > cM_ub) .* (c - cM_ub).^2;

yhat_PM = @(p, x) ...
    bnd_cM(p(2)) - ...
    (bnd_cM(p(2)) - PM0) .* exp(-exp(p(1)) .* (x - k0));

obj_PM = @(p) huber_loss(P_M, yhat_PM(p, k_emp)) + pen_cM(p(2));

p_optM = fminsearch(obj_PM, [log(0.12); max(0.8, max(P_M))], opt);

bM_opt = exp(p_optM(1));
cM_opt = bnd_cM(p_optM(2));

% 6.3 Fit mu_M with exponential shrinkage toward zero.
mask_muM = (k_emp >= 7) & (k_emp <= cfg.k_anchor) & isfinite(mu_M);

if sum(mask_muM) < 3
    mask_muM = isfinite(mu_M);
end

xm = k_emp(mask_muM);
ym = mu_M(mask_muM);

idx_anchor = find(k_emp == cfg.k_anchor, 1);
muM_anchor = mu_M(idx_anchor);

yhat_muM = @(p, x) ...
    muM_anchor .* exp(-exp(p(1)) .* (x - cfg.k_anchor));

obj_muM = @(p) huber_loss(ym, yhat_muM(p, xm));

p_opt_muM = fminsearch(obj_muM, log(0.08), opt);

a_muM = exp(p_opt_muM(1));

% 6.4 Fit sig_R with positive exponential decay.
mask_sigR = (k_emp >= cfg.k_emp_min) & ...
    (k_emp <= cfg.k_anchor) & ...
    (sig_R > 0) & ...
    isfinite(sig_R);

if sum(mask_sigR) < 3
    error('Not enough valid sigma_R samples for curve fitting.');
end

xs = k_emp(mask_sigR);
ys = sig_R(mask_sigR);

k0_s = min(xs);

c_lb_s = 0.0003;
c_ub_s = 0.0012;

bnd_cs = @(c) min(max(c, c_lb_s), c_ub_s);
pen_cs = @(c) ...
    1e6 * (c < c_lb_s) .* (c_lb_s - c).^2 + ...
    1e6 * (c > c_ub_s) .* (c - c_ub_s).^2;

yhat_sigR = @(p, x) ...
    bnd_cs(p(3)) + exp(p(1)) .* exp(-exp(p(2)) .* (x - k0_s));

obj_sigR = @(p) huber_loss(ys, yhat_sigR(p, xs)) + pen_cs(p(3));

p_opt_sigR = fminsearch( ...
    obj_sigR, ...
    [log(max(ys) - min(ys) + 1e-6); log(0.18); min(ys)], ...
    opt);

A_sigR = exp(p_opt_sigR(1));
b_sigR = exp(p_opt_sigR(2));
c_sigR = bnd_cs(p_opt_sigR(3));

%% 7) Compute fitting R-squared values
R2_PR = local_r2(P_R, yhat_PR(p_optR, k_emp));
R2_PM = local_r2(P_M, yhat_PM(p_optM, k_emp));
R2_muM = local_r2(ym, yhat_muM(p_opt_muM, xm));
R2_sigR = local_r2(ys, yhat_sigR(p_opt_sigR, xs));

fprintf('\n================ Exponential fitting results ================\n');
fprintf('P_R(k)          R2 = %.4f\n', R2_PR);
fprintf('P_M(k)          R2 = %.4f\n', R2_PM);
fprintf('mu_M(k)         R2 = %.4f\n', R2_muM);
fprintf('sigma_R(k)      R2 = %.4f\n', R2_sigR);
fprintf('=============================================================\n');

%% 8) Construct full extrapolated parameter curves for k = 5 to 50
k_vals = (cfg.k_emp_min:cfg.k_extrap_max)';
num_k_vals = numel(k_vals);

PR_curve = min(max( ...
    cR_opt + (PR0 - cR_opt) .* exp(-bR_opt .* (k_vals - k0)), ...
    0), 0.40);

w_curve = PR_curve;

PM_curve = cM_opt - (cM_opt - PM0) .* exp(-bM_opt .* (k_vals - k0));
PM_curve = min(max(PM_curve, 0), 1);

muM_curve = muM_anchor .* exp(-a_muM .* (k_vals - cfg.k_anchor));

mask_muR_tail = (k_emp >= 15) & (k_emp <= cfg.k_anchor);

if any(mask_muR_tail)
    muR_const = median(mu_R(mask_muR_tail), 'omitnan');
else
    muR_const = median(mu_R, 'omitnan');
end

muR_curve = muR_const * ones(num_k_vals, 1);

sigR_curve = max( ...
    c_sigR + A_sigR .* exp(-b_sigR .* (k_vals - k0_s)), ...
    1e-6);

SigmaR_width_curve = 2 * sigR_curve;

RightLine_Lower_curve = muR_curve - sigR_curve;
RightLine_Upper_curve = muR_curve + sigR_curve;

% Generate the target RMSE curve.
% Empirical RMSE values are kept for k = 5 to 21.
% The fitted power-law curve is used only for extrapolated k values.

rmse_target = zeros(num_k_vals, 1);

for i = 1:num_k_vals

    if k_vals(i) <= cfg.k_emp_max

        idx_emp = find(k_emp == k_vals(i), 1);
        rmse_target(i) = rmseK(idx_emp);

    else

        % Direct power-law extrapolation without anchor scaling.
        rmse_target(i) = fit_RMSE(k_vals(i));
    end
end

if any(~isfinite(rmse_target)) || any(rmse_target <= 0)
    error('Invalid RMSE target values were generated.');
end

% Back-calculate the main-mode width according to the target RMSE curve.
sigM_curve = zeros(num_k_vals, 1);

for i = 1:num_k_vals

    rt = rmse_target(i);
    w = w_curve(i);
    muM0 = muM_curve(i);
    muR0 = muR_curve(i);
    sigR0 = sigR_curve(i);

    w_eff = w;
    min_sigM = 0.0010;

    for it = 1:40

        num = rt^2 ...
            - w_eff * (sigR0^2 + muR0^2) ...
            - (1 - w_eff) * muM0^2;

        den = max(1 - w_eff, 1e-8);

        if (num / den) > min_sigM^2
            break;
        end

        w_eff = 0.92 * w_eff;
    end

    w_curve(i) = w_eff;

    num = rt^2 ...
        - w_eff * (sigR0^2 + muR0^2) ...
        - (1 - w_eff) * muM0^2;

    sigM_curve(i) = sqrt(max(num / max(1 - w_eff, 1e-8), min_sigM^2));
end

%% 9) Generate Monte Carlo residual samples and bridge distributions
base_u = rand(cfg.N_sim, 1);
base_z = randn(cfg.N_sim, 1);
base_pick = rand(cfg.N_sim, 1);

saved_noise_for_plot = cell(num_k_vals, 1);
err_anchor = err_cell{k_emp == cfg.k_anchor};

for i = 1:num_k_vals

    k_now = k_vals(i);

    % Generate raw two-mode parametric residual samples.
    isR = base_pick < w_curve(i);

    e_par = zeros(cfg.N_sim, 1);

    e_par(~isR) = muM_curve(i) + sigM_curve(i) * base_z(~isR);
    e_par(isR)  = muR_curve(i) + sigR_curve(i) * base_z(isR);

    if k_now <= cfg.k_anchor

        % Empirical bootstrap for the observed k range.
        e_data = sort(err_cell{k_emp == k_now});

        p = ((1:numel(e_data))' - 0.5) / numel(e_data);
        e_sample = interp1(p, e_data, base_u, 'linear', 'extrap');

    elseif k_now < cfg.k_bridge_end

        % Bridge empirical and parametric distributions.
        t = (k_now - cfg.k_anchor) / (cfg.k_bridge_end - cfg.k_anchor);
        alpha = 3 * (min(max(t, 0), 1))^2 - 2 * (min(max(t, 0), 1))^3;

        e_data = sort(err_anchor);
        p = ((1:numel(e_data))' - 0.5) / numel(e_data);
        e_emp = interp1(p, e_data, base_u, 'linear', 'extrap');

        e_sample = (1 - alpha) .* e_emp + alpha .* e_par;

    else

        % Fully extrapolated parametric distribution.
        e_sample = e_par;
    end

    saved_noise_for_plot{i} = e_sample;
end

%% 10) Save the extrapolated parameter table and model file
ResultTable = table( ...
    k_vals, ...
    rmse_target, ...
    w_curve, ...
    PM_curve, ...
    muM_curve, ...
    sigM_curve, ...
    muR_curve, ...
    sigR_curve, ...
    'VariableNames', { ...
    'k', ...
    'RMSE_target', ...
    'w_right', ...
    'P_main', ...
    'mu_main', ...
    'sig_main', ...
    'mu_right', ...
    'sig_right'});

writetable(ResultTable, cfg.param_csv);

CoreRegionFeatureTable = table( ...
    k_vals, ...
    PR_curve, ...
    PM_curve, ...
    SigmaR_width_curve, ...
    RightLine_Lower_curve, ...
    RightLine_Upper_curve, ...
    'VariableNames', { ...
    'k', ...
    'P_R_fit', ...
    'P_M_fit', ...
    'Sigma_R_width_fit', ...
    'RightLine_Lower', ...
    'RightLine_Upper'});

writetable(CoreRegionFeatureTable, cfg.core_region_csv);

fprintf('Core region-feature table saved: %s\n', cfg.core_region_csv);

save(cfg.model_mat, ...
    'cfg', ...
    'region', ...
    'k_emp', ...
    'k_vals', ...
    'err_cell', ...
    'num_outer_used_list', ...
    'num_inner_used_list', ...
    'num_residual_used_list', ...
    'rmseK', ...
    'rmse_target', ...
    'P_M', ...
    'P_R', ...
    'P_V', ...
    'P_L', ...
    'mu_M', ...
    'mu_R', ...
    'sig_M', ...
    'sig_R', ...
    'PR_curve', ...
    'PM_curve', ...
    'w_curve', ...
    'muM_curve', ...
    'sigM_curve', ...
    'muR_curve', ...
    'sigR_curve', ...
    'SigmaR_width_curve', ...
    'RightLine_Lower_curve', ...
    'RightLine_Upper_curve', ...
    'a_RMSE', ...
    'b_RMSE', ...
    'c_RMSE', ...
    'R2_RMSE', ...
    'R2_PR', ...
    'R2_PM', ...
    'R2_muM', ...
    'R2_sigR', ...
    'bR_opt', ...
    'cR_opt', ...
    'bM_opt', ...
    'cM_opt', ...
    'a_muM', ...
    'A_sigR', ...
    'b_sigR', ...
    'c_sigR', ...
    'ResultTable', ...
    'CoreRegionFeatureTable', ...
    'EmpiricalFeatureTable', ...
    'saved_noise_for_plot', ...
    '-v7.3');

fprintf('Extrapolated parameter table saved: %s\n', cfg.param_csv);
fprintf('Residual extrapolation model saved: %s\n', cfg.model_mat);

%% 11) Panel E: Fit of right-mode probability mass P_R
fig_PR = figure( ...
    'Color', 'w', ...
    'Position', [100, 100, 700, 500], ...
    'Name', 'ExD03c_PR_fit');

hold on;
grid on;
box on;

h_pts = plot(k_emp, P_R, 'ko', ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', 'k', ...
    'MarkerSize', 6, ...
    'LineStyle', 'none', ...
    'DisplayName', 'Empirical data');

h_fit = plot(k_vals, yhat_PR(p_optR, k_vals), 'r-', ...
    'LineWidth', 2.5, ...
    'DisplayName', 'Exponential fit');

uistack(h_fit, 'top');

xlabel('k', 'FontSize', 12, 'FontName', 'Arial');
ylabel('P_R(k)', 'FontSize', 12, 'FontName', 'Arial');

title('Exponential decay fit of right-mode mass P_R(k)', ...
    'FontSize', 13, ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal');

legend([h_pts, h_fit], ...
    {'Empirical data', 'Exponential fit'}, ...
    'Location', 'northeast', ...
    'Box', 'off', ...
    'FontSize', 11);

txt_PR = sprintf(['P_R(k) = %.4f + (%.4f - %.4f) exp[-%.4f(k - %d)]\n' ...
    'R^2 = %.4f'], ...
    cR_opt, PR0, cR_opt, bR_opt, k0, R2_PR);

text(0.42, 0.75, txt_PR, ...
    'Units', 'normalized', ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'BackgroundColor', [1 1 1], ...
    'EdgeColor', 'k');

set(gca, ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'LineWidth', 1.0, ...
    'TickDir', 'out', ...
    'GridLineStyle', ':', ...
    'GridAlpha', 0.25);
xlim([cfg.k_emp_min, cfg.k_extrap_max]);
local_save_figure(fig_PR, cfg.fig_PR, cfg.png_PR, cfg.png_resolution);

%% 12) Panel F: Fit of main-mode probability mass P_M
fig_PM = figure( ...
    'Color', 'w', ...
    'Position', [150, 150, 700, 500], ...
    'Name', 'ExD03d_PM_fit');

hold on;
grid on;
box on;

h_pts = plot(k_emp, P_M, 'ko', ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', 'k', ...
    'MarkerSize', 6, ...
    'LineStyle', 'none', ...
    'DisplayName', 'Empirical data');

h_fit = plot(k_vals, yhat_PM(p_optM, k_vals), 'b-', ...
    'LineWidth', 2.5, ...
    'DisplayName', 'Exponential fit');

uistack(h_fit, 'top');

xlabel('k', 'FontSize', 12, 'FontName', 'Arial');
ylabel('P_M(k)', 'FontSize', 12, 'FontName', 'Arial');

title('Exponential growth fit of main-mode mass P_M(k)', ...
    'FontSize', 13, ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal');

legend([h_pts, h_fit], ...
    {'Empirical data', 'Exponential fit'}, ...
    'Location', 'southeast', ...
    'Box', 'off', ...
    'FontSize', 11);

txt_PM = sprintf(['P_M(k) = %.4f - (%.4f - %.4f) exp[-%.4f(k - %d)]\n' ...
    'R^2 = %.4f'], ...
    cM_opt, cM_opt, PM0, bM_opt, k0, R2_PM);

text(0.28, 0.18, txt_PM, ...
    'Units', 'normalized', ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'BackgroundColor', [1 1 1], ...
    'EdgeColor', 'k');

set(gca, ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'LineWidth', 1.0, ...
    'TickDir', 'out', ...
    'GridLineStyle', ':', ...
    'GridAlpha', 0.25);

xlim([cfg.k_emp_min, cfg.k_extrap_max]);

local_save_figure(fig_PM, cfg.fig_PM, cfg.png_PM, cfg.png_resolution);

%% 13) Panel G: Fit of right-mode standard deviation sigma_R
fig_sigR = figure( ...
    'Color', 'w', ...
    'Position', [200, 200, 700, 500], ...
    'Name', 'ExD03e_sigmaR_fit');

hold on;
grid on;
box on;

mask_plot_sigR = (k_emp >= cfg.k_emp_min) & ...
    (k_emp <= cfg.k_anchor) & ...
    (sig_R > 0);

SigmaR_width_emp = 2 * sig_R;

h_pts = plot(k_emp(mask_plot_sigR), SigmaR_width_emp(mask_plot_sigR), 'ko', ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', 'k', ...
    'MarkerSize', 6, ...
    'LineStyle', 'none', ...
    'DisplayName', 'Empirical data');

h_fit = plot(k_vals, SigmaR_width_curve, 'g-', ...
    'LineWidth', 2.5, ...
    'DisplayName', 'Exponential fit');

uistack(h_fit, 'top');

xlabel('k', 'FontSize', 12, 'FontName', 'Arial');
ylabel('Right-tail width, 2\sigma_R(k)', 'FontSize', 12, 'FontName', 'Arial');

title('Exponential decay fit of right-tail red-line width 2\sigma_R(k)', ...
    'FontSize', 13, ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal');

legend([h_pts, h_fit], ...
    {'Empirical data', 'Exponential fit'}, ...
    'Location', 'northeast', ...
    'Box', 'off', ...
    'FontSize', 11);

txt_sigR = sprintf(['2\\sigma_R(k) = %.6f + %.6f exp[-%.4f(k - %d)]\n' ...
    'R^2 = %.4f'], ...
    2 * c_sigR, 2 * A_sigR, b_sigR, k0_s, R2_sigR);

text(0.40, 0.75, txt_sigR, ...
    'Units', 'normalized', ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'BackgroundColor', [1 1 1], ...
    'EdgeColor', 'k');

set(gca, ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'LineWidth', 1.0, ...
    'TickDir', 'out', ...
    'GridLineStyle', ':', ...
    'GridAlpha', 0.25);

xlim([cfg.k_emp_min, cfg.k_extrap_max]);

local_save_figure(fig_sigR, cfg.fig_sigR, cfg.png_sigR, cfg.png_resolution);

%% 14) Additional panel: RMSE scaling-law extrapolation
fig_RMSE = figure( ...
    'Color', 'w', ...
    'Position', [250, 250, 700, 500], ...
    'Name', 'ExD03b_RMSE_scaling_fit');

hold on;
grid on;
box on;

x_data = k_emp(:);
y_data = rmseK(:);

valid_rmse_plot = isfinite(x_data) & isfinite(y_data) & (y_data > 0);
x_data = x_data(valid_rmse_plot);
y_data = y_data(valid_rmse_plot);

[x_data, ord_rmse] = sort(x_data, 'ascend');
y_data = y_data(ord_rmse);

x_extrap_RMSE = linspace(cfg.k_emp_min, cfg.k_extrap_max, 200);
y_extrap_RMSE = fit_RMSE(x_extrap_RMSE);

h_pts = plot(x_data, y_data, 'ko', ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', 'k', ...
    'MarkerSize', 6, ...
    'LineStyle', 'none', ...
    'DisplayName', 'Empirical data');

h_fit = plot(x_extrap_RMSE, y_extrap_RMSE, 'm-', ...
    'LineWidth', 2.5, ...
    'DisplayName', 'Power-law fit');

uistack(h_fit, 'top');

xlabel('k', 'FontSize', 12, 'FontName', 'Arial');
ylabel('RMSE', 'FontSize', 12, 'FontName', 'Arial');

title('Power-law scaling of prediction error', ...
    'FontSize', 13, ...
    'FontName', 'Arial', ...
    'FontWeight', 'normal');

legend([h_pts, h_fit], ...
    {'Empirical data', 'Power-law fit'}, ...
    'Location', 'northeast', ...
    'Box', 'off', ...
    'FontSize', 11);

txt_RMSE = sprintf(['RMSE(k) = %.4f k^{-%.4f} + %.4f\n' ...
    'R^2 = %.4f'], ...
    a_RMSE, b_RMSE, c_RMSE, R2_RMSE);

text(0.42, 0.78, txt_RMSE, ...
    'Units', 'normalized', ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'BackgroundColor', [1 1 1], ...
    'EdgeColor', 'k');

set(gca, ...
    'FontSize', 11, ...
    'FontName', 'Arial', ...
    'LineWidth', 1.0, ...
    'TickDir', 'out', ...
    'GridLineStyle', ':', ...
    'GridAlpha', 0.25);

xlim([cfg.k_emp_min, cfg.k_extrap_max]);

local_save_figure(fig_RMSE, cfg.fig_RMSE, cfg.png_RMSE, cfg.png_resolution);


%% 15) Panel H: Residual-distribution plots for k = 5 to 25
plot_k_list = 5:25;

color_main_area  = [0.46, 0.73, 0.46];
color_right_area = [0.85, 0.32, 0.32];

for i = 1:numel(plot_k_list)

    k_now = plot_k_list(i);

    if k_now <= cfg.k_emp_max

        idx_emp = find(k_emp == k_now, 1);
        e = err_cell{idx_emp};
        type_str = 'Empirical';
        color_hist = [0.78, 0.86, 0.95];
        color_line = [0.00, 0.20, 0.80];
        suffix_str = 'empirical';

    else

        idx_val = find(k_vals == k_now, 1);
        e = saved_noise_for_plot{idx_val};
        type_str = 'Extrapolated';
        color_hist = [0.90, 0.88, 0.95];
        color_line = [0.85, 0.10, 0.10];
        suffix_str = 'extrapolated';
    end

    e = e(isfinite(e));

    if isempty(e)
        warning('No valid residuals found for k = %d. Skipping.', k_now);
        continue;
    end

    % Recalculate display features from the current residual distribution.
    idx_main_show  = (e >= region.main(1))  & (e < region.main(2));
    idx_right_show = (e >= region.right(1)) & (e < region.right(2));

    val_PM = mean(idx_main_show);
    val_PR = mean(idx_right_show);

    eR_show = e(idx_right_show);

    if ~isempty(eR_show)

        curr_muR = mean(eR_show);

        val_sigR = iqr(eR_show) / 1.349;

        if numel(eR_show) < 4 || val_sigR == 0 || isnan(val_sigR)
            val_sigR = std(eR_show);
        end

        val_sigR = max(val_sigR, 1e-4);

    else

        curr_muR = mean(region.right);
        val_sigR = 0.005;
    end

    fig_dist = figure( ...
        'Color', 'w', ...
        'Units', 'centimeters', ...
        'Position', [2, 2, 5, 4], ...
        'PaperUnits', 'centimeters', ...
        'PaperPosition', [0, 0, 5, 4], ...
        'PaperSize', [5, 4], ...
        'InvertHardcopy', 'off', ...
        'Resize', 'off', ...
        'Name', sprintf('ExD03a_residual_distribution_k_%02d_%s', k_now, suffix_str));

    hold on;
    grid on;
    box on;

    histogram(e, cfg.hist_bins, ...
        'Normalization', 'pdf', ...
        'FaceColor', color_hist, ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.68);

    [f, xi] = ksdensity(e, 'Bandwidth', cfg.kde_bw);

    % Highlight the main-mode and right-mode regions.
    idx_m = (xi >= region.main(1)) & (xi <= region.main(2));

    if any(idx_m)
        area(xi(idx_m), f(idx_m), ...
            'FaceColor', color_main_area, ...
            'FaceAlpha', 0.42, ...
            'EdgeColor', 'none');
    end

    idx_r = (xi >= region.right(1)) & (xi <= region.right(2));

    if any(idx_r)
        area(xi(idx_r), f(idx_r), ...
            'FaceColor', color_right_area, ...
            'FaceAlpha', 0.42, ...
            'EdgeColor', 'none');
    end

    plot(xi, f, '-', ...
        'Color', color_line, ...
        'LineWidth', 1.1);

    % Visualize zero bias and right-mode width.
    xlim([-0.06, 0.06]);

    yl = ylim;
    ylim([0, yl(2) * 1.18]);

    x_left = curr_muR - val_sigR;
    x_right = curr_muR + val_sigR;
    val_SigmaR_width = x_right - x_left;

    xline(0, 'k--', 'LineWidth', 0.9);
    xline(x_left, '--', 'Color', [0.65, 0.15, 0.15], 'LineWidth', 0.8);
    xline(x_right, '--', 'Color', [0.65, 0.15, 0.15], 'LineWidth', 0.8);

    xlabel('Residual', ...
        'FontName', 'Arial', ...
        'FontSize', 7);

    ylabel('Density', ...
        'FontName', 'Arial', ...
        'FontSize', 7);

    ax = gca;

    ax.FontName = 'Arial';
    ax.FontSize = 6;
    ax.LineWidth = 0.5;
    ax.Units = 'normalized';
    ax.Position = [0.18, 0.20, 0.75, 0.70];
    ax.GridLineStyle = ':';
    ax.GridAlpha = 0.20;

    out_png = fullfile(cfg.dist_dir, ...
        sprintf('ExD03a_residual_distribution_k_%02d_%s.png', k_now, suffix_str));

    out_fig = fullfile(cfg.dist_dir, ...
        sprintf('ExD03a_residual_distribution_k_%02d_%s.fig', k_now, suffix_str));

    local_save_figure(fig_dist, out_fig, out_png, cfg.png_resolution);

    close(fig_dist);

    fprintf('Saved residual-distribution figure for k = %d.\n', k_now);
end

fprintf('\n>>> Part3 Exp03 residual-error extrapolation completed.\n');
fprintf('>>> Saved parameter table: %s\n', cfg.param_csv);
fprintf('>>> Saved empirical feature table: %s\n', cfg.feature_csv);
fprintf('>>> Saved core region-feature table: %s\n', cfg.core_region_csv);
fprintf('>>> Saved model file: %s\n', cfg.model_mat);
fprintf('>>> Saved ExD03b: %s\n', cfg.png_RMSE);
fprintf('>>> Saved ExD03c: %s\n', cfg.png_PR);
fprintf('>>> Saved ExD03d: %s\n', cfg.png_PM);
fprintf('>>> Saved ExD03e: %s\n', cfg.png_sigR);
fprintf('>>> Saved ExD03a folder: %s\n', cfg.dist_dir);

fprintf('\n================ Part3 Exp03 completed ================\n');

%% Local helper functions
function R2 = local_r2(y, yhat)
% Compute R-squared with numerical protection.

y = y(:);
yhat = yhat(:);

valid = isfinite(y) & isfinite(yhat);
y = y(valid);
yhat = yhat(valid);

if numel(y) < 2
    R2 = NaN;
    return;
end

sst = sum((y - mean(y)).^2);
sse = sum((y - yhat).^2);

if sst < 1e-12
    R2 = NaN;
else
    R2 = 1 - sse / sst;
end
end

function local_save_figure(fig_handle, fig_file, png_file, resolution)
% Save a figure as both FIG and PNG files.

out_dir = fileparts(fig_file);

if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end