%% P3_Exp04_ResidualRegionBoundaryRobustness.m
% Purpose:
% Evaluate whether the empirical residual-feature trends used in Part 3
% remain stable when the fixed near-zero and positive right-tail region
% boundaries are narrowed or widened by 20%.
%
% Design principles:
%   1) all-inner residuals are the only empirical source;
%   2) raw empirical features and three-point-smoothed fitting inputs are
%      stored separately;
%   3) the same functional forms and fitting constraints as Exp03 are used;
%   4) this experiment is a feature-definition robustness check only.
%      It does not rebuild the full residual generator or propagate each
%      boundary scenario into Part 4 or Part 5;
%   5) distribution illustrations use empirical residuals only, so changing
%      a diagnostic boundary does not also change the underlying residual
%      distribution being displayed.

clc;
clear;
close all;

%% 1) Configuration
cfg = struct();

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

cfg.output_dir  = fullfile(script_dir, 'Output');
cfg.results_dir = fullfile(cfg.output_dir, 'Results');

cfg.figure_root = fullfile(script_dir, 'Figures');
cfg.supp_fig_dir = fullfile(cfg.figure_root, 'Supplementary');

cfg.input_mat = fullfile(cfg.results_dir, ...
    'P3_Exp01_NestedResampling_Final.mat');

cfg.fit_summary_csv = fullfile(cfg.results_dir, ...
    'P3_Exp04_ResidualRegionBoundaryRobustness_FitSummary.csv');
cfg.feature_curves_csv = fullfile(cfg.results_dir, ...
    'P3_Exp04_ResidualRegionBoundaryRobustness_FeatureCurves.csv');
cfg.fit_curves_csv = fullfile(cfg.results_dir, ...
    'P3_Exp04_ResidualRegionBoundaryRobustness_FitCurves.csv');
cfg.trend_check_csv = fullfile(cfg.results_dir, ...
    'P3_Exp04_ResidualRegionBoundaryRobustness_TrendCheck.csv');
cfg.all_inner_counts_csv = fullfile(cfg.results_dir, ...
    'P3_Exp04_ResidualRegionBoundaryRobustness_AllInnerCounts.csv');
cfg.model_mat = fullfile(cfg.results_dir, ...
    'P3_Exp04_ResidualRegionBoundaryRobustness_Model.mat');

cfg.fig_r2_summary = fullfile(cfg.supp_fig_dir, ...
    'SupFig12a_ResidualRegionBoundary_R2_summary.fig');
cfg.png_r2_summary = fullfile(cfg.supp_fig_dir, ...
    'SupFig12a_ResidualRegionBoundary_R2_summary.png');

cfg.fig_PM = fullfile(cfg.supp_fig_dir, ...
    'SupFig12b_ResidualRegionBoundary_PM_sensitivity.fig');
cfg.png_PM = fullfile(cfg.supp_fig_dir, ...
    'SupFig12b_ResidualRegionBoundary_PM_sensitivity.png');

cfg.fig_PR = fullfile(cfg.supp_fig_dir, ...
    'SupFig12c_ResidualRegionBoundary_PR_sensitivity.fig');
cfg.png_PR = fullfile(cfg.supp_fig_dir, ...
    'SupFig12c_ResidualRegionBoundary_PR_sensitivity.png');

cfg.fig_sigR = fullfile(cfg.supp_fig_dir, ...
    'SupFig12d_ResidualRegionBoundary_SigmaR_sensitivity.fig');
cfg.png_sigR = fullfile(cfg.supp_fig_dir, ...
    'SupFig12d_ResidualRegionBoundary_SigmaR_sensitivity.png');

cfg.dist_dir = fullfile(cfg.supp_fig_dir, ...
    'SupFig12_residual_region_distributions_empirical_k05_to_k20');

cfg.png_resolution = 600;
cfg.do_plot_distribution = true;

folders = {cfg.output_dir, cfg.results_dir, cfg.figure_root, ...
    cfg.supp_fig_dir, cfg.dist_dir};
for i = 1:numel(folders)
    if ~exist(folders{i}, 'dir')
        mkdir(folders{i});
    end
end

fprintf('================ P3 Exp04: residual-region boundary robustness ================\n');
fprintf('Input result file: %s\n', cfg.input_mat);
fprintf('Output folder:     %s\n', cfg.results_dir);
fprintf('Figure folder:     %s\n', cfg.supp_fig_dir);

%% 2) Analysis settings
cfg.k_emp_min = 5;
cfg.k_emp_max = 21;
cfg.k_extrap_max = 50;

k_emp = (cfg.k_emp_min:cfg.k_emp_max)';
k_vals = (cfg.k_emp_min:cfg.k_extrap_max)';

% Only empirical distributions are illustrated in this robustness check.
cfg.plot_k_list = [5, 10, 15, 20];

% Baseline fixed diagnostic regions from Exp03.
base_main  = [-0.012,  0.015];
base_right = [ 0.028,  0.052];

% Region-width perturbation scenarios.
ScenarioName = [
    "Baseline"
    "Narrow_all_20"
    "Wide_all_20"
    "Narrow_main_20"
    "Wide_main_20"
    "Narrow_right_20"
    "Wide_right_20"
    ];

main_mult = [1.0; 0.8; 1.2; 0.8; 1.2; 1.0; 1.0];
right_mult = [1.0; 0.8; 1.2; 1.0; 1.0; 0.8; 1.2];

nScenario = numel(ScenarioName);

% Density-plot settings.
cfg.kde_bw = 0.0055;
cfg.hist_edges = linspace(-0.06, 0.06, 70);

%% 3) Load and pool all-inner residuals
if ~exist(cfg.input_mat, 'file')
    error(['Input data file not found:\n%s\n' ...
        'Run P3_Exp01_NestedResampling_ErrorEvaluation.m first.'], ...
        cfg.input_mat);
end

S = load(cfg.input_mat);

required_vars = {'train_size_list', 'all_inner_errs'};
for i = 1:numel(required_vars)
    if ~isfield(S, required_vars{i})
        error('Required variable "%s" is missing from %s.', ...
            required_vars{i}, cfg.input_mat);
    end
end

train_size_list = double(S.train_size_list(:));
all_inner_errs = S.all_inner_errs;

num_k_emp = numel(k_emp);
err_cell = cell(num_k_emp, 1);

num_outer_used_list = zeros(num_k_emp, 1);
num_inner_used_list = zeros(num_k_emp, 1);
num_residual_used_list = zeros(num_k_emp, 1);

for i = 1:num_k_emp
    k_now = k_emp(i);
    idx_k = find(train_size_list == k_now, 1);

    if isempty(idx_k)
        error('k = %d was not found in train_size_list.', k_now);
    end

    err_all = [];
    num_outer_used = 0;
    num_inner_used = 0;

    for outer_id = 1:size(all_inner_errs, 2)
        E = all_inner_errs{idx_k, outer_id};

        if isempty(E)
            continue;
        end

        E = double(E);
        if all(~isfinite(E(:)))
            continue;
        end

        num_outer_used = num_outer_used + 1;
        num_inner_used = num_inner_used + size(E, 2);

        E = E(isfinite(E));
        err_all = [err_all; E(:)]; %#ok<AGROW>
    end

    if isempty(err_all)
        error('No valid all-inner residuals were found for k = %d.', k_now);
    end

    err_cell{i} = err_all(:);
    num_outer_used_list(i) = num_outer_used;
    num_inner_used_list(i) = num_inner_used;
    num_residual_used_list(i) = numel(err_all);

    fprintf(['k = %d | outer runs = %d | inner runs = %d | ' ...
        'all-inner residual samples = %d\n'], ...
        k_now, num_outer_used, num_inner_used, numel(err_all));
end

AllInnerCountTable = table( ...
    k_emp, ...
    num_outer_used_list, ...
    num_inner_used_list, ...
    num_residual_used_list, ...
    'VariableNames', { ...
    'k', ...
    'N_outer_runs', ...
    'N_inner_runs_all_inner', ...
    'N_residuals_all_inner'});

writetable(AllInnerCountTable, cfg.all_inner_counts_csv);

%% 4) Scenario-wise feature extraction and fitting
FitSummary_All = table();
FeatureCurve_All = table();
FitCurve_All = table();
Store = struct();

for ss = 1:nScenario
    curr_name = ScenarioName(ss);

    region_main = local_scaled_region(base_main, main_mult(ss));
    region_right = local_scaled_region(base_right, right_mult(ss));

    fprintf('\n======================================================\n');
    fprintf('Current scenario: %s\n', curr_name);
    fprintf('Near-zero region = [%.5f, %.5f]\n', ...
        region_main(1), region_main(2));
    fprintf('Right-tail region = [%.5f, %.5f]\n', ...
        region_right(1), region_right(2));
    fprintf('======================================================\n');

    % Raw empirical features.
    P_M_raw = nan(num_k_emp, 1);
    P_R_raw = nan(num_k_emp, 1);
    mu_M_raw = nan(num_k_emp, 1);
    mu_R_raw = nan(num_k_emp, 1);
    sig_M_raw = nan(num_k_emp, 1);
    sig_R_raw = nan(num_k_emp, 1);

    for ii = 1:num_k_emp
        e = err_cell{ii};

        idx_main = (e >= region_main(1)) & (e < region_main(2));
        idx_right = (e >= region_right(1)) & (e < region_right(2));

        P_M_raw(ii) = mean(idx_main);
        P_R_raw(ii) = mean(idx_right);

        eM = e(idx_main);
        if isempty(eM)
            eM = e;
        end

        mu_M_raw(ii) = median(eM);
        sig_M_raw(ii) = local_robust_sigma(eM, 1e-4);

        eR = e(idx_right);
        if isempty(eR)
            mu_R_raw(ii) = mean(region_right);
            sig_R_raw(ii) = 0.005;
        else
            mu_R_raw(ii) = mean(eR);
            sig_R_raw(ii) = local_robust_sigma(eR, 1e-4);
        end
    end

    % Three-point moving averages are fitting inputs only.
    P_M_fit_input = min(max( ...
        smoothdata(P_M_raw, 'movmean', 3), 0), 1);
    P_R_fit_input = min(max( ...
        smoothdata(P_R_raw, 'movmean', 3), 0), 0.40);
    mu_M_fit_input = smoothdata(mu_M_raw, 'movmean', 3);
    mu_R_fit_input = smoothdata(mu_R_raw, 'movmean', 3);
    sig_M_fit_input = max( ...
        smoothdata(sig_M_raw, 'movmean', 3), 1e-4);
    sig_R_fit_input = max( ...
        smoothdata(sig_R_raw, 'movmean', 3), 1e-4);

    % Apply the same curve structures and constraints as Exp03.
    fit_PR = local_fit_PR(k_emp, P_R_fit_input);
    fit_PM = local_fit_PM(k_emp, P_M_fit_input);
    fit_muM = local_fit_muM(k_emp, mu_M_fit_input, cfg.k_emp_max);
    fit_sigR = local_fit_sigR(k_emp, sig_R_fit_input);

    PR_fit_emp = fit_PR.predict(k_emp);
    PR_fit_full = fit_PR.predict(k_vals);

    PM_fit_emp = fit_PM.predict(k_emp);
    PM_fit_full = fit_PM.predict(k_vals);

    muM_fit_full = fit_muM.predict(k_vals);

    sigR_fit_emp = fit_sigR.predict(k_emp);
    sigR_fit_full = fit_sigR.predict(k_vals);

    % R-squared against both raw observations and smoothed fitting inputs.
    R2_PR_raw = local_r2(P_R_raw, PR_fit_emp);
    R2_PR_fit_input = local_r2(P_R_fit_input, PR_fit_emp);

    R2_PM_raw = local_r2(P_M_raw, PM_fit_emp);
    R2_PM_fit_input = local_r2(P_M_fit_input, PM_fit_emp);

    muM_fit_emp = fit_muM.predict(k_emp);
    R2_muM_raw = local_r2(mu_M_raw, muM_fit_emp);
    R2_muM_fit_input = local_r2(mu_M_fit_input, muM_fit_emp);

    R2_sigR_raw = local_r2(sig_R_raw, sigR_fit_emp);
    R2_sigR_fit_input = local_r2(sig_R_fit_input, sigR_fit_emp);

    % Trend checks use raw empirical endpoints and fitted endpoints.
    Delta_PM_raw = P_M_raw(end) - P_M_raw(1);
    Delta_PR_raw = P_R_raw(end) - P_R_raw(1);
    Delta_sigR_raw = sig_R_raw(end) - sig_R_raw(1);

    Delta_PM_fit = PM_fit_emp(end) - PM_fit_emp(1);
    Delta_PR_fit = PR_fit_emp(end) - PR_fit_emp(1);
    Delta_sigR_fit = sigR_fit_emp(end) - sigR_fit_emp(1);

    FitSummary = table( ...
        curr_name, ...
        main_mult(ss), ...
        right_mult(ss), ...
        region_main(1), ...
        region_main(2), ...
        region_right(1), ...
        region_right(2), ...
        R2_PM_raw, ...
        R2_PM_fit_input, ...
        R2_PR_raw, ...
        R2_PR_fit_input, ...
        R2_muM_raw, ...
        R2_muM_fit_input, ...
        R2_sigR_raw, ...
        R2_sigR_fit_input, ...
        Delta_PM_raw, ...
        Delta_PR_raw, ...
        Delta_sigR_raw, ...
        Delta_PM_fit, ...
        Delta_PR_fit, ...
        Delta_sigR_fit, ...
        fit_PM.rate, ...
        fit_PM.plateau, ...
        fit_PR.rate, ...
        fit_PR.plateau, ...
        fit_sigR.amplitude, ...
        fit_sigR.rate, ...
        fit_sigR.plateau, ...
        'VariableNames', { ...
        'Scenario', ...
        'MainWidthMultiplier', ...
        'RightWidthMultiplier', ...
        'MainLower', ...
        'MainUpper', ...
        'RightLower', ...
        'RightUpper', ...
        'R2_PM_raw', ...
        'R2_PM_fit_input', ...
        'R2_PR_raw', ...
        'R2_PR_fit_input', ...
        'R2_muM_raw', ...
        'R2_muM_fit_input', ...
        'R2_sigR_raw', ...
        'R2_sigR_fit_input', ...
        'Delta_PM_raw_k21_minus_k5', ...
        'Delta_PR_raw_k21_minus_k5', ...
        'Delta_sigR_raw_k21_minus_k5', ...
        'Delta_PM_fit_k21_minus_k5', ...
        'Delta_PR_fit_k21_minus_k5', ...
        'Delta_sigR_fit_k21_minus_k5', ...
        'PM_growth_rate', ...
        'PM_plateau', ...
        'PR_decay_rate', ...
        'PR_plateau', ...
        'sigR_amplitude', ...
        'sigR_decay_rate', ...
        'sigR_plateau'});

    FitSummary_All = [FitSummary_All; FitSummary]; %#ok<AGROW>

    FeatureTable = table( ...
        repmat(curr_name, num_k_emp, 1), ...
        k_emp, ...
        num_outer_used_list, ...
        num_inner_used_list, ...
        num_residual_used_list, ...
        repmat(region_main(1), num_k_emp, 1), ...
        repmat(region_main(2), num_k_emp, 1), ...
        repmat(region_right(1), num_k_emp, 1), ...
        repmat(region_right(2), num_k_emp, 1), ...
        P_M_raw, ...
        P_M_fit_input, ...
        P_R_raw, ...
        P_R_fit_input, ...
        mu_M_raw, ...
        mu_M_fit_input, ...
        sig_M_raw, ...
        sig_M_fit_input, ...
        mu_R_raw, ...
        mu_R_fit_input, ...
        sig_R_raw, ...
        sig_R_fit_input, ...
        'VariableNames', { ...
        'Scenario', ...
        'k', ...
        'N_outer_runs', ...
        'N_inner_runs_all_inner', ...
        'N_residuals_all_inner', ...
        'MainLower', ...
        'MainUpper', ...
        'RightLower', ...
        'RightUpper', ...
        'P_M_raw', ...
        'P_M_fit_input', ...
        'P_R_raw', ...
        'P_R_fit_input', ...
        'mu_M_raw', ...
        'mu_M_fit_input', ...
        'sig_M_raw', ...
        'sig_M_fit_input', ...
        'mu_R_raw', ...
        'mu_R_fit_input', ...
        'sig_R_raw', ...
        'sig_R_fit_input'});

    FeatureCurve_All = [FeatureCurve_All; FeatureTable]; %#ok<AGROW>

    FitCurveTable = table( ...
        repmat(curr_name, numel(k_vals), 1), ...
        k_vals, ...
        PM_fit_full, ...
        PR_fit_full, ...
        muM_fit_full, ...
        sigR_fit_full, ...
        2 * sigR_fit_full, ...
        'VariableNames', { ...
        'Scenario', ...
        'k', ...
        'P_M_fit', ...
        'P_R_fit', ...
        'mu_M_fit', ...
        'sigma_R_fit', ...
        'RightTailWidth_2sigma_R_fit'});

    FitCurve_All = [FitCurve_All; FitCurveTable]; %#ok<AGROW>

    Store(ss).Scenario = curr_name;
    Store(ss).region_main = region_main;
    Store(ss).region_right = region_right;
    Store(ss).k_emp = k_emp;
    Store(ss).k_vals = k_vals;

    Store(ss).P_M_raw = P_M_raw;
    Store(ss).P_M_fit_input = P_M_fit_input;
    Store(ss).P_R_raw = P_R_raw;
    Store(ss).P_R_fit_input = P_R_fit_input;
    Store(ss).sig_R_raw = sig_R_raw;
    Store(ss).sig_R_fit_input = sig_R_fit_input;

    Store(ss).PM_fit_full = PM_fit_full;
    Store(ss).PR_fit_full = PR_fit_full;
    Store(ss).sigR_fit_full = sigR_fit_full;
end

%% 5) Save result tables
writetable(FitSummary_All, cfg.fit_summary_csv);
writetable(FeatureCurve_All, cfg.feature_curves_csv);
writetable(FitCurve_All, cfg.fit_curves_csv);

TrendCheck = table( ...
    FitSummary_All.Scenario, ...
    FitSummary_All.Delta_PM_raw_k21_minus_k5 > 0, ...
    FitSummary_All.Delta_PR_raw_k21_minus_k5 < 0, ...
    FitSummary_All.Delta_sigR_raw_k21_minus_k5 < 0, ...
    FitSummary_All.Delta_PM_fit_k21_minus_k5 > 0, ...
    FitSummary_All.Delta_PR_fit_k21_minus_k5 < 0, ...
    FitSummary_All.Delta_sigR_fit_k21_minus_k5 < 0, ...
    'VariableNames', { ...
    'Scenario', ...
    'Raw_PM_increases', ...
    'Raw_PR_decreases', ...
    'Raw_sigmaR_decreases', ...
    'Fit_PM_increases', ...
    'Fit_PR_decreases', ...
    'Fit_sigmaR_decreases'});

writetable(TrendCheck, cfg.trend_check_csv);

save(cfg.model_mat, ...
    'cfg', ...
    'ScenarioName', ...
    'main_mult', ...
    'right_mult', ...
    'k_emp', ...
    'k_vals', ...
    'err_cell', ...
    'AllInnerCountTable', ...
    'FitSummary_All', ...
    'FeatureCurve_All', ...
    'FitCurve_All', ...
    'TrendCheck', ...
    'Store', ...
    '-v7.3');

disp('================ Region-boundary robustness summary ================');
disp(FitSummary_All);
disp(TrendCheck);

%% 6) Supplementary Fig. 12a: R2 against raw all-inner features
fig1 = figure( ...
    'Color', 'w', ...
    'Name', 'SupFig12a_ResidualRegionBoundary_R2_summary', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, 18, 9]);

R2_mat = [ ...
    FitSummary_All.R2_PM_raw, ...
    FitSummary_All.R2_PR_raw, ...
    FitSummary_All.R2_sigR_raw];

bar(R2_mat, 'grouped');
grid on;
box on;

ylim([0, 1.05]);
xticks(1:nScenario);
xticklabels(FitSummary_All.Scenario);
xtickangle(30);

ylabel('Goodness of fit to raw features, R^2', ...
    'FontName', 'Arial', ...
    'FontSize', 10);

legend({'P_M(k)', 'P_R(k)', '2\sigma_R(k)'}, ...
    'Location', 'southoutside', ...
    'Orientation', 'horizontal', ...
    'FontName', 'Arial', ...
    'FontSize', 9);

title('Feature-fit robustness under residual-region perturbations', ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'normal');

set(gca, ...
    'FontName', 'Arial', ...
    'FontSize', 8, ...
    'LineWidth', 0.8, ...
    'TickLabelInterpreter', 'none');

local_save_figure( ...
    fig1, cfg.fig_r2_summary, cfg.png_r2_summary, cfg.png_resolution);

%% 7) Supplementary Fig. 12b: near-zero-region probability
show_PM = ["Baseline", "Narrow_main_20", "Wide_main_20"];
legend_PM = ["Baseline", "Near-zero region -20%", "Near-zero region +20%"];

fig2 = figure( ...
    'Color', 'w', ...
    'Name', 'SupFig12b_ResidualRegionBoundary_PM_sensitivity', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, 16, 10]);

hold on;
grid on;
box on;

color_PM = [ ...
    0.00, 0.00, 0.00; ...
    0.35, 0.20, 0.80; ...
    0.20, 0.65, 0.20];

line_style_PM = {'-', '--', '-.'};

for ii = 1:numel(show_PM)
    idx_show = find(ScenarioName == show_PM(ii), 1);

    plot(Store(idx_show).k_vals, Store(idx_show).PM_fit_full, ...
        line_style_PM{ii}, ...
        'Color', color_PM(ii, :), ...
        'LineWidth', 2.2, ...
        'DisplayName', legend_PM(ii));

    scatter(Store(idx_show).k_emp, Store(idx_show).P_M_raw, ...
        28, color_PM(ii, :), 'filled', ...
        'MarkerFaceAlpha', 0.55, ...
        'HandleVisibility', 'off');
end

xlabel('Number of labelled target packs, k', ...
    'FontName', 'Arial', 'FontSize', 10);
ylabel('Near-zero-region probability, P_M(k)', ...
    'FontName', 'Arial', 'FontSize', 10);
title('Sensitivity of P_M(k) to near-zero-region width', ...
    'FontName', 'Arial', 'FontSize', 11, 'FontWeight', 'normal');

legend('Location', 'southeast', 'FontName', 'Arial', 'FontSize', 8);
set(gca, 'FontName', 'Arial', 'FontSize', 8, 'LineWidth', 0.8);

local_save_figure(fig2, cfg.fig_PM, cfg.png_PM, cfg.png_resolution);

%% 8) Supplementary Fig. 12c: positive right-tail-region probability
show_R = ["Baseline", "Narrow_right_20", "Wide_right_20"];
legend_R = ["Baseline", "Right-tail region -20%", "Right-tail region +20%"];

fig3 = figure( ...
    'Color', 'w', ...
    'Name', 'SupFig12c_ResidualRegionBoundary_PR_sensitivity', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, 16, 10]);

hold on;
grid on;
box on;

color_R = [ ...
    0.00, 0.00, 0.00; ...
    0.75, 0.20, 0.20; ...
    0.90, 0.50, 0.10];

line_style_R = {'-', '--', '-.'};

for ii = 1:numel(show_R)
    idx_show = find(ScenarioName == show_R(ii), 1);

    plot(Store(idx_show).k_vals, Store(idx_show).PR_fit_full, ...
        line_style_R{ii}, ...
        'Color', color_R(ii, :), ...
        'LineWidth', 2.2, ...
        'DisplayName', legend_R(ii));

    scatter(Store(idx_show).k_emp, Store(idx_show).P_R_raw, ...
        28, color_R(ii, :), 'filled', ...
        'MarkerFaceAlpha', 0.55, ...
        'HandleVisibility', 'off');
end

xlabel('Number of labelled target packs, k', ...
    'FontName', 'Arial', 'FontSize', 10);
ylabel('Positive right-tail-region probability, P_R(k)', ...
    'FontName', 'Arial', 'FontSize', 10);
title('Sensitivity of P_R(k) to positive right-tail-region width', ...
    'FontName', 'Arial', 'FontSize', 11, 'FontWeight', 'normal');

legend('Location', 'northeast', 'FontName', 'Arial', 'FontSize', 8);
set(gca, 'FontName', 'Arial', 'FontSize', 8, 'LineWidth', 0.8);

local_save_figure(fig3, cfg.fig_PR, cfg.png_PR, cfg.png_resolution);

%% 9) Supplementary Fig. 12d: positive right-tail width 2*sigma_R
fig4 = figure( ...
    'Color', 'w', ...
    'Name', 'SupFig12d_ResidualRegionBoundary_SigmaR_sensitivity', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, 16, 10]);

hold on;
grid on;
box on;

for ii = 1:numel(show_R)
    idx_show = find(ScenarioName == show_R(ii), 1);

    plot(Store(idx_show).k_vals, ...
        2 * Store(idx_show).sigR_fit_full, ...
        line_style_R{ii}, ...
        'Color', color_R(ii, :), ...
        'LineWidth', 2.2, ...
        'DisplayName', legend_R(ii));

    scatter(Store(idx_show).k_emp, ...
        2 * Store(idx_show).sig_R_raw, ...
        28, color_R(ii, :), 'filled', ...
        'MarkerFaceAlpha', 0.55, ...
        'HandleVisibility', 'off');
end

xlabel('Number of labelled target packs, k', ...
    'FontName', 'Arial', 'FontSize', 10);
ylabel('Positive right-tail width, 2\sigma_R(k)', ...
    'FontName', 'Arial', 'FontSize', 10);
title('Sensitivity of 2\sigma_R(k) to positive right-tail-region width', ...
    'FontName', 'Arial', 'FontSize', 11, 'FontWeight', 'normal');

legend('Location', 'northeast', 'FontName', 'Arial', 'FontSize', 8);
set(gca, 'FontName', 'Arial', 'FontSize', 8, 'LineWidth', 0.8);

local_save_figure(fig4, cfg.fig_sigR, cfg.png_sigR, cfg.png_resolution);

%% 10) Empirical residual-distribution illustrations
if cfg.do_plot_distribution
    show_dist_scenarios = ["Baseline", "Narrow_all_20", "Wide_all_20"];
    dist_scenario_labels = ["Baseline", "All regions -20%", "All regions +20%"];

    color_hist = [0.82, 0.89, 0.96];
    color_line = [0.10, 0.35, 0.75];
    color_main_fill = [0.46, 0.73, 0.46];
    color_right_fill = [0.88, 0.55, 0.55];

    for kk = 1:numel(cfg.plot_k_list)
        k_now = cfg.plot_k_list(kk);
        idx_emp = find(k_emp == k_now, 1);
        e = err_cell{idx_emp};

        for rr = 1:numel(show_dist_scenarios)
            scen_now = show_dist_scenarios(rr);
            scen_label = dist_scenario_labels(rr);
            idx_scen = find(ScenarioName == scen_now, 1);

            region_main = Store(idx_scen).region_main;
            region_right = Store(idx_scen).region_right;

            fig_k = figure( ...
                'Color', 'w', ...
                'Name', sprintf( ...
                'SupFig12_distribution_%s_k_%02d', scen_now, k_now), ...
                'Units', 'centimeters', ...
                'Position', [2, 2, 8, 6]);

            hold on;
            grid on;
            box on;

            histogram(e, cfg.hist_edges, ...
                'Normalization', 'pdf', ...
                'FaceColor', color_hist, ...
                'EdgeColor', 'none', ...
                'FaceAlpha', 0.75);

            [f, xi] = ksdensity(e, 'Bandwidth', cfg.kde_bw);

            idx_m = (xi >= region_main(1)) & (xi <= region_main(2));
            if any(idx_m)
                area(xi(idx_m), f(idx_m), ...
                    'FaceColor', color_main_fill, ...
                    'FaceAlpha', 0.35, ...
                    'EdgeColor', 'none');
            end

            idx_r = (xi >= region_right(1)) & (xi <= region_right(2));
            if any(idx_r)
                area(xi(idx_r), f(idx_r), ...
                    'FaceColor', color_right_fill, ...
                    'FaceAlpha', 0.35, ...
                    'EdgeColor', 'none');
            end

            plot(xi, f, '-', 'Color', color_line, 'LineWidth', 1.8);

            xline(0, 'k--', 'LineWidth', 0.8);
            xline(region_main(1), '--', ...
                'Color', [0.20, 0.55, 0.20], 'LineWidth', 0.8);
            xline(region_main(2), '--', ...
                'Color', [0.20, 0.55, 0.20], 'LineWidth', 0.8);
            xline(region_right(1), '--', ...
                'Color', [0.70, 0.20, 0.20], 'LineWidth', 0.8);
            xline(region_right(2), '--', ...
                'Color', [0.70, 0.20, 0.20], 'LineWidth', 0.8);

            xlim([-0.06, 0.06]);
            yl = ylim;
            ylim([0, yl(2) * 1.10]);

            xlabel('Residual error', 'FontName', 'Arial', 'FontSize', 9);
            ylabel('Probability density', 'FontName', 'Arial', 'FontSize', 9);
            title(sprintf('%s, k = %d', scen_label, k_now), ...
                'FontName', 'Arial', ...
                'FontSize', 10, ...
                'FontWeight', 'normal');

            text(0.04, 0.90, 'Empirical all-inner residuals', ...
                'Units', 'normalized', ...
                'FontName', 'Arial', ...
                'FontSize', 8, ...
                'FontWeight', 'bold', ...
                'Color', color_line);

            set(gca, ...
                'FontName', 'Arial', ...
                'FontSize', 8, ...
                'LineWidth', 0.8, ...
                'TickDir', 'out');

            out_fig = fullfile(cfg.dist_dir, sprintf( ...
                'SupFig12_distribution_%s_k_%02d.fig', scen_now, k_now));
            out_png = fullfile(cfg.dist_dir, sprintf( ...
                'SupFig12_distribution_%s_k_%02d.png', scen_now, k_now));

            local_save_figure( ...
                fig_k, out_fig, out_png, cfg.png_resolution);
            close(fig_k);
        end
    end
end

fprintf('\n================ P3 Exp04 completed ================\n');
fprintf('Fit summary:       %s\n', cfg.fit_summary_csv);
fprintf('Feature curves:    %s\n', cfg.feature_curves_csv);
fprintf('Fit curves:        %s\n', cfg.fit_curves_csv);
fprintf('Trend check:       %s\n', cfg.trend_check_csv);
fprintf('All-inner counts:  %s\n', cfg.all_inner_counts_csv);
fprintf('Model file:        %s\n', cfg.model_mat);
fprintf('Figure folder:     %s\n', cfg.supp_fig_dir);

%% Local helper functions
function region_out = local_scaled_region(region_in, width_multiplier)
center = mean(region_in);
half_width = 0.5 * (region_in(2) - region_in(1));
region_out = [ ...
    center - width_multiplier * half_width, ...
    center + width_multiplier * half_width];
end

function sigma_value = local_robust_sigma(x, minimum_sigma)
x = x(isfinite(x));
if isempty(x)
    sigma_value = minimum_sigma;
    return;
end

sigma_value = iqr(x) / 1.349;
if numel(x) < 4 || ~isfinite(sigma_value) || sigma_value <= 0
    sigma_value = std(x);
end

if ~isfinite(sigma_value) || sigma_value <= 0
    sigma_value = minimum_sigma;
end

sigma_value = max(sigma_value, minimum_sigma);
end

function fit_result = local_fit_PR(k, y)
k0 = min(k);
y0 = y(1);

huber_loss = @(obs, pred) local_huber_loss(obs, pred);

c_lb = 0.00;
c_ub = 0.08;

bound_c = @(c) min(max(c, c_lb), c_ub);
penalty_c = @(c) ...
    1e6 * (c < c_lb) .* (c_lb - c).^2 + ...
    1e6 * (c > c_ub) .* (c - c_ub).^2;

predict_from_p = @(p, x) ...
    bound_c(p(2)) + ...
    (y0 - bound_c(p(2))) .* exp(-exp(p(1)) .* (x - k0));

objective = @(p) ...
    huber_loss(y, predict_from_p(p, k)) + penalty_c(p(2));

options = optimset( ...
    'Display', 'off', ...
    'MaxFunEvals', 6000, ...
    'MaxIter', 6000);

p = fminsearch(objective, ...
    [log(0.18); min(y(end), 0.05)], options);

fit_result.rate = exp(p(1));
fit_result.plateau = bound_c(p(2));
fit_result.predict = @(x) ...
    fit_result.plateau + ...
    (y0 - fit_result.plateau) .* ...
    exp(-fit_result.rate .* (x - k0));
end

function fit_result = local_fit_PM(k, y)
k0 = min(k);
y0 = y(1);

c_lb = max(y);
c_ub = max(0.95, c_lb + 1e-4);

bound_c = @(c) min(max(c, c_lb), c_ub);
penalty_c = @(c) ...
    1e6 * (c < c_lb) .* (c_lb - c).^2 + ...
    1e6 * (c > c_ub) .* (c - c_ub).^2;

predict_from_p = @(p, x) ...
    bound_c(p(2)) - ...
    (bound_c(p(2)) - y0) .* exp(-exp(p(1)) .* (x - k0));

objective = @(p) ...
    local_huber_loss(y, predict_from_p(p, k)) + penalty_c(p(2));

options = optimset( ...
    'Display', 'off', ...
    'MaxFunEvals', 6000, ...
    'MaxIter', 6000);

p = fminsearch(objective, ...
    [log(0.12); max(0.8, max(y))], options);

fit_result.rate = exp(p(1));
fit_result.plateau = bound_c(p(2));
fit_result.predict = @(x) ...
    fit_result.plateau - ...
    (fit_result.plateau - y0) .* ...
    exp(-fit_result.rate .* (x - k0));
end

function fit_result = local_fit_muM(k, y, anchor_k)
mask = (k >= 7) & (k <= anchor_k) & isfinite(y);
if sum(mask) < 3
    mask = isfinite(y);
end

idx_anchor = find(k == anchor_k, 1);
anchor_value = y(idx_anchor);

predict_from_p = @(p, x) ...
    anchor_value .* exp(-exp(p(1)) .* (x - anchor_k));

objective = @(p) ...
    local_huber_loss(y(mask), predict_from_p(p, k(mask)));

options = optimset( ...
    'Display', 'off', ...
    'MaxFunEvals', 6000, ...
    'MaxIter', 6000);

p = fminsearch(objective, log(0.08), options);

fit_result.rate = exp(p(1));
fit_result.anchor = anchor_value;
fit_result.predict = @(x) ...
    anchor_value .* exp(-fit_result.rate .* (x - anchor_k));
end

function fit_result = local_fit_sigR(k, y)
mask = isfinite(y) & (y > 0);
x = k(mask);
obs = y(mask);

if numel(x) < 3
    error('Not enough valid sigma_R values for fitting.');
end

k0 = min(x);

c_lb = 0.0003;
c_ub = 0.0012;

bound_c = @(c) min(max(c, c_lb), c_ub);
penalty_c = @(c) ...
    1e6 * (c < c_lb) .* (c_lb - c).^2 + ...
    1e6 * (c > c_ub) .* (c - c_ub).^2;

predict_from_p = @(p, xx) ...
    bound_c(p(3)) + ...
    exp(p(1)) .* exp(-exp(p(2)) .* (xx - k0));

objective = @(p) ...
    local_huber_loss(obs, predict_from_p(p, x)) + penalty_c(p(3));

options = optimset( ...
    'Display', 'off', ...
    'MaxFunEvals', 6000, ...
    'MaxIter', 6000);

initial_amplitude = max(max(obs) - min(obs), 1e-5);
p = fminsearch(objective, ...
    [log(initial_amplitude); log(0.18); min(obs)], options);

fit_result.amplitude = exp(p(1));
fit_result.rate = exp(p(2));
fit_result.plateau = bound_c(p(3));
fit_result.predict = @(xx) ...
    fit_result.plateau + ...
    fit_result.amplitude .* exp(-fit_result.rate .* (xx - k0));
end

function loss_value = local_huber_loss(y, yhat)
residual = y(:) - yhat(:);
delta = 1.5 * max(mad(residual, 1), 1e-6);

abs_residual = abs(residual);
loss_each = zeros(size(residual));

small = abs_residual <= delta;
loss_each(small) = 0.5 * residual(small).^2;
loss_each(~small) = ...
    delta .* (abs_residual(~small) - 0.5 * delta);

loss_value = sum(loss_each, 'omitnan');
end

function R2 = local_r2(y, yhat)
y = y(:);
yhat = yhat(:);

valid = isfinite(y) & isfinite(yhat);
y = y(valid);
yhat = yhat(valid);

if numel(y) < 2
    R2 = NaN;
    return;
end

den = sum((y - mean(y)).^2);
if den <= 0
    R2 = NaN;
else
    R2 = 1 - sum((y - yhat).^2) / den;
end
end

function local_save_figure(fig_handle, fig_file, png_file, resolution)
out_dir = fileparts(fig_file);
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

savefig(fig_handle, fig_file);
exportgraphics(fig_handle, png_file, 'Resolution', resolution);

fprintf('[Figure] Saved: %s\n', png_file);
end
