%% P3_Exp01_NestedResampling_ErrorEvaluation.m
% Purpose:
% This script performs nested-resampling error evaluation for target-domain
% pack-level SOH prediction.
% The experiment repeatedly splits target packs into a fixed test set and a
% training candidate pool. For each outer split, different target-domain
% label sizes k are evaluated. For each k, repeated inner random training
% subsets are sampled, the L2-SP fine-tuning model is trained, and prediction
% errors are evaluated on the fixed test packs.



clc; clear; close all;

%% 1) Configuration and output setup
rng(42);
cfg = struct();

% Use the current script folder as the Part3 root folder.
script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

% Use the parent folder as the project root.
project_root = fileparts(script_dir);

% Output folders for Part3.

cfg.output_dir = fullfile(script_dir, 'Output');
cfg.output_results_dir = fullfile(cfg.output_dir, 'Results');

if ~exist(cfg.output_dir, 'dir')
    mkdir(cfg.output_dir);
end

if ~exist(cfg.output_results_dir, 'dir')
    mkdir(cfg.output_results_dir);
end

% Input files from Part2 and Part1.
cfg.target_mat = fullfile(project_root, ...
'Part2_Target-domain_Prediction', ...
'Output', ...
'Data', ...
'P2_Exp01_TargetPack_Input.mat');

cfg.source_mat = fullfile(project_root, ...
'Part1_Source-domain_Prediction', ...
'Output', ...
'Models', ...
'P1_SourceDomain_CNN_Model.mat');

% Output files generated by Part3/Main01.
timestamp = datestr(now, 'mmdd_HHMM');

cfg.log_file = fullfile(cfg.output_results_dir, sprintf('P3_Exp01_NestedResampling_Log_%s.txt', timestamp));
cfg.checkpoint_file = fullfile(cfg.output_results_dir, 'P3_Exp01_NestedResampling_Checkpoint.mat');
cfg.final_mat = fullfile(cfg.output_results_dir, 'P3_Exp01_NestedResampling_Final.mat');
cfg.summary_csv = fullfile(cfg.output_results_dir, 'P3_Exp01_NestedResampling_Summary.csv');

% Input dimensions.
cfg.M = 512;
cfg.nCell = 45;

% Training settings.
cfg.maxEpochs = 60;
cfg.warmupEpochs = 20;
cfg.lr_head = 1e-3;
cfg.lr_enc = 1e-5;
cfg.tune_last_conv = 3;
cfg.beta1 = 0.9;
cfg.beta2 = 0.999;
cfg.batch_size = 3;

% Network architecture settings.
cfg.dEmbed = 64;
cfg.dAttH = 32;
cfg.dHeadH = 16;
cfg.attn_tau = 0.1;

% Regularization settings.
cfg.l2_head = 1e-4;
cfg.lambda_sp = 0.005;
cfg.clip_enc = 1.0;
cfg.clip_head = 1.0;

% Nested-resampling settings.
cfg.repeats = 50;
cfg.n_test_fixed = 5;
cfg.min_train = 5;
cfg.inner_repeats = 20;

% Initialize log file.
fid = fopen(cfg.log_file, 'w');

if fid == -1
    error('Unable to create log file: %s', cfg.log_file);
end

fprintf(fid, '=== P3_Exp01 nested-resampling experiment started: %s ===\n', datestr(now));
fclose(fid);

log_print = @(fmt, varargin) local_log_message(cfg.log_file, fmt, varargin{:});

log_print('================ P3_Exp01 nested-resampling error evaluation ================\n');
log_print('Target-domain data file:  %s\n', cfg.target_mat);
log_print('Source-domain model file: %s\n', cfg.source_mat);
log_print('Checkpoint file:          %s\n', cfg.checkpoint_file);
log_print('Final result file:        %s\n', cfg.final_mat);

%% 2) Load target-domain data
if ~exist(cfg.target_mat, 'file')
    error('Target-domain data not found: %s', cfg.target_mat);
end

T = load(cfg.target_mat);

X_img = single(T.X_img);
y_all = single(T.y_all(:));

if isfield(T, 'SN_List')
    SN_List = T.SN_List(:);
else
    SN_List = strings(numel(y_all), 1);

    for i = 1:numel(y_all)
        SN_List(i) = sprintf('Pack_%d', i);
    end
end

if isfield(T, 'cfg')
    cfgT = T.cfg;
else
    cfgT = struct();
end

Npack = size(X_img, 4);

if Npack <= cfg.n_test_fixed
    error('Npack must be larger than cfg.n_test_fixed.');
end

if size(X_img, 1) ~= cfg.nCell
    error('Unexpected number of cells. Expected %d, but got %d.', cfg.nCell, size(X_img, 1));
end

if size(X_img, 2) ~= cfg.M
    error('Unexpected input length. Expected M = %d, but got M = %d.', cfg.M, size(X_img, 2));
end

log_print('\n[Target] Dataset loaded successfully.\n');
log_print('[Target] Npack = %d | nCell = %d | M = %d\n', Npack, size(X_img, 1), size(X_img, 2));
log_print('[Target] SOH range: %.4f - %.4f\n', min(y_all), max(y_all));

%% 3) Load source-domain model and normalize target inputs
if ~exist(cfg.source_mat, 'file')
    error('Source-domain model not found: %s', cfg.source_mat);
end

S = load(cfg.source_mat);

netFull = S.netFull;
muX_full = double(S.muX_full);
sgX_full = double(S.sgX_full);

if sgX_full < 1e-12
    sgX_full = 1;
end

% Normalize target-domain voltage curves using source-domain statistics.
X_img = (X_img - muX_full) / sgX_full;

log_print('[Source] Source-domain model loaded successfully.\n');

%% 4) Prepare source-initialized encoder and L2-SP reference encoder
layers = netFull.Layers;
idx_gap = find(arrayfun(@(L) strcmp(L.Name, 'gap'), layers), 1, 'first');

if isempty(idx_gap)
    error('The source-domain network does not contain a layer named "gap".');
end

lgraphEnc = layerGraph(layers(1:idx_gap));
enc_ref = dlnetwork(lgraphEnc);

n_train_pool_max = Npack - cfg.n_test_fixed;
train_size_list = n_train_pool_max:-1:cfg.min_train;
n_sizes = numel(train_size_list);

log_print('[Setup] Maximum training pool size = %d\n', n_train_pool_max);
log_print('[Setup] Training label sizes k: %s\n', mat2str(train_size_list));
log_print('[Setup] Outer repeats = %d | Inner repeats = %d | Test packs per split = %d\n', ...
    cfg.repeats, cfg.inner_repeats, cfg.n_test_fixed);

%% 5) Initialize or recover checkpoint
if exist(cfg.checkpoint_file, 'file')

    log_print('\n[Recover] Existing checkpoint detected. Loading previous progress...\n');

    C = load(cfg.checkpoint_file);

    b = C.b;
    start_rep = b + 1;

    res_RMSE_outer = C.res_RMSE_outer;
    res_MAE_outer = C.res_MAE_outer;
    res_MAPE_outer = C.res_MAPE_outer;

    all_idx_test_fixed = C.all_idx_test_fixed;
    all_inner_RMSEs = C.all_inner_RMSEs;
    all_inner_MAEs = C.all_inner_MAEs;
    all_inner_MAPEs = C.all_inner_MAPEs;
    all_inner_R2s = C.all_inner_R2s;
    all_inner_errs = C.all_inner_errs;

    pool_y_true_per_size = C.pool_y_true_per_size;
    pool_y_pred_per_size = C.pool_y_pred_per_size;

    if isfield(C, 'rng_state')
        rng(C.rng_state);
    end

    if isfield(C, 'train_size_list')
        if ~isequal(C.train_size_list, train_size_list)
            error('The checkpoint train_size_list is inconsistent with the current configuration.');
        end
    end

    log_print('[Recover] Completed outer repetitions: %d / %d\n', b, cfg.repeats);
    log_print('[Recover] Resuming from outer repetition %d.\n', start_rep);

else

    log_print('\n[Setup] No checkpoint found. Initializing result storage...\n');

    start_rep = 1;

    res_RMSE_outer = zeros(n_sizes, cfg.repeats);
    res_MAE_outer = zeros(n_sizes, cfg.repeats);
    res_MAPE_outer = zeros(n_sizes, cfg.repeats);

    all_idx_test_fixed = zeros(cfg.repeats, cfg.n_test_fixed);

    all_inner_RMSEs = cell(n_sizes, cfg.repeats);
    all_inner_MAEs = cell(n_sizes, cfg.repeats);
    all_inner_MAPEs = cell(n_sizes, cfg.repeats);
    all_inner_R2s = cell(n_sizes, cfg.repeats);
    all_inner_errs = cell(n_sizes, cfg.repeats);

    pool_y_true_per_size = cell(n_sizes, 1);
    pool_y_pred_per_size = cell(n_sizes, 1);
end

if start_rep > cfg.repeats
    log_print('\n[Recover] All outer repetitions have already been completed.\n');
end

%% 6) Nested-resampling training and evaluation
for b = start_rep:cfg.repeats

    t_start_rep = tic;

    perm_all = randperm(Npack);

    idx_test_fixed = perm_all(1:cfg.n_test_fixed);
    idx_train_pool = perm_all(cfg.n_test_fixed + 1:end);

    all_idx_test_fixed(b, :) = idx_test_fixed;

    y_test_true = y_all(idx_test_fixed);
    X_test_batch = X_img(:, :, 1, idx_test_fixed);

    log_print('\n>>> [Outer Rep %02d/%02d] Test pack indices: %s\n', ...
        b, cfg.repeats, mat2str(idx_test_fixed));

    for i_sz = 1:n_sizes

        k = train_size_list(i_sz);

        curr_inner_reps = cfg.inner_repeats;

        if k == numel(idx_train_pool)
            curr_inner_reps = 1;
        end

        inner_RMSEs = zeros(curr_inner_reps, 1);
        inner_MAEs = zeros(curr_inner_reps, 1);
        inner_MAPEs = zeros(curr_inner_reps, 1);
        inner_R2s = zeros(curr_inner_reps, 1);
        inner_errs = zeros(cfg.n_test_fixed, curr_inner_reps, 'single');

        sum_pred_inner = zeros(size(y_test_true), 'single');

        for mc = 1:curr_inner_reps

            % Sample the current training subset from the training pool.
            perm_pool = randperm(numel(idx_train_pool));
            idx_train_curr = idx_train_pool(perm_pool(1:k));

            y_train_raw = y_all(idx_train_curr);

            muY = mean(y_train_raw);
            sgY = std(y_train_raw);

            if sgY < 1e-12
                sgY = 1;
            end

            y_train_norm = (y_train_raw - muY) / sgY;

            % Reset the trainable encoder for the current inner run.
            currEnc = dlnetwork(lgraphEnc);

            % Initialize attention and regression-head parameters.
            attW1 = dlarray(0.01 * randn(cfg.dAttH, cfg.dEmbed, 'single'));
            attb1 = dlarray(zeros(cfg.dAttH, 1, 'single'));
            attW2 = dlarray(0.01 * randn(1, cfg.dAttH, 'single'));
            attb2 = dlarray(zeros(1, 1, 'single'));

            headW1 = dlarray(0.01 * randn(cfg.dHeadH, cfg.dEmbed, 'single'));
            headb1 = dlarray(zeros(cfg.dHeadH, 1, 'single'));
            headW2 = dlarray(0.01 * randn(1, cfg.dHeadH, 'single'));
            headb2 = dlarray(zeros(1, 1, 'single'));

            avgG_enc = [];
            avgSqG_enc = [];
            avgG_head = cell(8, 1);
            avgSqG_head = cell(8, 1);

            iter = 0;

            % Mini-batch training loop.
            for ep = 1:cfg.maxEpochs

                order = randperm(k);
                num_batches = ceil(k / cfg.batch_size);

                for b_idx = 1:num_batches

                    iter = iter + 1;

                    idx_batch_start = (b_idx - 1) * cfg.batch_size + 1;
                    idx_batch_end = min(b_idx * cfg.batch_size, k);
                    idx_in_tr = order(idx_batch_start:idx_batch_end);

                    curr_bs = numel(idx_in_tr);

                    X_batch_tensor = zeros(1, cfg.M, 1, cfg.nCell * curr_bs, 'single');

                    for c = 1:curr_bs
                        p = idx_train_curr(idx_in_tr(c));

                        X_batch_tensor(1, :, 1, (c - 1) * cfg.nCell + 1:c * cfg.nCell) = ...
                            reshape(X_img(:, :, 1, p)', [1, cfg.M, 1, cfg.nCell]);
                    end

                    dlX = dlarray(X_batch_tensor, 'SSCB');
                    y_true_dl = dlarray(y_train_norm(idx_in_tr)');

                    [~, grads] = dlfeval(@local_model_grads, ...
                        dlX, ...
                        y_true_dl, ...
                        currEnc, ...
                        enc_ref, ...
                        attW1, ...
                        attb1, ...
                        attW2, ...
                        attb2, ...
                        headW1, ...
                        headb1, ...
                        headW2, ...
                        headb2, ...
                        cfg, ...
                        curr_bs);

                    % Update attention module and regression head.
                    headParams = {attW1, attb1, attW2, attb2, ...
                        headW1, headb1, headW2, headb2};

                    headGrads = {grads.attW1, grads.attb1, grads.attW2, grads.attb2, ...
                        grads.headW1, grads.headb1, grads.headW2, grads.headb2};

                    if cfg.clip_head > 0
                        headGrads = local_clip_grads_cell(headGrads, cfg.clip_head);
                    end

                    for z = 1:8
                        [headParams{z}, avgG_head{z}, avgSqG_head{z}] = adamupdate( ...
                            headParams{z}, ...
                            headGrads{z}, ...
                            avgG_head{z}, ...
                            avgSqG_head{z}, ...
                            iter, ...
                            cfg.lr_head, ...
                            cfg.beta1, ...
                            cfg.beta2);
                    end

                    [attW1, attb1, attW2, attb2, ...
                        headW1, headb1, headW2, headb2] = headParams{:};

                    % Update encoder after the warm-up stage.
                    if ep > cfg.warmupEpochs

                        genc = local_mask_enc_grads_keep_last_conv( ...
                            currEnc, grads.enc, cfg.tune_last_conv);

                        if cfg.clip_enc > 0
                            genc = local_clip_grads_table(genc, cfg.clip_enc);
                        end

                        [currEnc, avgG_enc, avgSqG_enc] = adamupdate( ...
                            currEnc, ...
                            genc, ...
                            avgG_enc, ...
                            avgSqG_enc, ...
                            iter, ...
                            cfg.lr_enc, ...
                            cfg.beta1, ...
                            cfg.beta2);
                    end
                end
            end

            % Inference on the fixed test packs.
            X_test_all = zeros(1, cfg.M, 1, cfg.nCell * cfg.n_test_fixed, 'single');

            for j = 1:cfg.n_test_fixed
                X_test_all(1, :, 1, (j - 1) * cfg.nCell + 1:j * cfg.nCell) = ...
                    reshape(X_test_batch(:, :, 1, j)', [1, cfg.M, 1, cfg.nCell]);
            end

            dlX_test = dlarray(X_test_all, 'SSCB');

            Z_raw_test = predict(currEnc, dlX_test);

            Z_te = reshape(stripdims(Z_raw_test), ...
                [cfg.dEmbed, cfg.nCell * cfg.n_test_fixed]);

            ypred_norm = local_model_predict_head_aligned_batched( ...
                Z_te, ...
                attW1, ...
                attb1, ...
                attW2, ...
                attb2, ...
                headW1, ...
                headb1, ...
                headW2, ...
                headb2, ...
                cfg, ...
                cfg.n_test_fixed);

            y_test_pred_mc = gather(extractdata(ypred_norm))' * sgY + muY;
            y_test_pred_mc = single(y_test_pred_mc(:));

            % Store inner-run statistics.
            err = y_test_pred_mc - y_test_true;

            inner_errs(:, mc) = err;
            inner_RMSEs(mc) = sqrt(mean(err.^2));
            inner_MAEs(mc) = mean(abs(err));
            inner_MAPEs(mc) = mean(abs(err ./ y_test_true));
            inner_R2s(mc) = 1 - sum(err.^2) / ...
                (sum((y_test_true - mean(y_test_true)).^2) + 1e-12);

            sum_pred_inner = sum_pred_inner + y_test_pred_mc;

            clear currEnc grads;
        end

        % Store outer-level results for the current k.
        res_RMSE_outer(i_sz, b) = mean(inner_RMSEs);
        res_MAE_outer(i_sz, b) = mean(inner_MAEs);
        res_MAPE_outer(i_sz, b) = mean(inner_MAPEs);

        all_inner_RMSEs{i_sz, b} = inner_RMSEs;
        all_inner_MAEs{i_sz, b} = inner_MAEs;
        all_inner_MAPEs{i_sz, b} = inner_MAPEs;
        all_inner_R2s{i_sz, b} = inner_R2s;
        all_inner_errs{i_sz, b} = inner_errs;

        pool_y_true_per_size{i_sz} = [pool_y_true_per_size{i_sz}; y_test_true];
        pool_y_pred_per_size{i_sz} = [pool_y_pred_per_size{i_sz}; sum_pred_inner / curr_inner_reps];

        log_print('    |-- k = %02d | inner repeats = %02d | Mean RMSE = %.4f | Mean MAE = %.4f\n', ...
            k, curr_inner_reps, res_RMSE_outer(i_sz, b), res_MAE_outer(i_sz, b));
    end

    % Save checkpoint after each outer repetition.
    rng_state = rng;
    time_rep = toc(t_start_rep);

    save(cfg.checkpoint_file, ...
        'b', ...
        'cfg', ...
        'cfgT', ...
        'SN_List', ...
        'Npack', ...
        'train_size_list', ...
        'res_RMSE_outer', ...
        'res_MAE_outer', ...
        'res_MAPE_outer', ...
        'all_inner_RMSEs', ...
        'all_inner_MAEs', ...
        'all_inner_MAPEs', ...
        'all_inner_R2s', ...
        'all_inner_errs', ...
        'pool_y_true_per_size', ...
        'pool_y_pred_per_size', ...
        'all_idx_test_fixed', ...
        'rng_state', ...
        '-v7.3');

    log_print('*** [Outer Rep %02d completed] Time = %.1f s | Checkpoint saved. ***\n', ...
        b, time_rep);
end

%% 7) Final summary and export
completed_repeats = cfg.repeats;

mean_RMSE = mean(res_RMSE_outer(:, 1:completed_repeats), 2);
std_RMSE = std(res_RMSE_outer(:, 1:completed_repeats), 0, 2);

mean_MAE = mean(res_MAE_outer(:, 1:completed_repeats), 2);
std_MAE = std(res_MAE_outer(:, 1:completed_repeats), 0, 2);

mean_MAPE = mean(res_MAPE_outer(:, 1:completed_repeats), 2);
std_MAPE = std(res_MAPE_outer(:, 1:completed_repeats), 0, 2);

Summary_Table = table( ...
    train_size_list(:), ...
    mean_RMSE(:), ...
    std_RMSE(:), ...
    mean_MAE(:), ...
    std_MAE(:), ...
    mean_MAPE(:), ...
    std_MAPE(:), ...
    'VariableNames', { ...
    'Train_Size_k', ...
    'Mean_RMSE', ...
    'Std_RMSE', ...
    'Mean_MAE', ...
    'Std_MAE', ...
    'Mean_MAPE', ...
    'Std_MAPE'});

writetable(Summary_Table, cfg.summary_csv);

save(cfg.final_mat, ...
    'cfg', ...
    'cfgT', ...
    'SN_List', ...
    'Npack', ...
    'train_size_list', ...
    'res_RMSE_outer', ...
    'res_MAE_outer', ...
    'res_MAPE_outer', ...
    'all_inner_RMSEs', ...
    'all_inner_MAEs', ...
    'all_inner_MAPEs', ...
    'all_inner_R2s', ...
    'all_inner_errs', ...
    'pool_y_true_per_size', ...
    'pool_y_pred_per_size', ...
    'all_idx_test_fixed', ...
    'Summary_Table', ...
    '-v7.3');

log_print('\n================ P3_Exp01 nested-resampling completed ================\n');
log_print('Final result file: %s\n', cfg.final_mat);
log_print('Summary CSV file:  %s\n', cfg.summary_csv);

%% Local helper functions
function local_log_message(fname, fmt, varargin)
% Write a message to both the command window and the log file.

msg = sprintf(fmt, varargin{:});
fprintf('%s', msg);

try
    fid = fopen(fname, 'a');

    if fid ~= -1
        fprintf(fid, '%s', msg);
        fclose(fid);
    end
catch
end
end

function [loss, grads] = local_model_grads( ...
    X, ...
    y, ...
    net, ...
    net_ref, ...
    attW1, ...
    attb1, ...
    attW2, ...
    attb2, ...
    headW1, ...
    headb1, ...
    headW2, ...
    headb2, ...
    cfg, ...
    curr_bs)
% Compute loss and gradients for one mini-batch.

Z_raw = predict(net, X);
Z = reshape(stripdims(Z_raw), [cfg.dEmbed, cfg.nCell * curr_bs]);

ypred = local_model_predict_head_aligned_batched( ...
    Z, ...
    attW1, ...
    attb1, ...
    attW2, ...
    attb2, ...
    headW1, ...
    headb1, ...
    headW2, ...
    headb2, ...
    cfg, ...
    curr_bs);

mse_loss = mean((ypred(:) - y(:)).^2);

% L2-SP regularization on encoder parameters.
l2_sp_term = 0;

if cfg.lambda_sp > 0

    T_curr = net.Learnables;
    T_ref = net_ref.Learnables;

    for i = 1:height(T_curr)
        diff = T_curr.Value{i} - T_ref.Value{i};
        l2_sp_term = l2_sp_term + sum(diff(:).^2);
    end
end

% L2 regularization on attention and regression-head weight matrices.
l2_head_term = sum(attW1(:).^2) + ...
               sum(attW2(:).^2) + ...
               sum(headW1(:).^2) + ...
               sum(headW2(:).^2);

loss = mse_loss + cfg.l2_head * l2_head_term + cfg.lambda_sp * l2_sp_term;

all_grads = dlgradient(loss, ...
    {net.Learnables, attW1, attb1, attW2, attb2, headW1, headb1, headW2, headb2});

grads.enc = all_grads{1};
grads.attW1 = all_grads{2};
grads.attb1 = all_grads{3};
grads.attW2 = all_grads{4};
grads.attb2 = all_grads{5};
grads.headW1 = all_grads{6};
grads.headb1 = all_grads{7};
grads.headW2 = all_grads{8};
grads.headb2 = all_grads{9};
end

function ypred = local_model_predict_head_aligned_batched( ...
    Z_2d, ...
    attW1, ...
    attb1, ...
    attW2, ...
    attb2, ...
    headW1, ...
    headb1, ...
    headW2, ...
    headb2, ...
    cfg, ...
    curr_bs)
% Forward pass for batched soft-min attention and MLP regression head.

H_2d = relu(attW1 * Z_2d + attb1);

score_3d = reshape( ...
    -(attW2 * H_2d + attb2) / cfg.attn_tau, ...
    [1, cfg.nCell, curr_bs]);

score_3d = score_3d - max(score_3d, [], 2);

w_3d = exp(score_3d) ./ sum(exp(score_3d), 2);

Z_3d = reshape(Z_2d, [cfg.dEmbed, cfg.nCell, curr_bs]);

zbag_2d = reshape(sum(Z_3d .* w_3d, 2), ...
    [cfg.dEmbed, curr_bs]);

ypred = headW2 * relu(headW1 * zbag_2d + headb1) + headb2;
end

function genc = local_mask_enc_grads_keep_last_conv(net, genc, keep_last_conv)
% Keep gradients only for the last several convolutional layers.

L = net.Layers;
layerNames = string({L.Name});
isConv = false(size(L));

for i = 1:numel(L)

    cls = class(L(i));

    if contains(cls, 'Convolution', 'IgnoreCase', true) || ...
            contains(L(i).Name, 'conv', 'IgnoreCase', true)
        isConv(i) = true;
    end
end

convIdx = find(isConv);

if isempty(convIdx)

    learnLayer = string(genc.Layer);
    uniq = unique(learnLayer, 'stable');
    nUniq = numel(uniq);
    keep = uniq(max(1, nUniq - 4):nUniq);

else

    k = min(keep_last_conv, numel(convIdx));
    keep = layerNames(convIdx(end - k + 1:end));
end

for i = 1:height(genc)

    if ~ismember(string(genc.Layer(i)), keep)

        gi = genc.Value{i};

        if isempty(gi)
            continue;
        end

        gi_data = extractdata(gi);
        genc.Value{i} = dlarray(zeros(size(gi_data), 'like', gi_data));
    end
end
end

function gcell = local_clip_grads_cell(gcell, clipnorm)
% Clip gradients stored in a cell array by global norm.

ss = 0;

for i = 1:numel(gcell)

    gi = gcell{i};

    if isempty(gi)
        continue;
    end

    gi_data = extractdata(gi);
    ss = ss + sum(gi_data(:).^2);
end

gn = sqrt(ss + 1e-12);

if gn > clipnorm

    scale = clipnorm / gn;

    for i = 1:numel(gcell)

        if isempty(gcell{i})
            continue;
        end

        gcell{i} = gcell{i} * scale;
    end
end
end

function gtab = local_clip_grads_table(gtab, clipnorm)
% Clip gradients stored in a dlnetwork learnables table by global norm.

ss = 0;

for i = 1:height(gtab)

    gi = gtab.Value{i};

    if isempty(gi)
        continue;
    end

    gi_data = extractdata(gi);
    ss = ss + sum(gi_data(:).^2);
end

gn = sqrt(ss + 1e-12);

if gn > clipnorm

    scale = clipnorm / gn;

    for i = 1:height(gtab)

        gi = gtab.Value{i};

        if isempty(gi)
            continue;
        end

        gtab.Value{i} = gi * scale;
    end
end
end